### ISSUE TITLE
Feature request: provide an option for @JsonClass to skip nulls into default values for kotlin

### ISSUE THREAD

**Issue by ildar2** [square/moshi#1000]
I'm aware of #762, #843 and others, but the solutions are ugly

I have two classes for localization strings (110+ pre-auth and 477+ fields post-auth) and I can't afford creating duplication non-null values for each of them. Also any type adapters are not an option too

Ideal variant would be if the parser would substitute nulls with default value for non-null fields. I get it, it's your design desision not to do that, so there could be an option for this to happen:

For example, a parameter for @JsonClass annotation, like "stripNulls". It would be a fine solution, that won't affect current behaviour, but at the same time provide a lot of flexibility. Gson doesn't have this feature, anyway.

**Comment by ZacSweers** [comment]
Let's not duplicate issues, the feature request is the same as #843

**Comment by saqibmirza2007** [comment]
@ZacSweers  can you please tell me status of **defaultIfNull** feature status in. I am using Moshi 1.9.2 with codegenerator.
