### ISSUE TITLE
Will Moshi be grown in the direction of KMP?

### ISSUE THREAD

**Issue by joblolin95** [square/moshi#1002]
Hello! 
As active as you all (Square) have been in the Kotlin multiplatform community, do you see Moshi moving towards KMP at any time in the near future?

I've been working more and more in KMP over the past few months, and as I didn't see any documentation or previous issues answering said question, I thought I'd ask.

**Comment by JakeWharton** [comment]
Frankly, this is mostly up to Kotlin. It depends on one or both of an adequate reflection solution for every supported platform and/or an adequate code introspection and generation pipeline that works for every supported platform.
