### ISSUE TITLE
Kotlin Codegen with Enums + Retrofit

### ISSUE THREAD

**Issue by renhaoh** [square/moshi#1005]
Seems to be a similar issue to **#1006**

Hi, I'm using moshi with codegen and retrofit, with the default MoshiConverterFactory.create().

I have a data class and an enum (here is an example):
```
@JsonClass(generateAdapter = true)
data class Animal(
        val genus: GenusType? = null,
        val isAquatic: Boolean? = null
)
enum class GenusType {
    @Json(name = "one") GENUS_ONE,
    @Json(name = "two") GENUS_TWO,
}
```
In the generated adapter file for Animal, while debugging the fromJson() method, I noticed that the boolean and enum fields both have the correct (method) local values after the reading finishes. However, 
```
val localConstructor: Constructor<Animal> = this.constructorRef ?:
        Animal::class.java.getDeclaredConstructor(GenusType::class.java, Boolean::class.java,
        Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef =
        it }
```
I end with a NoSuchMethodException:
```<init> [class package.Animal, boolean, int, class kotlin.jvm.internal.DefaultConstructorMarker]```

I'm actually having the same issues with some other classes:
```
java.lang.NoSuchMethodException: <init> [int, int, boolean, boolean, int, int, class kotlin.jvm.internal.DefaultConstructorMarker]
```
For the above exception, the code to set the local constructor is:
```
val localConstructor: Constructor<PageInfo> = this.constructorRef ?:
        PageInfo::class.java.getDeclaredConstructor(Int::class.java, Int::class.java,
        Boolean::class.java, Boolean::class.java, Int::class.java, Int::class.javaPrimitiveType,
        Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
```
PageInfo is basically a couple of Int? and Boolean? nullables.

Is there something in the build process that I am missing? I've enabled the kotlin-kapt plugin and have the following gradle dependencies:
```
implementation 'com.squareup.moshi:moshi:1.9.1'
implementation 'com.squareup.retrofit2:converter-moshi:2.6.2'
kapt("com.squareup.moshi:moshi-kotlin-codegen:1.9.1")
```

**Comment by ZacSweers** [comment]
Same issue and this is fixed in master. Deduping to there
