### ISSUE TITLE
Dynamic constructor invocation throws NoSuchMethodException with nullable number param

### ISSUE THREAD

**Issue by luis-cortes** [square/moshi#1006]
The following causes a `NoSuchMethodException` to be thrown at runtime.

```
@JsonClass(generateAdapter = true)
data class ProfileResponse(
  val id: Long = 0,
  val heightInches: Int?,
```

The problem seems to stem from the nullable `heightInches` parameter. Removing the `?` fixes the issue.

**Stacktrace:**
```
E: java.lang.NoSuchMethodException: com.example.ProfileResponse.<init> [long, int, int, class kotlin.jvm.internal.DefaultConstructorMarker]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at com.example.ProfileResponseJsonAdapter.fromJson(ProfileResponseJsonAdapter.kt:50)
```

**Generated lines in question when the property is nullable:**
```
val localConstructor: Constructor<ProfileResponse> = this.constructorRef ?:
        ProfileResponse::class.java.getDeclaredConstructor(Long::class.javaPrimitiveType,
        Int::class.java, Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
        this.constructorRef = it }
```

**Generated lines in question when the property is non-nullable:**
```
val localConstructor: Constructor<ProfileResponse> = this.constructorRef ?:
        ProfileResponse::class.java.getDeclaredConstructor(Long::class.javaPrimitiveType,
        Int::class.javaPrimitiveType, Int::class.javaPrimitiveType,
        Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
```

**Diff:**
`Int::class.java` when the property is nullable
`Int::class.javaPrimitiveType` when it's non-nullable

**Other notes:**
Same thing happens for `Long`s. I suspect it happens for other numeric types as well. 

**Version:** 
1.9.1

**Comment by ZacSweers** [comment]
Can you try the current master snapshot?  We fixed some issues around this a couple days ago

**Comment by renhaoh** [comment]
Worked for me! @ZacSweers do you know when an official release will be cut?

**Comment by luis-cortes** [comment]
Thanks @ZacSweers. Worked for me as well using `1.10.0-SNAPSHOT`

**Comment by ZacSweers** [comment]
Thanks for confirming. Release should be soon!
