### ISSUE TITLE
Type error with default value for nullable primitive types

### ISSUE THREAD

**Issue by speekha** [square/moshi#1007]
When mapping class uses a "nullable primitive type" for a property (thus not really a primitive type but the corresponding boxed java type) with a default value (either null or not), java constructor isn't retrieved properly (NoSuchMethodException). 
For instance with a Int? parameter with a default value, the generated adapter uses the java primitive type (Int::class.java) as constructor parameter instead of the boxed type (Integer::class.java).

Here is an example: 

```
@JsonClass(generateAdapter = true)
data class TestJson (
    val field: Int? = null
)
```

With this class, trying to map a Json string will crash with a NoSuchMethodException due to the mixup between primitive type and boxed type. here's the faulty generated code (as decompiled by IntelliJ):

```
val localConstructor: Constructor<TestJson> = this.constructorRef ?:
        TestJson::class.java.getDeclaredConstructor(
            Boolean::class.java,
            Int::class.javaPrimitiveType, 
            Util.DEFAULT_CONSTRUCTOR_MARKER
        ).also { this.constructorRef = it }
```

This implies we can't have default values for missing primitive fields.

Appeared in 1.9. Worked properly in 1.8.

**Comment by ZacSweers** [comment]
This is fixed in master and will be available in the next release

**Comment by imecstamas** [comment]
When we can expect the next release? :)
