### ISSUE TITLE
Support for Moshi.Builder(Moshi.Builder) constructor or add method.

### ISSUE THREAD

**Issue by serj-lotutovici** [square/moshi#101]
This may sound like a stupid request, and no other (know to me) json library allows such possibilities, but there is a case when this is very handy. I have the following setup:
* One api client that uses Moshi for json parsing.
* The api client is shipped with predefined pojos, some of which require custom adapter factories (set by the api client).
* The api client is used by multiple teams (not only onsite).
* Other teams consume other "private" apis. Which result in -> new pojos and eventually requirement to set new adapters/adapter factories.

The point is that the client could expose in it's builder methods that will just mirror the ones in `Moshi.Builder` (currently 4 of them), but a more cleaner solution, would be just have one method `addAll(builder)` or `addFrom(builder)`.

**Comment by swankjesse** [comment]
What about a mechanism to recover the factories from a `Moshi` instance?

**Comment by serj-lotutovici** [comment]
That was actually my initial idea, but I was afraid that it would sound a little unreasonable. Since `Moshi` also instantiates a `Map` and a `ThreadLocal`, and in my use case this is needed to initialise a bigger `Moshi` object, so some performance geeks would argue that this is redundant memory allocation :smile:.

But it works for me. If you agree on `Moshi.Builder#addFrom(Moshi)` I will come up with a PR later today.
