### ISSUE TITLE
can @Json support multi alternative alias 

### ISSUE THREAD

**Issue by changety** [square/moshi#1012]
in fact,  the same filed in data class， different apis may have some different  key for the same filed， so can the moshi lib support multi alternative alias  for @Json  annotation, like this :
@Json(name = "nickname, name, etc")

**Comment by ZacSweers** [comment]
Moshi doesn't support this, there would be no way to reconcile what to do in cases of multiple matches without some awkward APIs. The correct way to handle this would be to make the possible properties/fields private and initialize a "right" field/property at your own discretion

```kotlin
data class Foo(
  private val nickname: String? = null,
  private val name: String? = null
) {
  val actualName = name ?: nickname // or throw if it's expected
}
```

```java
class Foo {
  
  private String nickname;
  private String name;

  public String actualName() {
    return name != null ? name : nickname; // or throw if it's expected
  }
}
```
