### ISSUE TITLE
Getting java.lang.NoSuchMethodException when deserializing a List<>?

### ISSUE THREAD

**Issue by Orgmir** [square/moshi#1015]
Hi,

I am getting a weird exception when I try to deserialize an empty json object `{}` using code-gen. I'm using 1.9.1 and kotlin 1.3.50

The class in question:
``` kotlin
@JsonClass(generateAdapter = true)
data class Example(val bool: Boolean?, val list: List<Boolean>? = null)
```

The exception thrown:
```
java.lang.NoSuchMethodException: com.example.Example.<init>(boolean, java.util.List, int, kotlin.jvm.internal.DefaultConstructorMarker)

	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.example.ExampleJsonAdapter.fromJson(ExampleJsonAdapter.kt:63)
	at com.example.ExampleJsonAdapter.fromJson(ExampleJsonAdapter.kt:21)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
```

I am writing some tests to make sure my deserialization does not crash even if the json payload is missing required values. I would think that class would always deserialize into an object with null parameters, but Moshi is throwing that one on me.

Not sure if this is related with #1013, but the stacktrace looked different enough to me so here it goes. 

I have also tested on 1.9.0 and it works without crashing.

**Comment by ZacSweers** [comment]
This is the same issue as #1013 and will be fixed in the next release
