### ISSUE TITLE
Optional list not working with the latest Moshi 1.9.1 release

### ISSUE THREAD

**Issue by leventepal** [square/moshi#1021]
I have the following data class with an optional list of models:
```
@JsonClass(generateAdapter = true)
data class UserProfileDTO(
   @Json(name = "entries") val entryDtos: List<EntryDTO>?
)
```

It's crashing in the generated adapter:

`com.squareup.moshi.JsonDataException: Non-null value 'entryDtos' (JSON name 'entries') was null at $.entries`

**Comment by ZacSweers** [comment]
This is fixed on master and will.be available in the next release.
