### ISSUE TITLE
Generated JsonAdapters for nested data classes ignore parent class visibility modifier

### ISSUE THREAD

**Issue by roman-tikhonov** [square/moshi#1022]
Hi!

I am using `moshi-kotlin-codegen:1.8.0` to generate adapters for the following classes:
```kotlin
@JsonClass(generateAdapter = true)
internal data class Parent(    
  val type: Int,
  val name: String? = null) {

  @JsonClass(generateAdapter = true)
  data class NestedClass(
    val nestedProperty: String
  )
}
```

Expected:
moshi generates two JsonAdapters, both with `internal` visibility modifier, because visibility of nested classes cannot exceed visibility of the enclosing class.

Actual:
moshi generates ParentJsonAdapter as `internal`, but NestedClassJsonAdapter as `public`.

**Comment by ZacSweers** [comment]
Interesting! Thanks for the report. Just to confirm - does this fail to compile or is this more of a style thing?

**Comment by roman-tikhonov** [comment]
It fails to compile with the following message:
```
> Task :api:compileKotlin FAILED
e: Parent_NestedClassJsonAdapter.kt: (15, 60): 'public' subclass exposes its 'internal' supertype argument containing declaration Parent
```

**Comment by roman-tikhonov** [comment]
And the generated Adapter declaration looks like:
```
class Parent_NestedClassJsonAdapter(moshi: Moshi) : JsonAdapter<Parent.NestedClass>() { ... }
```

**Comment by ZacSweers** [comment]
Thanks! Can fix

**Comment by ZacSweers** [comment]
PR #1026

**Comment by roman-tikhonov** [comment]
Thanks for the quick fix! Do you know in which release version will this fix be included?

**Comment by ZacSweers** [comment]
1.9.2 was released with this today. In general though, we can't offer ETAs
or info on which release things will be fixed in other than "the next one"
🙂
