### ISSUE TITLE
Json response with Java keyword for parameter name

### ISSUE THREAD

**Issue by imminent** [square/moshi#103]
We have a case where our API has labeled a parameter as "default", which is a protected keyword that can't be used as a variable name in Java. Given that you can't rename parameters with `@SerialedName`, as in Gson, is there some way to maybe prepend a character like "_" to get around this?

**Comment by JakeWharton** [comment]
You can use `@Json(name = "default")` similar to `@SerializedName`.

**Comment by imminent** [comment]
Yeah, https://github.com/square/moshi/issues/28 just found that. Thanks for being even quicker than my lookup

**Comment by imminent** [comment]
@JakeWharton though I might mention, it would have saved me if that was mentioned round:

"

**Comment by JakeWharton** [comment]
Yep yep: https://github.com/square/moshi/issues/104
