### ISSUE TITLE
Is it possible (and how) to handle alternative representations of the value ?

### ISSUE THREAD

**Issue by semenoh** [square/moshi#1030]
Sometimes the server returns different types of value for the same key. 
For example, if there is only one item in the collection it sends this object instead of an array:
```json
[
  { "items" : [ "item1",  "item2" ] },
  { "items" : "item3" }
]

How can I handle such a situation with Moshi?

**Comment by JakeWharton** [comment]
Please ask general usage questions on StackOverflow with the 'moshi' tag where they are more easily searched, archived, and answered by the Moshi community. Feel free to link the question here when you do.
