### ISSUE TITLE
maven no 1.9.2

### ISSUE THREAD

**Issue by onexuan** [square/moshi#1031]
maven no 1.9.2

https://mvnrepository.com/artifact/com.squareup.moshi/moshi

**Comment by JakeWharton** [comment]
mvnrepository.com is a third-party, often out-of-date index (as evidence by this issue). Do not use it.

Maven Central is indexed at search.maven.org and repo1.maven.org. 1.9.2 is indeed there: http://repo1.maven.org/maven2/com/squareup/moshi/moshi/1.9.2/

**Comment by onexuan** [comment]
OK,Thanks
