### ISSUE TITLE
@RawValue annotation gives error on 1.9.x

### ISSUE THREAD

**Issue by KirkBushman** [square/moshi#1033]
Hi, 

`override val mydate: @RawValue Any`

I have a property of a model that can be float or boolean, 
to handle the type casting problem I was parsing to Any in Moshi 1.8.0,
but once I updated to 1.9.x I get this error: 

> This annotation is not applicable to target 'expression'

It's giving this error in the generated class: 

`private val anyAdapter: JsonAdapter<@RawValue Any> = moshi.adapter(@RawValue Any::class.java, emptySet(), "mydate")
`

Should I get around this issue in another way, that is recommended or is this a bug?

**Comment by ZacSweers** [comment]
What is “RawValue”?

**Comment by KirkBushman** [comment]
It's an annotation that is part of Kotlin Parcelize, it allows to parse a Any object to a HashMap of key/values.
It is a parameter type Annotation, and Moshi brings it in the generated class, where it does not belong and it gives an error.

This did not happen on 1.8.0.

**Comment by ZacSweers** [comment]
Weird. Can you link me the class or paste its source? As a workaround if you can modify it to be applicable to expressions it should work. I think I know what the issue is but need to check with a repro example. The new metadata backend is a lot more thorough than the previous one was on 1.8.0

**Comment by KirkBushman** [comment]
Yes, this is the class https://github.com/KirkBushman/ARAW/blob/master/lib/src/main/java/com/kirkbushman/araw/models/Comment.kt

If you try to move the project from 1.8.0 to 1.9.x you should get the error

**Comment by ZacSweers** [comment]
PR [here](https://github.com/square/moshi/pull/1039), as this does reveal a valid bug. 

That said - I'd highly recommend not trying to mix JSON classes with other serialization types (parcelize, DB entities, etc). For example in this case - `Parcel.writeValue()` or `readValue()` (which RawValue indicates) has very different serialization behavior than Moshi's `Object`/`Any` serialization and result in inconsistent/undefined runtime behavior.

**Comment by KirkBushman** [comment]
Thank you a lot.

I'll keep that in mind.

Is there a chance for you to push a new minor with this fix?

**Comment by KirkBushman** [comment]
Hey, don't want to push things, but... when is the eta of the next minor? just to get rid of these little issues...
