### ISSUE TITLE
CodeGen adapter allows extra property names

### ISSUE THREAD

**Issue by plannigan** [square/moshi#1037]
The adapter that is generated as part of the Kotline CodeGen step ignores any names it does not expect.

```
-1 -> {
  // Unknown name, skip it.
  reader.skipName()
  reader.skipValue()
}
```

It would be nice if there was a "strict" option that throws a `JsonDataException` instead of ignoring the unexpected entry.

**Comment by ZacSweers** [comment]
All Moshi adapters support this via setting `failOnUnknown()` on the adapter or JsonReader passed in. When set, Moshi will throw an exception when skipName or skipValue is called
