### ISSUE TITLE
Kotlin reflection adapter behaves differently from codegen generated adapter

### ISSUE THREAD

**Issue by strooooke** [square/moshi#1043]
In the following situation:

```
data class PushTokenRegistration(val userId: String, val pushToken: String) {
  val platform: String = "android"
}
```

The reflection adapter (same as the Java reflection adapter used to) generates JSON like

```
{
  userId: "foo",
  pushToken: "bar",
  platform: "android"
}
```

as expected by me.

The codegen generated adapter ignores the `platform` property while serializing.

**Comment by swankjesse** [comment]
Yikes, the reflection adapter is incorrect. It should only encode values that it can decode.

**Comment by strooooke** [comment]
I am slightly sad about this - this has been working like this for ages now (with the Java reflection adapter), gives a nice readable declaration in one place - and it _does_ round-trip correctly - there is nothing to do when decoding this field: it cannot be set, but it already has the one possible value.

**Comment by ZacSweers** [comment]
Seems like that belongs in a companion object then? It's effectively a
constant

**Comment by strooooke** [comment]
From my (the client) point of view, it is. It's the server that needs to be told - because the other value is `ios`.

Of course, that problem is solvable by writing a custom Adapter, delegating to the generated one and adding in the additional fields - but I liked that it worked like this beforehand.

And of course, the various automagic adapters behave the same, that's the most important thing.

**Comment by ZacSweers** [comment]
Yeah moshi tries very hard to be symmetric, if you want a write-only value then you should write a custom adapter that delegates/works with the generated one

**Comment by ZacSweers** [comment]
Strangely, this should be covered already https://github.com/square/moshi/blob/efb0fc09230b656387808cf78b47ce966e9322f6/kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt#L239

So something appears to be wrong

**Comment by ZacSweers** [comment]
This appears to be working correctly on master with the repro case

```kotlin
@Test fun valNonParamPropsIgnored() {
  val moshi = Moshi.Builder()
      .add(KotlinJsonAdapterFactory())
      .build()

  val adapter = moshi.adapter<PushTokenRegistration>()
  val instance = PushTokenRegistration("foo", "bar")
  assertThat(adapter.toJson(instance)).isEqualTo("{\"userId\":\"foo\",\"pushToken\":\"bar\"}")
}

data class PushTokenRegistration(val userId: String, val pushToken: String) {
  val platform: String = "android"
}
```
