### ISSUE TITLE
No-op version of moshi-kotlin?

### ISSUE THREAD

**Issue by plnice** [square/moshi#1048]
Hi, we want to setup moshi as follows to speed up debug builds:
```
implementation "com.squareup.moshi:moshi:1.9.2"
implementation "com.squareup.moshi:moshi-adapters:1.9.2"
debugImplementation "com.squareup.moshi:moshi-kotlin:1.9.2"
kaptRelease "com.squareup.moshi:moshi-kotlin-codegen:1.9.2"
```
and use `KotlinJsonAdapterFactory()` in debug builds.

However, that would require adding debug source set, where provider for `Moshi` with `KotlinJsonAdapterFactory` would be set up - since there's no `KotlinJsonAdapterFactory` class for release builds and the build would fail.

Would there be a possibility to prepare no-op version of `moshi-kotlin` artifact to solve the issue? The depedencies configuration would become
```
...
debugImplementation "com.squareup.moshi:moshi-kotlin:1.9.2"
releaseImplementation "com.squareup.moshi:moshi-kotlin-no-op:1.9.2"
kaptRelease "com.squareup.moshi:moshi-kotlin-codegen:1.9.2"
``` 
and we could use the no-op version of `KotlinJsonAdapterFactory()` in release builds.

Or maybe there's another way of how to achieve the state of no annotation processor in debug builds without introducing debug source set?

**Comment by ZacSweers** [comment]
The correct way to do this would be to only add the KotlinJsonAdapterFactory in your debug source set. There are many ways to accomplish this, such as a simple provider interface with different implementations in debug/release.
