### ISSUE TITLE
Codegen: Cannot serialize Kotlin type from custom adapter

### ISSUE THREAD

**Issue by stoyicker** [square/moshi#1054]
I have an API which provides a model that may be an object, or false. I understand this is bad, but it cannot be changed.
Therefore, I have an adapter to handle the situation:

```kotlin
internal class JsonObjectOrFalseAdapter<T> private constructor(
    private val objectDelegate: JsonAdapter<T>?) : JsonAdapter<T>() {
  class Factory(private val objectDelegateFactory: JsonAdapter.Factory) : JsonAdapter.Factory {
    override fun create(type: Type, annotations: Set<Annotation>?, moshi: Moshi) =
        when (hasJsonObjectOrFalseAnnotation(annotations)) {
          false -> null
          true -> JsonObjectOrFalseAdapter(
              objectDelegateFactory.create(type, Collections.emptySet(), moshi))
        }
  }

  override fun fromJson(reader: JsonReader) = when (reader.peek()) {
    JsonReader.Token.BOOLEAN -> when (reader.nextBoolean()) {
      false -> null // Response was false
      else ->
        throw IllegalStateException("Non-false boolean for @JsonObjectOrFalse field")
    }
    JsonReader.Token.BEGIN_OBJECT -> objectDelegate?.fromJson(reader)
    else ->
      throw IllegalStateException("Non-object-non-boolean value for @JsonObjectOrFalse field")
  }

  override fun toJson(writer: JsonWriter, value: T?) =
      objectDelegate?.toJson(writer, value) ?: Unit
}

private fun hasJsonObjectOrFalseAnnotation(annotations: Set<Annotation>?) =
    annotations?.firstOrNull { it.annotationClass == JsonObjectOrFalse::class } != null
```

Today I have tried to migrate my model codebase from using reflect to codegen (v1.9.2) for adapters and now I get an exception for a type annotated with Json(generateAdapter = true) (in fact, all of my models that need adapters are now annotated as such, as I believe this is required) that leads to this adapter. I don't really understand the interaction between manual and generated adapters well enough to tell what's going on, so can I please get some help?

**Comment by rharter** [comment]
It'd be helpful if you could share the exception you're getting.

**Comment by stoyicker** [comment]
```
Caused by: java.lang.IllegalArgumentException: Cannot serialize Kotlin type data.tinder.like.Match. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapter from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
    for class data.tinder.like.Match match
    for class data.tinder.like.LikeResponse
        at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:349)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:150)
        at data.tinder.like.LikeResponseJsonAdapter.<init>(LikeResponseJsonAdapter.kt:25)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:540)
        at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
```

LikeResponse:

```kotlin
@JsonClass(generateAdapter = true)
internal class LikeResponse(
    @field:Json(name = "match")
    @field:JsonObjectOrFalse
    val match: Match?,
    @field:Json(name = "rate_limited_until")
    val rateLimitedUntil: Long?)
```
Match
```kotlin
@JsonClass(generateAdapter = true)
internal data class Match(@field:Json(name = "id") val id: String)
```

**Comment by ZacSweers** [comment]
It seems like it’s not trying to look up the generated adapter, which could be indicative of the JsonClass annotation being stripped at runtime. Are you using proguard or R8? Moshi embeds proguard rules that should keep jsonclass annotations, but maybe your configuration isn’t picking that up.

Also side note: no need for `field:` site targets on `@Json` annotations

**Comment by stoyicker** [comment]
I was testing on a debug version where I had no proguard nor r8. I've set up a test with minifying enabled just because why not, but it'll take a bit until I can get the app to a similar situation to see if it breaks too (I don't see why it wouldn't, anyway).
Good to know about field: not being needed, thanks!

**Comment by rharter** [comment]
Would you mind sharing the @JsonObjectOrFalse definition? I'm curious what
the scope annotations are on that.

**Comment by stoyicker** [comment]
package data.network

import com.squareup.moshi.JsonQualifier

@JsonQualifier
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FIELD)
internal annotation class JsonObjectOrFalse

**Comment by pueffl** [comment]
Just came over this bug because I had the same exception. The problem form me was that I forgot to add KotlinJsonAdapterFactory:

   val moshi = Moshi.Builder()
            .add(jsonApiAdapterFactory)
            .add(PolymorphicJsonAdapterFactory.of(JsonApiError::class.java, "error")
                    .withSubtype(JsonApiErrorBadRequest::class.java, "errorBadRequest")
                    .withSubtype(JsonApiErrorForbidden::class.java, "errorForbidden")
                    .withSubtype(JsonApiErrorNotFound::class.java, "errorNotFound")
                    .withSubtype(JsonApiErrorConflict::class.java, "errorConflict")
                    .withSubtype(JsonApiErrorInternalServerError::class.java, "errorInternal")
                    .withSubtype(JsonApiErrorNotImplemented::class.java, "errorNotImplemented")
            )
            .**add(KotlinJsonAdapterFactory())**
            .build()

**Comment by ZacSweers** [comment]
@pueffl that's not a solution for this case as OP is trying to use code gen, not reflection.

**Comment by ZacSweers** [comment]
@stoyicker can you make a reproducing project? Without seeing your moshi wiring I'm not sure we can help with the available information. Could be as simple as forgetting to register that custom factory. You should be able to breakpoint this and debug it locally yourself to see where it hits in your factory. Let's move this over to stackoverflow for future followups since this is a usage question and not a bug as far as I can see
