### ISSUE TITLE
How to skip data containers

### ISSUE THREAD

**Issue by meruiden** [square/moshi#1055]
Hi, Our backend uses fractal which wraps every subobject in "data": like so:

```json
"graphic": {
    "data": {
        "id": 44833,
        "is_icon": false,
        "graphic": "https://..."
    }
}
```

this forces me to make containers for about everything. so my structure will then become

```
Item
    graphic: GraphicContainer
        data: Graphic
```

is there a workaround for this?

**Comment by ZacSweers** [comment]
You can use something like [an enveloping adapter approach](https://github.com/serj-lotutovici/moshi-lazy-adapters#wrapped). In the future please post usage questions on stackoverflow, as we like to keep this issue tracker just for bug reports and feature requests.

**Comment by meruiden** [comment]
This method works but only for root objects. The Wrapped parameter wont work if specified from a data class rather than the APIInterface so this problem still remains for me. for example:

``` json

{
  "data": {
    "items": [
      {
        "data": {
          "item": {
            "foo": "bar"
          }
        }
      }
    ]
  }
}  
```

With @Wrapped I can get the items list but the item classes still need a data variable containing the actual data.

**Comment by JakeWharton** [comment]
You can write a Moshi adapter which handles enveloping which will work anywhere in the JSON tree.
