### ISSUE TITLE
No JsonAdapter for Generic Type (inside generic function)

### ISSUE THREAD

**Issue by bahung1221** [square/moshi#1056]
Hi there,
I'm facing a error `No JsonAdapter for R` when parsing json to data class inside generic function, i researched and try many way but it still not working. 
The problem is that `generic function` doesn't know what is actually type of generic parameter `R` so i can't manually assign type of R when parsing.

How can i resovle this problem? :(

```kotlin
fun <T, R> sendRequest(msg: Deribit.Request.Message<T>): Deribit.Response.Result<R> {
    ...
        val type = object : TypeToken<Deribit.Response.Result<R>>() {}.type
        
        return moshi.adapter<Deribit.Response.Result<R>>(
            type
        ).fromJson(jsonElement.toString())
    ...
}
```

I also use `reified` function that return `ParameterizedTypeReference` but it still not working
```kotlin
private inline fun <reified T: Any> typeRef(): ParameterizedTypeReference<T> = object: ParameterizedTypeReference<T>(){}
...
// USAGE
val data = moshi.adapter<Deribit.Response.Result<R>>(
            typeRef<Deribit.Response.Result<R>>().type
        ).fromJson(jsonElement.toString())
```

Thank you and best regards!!!

**Comment by ZacSweers** [comment]
Please post on Stackoverflow and use the Moshi tag, as we like to keep the issue tracker just for bug reports or feature requests.

**Comment by bahung1221** [comment]
I posted to stackoverflow https://stackoverflow.com/questions/59553184/no-jsonadapter-for-generic-type-inside-generic-function

Thank you!
