### ISSUE TITLE
Annotations empty in JsonAdapter.Factory create

### ISSUE THREAD

**Issue by MarcWillwacher** [square/moshi#1058]
I defined an annotation:

```kotlin
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS, AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER)
internal annotation class Uncrypted
```

Set this annotation to property:
```kotlin
@JsonClass(generateAdapter = true)
data class CrashReportMeta(
    @Uncrypted
    val platform: String = "android",
    @field:Uncrypted
    val system: String,
    val version: String,
    val crashDate: Date,
    val device: String,
    val crashTyp: CrashReportMetaCrashType,
    val connection: CrashReportMetaConnection,
    val mandant: CrashReportMetaMandant
)
```

In create methode, size of annotations is always "0":

```java
public static final JsonAdapter.Factory FACTORY = new JsonAdapter.Factory() {
        @Override
        public JsonAdapter<?> create(
                Type type, Set<? extends Annotation> annotations, Moshi moshi) {
            if (annotations.size() > 0) Log.d("annotation drin", annotations.toString());
```

**Comment by ZacSweers** [comment]
Can you paste the full generated `CrashReportMetaJsonAdapter`? Which lookup is not reporting annotations? We need more information in order to help

**Comment by MarcWillwacher** [comment]
Thanks for the answer. Sorry, but I found the solution yesterday. Didn't understand that, when an annotated property was handled by an adapter, it is possible to handle it also in the next adapter, but without the annotation. Was a missunderstanding of adapters.

**Comment by realbarisbasturk** [comment]
In case anybody else have the problem with accessing the annotations inside JsonAdapter.Factory#create method, I was missing the @JsonQualifier annotation which needed to be applied to the custom annotation. Also make sure that your custom annotation has RUNTIME retention.
