### ISSUE TITLE
Serialize Map in Kotlin

### ISSUE THREAD

**Issue by mboudraa** [square/moshi#106]
When you try to serialize `Map<String,String>`, Kotlin actually generates wildcards, i.e. `? extends String`.  This seems to confuse Moshi
Moshi tries to generate an adapter for `? extends String` which is the type of the Map's values but doesn't check the default adapters.
Thanks to @cypressious for his remarks

**Comment by cypressious** [comment]
You don't need Kotlin to reproduce it. Here's a minimal failing example in Java:

```java
class Dao {
    Map<String, ? extends String> map;
}

public class MoshiTest {
    @Test
    public void testMoshi() throws Exception {
        new Moshi.Builder().build().adapter(Dao.class);
    }
}
```

**Comment by swankjesse** [comment]
Yup. For strings this is easy. But when the wildcard really means something, we're in trouble. For example, how would we decode this?

`Map<String, ? extends Object>`

Would we use the base type? That's a bit weird because it'll be asymmetrical. I _might_ be overthinking this.

**Comment by mboudraa** [comment]
Maybe we can have a specific use case for simple types like Primitives and Strings

**Comment by cypressious** [comment]
Or final types.

Kirill Rakhman
Am 30.10.2015 12:08 nachm. schrieb "Mounir Boudraa" <
notifications@github.com>:

**Comment by mboudraa** [comment]
By the way it's exactly the same beaviour for all Generics in kotlin. For instance, For `List<Something>` it will generate `List<? extends Something>`.
In addition when we register an adapter class for `Something`, moshi ignores it because it looks for an adapter for `? extends Something`

**Comment by mboudraa** [comment]
@swankjesse Maybe you want me to create another issue to fit the need better ?

**Comment by adelnizamutdinov** [comment]
I stumbled upon the same issue when using kotlin's wildcard collections
I really like what @cypressious suggests, what about treating wildcards such as `? extends FinalType` as `FinalType`?

**Comment by adelnizamutdinov** [comment]
and if I would implement that, would it be sensible to put that into `Types.equals`?

**Comment by adelnizamutdinov** [comment]
in the meantime I'm using this workaround, maybe it'll help someone:

```kotlin
inline fun <reified T : Any> Moshi.Builder.addWithSubtypes(adapter: JsonAdapter<T>): Moshi.Builder =
    add(object : JsonAdapter.Factory {
      val subtype = Types.subtypeOf(T::class.java)

      override fun create(type: Type?, annotations: MutableSet<out Annotation>?, moshi: Moshi?): JsonAdapter<*>? =
          when (type) {
            T::class.java, subtype -> adapter
            else                   -> null
          }
    })
```

**Comment by swankjesse** [comment]
@adelnizamutdinov nice! Yeah, I think we probably just want to treat `? extends Type` as `Type`. I don’t think it’s reasonable to look at the final/nonfinal attribute of the class because that’s often an implementation detail. (Think of Guava’s ImmutableList, which is non-final).

**Comment by JakeWharton** [comment]
I think Kotlin has relaxed the wildcard emission in class files in later betas of 1.0. I'll check today.

**Comment by JakeWharton** [comment]
This works in Kotlin 1.0 or newer
