### ISSUE TITLE
IllegalStateException: Dangling name for nullable value

### ISSUE THREAD

**Issue by roudyirany** [square/moshi#1061]
I have a Kotlin data class that is annotated with `@JsonClass(generateAdapter = true)` and one of its fields is a nullable class marked with a `@Json(name = "")` annotation. If I build my project using Moshi 1.8.0 and the nullable field in the JSON is missing, the value is parsed correctly as null. However, with version 1.9.2, I am getting an `IllegalStateException: Dangling name` error that makes my application crash.

**Comment by ZacSweers** [comment]
Can you give a concrete repro snippet and also paste what the generated adapter code looks like?

**Comment by roudyirany** [comment]
I can't do that as the code I'm working with is not mine, sorry. However, what I suspect is happening:
* Put nullable field in last position in data class constructor
* Add @JsonClass(generateAdapter = true) annotation
* Parse the data class from a JSON response not having that nullable field in it
* deferredName in the writer for the concerned adapter stores the name of the nullable field but the value is non-existent
* When closing that writer, deferredName is not null and it triggers the dangling name error

I think the critical part is the nullable field being in the last position in the field list as I have another nullable field at the beginning of the data class and that one behaves normally.

**Comment by roudyirany** [comment]
Update: Switching the order of the data class fields triggers an IllegalStateException with message "Nesting problem.".
