### ISSUE TITLE
Generate proguard rules in code gen directly

### ISSUE THREAD

**Issue by ZacSweers** [square/moshi#1065]
This way we can generate exact matching rules for what's needed rather than the current blanketed ones.

- Collect rules on a per-processor basis
- For each class
  ```
  -keepnames class {the target class}
  -if class {the target class}
  -keep class {the generated adapter} {
      <init>({exact constructor});
      private final {adapter fields}
  }
  ```
- For each qualifier
  ```
  -keep interface {the qualifier class}
  ```

**Comment by ZacSweers** [comment]
We can also also generate targeted keep rules for the synthetic default constructors we want to keep

**Comment by rbpape** [comment]
Hi @ZacSweers - I've been experiencing some Proguard issues that I think [your commit](https://github.com/square/moshi/commit/debb7d31603b54a2fcf1a51eb0a3c2762772491f) could help fix. Is there a timeline for the next Moshi release?

If a new release is not coming soon, do you think generated Proguard rules are ready to use in a SNAPSHOT version? Is there any configuration needed for generated rules?
