### ISSUE TITLE
Does it support Json key or value sorting?

### ISSUE THREAD

**Issue by Joslyn-Chen** [square/moshi#1066]
Sometimes we need json key or value sorting (alphabetical sorting), and sometimes the order cannot be changed.for example:
`
data class Test(
    val bbb:String = "bbb",
    val ccc:String = "ccc",
    val aaa:String = "aaa"
  )
`
I want:"{"aaa":"aaa","bbb":"bbb","ccc":"ccc"}".
Another problem:If the Test class has a parent class, such as:
`
class BaseTest(
    val fff:String = "fff",
    val ddd:String = "ddd"
  )
`
Does it affect serialization order?

**Comment by ZacSweers** [comment]
Moshi doesn’t offer ordering guarantees for reflective or code gen serialization. If you need a specific order, you should write a custom adapter.
