### ISSUE TITLE
Kotlin List/Array Do Not Deserialize Correctly by Default

### ISSUE THREAD

**Issue by james-novino** [square/moshi#1072]
When using Moshi 1.9.2 with either the Reflection / Code Generation. Kotlin List/Array/Set do not deserialize correctly. Small test case for reproduction: 

```kotlin
    val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    inline fun <reified T> fromJson(x: String): T = this.moshi.adapter(T::class.java).fromJson(x)!!
    inline fun <reified T>  toJson(item: T): String = this.moshi.adapter(T::class.java).toJson(item)
    
    @JsonClass(generateAdapter = true)
    data class TestData(val str: String, val int: Int, val double: Double, val bool: Boolean)

    @Test
    fun `test serialization & deserialization of List`() {
        val obj = listOf(TestData("mario", 10, 5.0, false),  TestData("wario", 20, 10.0, true))
        val serialized = Json.toJson(obj)
        val expected = "[{\"str\":\"mario\",\"int\":10,\"double\":5.0,\"bool\":false},{\"str\":\"wario\",\"int\":20,\"double\":10.0,\"bool\":true}]"
        assert(expected == serialized)
        val deserialized = Json.fromJson<List<TestData>>(serialized)
        assertEquals(obj, deserialized)
    }

   @Test
    fun `test serialization & deserialization of Array`() {
        val obj = arrayOf( TestData("mario", 10, 5.0, false),  TestData("wario", 20, 10.0, true))
        val serialized = Json.toJson(obj)
        assertEquals("[{\"str\":\"mario\",\"int\":10,\"double\":5.0,\"bool\":false},{\"str\":\"wario\",\"int\":20,\"double\":10.0,\"bool\":true}]", serialized)
        val deserialized = Json.fromJson<Array<TestData>>(serialized)
        assertArrayEquals(obj, deserialized)
    }
```

Both the List & Array serialize correctly in the above example, however when trying to deserialize them back into a List or Array, instead of the kotlin.collections values I see ArrayList instead: 

![image](https://user-images.githubusercontent.com/10082447/72391364-ec282800-36fa-11ea-8aa1-9f1514f513fc.png)

**Comment by ZacSweers** [comment]
Reified alone in Kotlin will only give you raw types, not their generic type arguments. You would need to use Types.newParameterizedType() or Kotlin's new typeOf() API

**Comment by james-novino** [comment]
@ZacSweers Neither the `Types.newParameterizedType()` nor Kotlin's new `typeOf()` API. Seem to work for the use case outline above. The `typeOf` endpoint throws an exception which leads me to believe that's not the suggested solution :
```
kotlin.NotImplementedError: An operation is not implemented: Java type is not yet supported for types created with createType (classifier = class kotlin.collections.List)
```

The `Types.newParameterizedType()` returns the same result as before: 
```
    inline fun <reified T> fromJsonList(x: String): List<T> = this.moshi.adapter<List<T>>(Types.newParameterizedType(List::class.java, T::class.java).rawType).fromJson(x)!!
```
The samples seem to be in Java in this repo and there does not seem to be many examples or tests for how this is supposed to work in Kotlin. If these resources exist would greatly appreciate a link or a few snippets about how we are supposed to handle these cases with Moshi.

**Comment by JakeWharton** [comment]
You're calling rawType which negates the advantage of using
Types.newParameterizedType

**Comment by ZacSweers** [comment]
If you want to use reified, you need to implement your own `javaType`, like this: https://github.com/square/moshi/blob/master/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/-MoshiKotlinExtensions.kt

If you want to use `Types.newParameterizedType()`, as Jake mentioned you've misused the API. Even if you removed the `rawType` call, that would only work if your element type is a class and not another generic type. You won't get mileage trying to rely on reified for that case without using `typeOf()`.

There are _tons_ of tests for kotlin, please see the `kotlin` directory of this repo.
