### ISSUE TITLE
No throw exception when Nonnull list item is null

### ISSUE THREAD

**Issue by liangchenhe55** [square/moshi#1085]
version: 1.9.2, use kotlin with kapt

```kotlin
data class Config(
    val id: String,
    val type: String,
    val items: List<BaseItem>
)
```

Since the specific type of `items` is depend on `type`, so I write an custom adapter to resolve `Config` and it may return `null` if the type is not supported.

Since `items` not allow null item, an exception should be thrown when my custom adapter returns an null, but everything is fine. Until I used that item, an NPE happend. Because the definition is notnull, so I do not check it in runtime and IDE gives no warning.

**Comment by ZacSweers** [comment]
It’s hard to advise without seeing your custom adapter for config. Please post on stackoverflow with the `moshi` tag as we like to keep the issue tracker just for bug reports.
