### ISSUE TITLE
CollectionJsonAdapter crashes on JSON object

### ISSUE THREAD

**Issue by adi1133** [square/moshi#109]
I am having an issue when an api returns an object or an array of objects depending on the number of results. 
This behaviour currently crashes moshi with **Expected BEGIN_ARRAY but was BEGIN_OBJECT**
I am using the yahoo geolocation api and I have no way to alter the way it works.
Currently I use a custom JsonAdapter.Factory

Api example that responds with
* an array [Springfield](https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20geo.places%20where%20text%20=%20%22Springfield%22)
* a list [Blytheville](https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20geo.places%20where%20text%20=%20%22Blytheville%22)

Check the json field called **place** in examples above

**Comment by JakeWharton** [comment]
You can use a `JsonAdapter.Factory` to massage broken APIs like this into treating those objects as single element lists.

Something like:
```java
public final class ObjectAsListJsonAdapterFactory implements JsonAdapter.Factory {
  @Override public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
    if (!List.class.isAssignableFrom(Types.getRawType(type))) {
      return null;
    }
    JsonAdapter<List<Object>> listDelegate = moshi.nextAdapter(this, type, annotations);
    Type innerType = Types.collectionElementType(type, List.class);
    JsonAdapter<Object> objectDelegate = moshi.adapter(innerType, annotations);
    return new ListJsonAdapter<>(listDelegate, objectDelegate);
  }

  static class ListJsonAdapter<T> extends JsonAdapter<List<T>> {
    private final JsonAdapter<List<T>> listDelegate;
    private final JsonAdapter<T> objectDelegate;

    private ListJsonAdapter(JsonAdapter<List<T>> listDelegate, JsonAdapter<T> objectDelegate) {
      this.listDelegate = listDelegate;
      this.objectDelegate = objectDelegate;
    }

    @Override public List<T> fromJson(JsonReader jsonReader) throws IOException {
      if (jsonReader.peek() == JsonReader.Token.BEGIN_OBJECT) {
        return Collections.singletonList(objectDelegate.fromJson(jsonReader));
      } else {
        return listDelegate.fromJson(jsonReader);
      }
    }

    @Override public void toJson(JsonWriter jsonWriter, List<T> list) throws IOException {
      listDelegate.toJson(jsonWriter, list);
    }
  }
}
```
Might need to customize to taste.

**Comment by IgorGanapolsky** [comment]
Are there any examples of how to use `JsonAdapter.Factory` in code?

**Comment by swankjesse** [comment]
@IgorGanapolsky not yet! https://github.com/square/moshi/issues/136
