### ISSUE TITLE
Alternative to @JsonClass(generateAdapter = true) for using codegen in external Kotlin classes

### ISSUE THREAD

**Issue by marcosalis** [square/moshi#1090]
Note: I'm using Moshi `1.9.2`.

As far as I'm aware, there is currently no alternative to annotating a Kotlin class with `@JsonClass(generateAdapter = true)` to use codegen for its (de)serialization.
This means that, in order to use Moshi on third party code, or (de)serialize Kotlin classes from a module where Moshi is not wanted as dependency, the only way is to use reflection.

I wonder if it weren't possible to consider declaring "external" classes somewhere else (e.g. in `Moshi.Builder()`) and for the generated class to be placed in the same Gradle module as the Moshi initialization is performed.
Obviously, this would only work with `public` classes and properties, but it would at least allow to get rid of `kotlin-reflect` fully on complex codebases.

**Comment by ZacSweers** [comment]
You should write a custom adapter for classes you don’t control. Aside from limitations on how annotation processing itself works, you almost certainly don’t want code gen to run against types you don’t own because they may have implementation detail behavior that you’d then be encoding.

**Comment by marcosalis** [comment]
What about providing the `@JsonClass` annotation on a separate dependency?
More than third-party code, I'm thinking about Kotlin types you _do_ own but they're on a different Gradle module, one that's Kotlin only or, for whatever reason, you don't want to make it dependant on libraries.
`kapt`, AFAIK, allows accessing classes from other Gradle modules as long as they're accessible at compile time.

**Comment by ZacSweers** [comment]
I don’t understand how extracting the annotation to another library allows you to avoid depending on a library? It’s just a different library, you’d still have to depend on it. If you want it to be compileOnly, you can make moshi compileOnly as well
