### ISSUE TITLE
Expected BEGIN_ARRAY but was NULL for Nullable list 

### ISSUE THREAD

**Issue by randomaspirer** [square/moshi#1096]
I have a data class which has property which is nullable list

```kotlin
@JsonClass(generateAdapter = true)
data class BookResponse(
    @Json(name = "booksList")
    val booksList: List<Book>? = null
)
```

i checked the generated adapter and it is a nullable list but when i run tests and the actual response from JSON is null i get the error
Expected BEGIN_ARRAY but was NULL for Nullable list

Dependency used:
"com.squareup.moshi:moshi:1.9.2"
"com.squareup.moshi:moshi-kotlin-codegen:1.9.2"

**Comment by ZacSweers** [comment]
Please post usage questions on stackoverflow with the moshi tag, and be sure to include more details (sample json, test case, etc).
