### ISSUE TITLE
Moshi only access UTF8 string format?

### ISSUE THREAD

**Issue by aaakinshin** [square/moshi#110]
My code:

1) POJO class
public class LoginResponse {

    public Integer ClientID;
    public String message;
    public String result;
    public String sessionID;
    
}

2) My usage moshi library:

                            Moshi moshi = new Moshi.Builder()
                                    .add(new LoginJsonAdapter())
                                    .build();
                            Log.v("moshi", "moshi 2.3.2");
                            JsonAdapter<LoginResponse> jsonAdapter = moshi.adapter(LoginResponse.class);
                            LoginResponse loginResponse = jsonAdapter.fromJson(mSringModelResponse);

3) My actual JSon from server, example:

mSringModelResponse is simple java String.

{"ClientID":1,"message":"","result":"OK","sessionID":"0213a0c8-01fff99-4f5c-ad96-e8ffddrreerra0cfac0"}

4) but nothing happen, I'll see it on my LogCat. Should I convert mSringModelResponse in UTF-8 format? Or what is problem?

Please, help.

**Comment by JakeWharton** [comment]
I do not see this behavior. Please provide an executable test case that demonstrates the problem. Here's mine:
```java
  static class LoginResponse {
    public Integer ClientID;
    public String message;
    public String result;
    public String sessionID;
  }
  @Test public void issue110() throws IOException {
    Moshi moshi = new Moshi.Builder()
        .build();
    JsonAdapter<LoginResponse> jsonAdapter = moshi.adapter(LoginResponse.class);
    String response =
        "{\"ClientID\":1,\"message\":\"\",\"result\":\"OK\",\"sessionID\":\"0213a0c8-01fff99-4f5c-ad96-e8ffddrreerra0cfac0\"}";
    LoginResponse loginResponse = jsonAdapter.fromJson(response);
    System.out.println("ClientID: " + loginResponse.ClientID);
    System.out.println("message: " + loginResponse.message);
    System.out.println("result: " + loginResponse.result);
    System.out.println("sessionID: " + loginResponse.sessionID);
  }
```

**Comment by JakeWharton** [comment]
Output was:
```
ClientID: 1
message: 
result: OK
sessionID: 0213a0c8-01fff99-4f5c-ad96-e8ffddrreerra0cfac0
```

**Comment by Gilb007** [comment]
Hi JakeWharton, thank you for answer and awesome libraries. 
I've found what problem is.
It turned that does not matter what kind is string (utf8 or unicode).

In moshi library documentation referred to creating own JsonAdapter for converting to java model or to json format. As soon as I commented out 

Moshi moshi = new Moshi.Builder()
                                   // .add(new LoginJsonAdapter())
                                    .build();

Instead of 

Moshi moshi = new Moshi.Builder()
                                    .add(new LoginJsonAdapter())
                                    .build();
All at once happen :)

That's what I had my LoginJsonAdapter():

public class LoginJsonAdapter {

    @FromJson
    LoginResponse eventFromJson(LoginResponse eventJson) {
        LoginResponse loginResponseJsonAdapterEvent = new LoginResponse();
        loginResponseJsonAdapterEvent.ClientID = eventJson.ClientID;
        loginResponseJsonAdapterEvent.message = eventJson.message;
        loginResponseJsonAdapterEvent.result = eventJson.result;
        loginResponseJsonAdapterEvent.sessionID = eventJson.sessionID;
        return loginResponseJsonAdapterEvent;
    }

    @ToJson
    LoginRequest eventToJson(LoginRequest eventModel) {
        LoginRequest json = new LoginRequest();
        json.login = eventModel.login;
        json.password = eventModel.password;
        json.OS = eventModel.OS;
        json.deviceID = eventModel.deviceID;
        return json;
    }
}

An other code was:

public class LoginResponse {

    public Integer ClientID;
    public String message;
    public String result;
    public String sessionID;

}

Moshi moshi = new Moshi.Builder()
                                    .add(new LoginJsonAdapter())
                                    .build();
                            JsonAdapter<LoginResponse> jsonAdapter = moshi.adapter(LoginResponse.class);
                            LoginResponse loginResponse = jsonAdapter.fromJson(mSringModelResponse);

I'm curious what is it..

**Comment by swankjesse** [comment]
@Gilb007 sounds like a better question for StackOverflow.
