### ISSUE TITLE
Multi-byte whitespace Unicode character is not skipped

### ISSUE THREAD

**Issue by reline** [square/moshi#1103]
I have a file from a third-party that begins with the zero width no-break space unicode character (UxFEFF) at the beginning of the file, and Moshi fails on the first char reporting an unexpected string. Is this and other multi-byte whitespace unicode characters planned to be supported? I wrote a test case that fails.

```
public final class JsonUtf8ReaderTest {
    .....
  @Test public void multiByteWhitespaceChar() throws Exception {
    Buffer buffer = new Buffer().writeUtf8("\uFEFF[]");

    JsonReader reader = JsonReader.of(buffer);
    reader.setLenient(true);
    reader.beginArray();
    reader.endArray();
    assertThat(buffer.size()).isEqualTo(0);
  }
```

**Comment by JakeWharton** [comment]
"FEFF" is not whitespace, it's a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). You'll need to detect this and skip it yourself before handing the stream to Moshi.

A simple way to do this is by calling `require(2)` on a `BufferedSource` and then doing a `rangeEquals` against `FEFF` in a `ByteString`.

If you want a more comprehensive implementation, you can check out the implementation added to OkHttp which correlates a BOM to a `Charset`: https://github.com/square/okhttp/blob/3f946d0b13534bcd1662e58624b0fc5816d1cc14/okhttp/src/main/java/okhttp3/internal/Util.kt#L255-L265
