### ISSUE TITLE
Identical identifiers for superclass (object) and subclass (data class) cause @JsonClass to not generate an adapter for the subclass

### ISSUE THREAD

**Issue by igorefremov** [square/moshi#1105]
### Problem
```kotlin
object SomeObject {
    @Parcelize
    @JsonClass(generateAdapter = true)
    data class SomeObject(
        @Json(name = "val1") val aString: String,
        @Json(name = "val2") val anotherString: String
    ) : Parcelable
}
```
results in `build/generated/source/kapt/prodRelease/com.some.project/SomeObject_SomeObjectJsonAdapter.kt` not being generated, which in turn causes a runtime exception when the adapter is needed

`java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class com.some.project.SomeObject$SomeObject`

### Version
```
implementation "com.squareup.moshi:moshi:1.9.2"
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.9.2"
```

### Notes
I'm not sure if `@Parcelize` has anything to do with it or not, as I did not test this without the `@Parcelize` annotation.

### Workaround
Rename the parent object:
```kotlin
object SomeObjectNs {
    @Parcelize
    @JsonClass(generateAdapter = true)
    data class SomeObject(
        @Json(name = "val1") val aString: String,
        @Json(name = "val2") val anotherString: String
    ) : Parcelable
}
```

**Comment by ZacSweers** [comment]
Can you provide a reproducible sample test or project?

**Comment by ZacSweers** [comment]
If renaming it fixes things, that sounds like a kapt caching issue

**Comment by igorefremov** [comment]
@ZacSweers 

[SampleApplication.zip](https://github.com/square/moshi/files/4250937/SampleApplication.zip)

**Comment by swankjesse** [comment]
Tracking as https://github.com/square/moshi/issues/1143
