### ISSUE TITLE
library version inconsistency notice.

### ISSUE THREAD

**Issue by calvinhkf** [square/moshi#1106]
Inconsistent library versions notice.

Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library.

Take com.squareup.okio:okio for example, this library is declared as version 2.1.0 in kotlin/codegen, 1.16.0 in moshi and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take com.squareup.okio:okio for example, if we harmonize all the library versions into 2.1.0. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table is listed below. It shows the overall harmonization effort by modules. The columns represents the number of library APIs and API calls(NA,NAC), deleted APIs and API calls(NDA,NDAC) as well as modified API and API calls(NMA,NMAC). Modified APIs refers to those APIs whose call graph is not the same as previous version. Take the first row for example, if upgrading the library into version 2.1.0. Given that 25 APIs is used in module moshi, 0 of them is deleted in a recommended version(which will throw a NoMethodFoundError unless re-compiling the project),  23 of them is regarded as modified which could break the former API contract.

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|moshi|25(40)|0(0)|23(37)|
|2|kotlin/codegen|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. The table is listed below. 

|Module|File|Type|API|
|-|-|-|-|
|moshi|moshi/src/test/java/com/squareup/moshi/JsonUtf8WriterTest.java|modify|okio.Buffer.readUtf8()|
|moshi|moshi/src/test/java/com/squareup/moshi/JsonUtf8WriterTest.java|modify|okio.Buffer.writeUtf8(java.lang.String)|
|moshi|moshi/src/test/java/com/squareup/moshi/JsonValueWriterTest.java|modify|okio.Buffer.writeUtf8(java.lang.String)|
|4|..|..|..|

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[square moshi.pdf](https://github.com/square/moshi/files/4273055/square.moshi.pdf)

**Comment by ZacSweers** [comment]
It's an implementation detail in code gen

**Comment by JakeWharton** [comment]
Okio 2 is binary compatible with Okio 1 which is enforced by the japicmp project so any incompatibility would be a severe problem for Okio but not Moshi.

One other note: the moshi and kotlin/codegen libraries should never be on the same classpath such that their dependencies interact in resolution of a single artifact. kotlin/codegen is for the processorpath and the moshi is for the runtime classpath.

**Comment by calvinhkf** [comment]
The tool right now do not take library and project runtime into consideration. Sorry for that false positive and thanks for your detailed reply~
