### ISSUE TITLE
Moshi does not respect Kotlin non-nullable properties.

### ISSUE THREAD

**Issue by fpsulli3** [square/moshi#1108]
Greetings. I am trying to follow the recommendation in the README

> Moshi is a great JSON library for Kotlin. It understands Kotlin’s non-nullable types and default parameter values. When you use Kotlin with Moshi you may use reflection, codegen, or both.

A simple example to replicate the issues I'm seeing (using codegen):

```kotlin
// Defined in src/main
@JsonClass(generateAdapter = true)
data class MyDto(
        val id: String,
        val status: Boolean)

   // Defined in src/test
    @Test
    fun simpleTest() {
        val moshi: Moshi = Moshi.Builder()
                .build()

        val someAdapter = moshi.adapter(MyDto::class.java)
        val dto = someAdapter.fromJson("{\"status\":false}")

        requireNotNull(dto)

        Assert.assertNull(dto.id)
    }
```
This test will pass (indicating that the id is null, despite being a non-nullable property).

I have kapt enabled and I am using the moshi-kotlin-codegen library:

```
// plugins
apply plugin: 'java-library'
apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'


    // In my dependencies
    kapt "com.squareup.moshi:moshi-kotlin-codegen:1.9.2"
```

I have also tried this with reflection / KotlinJsonAdapterFactory with the same result (id=null)

I have checked related issues but they either say to use reflection/KotlinJsonAdapterFactory (which doesn't work) or they refer to slightly different problems (e.g. null values in lists, nullability in generic type params, etc.)

Any help you can give would be much appreciated. My apologies if it turns out I'm just doing something dumb.

**Comment by swankjesse** [comment]
Got this?
```
implementation "com.squareup.moshi:moshi:1.9.2"
```

**Comment by fpsulli3** [comment]
Yes. It compiles and everything. I only included the codegen dependency in my example in order to show I've set up the annotation processor.

**Comment by fpsulli3** [comment]
Ok this is interesting. It passes when I run the tests from Android Studio, but it fails when running the test from the gradle CLI. 

(in the case the expected behavior is that the test would fail)

So I don't know what's going on here but it doesn't sound like a Moshi problem. I'll close this; hopefully someone will find it useful.
