### ISSUE TITLE
Should JsonEncodingException extend IOException

### ISSUE THREAD

**Issue by matejdro** [square/moshi#1109]
As mentioned in https://github.com/square/moshi/issues/829#issuecomment-477703187, `IOException` means that something is wrong with the transport of the data.

However, `JsonEncodingException` extends `IOException`, even though it does not necessarily signify transport error. For example, server could return malformed JSON or not return JSON at all - some badly programmed servers can return HTML instead of JSON whenever error occurs.

**Comment by JakeWharton** [comment]
Possibly. But can we compatibly change it? I'm not so sure...

**Comment by swankjesse** [comment]
Expecting HTML but getting JSON is a transport error. Something failed in the negotiation of content types.

I don’t think there’s any action to take here.

**Comment by matejdro** [comment]
Is it transfer error though? 

I thought transfer error means that something went wrong while transferring data from the server. But in this case data was transferred just fine, only server returned invalid data.

**Comment by swankjesse** [comment]
Transfer – the pipes work.
Transport – the pipes work and are hooked up to the right inputs and outputs.

I think JsonEncodingException and IOException cover all transport errors, not just physical connectivity.

**Comment by matejdro** [comment]
Alright, thanks for the explanation.
