### ISSUE TITLE
JsonDataException issue. How to ignore this ?

### ISSUE THREAD

**Issue by ChinhQT** [square/moshi#1110]
Hi, 

I want to ignore this issue. How to resolve this issue ?
Success -> data : [HomeData]
Fail -> data : ""
So, I can't parse the json. It will occur below crash. How to fix this ?

JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.data

**Comment by JakeWharton** [comment]
Please ask general usage questions on StackOverflow with the 'moshi' tag. The issue tracker is only used for bugs and feature requests. Feel free to link your question here, though, once created.
