### ISSUE TITLE
I created a moshi-java-codgen

### ISSUE THREAD

**Issue by nename0** [square/moshi#1113]
`error: @JsonClass can't be applied to X: must be a Kotlin class`

Well, I though, I have to create it myself. So here it is:

[nename0/moshi-java-codegen](https://github.com/nename0/moshi-java-codegen)

Has been an interesting project so far, diving into annotation processing, java source parsing and generation. I was able to use kotlin-codegen and LoganSquare as a reference. There are many test cases with odd cases like getters of inherited fields and shadowed fields. Also I started writing java 14 source and down-compiling to java 8 using [jabel](https://github.com/bsideup/jabel).
Also I would not disagree integrating this into the main moshi project if you want.

There are still some TODOs: 
- Support for non-nullary constructors (especially for java 14 record classes)
- Override json annotations in the adapter instead of Types.getFieldJsonQualifierAnnotations to prevent reflection (even the koltin-codegen does not do this but does not seem to hard to do)

**Comment by swankjesse** [comment]
This is cool!

We are unlikely to ship something like in Moshi itself this because we can’t make reflection and codegen equivalent. Our Java reflection does stuff you can’t do with codegen.

No action to take here.
