### ISSUE TITLE
Part of JSON is not parsed.

### ISSUE THREAD

**Issue by robertlevonyan** [square/moshi#1114]
I have an array of JSON objects like this:
`
{
	"id": 2,
	"transport_id": 1,
	"stop_id": 466,
	"reverse": 0
}
`
I've tried to convert it to a Kotlin data class, but seems only `"id"` is parsed.

**Comment by JakeWharton** [comment]
Please provide an executable test case or reproducing sample.

**Comment by robertlevonyan** [comment]
I've added moshi-kotlin-codegen with retrofit converter and it starts to work. Thanks!
