### ISSUE TITLE
Do not reference kotlin.Metadata

### ISSUE THREAD

**Issue by mopsalarm** [square/moshi#1115]
After updating from moshi 1.8.0 to 1.9.2 `kotlin.Metadata` annotations are suddenly kept by r8, which increases apk size on android unnecessarily. My guess is the class lookup in https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/internal/Util.java#L57

This is really not required if you are only using generated adapters for kotlin classes and don't want to use the `ClassJsonAdapter` at all.

**Comment by rharter** [comment]
Hmm, the only keep rule for `kotlin.Metadata` that we add is in the kotlin-reflect artifact.  Codegen also keeps the synthetic constructors marked with that, but I wouldn't expect that would keep the annotation.  Can you ensure you don't have the reflect artifact?

**Comment by mopsalarm** [comment]
Yes I am not using the reflect artifact. The line of code I highlighted in the issue is not present in the 1.8.0 release, so my guess is that r8 is smart enough to realize that the kotlin.Metadata class is used via r reflection and keeps it because of that.

**Comment by JakeWharton** [comment]
Ask it? `-whyareyoukeeping class kotlin.Metadata`

**Comment by mopsalarm** [comment]
Seems like my guess was correct:
moshi 1.9.2 

```kotlin.Metadata
|- is reflected from:
|  void com.squareup.moshi.internal.Util.<clinit>()
|- is reachable from:
|  com.squareup.moshi.internal.Util
|- is referenced from:
|  com.squareup.moshi.JsonAdapter com.squareup.moshi.Moshi.adapter(java.lang.reflect.Type,java.util.Set,java.lang.String)
|- is invoked from:
|  void com.pr0gramm.app.api.pr0gramm.Api_TagDetails_TagInfoJsonAdapter.<init>(com.squareup.moshi.Moshi)
```

Moshi 1.8.0

```Nothing is keeping kotlin.Metadata```

**Comment by Tolriq** [comment]
Faced the same after finding a workaround for my generics issue.
Adding 
```
-assumevalues public class com.squareup.moshi.internal.Util {
  private static final * METADATA return null;
}
```
To R8 config does workaround this.

**Comment by Tolriq** [comment]
FYI: Asked R8 team https://issuetracker.google.com/issues/152811099

Seems only a workaround is available for now.

**Comment by Thomas-Vos** [comment]
Hello @Tolriq, I tried your [workaround](https://github.com/square/moshi/issues/1115#issuecomment-606105674) by adding assumevalues but it does not work for me with Moshi 1.9.2/1.9.3. Do you have any suggestions?

```
-assumevalues public class com.squareup.moshi.internal.Util {
  private static final * METADATA return null;
}
-whyareyoukeeping class kotlin.Metadata
```

```
|- is reflected from:
|  void com.squareup.moshi.internal.Util.<clinit>()
|- is reachable from:
|  com.squareup.moshi.internal.Util
|- is referenced from:
|  java.lang.Object com.squareup.moshi.ClassJsonAdapter.fromJson(com.squareup.moshi.JsonReader)
|- is overriding method:
|  java.lang.Object com.squareup.moshi.JsonAdapter.fromJson(com.squareup.moshi.JsonReader)
|- is invoked from:
...
```

**Comment by mopsalarm** [comment]
There is a pull request with the workaround to not reference it still open.

**Comment by Tolriq** [comment]
Assume value no more works with last R8.

The proper fix is yet to be merged :(

I hope my 2 PR are one day merged and a new release is made.
