### ISSUE TITLE
How make sure generated adapters are using?

### ISSUE THREAD

**Issue by beigirad** [square/moshi#1122]
I added code-gen dependency and then added `@JsonClass(generateAdapter = true)` on my data classes.

I saw generated classes in the build folder, and there were all of them after decompiling the `.apk`. but I didn't find any reference to the generated adapter in the decompiled code that stands for using those.

Should I register all generated adapter explicitly somewhere?

How make sure that generated adapters are using or other methods are used for serializing/deserializing?

**Comment by worldsnas** [comment]
AFAIK you need to register each one of the manually on Moshi to work.
I usually use debugger to see if Moshi goes through my adapters or not. But I guess you can achieve this with test way better.
There is Kotshi lib that can help with wiring generating adapters together

**Comment by beigirad** [comment]
Thanks for your reply. 
Amazingly without any registration debugger goes through adapters.

It seems `moshi-kotlin-codegen` uses reflection. In `fromJson` method of adapters doesn't call my data class constructors. Why?

```
    @Suppress("UNCHECKED_CAST")
    val localConstructor: Constructor<TransactionList.Response.TransactionItem> =
        this.constructorRef ?:
        TransactionList.Response.TransactionItem::class.java.getDeclaredConstructor(Long::class.javaObjectType,
        String::class.java, Double::class.javaObjectType, Double::class.javaObjectType,
        Double::class.javaObjectType, Date::class.java, String::class.java,
        Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef =
        it }
    return localConstructor.newInstance(
        transactionId,
        paymentType,
        debit,
        credit,
        total,
        createdDate,
        description,
        mask0,
        null
    )
```

Isn't this against the purpose of using adapters (stop using reflection and better performance)?

**Comment by rharter** [comment]
this simply uses a small bit of reflection (not kotlin-reflect) to look up the default constructor of data classes. Otherwise it's not possible to support Kotlin's constructor's default value scemantics. This was a trade-off between supporting Kotlin features the way users expect, and looking up a single constructor with reflection (one time, then the resolved constructor is cached).

You can read more of the details in PR #896

**Comment by rharter** [comment]
also, you dont need to register them as you found  the standard adapter looks for a codegen adapter, then falls back to the reflection adapter if one isnt available.
