### ISSUE TITLE
Labels must be unique

### ISSUE THREAD

**Issue by candeiasdan** [square/moshi#1124]
Is there any limitation for Moshi to use unique labels while using `PolymorphicJsonAdapterFactory`?

I see that a PR was merged (https://github.com/square/moshi/pull/856) to allow the use of multiple SubTypes, but keeping a unique label.

Currently Moshi does support the following:
```
Moshi moshi = new Moshi.Builder()
.add(PolymorphicJsonAdapterFactory.of(Message.class, "type")
    .withSubtype(Success.class, "success")
    .withSubtype(Success.class, "data")
.build();

```

I would expect to be able to do:
```
Moshi moshi = new Moshi.Builder()
.add(PolymorphicJsonAdapterFactory.of(Message.class, "type")
    .withSubtype(Data.class, "data")
    .withSubtype(AnotherData.class, "data")
.build();
```

Is it possible to achieve such behaviour with `PolymorphicJsonAdapterFactory`?

**Comment by swankjesse** [comment]
No, definitely not. Otherwise it wouldn’t be able to pick the right type when decoding.
