### ISSUE TITLE
Add the ability to track data mapping issues

### ISSUE THREAD

**Issue by LachlanMcKee** [square/moshi#1126]
The `EnumJsonAdapter` provides the ability to specify an unknown fallback value. This is a great feature that can help avoid bugs.

However I feel that there are some scenarios where the developer may want to know when this happens. Perhaps that is an unexpected value that should be handled differently than others.

The `EnumJsonAdapter` does this fallback silently, and does not keep track of this.

My proposal is to add mechanism to the `JsonReader` that can be used to track these types of data mapping issues.

I raised the following PR to demonstrate this: https://github.com/square/moshi/pull/1125

Is this something worthwhile for the project? Another way I could solve this would be to wrap the `JsonReader` in a special reader that does this.

I am interested in also expanding upon this by adding the ability to filter out invalid elements from List/Sets and also log this.

I have another branch that expands upon this PR that can be found here: https://github.com/LachlanMcKee/moshi/commit/a6aa429030ba1325e8d6028669c8d6bd8720eadc (note: this code is not production ready, just wanted to get something working to demonstrate the concept)

**Comment by rharter** [comment]
Thanks for proposing this and sharing an example PR. I agree with you about the problem statement, but I'm not sure the proposed solution is ideal.

Adding custom functionality into the JsonReader for a specific class of object, Enums, violates some of Moshi's compostable nature, and that could easily be handled by the EnumJsonAdapter itself. Additionally, adding things to the reader to handle debug cases isn't ideal. 

Something I'd be more in favor of is adding an option to the EnumJsonAdapter itself to provide this functionality. Having a SAM interface that allowed the user to provide a custom action for unmatched strings would allow the user to do this without adding weight to the JsonReader.

```
EnumJsonAdapter.of(MyEnum.class)
  .onUnknownValue((name) -> {
    Log.d(TAG, "Unknown JSON type: " + name);
  })
  ...
```

While that's an option, I'm not sure I'm entirely convinced. what I've done in the past is only add unknown value support in production and let it crash in internal builds, or log unknown instances at the consumption point. Given the debug nature of this is might also make sense to just wrap the EnumJsonAdapter in another super thin one that reports unknown values, but only in debug builds.

**Comment by LachlanMcKee** [comment]
Hi @rharter. Thanks for getting back to me.

I was considering this as a legitimate production feature, not a debugging feature.

I mentioned in my issue further down that this could be extended to also tracking other invalid data such as filtered list elements.

While I agree it makes sense to have these unknown instances crash, you cannot always trust that the backend you are supporting doesn't necessarily change the enums at a later date.

I had also considered adding this at the point of the consumption point, however there is a good reason to keep track of this data at the point of parsing.

- If you were able to have this audit data in something like Retrofit, you could actually enrich this bad JSON logging with extra metadata from the API itself (headers/URL/parameters.
- Lets say you get several list/enum data mapping issues from a single API request. If you group them in the AuditData object, you can avoid sending multiple logs, and send a unified log to your error tracking service.

Another potential avenue is to create a special `AuditJsonReader` that extends and potential delegates to `JsonReader`. This would at least overburdening the `JsonReader`, but give developers the ability to keep track of this content.

**Comment by LachlanMcKee** [comment]
@rharter I have created a second PR to demonstrate what would need to be done to do this via delegation -> https://github.com/square/moshi/pull/1131

I think it would be quite useful to make the JsonReader an interface regardless of whether or not this change goes in. As this would expose the ability for me to create a companion library that would provide this functionality without affecting the main library (with the exception of some tweaks to the enum adapter potentially)

**Comment by swankjesse** [comment]
No further action for this in-framework.
