### ISSUE TITLE
DefaultIfNull generic annotation

### ISSUE THREAD

**Issue by saqibmirza2007** [square/moshi#1127]
Is there a way to achieve default if null functionality without using any custom adapter of moshi as making custom adapter for each data class is a bit hectic

**Comment by JakeWharton** [comment]
You can write a JsonAdapter.Factory that works for whichever types you want based on the annotation presence. There is no built-in mechanism for this otherwise.

**Comment by saqibmirza2007** [comment]
@JakeWharton  can you please share some kind of example that how can I achieve such thing. Like you are saying that if I want a String to map default value if null occurs and I will use that annotation in every data class without defining separate Adapter fro that class

**Comment by JakeWharton** [comment]
I see you're participating in #843. Let's keep discussion there as we're not going to add this functionality to the library directly, but it is possible to build such functionality yourself.
