### ISSUE TITLE
complex generic

### ISSUE THREAD

**Issue by SpringSmell** [square/moshi#1128]
for example class

BaseBean<BaseBeanT>{
    data1:**BaseBeanT**
    code:String
}

**BaseBeanT**<Page>{
   data2:**Page**
}

**Page**{
....
}

for example json

	"code": 1,
	"msg": "msg1",
	"data1": {
	      "code": 2,
		"msg": "msg2",
		"data2": {
			"code": 3,
			"msg": "msg3"
		}
	}

A<**B**> -> **B**<C> C...

I try to do :
Types.newParameterizedType(BeanJava::class.java, BaseBeanT::class.java, Page::class.java)

I failed
What should I do, please

**Comment by angusholder** [comment]
The code you've posted isn't very clear and seems to have some copy paste mistakes, but if I understand right, you're trying to use a type `BeanJava<BaseBean<Page>>`? If so, you want to nest `Types.newParameterizedType` in the same way, like 

    Types.newParameterizedType(
        BeanJava::class.java, 
        Types.newParameterizedType(BaseBean::class.java, Page::class.java)
    )

**Comment by swankjesse** [comment]
Unclear what action to take on this.
