### ISSUE TITLE
 HTTP FAILED: java.lang.IllegalArgumentException: Unable to create converter for class

### ISSUE THREAD

**Issue by saqibmirza2007** [square/moshi#1129]
I have recently updated Moshi From 1.6.0 to 1.9.2. Previously it worked fine but after update it is giving me this exception  

<-- HTTP FAILED: java.lang.IllegalArgumentException: Unable to create converter for class com.signinghub.sdk.models.responses.RMLogin
 D/OkHttp:     for method Authenticate.clientTokenRefresh

Here is my retrofit builder

 `val moshiBuilder = Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()
        retrofit = Retrofit.Builder()
            .baseUrl(baseURL)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(MoshiConverterFactory.create(moshiBuilder))
            .client(client.build())
            .build()`
 
And this is the Model class

`class RMLogin : BaseResponseModel() {

    @field:Json(name = "expires_in")
    var expiresIn: String = ""

    @field:Json(name = "access_token")
    var accessToken: String = ""

    @field:Json(name = "refresh_token")
    var refreshToken: String = ""

    @Transient
    var tokenExpiryTime: Long = 0L
}`

Is there anyone who can sort out this issue as I have been stuck. Thanks

**Comment by imayank91** [comment]
I have also been stuck with a similar situation.

**Comment by rharter** [comment]
StackOverflow is really the place for this kind of question.  [Here's a similar question](https://stackoverflow.com/questions/58900504/unable-to-create-body-converter-for-class-in-retrofit-using-moshi#comment104193950_58900933) with an answer, and the OP even posted the actual solution.

This looks like when you upgraded you didn't add the somewhat newer `moshi-kotlin` artifact.  If you'd like to avoid the reflection you can use the `moshi-kotlin-codegen` artifact instead.  Details here: https://github.com/square/moshi#kotlin

**Comment by YonasTatek** [comment]
did You add this line in `build.gradle(module:app)` file
in the plugin section
`id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.10'`
