### ISSUE TITLE
Failed to find the generated JsonAdapter class ClassNotFoundException

### ISSUE THREAD

**Issue by imayank91** [square/moshi#1130]
I have recently upgraded to Moshi 1.9.2 and I have been getting the following error

```
@JsonClass(generateAdapter = true)
@Parcelize
data class Help(
    val title: String,
    val detail: String?,
    val sub: List<Help>?
) : Parcel
```

`java.lang.RuntimeException: Failed to find the generated JsonAdapter class`

**Comment by rharter** [comment]
see [my response[(https://github.com/square/moshi/issues/1129#issuecomment-616213172) to the other issue you commented on.
