### ISSUE TITLE
Control serialization and deserialization separately?

### ISSUE THREAD

**Issue by yizems** [square/moshi#1140]
like fastJson:

```java

@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER })
public @interface JSONField {
    /**
     * config encode/decode ordinal
     * @since 1.1.42
     * @return
     */
    int ordinal() default 0;

    String name() default "";

    String format() default "";
   // look this
    boolean serialize() default true;

    boolean deserialize() default true;

    SerializerFeature[] serialzeFeatures() default {};

    Feature[] parseFeatures() default {};

    String[] alternateNames() default {};
}

```
serialize() and  deserialize() method independent

**Comment by JakeWharton** [comment]
For what purpose? It's hard for me to come up with a case for this that doesn't involve trying to mix and match models across domains.

**Comment by yizems** [comment]
sometimes,the service will return many flags. These flags do not need to be returned. It is not suitable to create an entity class separately.

And I also found some other problems, like this: 

```json
{
    "bbb": {
        "a": 1
    }
}
```

```json
{
    "bbb": ""
}
```

Some fields have a different structure when they have a value and when they have no value;

I deeply understand that this is not a problem of the framework, but I do n’t know what to do, not all services can give standardized json;
