### ISSUE TITLE
add adapter  to first of list if call newBuilder

### ISSUE THREAD

**Issue by dkonurov** [square/moshi#1141]
I add KotlinJsonAdapterFactory. when I call newBuilder of moshi  I cannot add my adapter for seealed class before old custom adapter's. If I try parse from Json sealed class KotlinJsonAdapterFactory throw Exception.

**Comment by swankjesse** [comment]
I wonder if we should just have a method like `addLast()` that pins adapters to the end of the list.

**Comment by ZacSweers** [comment]
I just ran into this same need in a project and would be game for an addLast(). Or make the builder factories list mutable (similar to what we do in javapoet/kotlinpoet builders)

**Comment by swankjesse** [comment]
Fixed in the upcoming release.
