### ISSUE TITLE
Question: Enum, codegen and proguard

### ISSUE THREAD

**Issue by glureau-betclic** [square/moshi#1147]
Trying to use an enum with Moshi-kotlin-codegen (1.9.2).

    enum class LevelDto {
        @Json(name = "low") low,
        @Json(name = "high") high
    }

This version is not safe for proguard, but I'm not sure if I should add a `@Keep` (or a proguard rule to preserve all enums) or a `@JsonAdapter(generateAdapter = false)`. The only "documentation" that I found points to use the latter, but it's 2 years old so I'd have a confirmation if possible.

https://github.com/square/moshi/blob/0c85eae34af00ecbee46beaa5b25fb4af00fb9f2/moshi/src/main/resources/META-INF/proguard/moshi.pro#L12

If it's still right, maybe editing the README.md could help future users?

**Comment by ZacSweers** [comment]
Feel free to send a PR to the README!
