### ISSUE TITLE
@Json annotation on enum values

### ISSUE THREAD

**Issue by ChristianBecker** [square/moshi#115]
Another difference between Gson and Moshi is, that Gson allows its `@SerializedName` annotation on enums:

```
enum CustomEnum {
  @SerializedName("not_a") a,
  b
}

@Test
public void testSerializedName() throws Exception {
  CustomEnum a = gson.getAdapter(CustomEnum.class).fromJson("not_a");
  assertThat(a).isEqualTo(CustomEnum.a);
}

@Test
public void testJson() throws Exception {
  CustomEnum a = moshi.adapter(CustomEnum.class).fromJson("not_a");
  assertThat(a).isEqualTo(CustomEnum.a);
}
```

This will work with Gson. Unfortunately, Moshi does not process its `@Json` annotation on enums.

Is this a desired behaviour is this just a missed edge case?

**Comment by swankjesse** [comment]
Yeah, that’s worth doing.

**Comment by inder123** [comment]
If you are going to do this, I recommend supporting a regex name:
The semantics should be that first an exact match is honored, then a reg-ex match.
This allows you to define a catch-all value, and also match uppercase/lower-case names to the same enum value.
