### ISSUE TITLE
How to implement custom adapters which can only serialize in 1.9.x?

### ISSUE THREAD

**Issue by davechallis** [square/moshi#1150]
I've got some classes that can be serialized into JSON, but can never be created from JSON. Using Kotlin and Moshi 1.8.0, I had adapters of the form:

```
class FooAdapter {
    @ToJson fun toJson(foo: Foo): Map<String, Any?> {
        return emptyMap()
    }
}

val moshi = Moshi.Builder()
    .add(FooAdapter())
    .add(KotlinJsonAdapterFactory())
    .build()

val adapter = moshi.adapter(Foo::class.java)
val json = adapter.toJson(Foo())
```

This worked fine in 1.8.0, but after upgrading to Moshi 1.9.2, with the same code above I get the following error:

```
java.lang.IllegalArgumentException: No @FromJson adapter for class com.example.Foo (with no annotations)
```

How can I change the above to work with Moshi 1.9.2 in order to define serialization only for a class?

The real class in question I'm working with represents a database transaction, so cannot be constructed directly from JSON, it can only be serialized (selected fields only of course).

**Comment by JakeWharton** [comment]
The recommended pattern is to have matching `@FromJson` whose body is `throw UnsupportedOperationException()`. Having symmetric serialization methods ensures that the behavior in both directions is well defined and self-documenting.

**Comment by davechallis** [comment]
@JakeWharton perfect, that works for me.
