### ISSUE TITLE
Codegen Adapters trying to set properties without backing fields

### ISSUE THREAD

**Issue by dhleong** [square/moshi#1151]
I have a model that looks something like this:

```kotlin
@Parcelize
@JsonClass(generateAdapter = true)
data class TimelineEntry internal constructor(
  val path: String,
  internal var durationLong: Long
) : Parcelable {


  var duration: Millis
    get() = Millis(durationLong)
    set(value) {
      durationLong = value.msValue
    }

}
```

where `Millis` is an `inline class`, and we have this weird extra `Long` field to work around a bug in `@Parcelize` where it doesn't handle inline classes correctly.

Even though the `Millis` property is not backed by a field, the moshi codegen tries to create an adapter for the `Millis` class, has an extra step in `fromJson` where it tries to set this property on `result`, and also writes it out in `toJson`.

Since `duration` does not have a backing field, the compiler won't let us mark it with `@Transient` to instruct Moshi to ignore it.

**Comment by dhleong** [comment]
See https://github.com/dhleong/moshi/commit/6b10dbd24269381823754839b4973928a78213c7 linked above which demonstrates that the generated adapter attempts to create a JSON adapter for the property type in the absence of inline classes.

**Comment by dhleong** [comment]
Pushed a fix (linked above) that fixes the issue without breaking other codegen tests. If you agree with this issue I'd be happy to open a PR!

**Comment by JakeWharton** [comment]
If you have a failing test and a fix please feel free to send a PR!
