### ISSUE TITLE
Is it possible to ignore unexpected type while parsing? 

### ISSUE THREAD

**Issue by egek92** [square/moshi#1154]
Like expecting Int but getting String for a field but instead of throwing exception I want to ignore that field.

**Comment by swankjesse** [comment]
There's a bunch of mechanism we could implement to make this possible, but it's difficult to do generally because the boundary of what to ignore is not obvious.

In the interim you can handle this specific case by writing a JsonAdapter for Int that calls skipValue if the type isn't as expected.
