### ISSUE TITLE
Critique and proposition for test improvement

### ISSUE THREAD

**Issue by Xiirf** [square/moshi#1157]
&emsp;We are 3 students who are making an analysis of your project’s tests as a school project.
As a result of this analysis, we wanted to suggest you some improvements:

**1. Project config troubleshooting**
&emsp;Before taking on the tests, we had some trouble running the all thing, on several IDEs (Eclipse, Netbeans...). The problem originated from the lack of encapsulation of the plugins tag by the pluginManagement tag in several maven config files (pom.xml):

`<build>`
&emsp;`<plugins>`
&emsp;&emsp;`<plugin>`
&emsp;&emsp;&emsp;`...`

to

`<build>`
&emsp;`<pluginManagement>`
&emsp;&emsp;`<plugins>`
&emsp;&emsp;&emsp;`<plugin>`
&emsp;&emsp;&emsp;&emsp;`...`

**2. Unit tests**

&emsp;While studying your unit tests, we noticed that there was a duplication of code. For example, in the test file [AdapterMethodsTest.java](https://github.com/square/moshi/blob/master/moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java)

```JAVA
Moshi moshi = new Moshi.Builder()
        .add(new PointWriterAndReaderJsonAdapter())
        .build();
JsonAdapter<Point> pointAdapter = moshi.adapter(Point.class);
```

is used in almost all the test. It would be better to have a method to create the JsonAdapter:

```JAVA
private JsonAdapter<Point> createJsonAdapter(Class... classes) throws Exception {
    Moshi.Builder builder = new Moshi.Builder();
    for (Class c : classes) {
      builder.add(c.newInstance());
    }
    Moshi moshi = builder.build();
    return moshi.adapter(Point.class);
  }
```

&emsp;Furthermore, it is recommended to have a single assert per test to see easily why the test failed. For example, the following test, in the file [JsonAdapterTest,](https://github.com/square/moshi/blob/master/moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java) has multiple assert and each one can fail for a different reason.

```JAVA
@Test public void nonNull() throws Exception {
    JsonAdapter<String> toUpperCase = new JsonAdapter<String>() {
      @Override public String fromJson(JsonReader reader) throws IOException {
        return reader.nextString().toUpperCase(Locale.US);
      }

      @Override public void toJson(JsonWriter writer, String value) throws IOException {
        writer.value(value.toUpperCase(Locale.US));
      }
    }.nonNull();

    JsonReader reader = factory.newReader("[\"a\", null, \"c\"]");
    reader.beginArray();
    assertThat(toUpperCase.fromJson(reader)).isEqualTo("A");
    try {
      toUpperCase.fromJson(reader);
      fail();
    } catch (JsonDataException expected) {
      assertThat(expected).hasMessage("Unexpected null at $[1]");
      assertThat(reader.nextNull()).isNull();
    }
    assertThat(toUpperCase.fromJson(reader)).isEqualTo("C");
    reader.endArray();

    JsonWriter writer = factory.newWriter();
    writer.beginArray();
    toUpperCase.toJson(writer, "a");
    try {
      toUpperCase.toJson(writer, null);
      fail();
    } catch (JsonDataException expected) {
      assertThat(expected).hasMessage("Unexpected null at $[1]");
      writer.nullValue();
    }
    toUpperCase.toJson(writer, "c");
    writer.endArray();
    assertThat(factory.json()).isEqualTo("[\"A\",null,\"C\"]");
  }
```
**3. Test proposition**

&emsp;At the moment we have found two design techniques applicable to the project. The first one is Metamorphic testing and the second one is the same using random input data.

&emsp;We have implemented the first one, the metamorphic tests with the main functionalities: the transformation of a JAVA object into a JSON object (with the toJSON method) and the transformation of a JSON object into a JAVA object (fromJson). The goal is to create a JAVA object, transform it into JSON and then transform the JSON object into a JAVA object. The attributes of the initial JAVA object must have the same values as the attributes of the JAVA object created at the end in order for the test to work. Let's see it with an example:

&emsp;For the example I created a simple class named Person containing 4 attributes

```JAVA
public class Person {
    private int age;
    private int size;
    private String name;
    private boolean single;

    public Person(int age, int size, String name, boolean single) {
        this.age = age;
        this.size = size;
        this.name = name;
        this.single = single;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isSingle() {
        return single;
    }

    public void setSingle(boolean single) {
        this.single = single;
    }

    @Override
    public String toString() {
        return "Person{" +
                "age=" + age +
                ", size=" + size +
                ", name='" + name + '\'' +
                ", single=" + single +
                '}';
    }
}
```
```JAVA
import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.Moshi;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;

public class MetamorphicTest {
    @Test
    public void metamorphicTestFromJavaObject() throws IOException {
        Moshi moshi = new Moshi.Builder().build();
        JsonAdapter<Person> jsonAdapter = moshi.adapter(Person.class);

        Person person = new Person(23, 175, "Flavien", true);
        String jsonPerson = jsonAdapter.toJson(person);


        Person person2 = jsonAdapter.fromJson(jsonPerson);

        System.out.println("Initial object: " + person.toString());
        System.out.println("Result object: " + person2.toString());

        assertEquals(person.getAge(), person2.getAge());
        assertEquals(person.getName(), person2.getName());
        assertEquals(person.getSize(), person2.getSize());
        assertEquals(person.isSingle(), person2.isSingle());
    }
}
```

&emsp;The objective of the second technique is to use random data in order to generate the test a random number of times with each iteration random and different data to cover a maximum of possibilities. 

```JAVA
import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.Moshi;
import org.junit.jupiter.api.Test;
import java.util.concurrent.ThreadLocalRandom;
import org.apache.commons.lang3.RandomStringUtils;
import java.util.*;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class PruebasAleatoriasUsingMetaformicas {

    @Test
    public void RandomTest() throws IOException {
        // Gen between 40 and 100 tests with random input
        int min = 40;
        int max = 100;
        int randomNumTest = ThreadLocalRandom.current().nextInt(min, max + 1);

        for (int i = 0; i< randomNumTest; i++){
            // Random age between 20 et 35 yo
            int minAge = 20;
            int maxAge = 35;
            int randomAge = ThreadLocalRandom.current().nextInt(minAge, maxAge + 1);

            // Random size between 150 and 190 cm
            int minSize = 150;
            int maxSize = 190;
            int randomSize = ThreadLocalRandom.current().nextInt(minSize, maxSize + 1);

            // Gen between name with 5 - 15 letters
            int minLetter = 5;
            int maxLetter = 15;
            int randomNumLetter = ThreadLocalRandom.current().nextInt(minLetter, maxLetter + 1);
            String name = RandomStringUtils.randomAlphanumeric(randomNumLetter).toUpperCase();

            // Random boolean
            // create random object
            Random randomBool = new Random();

            // get next next boolean value
            boolean single = randomBool.nextBoolean();
            this.metamorphicTestFromJavaObject(randomAge, randomSize, name, single);
        }
    }

    @Test
    public void metamorphicTestFromJavaObject(int age, int size, String name, boolean single) throws IOException {
        Moshi moshi = new Moshi.Builder().build();
        JsonAdapter<Person> jsonAdapter = moshi.adapter(Person.class);

        Person person = new Person(age, size, name, single);
        String jsonPerson = jsonAdapter.toJson(person);

        Person person2 = jsonAdapter.fromJson(jsonPerson);

        System.out.println("Initial object: " + person.toString());
        System.out.println("Result object: " + person2.toString());

        assertEquals(person.getAge(), person2.getAge());
        assertEquals(person.getName(), person2.getName());
        assertEquals(person.getSize(), person2.getSize());
        assertEquals(person.isSingle(), person2.isSingle());
    }
}

```

**4. Code Coverage**

&emsp;Last but not least, we check coverage measures to evaluate the overall “sufficiency” of your tests for the Java modules of the project (moshi and adapters), thanks to the PITest (just for the mutation coverage) and JaCoCo (for the rest) plugins.
&emsp;In a nutshell, the mutation coverage is obtained by doing a lot of randoms incorrect modifications to the source code (most of the time, deleting a line) and see if the one the tests that used to pass suddenly fail (if no tests fails after a mutation, it means that this specific line of your code is useless, or that your tests doesn’t cover this portion of your code)

&emsp;Here are the JaCoCo results:

![alt text](https://i.imgur.com/ChbTF29.png)

&emsp;First of all, we observed that not all methods are tested which is a generally either a problem of conception (useless methods or inadequate division of the code) or a problem of testing (missing tests, often because these methods were considered too trivial). The most concerned file we saw is the LinkedHashTreeMap class (the rate mutation coverage / statement coverage is really low, meaning in spite of tests covering almost every line, much of the behavior is not well tested). For the other files, after verifying most of the methods involved, it seems to be the second option.

&emsp;- Among those methods, there is obviously methods like equals(...), first(...), setters... that are not mandatory to test, although not useless to test.

![alt text](https://i.imgur.com/Ap0LzYl.png)

&emsp;- There is also “non-real” methods in the adapters module that exists just as a clone of an already tested method. But unit tests could be easily implemented on the grounds of the already implemented tests of the original method (although for now the method is just a basic call of the corresponding method in the other module, there is a risk of regression in future evolutions that a test on those methods could prevent)

![alt text](https://i.imgur.com/Ap0LzYl.png)

&emsp;- Lastly, there are some methods that don’t enter those categories and should get tested.

&emsp;As for the rest, the branch coverage is satisfying for most of the non-empty files (although com.squareup.moshi.LinkedHashTreeMap and com.squareup.moshi.internal.Util deserve a bit more attention) and there don’t seem to be any flaky test (tests for which different executions can have different results). For more details you can go through the attached JaCoCo results (the most important metric is the branch metric).

PS: to set up all this we made some small changes in the moshi package pom.xml to add jacoco and pit libraries:

```
<plugin>
    	<groupId>org.jacoco</groupId>
    	<artifactId>jacoco-maven-plugin</artifactId>
    	<version>0.8.5</version>
    	<executions>
        	<execution>
            	<goals>
                	<goal>prepare-agent</goal>
            	</goals>
        	</execution>
        	<execution>
            	<id>report</id>
            	<phase>prepare-package</phase>
            	<goals>
                		<goal>report</goal>
            	</goals>
        	</execution>
    	</executions>
  </plugin>
  <plugin>
    	<groupId>org.pitest</groupId>
    	<artifactId>pitest-maven</artifactId>
    	<version>1.4.3</version>
    	<configuration>
      	<targetClasses>
        		<param>com.squareup.moshi.*</param>
      	</targetClasses>
      	<targetTests>
        		<param>com.squareup.moshi.*</param>
      	</targetTests>
    	</configuration>
  	</plugin>
</plugins>
```

**Comment by JakeWharton** [comment]
So for 2 we consider that to be working as intended.

> It would be better to have a method to create the JsonAdapter

De-duplication is something that is valuable for production code but the inverse is true for tests. We value each test containing duplicated code so that the entire test can be read and understood given only local context.

Someone coming into the tests would have to find, read, and understand the behavior of that method before the rest of the test. Additionally, by using `Class`, it means you now can't use adapters which take arguments. So now you're either making the abstraction more complicated to support that case or you're only using the helper method in a subset of tests.

It's much easier to just duplicate the 4 lines which gives you access to the full API of the library.

**Comment by swankjesse** [comment]
For LinkedHashTreeMap, we’re relying on the fact that it’s a copy from another project that’s well tested. If we ever make significant changes to it, we should probably integrate Guava’s collection testing feature.

Not sure what action to take here.
