### ISSUE TITLE
Dependency on Okio v1.* is causing conflict with other square's libs

### ISSUE THREAD

**Issue by vforvoid** [square/moshi#1165]
Good day.

One of my modules (let's call it `module A`) is using `Moshi v1.9.3` which [depends on `Okio v.1.16.0`](https://github.com/square/moshi/blob/master/pom.xml#L37)

![image](https://user-images.githubusercontent.com/14206129/85274961-b8fb7900-b490-11ea-91a1-8e0f7ba3fa0b.png)

Another module of mine (let's call it `module B`) depends on `Okhttp v4.2.2` which depends on `Okio v2.2.2`

When my main module (`module C`) is depending on both modules `A` and `B` it's causing dependency conflict
```
|    \--- com.squareup.moshi:moshi-kotlin:1.9.2
|         +--- com.squareup.moshi:moshi:1.9.2
|         |    \--- com.squareup.okio:okio:1.16.0 -> 2.2.2 (*)
```
My code looks list this:
```
val source = Okio.source(inputStream)
val bufferedSource = Okio.buffer(source)
val jsonReader = JsonReader.of(bufferedSource)
```

Moshi is getting to work with `Okio v2` which leads to exception
`Exception in thread "main" java.lang.NoSuchMethodError: okio.BufferedSource.getBuffer()Lokio/Buffer;` [referencing this LoC](https://github.com/square/moshi/blob/52aaf9cc84e42727d3a4d43824062733c3689d64/moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java#L97).

If you look at [most recent Okio BufferedSource code](https://github.com/square/okio/blob/41231c1fa96086dcf6fb7a23a0504cfbc9829160/okio/src/jvmMain/kotlin/okio/BufferedSource.kt#L31), it doesn't have a `getBuffer` method. Now, I'm somewhat new to Java/Kotlin development, but isn't `val buffer: Buffer` should be an equivalent getter? Maybe I set up something wrong, but I don't even know where to start digging. I'm targeting JVM 1.6, Kotlin v1.3, language level 8 just in case this info is relevant. 

[This comment](https://github.com/square/moshi/issues/1106#issuecomment-593185809) states that `Okio 2 is binary compatible with Okio 1`. But in practice my code falls flat. I started reading about shading, but it seems like [the cure is worse than the disease](https://www.elastic.co/blog/to-shade-or-not-to-shade).

I guess I will try to fork Moshi, change the dependency manually and Jitpack it to my project for now.

**Comment by swankjesse** [comment]
Try depending on the latest Okio 2.x, version 2.6.0.

**Comment by vforvoid** [comment]
I tried, gives the same exception. I made a small project to demonstrate this problem:
https://github.com/vforvoid/moshi_diag

https://github.com/vforvoid/moshi_diag/blob/master/src/main/kotlin/SecondVersion.kt
Throws the same exception.

**Comment by vforvoid** [comment]
Well, I guess I got it working with the following Gradle script

```
    implementation("com.squareup.okio:okio:2.6.0") // should be first

    implementation("LIB THAT WAS USING OKIO") {
        exclude("com.squareup.okio", "okio")
    }
```
