### ISSUE TITLE
Update README shrinker rules copy

### ISSUE THREAD

**Issue by dovahkiin98** [square/moshi#1166]
Why does Moshi require ProGuard rules to be added manually?

Other Dependencies like `OkHttp` and `Retrofit` now add the ProGuard rules implicitly on build.

Can this be added to Moshi? Not worrying about ProGuard rules when using this Dependency?

From Retrofit's GitHub page :

> **R8 / ProGuard**
If you are using R8 the shrinking and obfuscation rules are included automatically.
> ProGuard users must manually add the options from retrofit2.pro. You might also need rules for OkHttp and Okio which are dependencies of this library.

**Comment by JakeWharton** [comment]
The copy is just old. This is already done.

**Comment by JakeWharton** [comment]
Also Retrofit's copy is also wrong since AGP extracts these files and supplies them to ProGuard for people still using ProGuard.
