### ISSUE TITLE
      require(parameter == null || parameter.type == property.returnType) has bug

### ISSUE THREAD

**Issue by changety** [square/moshi#1171]
this is the stacktrace
```java
Caused by: java.lang.IllegalArgumentException: 'data' has a constructor parameter of type Data? but a property of type Data?.
at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(ProGuard:235)
```

and the source code is 
```kotlin 
      require(parameter == null || parameter.type == property.returnType) {
        "'${property.name}' has a constructor parameter of type ${parameter!!.type} but a property of type ${property.returnType}."
      }
```

why this happen?  
the printed log "parameter of type Data? but a property of type Data?"，just  means Data? == Data?

**Comment by ZacSweers** [comment]
Can you share a sample code snippet that reproduces this?

**Comment by zzg080643** [comment]
> this is the stacktrace
> 
> ```java
> Caused by: java.lang.IllegalArgumentException: 'data' has a constructor parameter of type Data? but a property of type Data?.
> at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(ProGuard:235)
> ```
> 
> and the source code is
> 
> ```kotlin
>       require(parameter == null || parameter.type == property.returnType) {
>         "'${property.name}' has a constructor parameter of type ${parameter!!.type} but a property of type ${property.returnType}."
>       }
> ```
> 
> why this happen?
> the printed log "parameter of type Data? but a property of type Data?"，just means Data? == Data?

Have you fixed it？

**Comment by swankjesse** [comment]
We really like executable examples for problems like this. Please re-open with something we can run & fix!
