### ISSUE TITLE
Mapping nullable Boolean to false in Moshi

### ISSUE THREAD

**Issue by qbait** [square/moshi#1172]
I would like to get rid of nullables and automatically map `null` to `false` in Moshi

I created such adapter with annotation
```
object NullToFalseAdapter: JsonAdapter<Boolean>() {
    @FromJson
    @NullToFalse
    override fun fromJson(reader: JsonReader): Boolean {
        if (reader.peek() != JsonReader.Token.NULL) {
            return reader.nextBoolean()
        }
        reader.nextNull<Unit>()
        return false
    }

    @ToJson
    override fun toJson(writer: JsonWriter, @NullToFalse value: Boolean?) {
        writer?.value(value)
    }
}

@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class NullToFalse
```

I'm adding it in Builder

```
return Moshi.Builder()
    .add(NullToFalseAdapter)
    .build()
```
And using it in my model like

```
@NullToFalse
@Json(name = "all_day")
val allDay: Boolean = false,
```

However, I'm getting the error

>  Caused by: java.lang.IllegalArgumentException: No JsonAdapter for boolean annotated [@familynet.de.src.network.adapters.NullToFalse()]
> for boolean
> for class familynet.de.src.models.Event
> for java.util.List<familynet.de.src.models.Event>
> for class familynet.de.src.network.models.EventsResponse$Companion$Data
> for class familynet.de.src.network.models.EventsResponse
>     at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:348)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:149)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
>     at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:231)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
>     at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
>     at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
>     at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:231)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
>     at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:231)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
>     at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
>     at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
>     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
>     at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
>     at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:739)
>       ... 15 more

Any idea what's missing here?

**Comment by ZacSweers** [comment]
This should go on stackoverflow with the `moshi` tag
