### ISSUE TITLE
Expose string array in JsonReader.Options

### ISSUE THREAD

**Issue by hollyroberts** [square/moshi#1173]
When using `JsonReader.selectName(Options)` it would be useful to be able to access the list of strings stored by this class. For example to give a more descriptive deserialisation error message by listing the valid values. Unfortunately the field `String[] strings` in `JsonReader.Options` is package private and so cannot be accessed.

While there are a bunch of workarounds to not being able to access this field, they all have various drawbacks. For example:
- Use `nextString` instead of `selectName`/`selectString`. This offers the greatest flexibility, but means giving up the performance benefit.
- Hardcode the values in the logic. This requires strings to be duplicated and both need to be maintained.
- Store values in another array/list and pass into `Options.of`. This works equivalently but requires two effectively identical variables which isn't great.
- Use reflection to temporarily get access to the internal variable. Not actually hugely horrible as my use cases are mostly for exception handling which will be the slow path anyway.

So while I'm not quite clear what the reasoning was for making this field package private, I do see a use case for implementing an accessor. Either to directly expose the string array, or as a list instead.

**Comment by JakeWharton** [comment]
We don't want to expose the field directly since you could mutate the array. I don't see much reason to avoid exposing the values as a list (either as a copy or as an unmodifiable view).
