### ISSUE TITLE
Inline classes without adapters

### ISSUE THREAD

**Issue by jameswald** [square/moshi#1176]
The Kotlin codegen behavior currently converts `inline class Foo(val value: String)` to `"value": "..."`, however I would have expected single property inline types to serialize as `"..."`.

To implement this behavior I've added a JsonAdapter for every inline type such as:

```
@JsonClass(generateAdapter = true)
class User(val id: UserId)

inline class UserId(val value: String)

class MoshiProvider {
    companion object {
        private val defaultMoshi = Moshi.Builder().build()
    }

    fun create(): Moshi = Moshi.Builder()
        .add(UserId::class.java, UserIdJsonAdapter)
        .build()

    private object UserIdJsonAdapter : JsonAdapter<UserId>() {
        private val adapter: JsonAdapter<String> =
            defaultMoshi.adapter(String::class.java)

        override fun fromJson(reader: JsonReader) =
            adapter.fromJson(reader)?.let { UserId(it) }

        override fun toJson(writer: JsonWriter, value: UserId?) {
            adapter.toJson(writer, value?.value)
        }

        override fun toString(): String = adapter.toString()
    }
}
```

This serializes to `"user": { "id": "..." }` instead of `"user": { "id": { "value": "..." } }`.

When the times comes, would it make sense for Moshi to treat single property inline types this way by default? If not, perhaps codegen could add an `inline = true` flag on the `@JsonClass` annotation to generate adapters that inline eligible types.

```
@JsonClass(generateAdapter = true, inline = true)
inline class UserId(val value: String)
```

I may be unwittingly fighting conventions here if there's a cleaner solution that fits inline semantics.

**Comment by ZacSweers** [comment]
inline classes are not supported as they are not stable in kotlin itself. A test was added for it, but mostly just for curiosity.

**Comment by jameswald** [comment]
Thanks. I'll close this out since the feature isn't supported yet. Until then I'll investigate ways to implement this behavior more universally to reduce the maintenance burden.
