### ISSUE TITLE
Question: what's Moshi's backward/forward compatibility policy?

### ISSUE THREAD

**Issue by tbroyer** [square/moshi#1177]
Namely, does Moshi follows the same policy as OkHttp and Retrofit: https://jakewharton.com/java-interoperability-policy-for-major-version-updates/
…or I should rather *shade* it in my Gradle plugin? (or annotation processor, etc.)

**Comment by swankjesse** [comment]
We will do similarly to Retrofit and OkHttp. If we break compatibility we will ship under a new package name. (Everyone should do this!)

That said, I'm hoping that we never need to break compatibility. The biggest challenge we currently face is lack of native Kotlin things in JsonAdapter.Factory. But I expect to be able to implement that by adding stuff, not by changing stuff.

**Comment by tbroyer** [comment]
Thanks for the confirmation (I had little doubt, but this policy does not seem to be written down anywhere but in Jake's blog post, that only mentions OkHttp and Retrofit; and after a quick look, not even in OkHttp repository)
