### ISSUE TITLE
Transient Field Serialization

### ISSUE THREAD

**Issue by james-novino** [square/moshi#1178]
Wondering if it's possible to add a similar `@Transient` annotation to exclude properties for serialization and deserialization.

This annotation should only be used for Optional or Default fields but the cuntionakitu is

@Transient annotation for supported properties. This annotation excludes marked properties from process of serialization or deserialization. Requires default value. Don't confuse with kotlin.jvm.Transient!

```Kotlin
data class Data(
   @Transient
   val a: Int = 0,
   val b: Int)

```

For `Data(5, 42)` would serialize I to:

```json
{
  "b": 42
}
```

I looked through the documentation and available annotations and did not see anything mention this type of functionality, is this possible with Moshi?

**Comment by ZacSweers** [comment]
Moshi supports transient in kotlin, did you try your example and find it didn't work?

I don't understand what this is from 👇

> @transient annotation for supported properties. This annotation excludes marked properties from process of serialization or deserialization. Requires default value. Don't confuse with kotlin.jvm.Transient!

**Comment by swankjesse** [comment]
No action to take on this.
