### ISSUE TITLE
Parsing json to file

### ISSUE THREAD

**Issue by tibbi** [square/moshi#118]
Hello, I have some jsons which sometimes contain huge values (1+ MB), as images are base64 encoded in them. I know its not the best solution, but its on the server so lets say we cannot change it for now.
For example [{"image": "iAmALongBase64EncodedString"}]
What is the best way to decode the value and store it in a file for later use? Currently I parse that json value as a String, then write it to a file as an InputStream. However some devices get Out of Memory at parsing to a string as it can be huge. Is there any way of skipping the String part and write the value in a file as stream? Thanks!

**Comment by swankjesse** [comment]
We don't support that currently.

**Comment by tibbi** [comment]
okay thanks, guess I can close it then as its not an issue
