### ISSUE TITLE
JsonAdapter fromJson throws JsonDataException

### ISSUE THREAD

**Issue by theSurikat** [square/moshi#1184]
As we see [here](https://github.com/square/moshi/blob/50d09d476b8b7a7ba3e6087a9ba543542d8b2a20/moshi/src/main/java/com/squareup/moshi/JsonAdapter.java#L46) The signature for the function does not declare that it throw a JsonDataException. However in the line [here](https://github.com/square/moshi/blob/50d09d476b8b7a7ba3e6087a9ba543542d8b2a20/moshi/src/main/java/com/squareup/moshi/JsonAdapter.java#L50) it can explicitly throw a JsonDataException

Seems like a small bug, caused me a bit of a headache for a while though.

**Comment by JakeWharton** [comment]
It's not a checked exception so it doesn't appear in the signature. Want to send a PR to add it in the Javadoc?
