### ISSUE TITLE
should register all code-gen adapters

### ISSUE THREAD

**Issue by beigirad** [square/moshi#1188]
I want to use code-gen of moshi. I added  `@JsonClass(generateAdapter = true)` on above classes and found the generated adapters.

If I want to use these adapters, I should define all of them for `Moshi` object one by one?

In my case I'm using moshi-convertor of retrofit and I have a lot of data model. Should I pass their list to moshi object?

**Comment by beigirad** [comment]
response: It's not required to register them.

**Comment by ZacSweers** [comment]
Moshi automatically discovers these, no configuration is necessary
