### ISSUE TITLE
Generated adapter not respecting @Json name in base class on incremental builds

### ISSUE THREAD

**Issue by liamheneghan** [square/moshi#1193]
**Given the following:**
```kotlin
@JsonClass(generateAdapter = true)
open class BaseEntity(
    @property:Json(name = "some_reference")
    var someReference: String? = null,
    var counter: Int = 1
)

@JsonClass(generateAdapter = true)
data class NameEntity(
    val name: String
) : BaseEntity()
```
I've only included snippets from the generated adapters for brevity.

- A clean build will generate a `NameEntityJsonAdapter` with the following toJson method:
```kotlin
  override fun toJson(writer: JsonWriter, value: NameEntity?) {
    if (value == null) {
      throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("name")
    stringAdapter.toJson(writer, value.name)
    writer.name("counter")
    intAdapter.toJson(writer, value.counter)
    writer.name("some_reference")
    nullableStringAdapter.toJson(writer, value.someReference)
    writer.endObject()
  }
```

- Edit the `name` field of `NameEntity` to a nullable type (String?) and build again via `./gradlew :app:assembleDebug`. This will generate a `NameEntityJsonAdapter` with the following toJson method:
```kotlin
override fun toJson(writer: JsonWriter, value: NameEntity?) {
    if (value == null) {
      throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("name")
    nullableStringAdapter.toJson(writer, value.name)
    writer.name("counter")
    intAdapter.toJson(writer, value.counter)
    writer.name("someReference")
    nullableStringAdapter.toJson(writer, value.someReference)
    writer.endObject()
  }
```

**Observed:**
Generated adapter is no longer following the specified encoding for `someReference` specified in the base class.

**Versions/dependencies:**
```
implementation("com.squareup.moshi:moshi:1.9.3")
implementation("com.squareup.moshi:moshi-kotlin:1.9.3")
kapt("com.squareup.moshi:moshi-kotlin-codegen:1.9.3")

Kotlin version 1.4.0
AGP 4.1.0-rc01
Plugins
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
```

I don't know how to write a test to accurately recreate this incremental change scenario sorry.

**Comment by ZacSweers** [comment]
What happens if you don't use the property site target? That's not necessary in moshi code gen

**Comment by liamheneghan** [comment]
Without the property site target the generated adapter does not use the specified encoding. It remains `someReference`.

**Comment by ZacSweers** [comment]
That doesn't really make sense since we have plenty of cases like that work fine. I think something is up with your build and this belongs in the kotlin issue tracker with a reproducible sample for the incremental issues. Nothing Moshi can really do about it

**Comment by liamheneghan** [comment]
Thanks for your help. If I were to attach the sample project here would you take a look? Its a new project from Android Studio with minimal changes. I know the whole issue seems odd. I did get a colleague to check they could reproduce it.

**Comment by ZacSweers** [comment]
No I think you should post it on youtrack as a kapt bug.

**Comment by liamheneghan** [comment]
Thanks. I've raised this on youtrack. https://youtrack.jetbrains.com/issue/KT-41403
