### ISSUE TITLE
Custom adapter not being used (being overridden)?

### ISSUE THREAD

**Issue by charlieAndroidDev** [square/moshi#1199]
Versions:

```groovy
implementation 'com.squareup.moshi:moshi:1.9.3'
implementation 'com.squareup.moshi:moshi-kotlin:1.9.3'
```

Here is my custom adapter used to parse either an array or an object of some type:

```kotlin
class SingleToArrayAdapter(
    val delegateAdapter: JsonAdapter<List<Any>>,
    val elementAdapter: JsonAdapter<Any>
) : JsonAdapter<Any>() {

    companion object {
        val INSTANCE = SingleToArrayAdapterFactory()
    }

    override fun fromJson(reader: JsonReader): Any? =
        if (reader.peek() != JsonReader.Token.BEGIN_ARRAY) {
            Collections.singletonList(elementAdapter.fromJson(reader))
        } else delegateAdapter.fromJson(reader)

    override fun toJson(writer: JsonWriter, value: Any?) =
        throw UnsupportedOperationException("SingleToArrayAdapter is only used to deserialize objects")

    class SingleToArrayAdapterFactory : JsonAdapter.Factory {
        override fun create(type: Type, annotations: Set<Annotation>, moshi: Moshi): JsonAdapter<Any>? {
            val delegateAnnotations = Types.nextAnnotations(annotations, SingleToArray::class.java)
            if (delegateAnnotations == null) return null
            if (Types.getRawType(type) != List::class.java) throw IllegalArgumentException("Only lists may be annotated with @SingleToArray. Found: $type")
            val elementType = Types.collectionElementType(type, List::class.java)
            val delegateAdapter: JsonAdapter<List<Any>> = moshi.adapter(type, delegateAnnotations)
            val elementAdapter: JsonAdapter<Any> = moshi.adapter(elementType)

            return SingleToArrayAdapter(delegateAdapter, elementAdapter)
        }
    }
}
```

And I add it before the `KotlinJsonAdapterFactory()` as per the docs.

```kotlin
@Singleton
@Provides
@Named("journey")
fun provideMoshi(): Moshi {
    return Moshi.Builder()
        .add(SingleToArrayAdapter.INSTANCE)
        .add(KotlinJsonAdapterFactory())
        .build()
}
```

And I use this instance in my `Retrofit` builder:

```kotlin
@Singleton
@Provides
@Named("JourneyPlan")
fun provideJourneyRetrofit(@Named("NREOk") okHttpClient: Lazy<OkHttpClient>, @Named("journey") moshi: Moshi): Retrofit {
    return Retrofit.Builder()
        .baseUrl("https://livetracktimes.co.uk/")
        .callFactory { okHttpClient.get().newCall(it) }
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .build()
}
```

But I get an `E/NreRepositoryImpl: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.outwardJourney[0].leg[0].originInstants`

Which, with just the `KotlinJsonAdapterFactory()`, makes sense but I thought Moshi would use my custom adapter?  It used to work in previous versions of Moshi flawlessly.

Here is the usage of `@SingleToArray` in the `Leg` class:

```kotlin
....
@SingleToArray
@Json(name = "originInstants")
val originInstants: List<OriginInstants?>,
....
```

<details>
<summary>Raw JSON</summary>
{
    "response": "Ok",
    "generatedTime": "2020-08-28T13:07:04.858Z",
    "outwardJourney": [{
            "id": "1",
            "origin": "IPS",
            "destination": "NCL",
            "realtimeClassification": "ONTIME",
            "vstpService": "false",
            "timetable": {
                "scheduled": {
                    "departure": "2020-08-28T14:08:00.000+01:00",
                    "arrival": "2020-08-28T19:41:00.000+01:00"
                },
                "realtime": null
            },
            "leg": [{
                    "id": "1",
                    "board": {
                        "crsCode": "IPS",
                        "stationType": "NR"
                    },
                    "alight": {
                        "crsCode": "NRW",
                        "stationType": "NR"
                    },
                    "originInstants": {
                        "stationCRS": "LST",
                        "realTime": "2020-08-28T13:00:00.000+01:00",
                        "scheduledTime": "2020-08-28T13:00:00.000+01:00"
                    },
                    "origins": "LST",
                    "destinationInstants": {
                        "stationCRS": "NRW",
                        "realTime": "2020-08-28T14:50:00.000+01:00",
                        "scheduledTime": "2020-08-28T14:50:00.000+01:00"
                    },
                    "destinations": "NRW",
                    "realtimeClassification": "ONTIME",
                    "mode": "TRAIN",
                    "operator": {
                        "code": "LE",
                        "name": "Greater Anglia"
                    },
                    "trainUID": "P06262",
                    "trainRetailID": "LE011600",
                    "trainRID": "202008288006262",
                    "isReplacementBus": "false",
                    "temporaryTrain": "false",
                    "reservable": "S",
                    "seatingClass": "B",
                    "cateringCodes": "None Buffet",
                    "trainCategory": "XX",
                    "iptisTripIdentifier": "P06262|28/08/2020",
                    "timetable": {
                        "scheduled": {
                            "departure": "2020-08-28T14:08:00.000+01:00",
                            "arrival": "2020-08-28T14:50:00.000+01:00"
                        },
                        "realtime": {
                            "departure": "2020-08-28T14:08:00.000+01:00",
                            "arrival": "2020-08-28T14:50:00.000+01:00"
                        }
                    }
                }, {
                    "id": "2",
                    "board": {
                        "crsCode": "NRW",
                        "stationType": "NR"
                    },
                    "alight": {
                        "crsCode": "PBO",
                        "stationType": "NR"
                    },
                    "originInstants": [{
                        "stationCRS": "NRW",
                        "realTime": "2020-08-28T14:57:00.000+01:00",
                        "scheduledTime": "2020-08-28T14:57:00.000+01:00"
                    },
					{
						"stationCRS": "FBN",
                        "realTime": "2020-08-28T13:00:00.000+01:00",
                        "scheduledTime": "2020-08-28T13:00:00.000+01:00"
					}]
                    "origins": "NRW",
                    "destinationInstants": {
                        "stationCRS": "LIV",
                        "realTime": "2020-08-28T20:34:00.000+01:00",
                        "scheduledTime": "2020-08-28T20:34:00.000+01:00"
                    },
                    "destinations": "LIV",
                    "originPlatform": "5",
                    "realtimeClassification": "ONTIME",
                    "mode": "TRAIN",
                    "operator": {
                        "code": "EM",
                        "name": "East Midlands Railway"
                    },
                    "trainUID": "W88534",
                    "trainRetailID": "EM929800",
                    "trainRID": "202008288788534",
                    "isReplacementBus": "false",
                    "temporaryTrain": "false",
                    "reservable": "S",
                    "seatingClass": "S",
                    "cateringCodes": "None",
                    "trainCategory": "XX",
                    "iptisTripIdentifier": "W88534|28/08/2020",
                    "timetable": {
                        "scheduled": {
                            "departure": "2020-08-28T14:57:00.000+01:00",
                            "arrival": "2020-08-28T16:25:00.000+01:00"
                        },
                        "realtime": {
                            "departure": "2020-08-28T14:57:00.000+01:00",
                            "arrival": "2020-08-28T16:25:00.000+01:00"
                        }
                    }
                }]....................................................................
</details>

**Comment by ZacSweers** [comment]
You would need to hop in the debugger and see why your factory is not handling that type

**Comment by charlieAndroidDev** [comment]
> 
> 
> You would need to hop in the debugger and see why your factory is not handling that type

Thanks Zac, had a check with the debugger and seems like my `delegateAnnotations` is always null when using the `KotlinJsonAdapterFactory`.  Iinterestingly I still have the issue on `1.8.0` if I explicitly use `KotlinJsonAdapterFactory` which is now a requirement after that version, but everything is OK without the `KotlinJsonAdapterFacotry` on `1.8.0`.

**Comment by ZacSweers** [comment]
Is SingleToArray runtime retained and annotated with JsonQualifier?

**Comment by swankjesse** [comment]
No action to take on this.

**Comment by indalkarpriyanka** [comment]
> > You would need to hop in the debugger and see why your factory is not handling that type
> 
> Thanks Zac, had a check with the debugger and seems like my `delegateAnnotations` is always null when using the `KotlinJsonAdapterFactory`. Interestingly I still have the issue on `1.8.0` if I explicitly use `KotlinJsonAdapterFactory` which is now a requirement after that version, but everything is OK without the `KotlinJsonAdapterFacotry` on `1.8.0`.

How you solved this isssue ? Facing same issue in my project. delegateAnnotations` is always null.
