### ISSUE TITLE
Snapshots not updated and error when using manual build version

### ISSUE THREAD

**Issue by Tolriq** [square/moshi#1201]
Seems snapshots version are no more compiled and when I compile manually from master or via jitpack kapt later fails with:

```
Caused by: java.lang.NoClassDefFoundError: com/squareup/kotlinpoet/classinspector/elements/ElementsClassInspector
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.init(JsonClassCodegenProcessor.kt:95)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:38)
```

Seems like migration to gradle have impacted kotlin poet integration. (Maybe some implementation instead of api?)

**Comment by ZacSweers** [comment]
Please offer a reproducible sample, this isn't much information to go off of or what you were doing to arrive at that stacktrace

**Comment by Tolriq** [comment]
Just use ```implementation 'com.github.square.moshi:moshi:42f1d18f64'``` (Same for codegen) that is top of master on a project that use codegen.
Reverting to https://github.com/square/moshi/commit/24c0c498584ebc112c273f9bb047023fc0e42e5b and everything works again.

The kapt crash occurs at the first try to access Kotlin poet from the codegenprocessor so there's something missing.

I'd be happy to test if it's a problem with jitpack or my manual builds but as title says snapshots are not updated https://oss.sonatype.org/content/repositories/snapshots/com/squareup/moshi/moshi-kotlin/1.11.0-SNAPSHOT/ so can't test those more official builds.

About your edit, your commits are from the 28th, last build is 27th.

**Comment by Tolriq** [comment]
From Jenkins on last merge 

```
> Task :adapters:publishMavenPublicationToMavenRepository FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':adapters:publishMavenPublicationToMavenRepository'.
> Failed to publish publication 'maven' to repository 'maven'
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/com/squareup/moshi/moshi-adapters/1.11.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```

Probably some auth issue with the gradle migration too.

**Comment by JakeWharton** [comment]
I'll fix snapshots. We don't support jitpack so no promises it'll ever work.

**Comment by Tolriq** [comment]
I have same issue with local compilation, maybe there's some transitive stuff that needs to be manually added now? (Jitpack did work until the gradle migration, but I lack knowledge about the kapt part to debug :()
I unfortunately have to maintain a fork as read/write adapter was refused.

**Comment by JakeWharton** [comment]
Snaphots are publishing again.
