### ISSUE TITLE
Moshi's generated adapaters do not support Explicit API mode

### ISSUE THREAD

**Issue by StillLynnTheCloset** [square/moshi#1203]
Kotlin 1.4 added [Explicit API Mode](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) which applies stricter rules to promote more stable public APIs. 

These rules also apply to generated code, and currently (tested with version 1.10.0), Moshi does not generate visibility modifiers on generated adapter classes, which causes warnings or errors (depending on configuration).

**Comment by ZacSweers** [comment]
This seems like a feature request, not a bug

**Comment by JakeWharton** [comment]
We just need a KotlinPoet bump. It was changed to always emit explicit modifiers.
