### ISSUE TITLE
Invalid URL in code comment

### ISSUE THREAD

**Issue by ligi** [square/moshi#122]
https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/JsonReader.java#L1227

     // Skip a # hash end-of-line comment. The JSON RFC doesn't specify this behaviour, but it's
     // required to parse existing documents. See http://b/2571423.

The URL is invalid

**Comment by JakeWharton** [comment]
This is a reference to a non-public issue tracker inside Google and was copied from Gson's `JsonReader` class. There's nothing we could do except remove it.

**Comment by swankjesse** [comment]
Let’s remove it.
