### ISSUE TITLE
Make CollectionJsonAdapter public

### ISSUE THREAD

**Issue by konaire** [square/moshi#1226]
I'm writing a `JsonAdapter` for a list of items which won't fail when one of the items is malformed, instead it will skip such item, e.g. if one of the fields is nullable in the response from server, but it should not be nullable by the class declaration.

It would be handy to subclass `CollectionJsonAdapter` and override only `fromJson` without touching the `toJson` method. But I can't do that since `CollectionJsonAdapter` is a package-private class. Therefore I have to copy-paste `toJson` method from `CollectionJsonAdapter` to my new class. I'm wondering is it possible to make this class public or is there any other reason to keep it package-private?

**Comment by swankjesse** [comment]
You can get an instance by implementing JsonAdapter.Factory and calling Moshi.nextAdapter to look it up. It doesn't need to be a public class for you to get an instance of it!

**Comment by swankjesse** [comment]
Or you could just use our built in delegates feature.
https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/CustomAdapterWithDelegate.java

**Comment by konaire** [comment]
Cool, it will work in our case, thank you for the explanation @swankjesse.
