### ISSUE TITLE
Support YAML 1.2 

### ISSUE THREAD

**Issue by cgruber** [square/moshi#1229]
Given the creation of the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) and its goal of making it a strict subset of JSON, supporting it as a flavor for parsing and writing in moshi would be amazing.   Presently, to get YAML with kotlin data types, Jackson must be used with its wrapper of SnakeYaml and its kotlin module - that works, but having access to moshi's kotlin-focused features, its codegen abilities, etc., could really help, given that existing yaml parsers are SLLOOOOWWW.

**Comment by JakeWharton** [comment]
I use kotlinx.serialization and kaml for this (which also uses SnakeYAML). Moshi is not well-suited for swapping out the backing serialization format and I'm not sure we want to make it possible (ignoring whether or not it would even be doable).

**Comment by swankjesse** [comment]
Yeah, if we were gonna do a YAML thing it wouldn't be as a part of this project.

I think the world has enough YAML. Of all of the things in its class I think TOML is least worst, but I haven't used it enough to say with any conviction.

No action to take on this. If you'd like to make a Moshi-but-for-yaml thing, please do.

**Comment by cgruber** [comment]
Fair enough. I'm pretty down with kotlinx.serialization but snakeyaml is slow as molasses.  I'll peek at TOML again, but for our purposes it seemed a bit off. In our project we haven't landed on the final format, so still figuring out options. 

That said, if we did go with yaml, I'd probably want to borrow chunks of moshi, at least insofar as it has some extremely efficient parsing of similar structures. I really worry about parsing at-scale, relying on snakeyaml.

Anyway, thanks for at least looking at this.

**Comment by sschuberth** [comment]
> Fair enough. I'm pretty down with kotlinx.serialization but snakeyaml is slow as molasses.

You might want to give https://github.com/him188/yamlkt a try.
