### ISSUE TITLE
CollectionJsonAdapter not support annotation with Target TYPE_USE

### ISSUE THREAD

**Issue by dkonurov** [square/moshi#1239]
CollectionJsonAdapter not support annotation with Target TYPE_USE. I can't write 
`class A {
    List<@CustomAnnotation B> listB;
}
Class B {
}
`
because CollectionJsonAdapter doesn't send infromation about annotations to type of child.

**Comment by ZacSweers** [comment]
Dupe of #666, please use the search first

**Comment by dkonurov** [comment]
sorry
