### ISSUE TITLE
moshi.JsonDataException

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/moshi#124]
I keep getting an
 > error fetching results: com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $

I defined my Moshi adapter like this:
`public class SearchJsonAdapter {
    @FromJson
    public List<Phrase> fromJson(SearchResult result) {
        return result.phrases;
    }
}`

My Retrofit2 api is defined like this:
`@GET ("ac")Observable<Result<SearchResult>> fetchPhrases(
            @Query("q") String query,
            @Query("format") String format);`

And the model for SearchResult is defined like this:
`public final class SearchResult {
    public List<Phrase> phrases;
}`

So I am trying to fetch the following JSON: https://ac.duckduckgo.com/ac/?q=android&format=json
which would output this in the browser:
>[
-{
phrase: "android device manager"
},
-{
phrase: "android"
},
{
phrase: "android apps"
}
]

Do you know what I did wrong in the Moshi code?

**Comment by serj-lotutovici** [comment]
Your json is coming in as an array. You don't need `SearchResult` nor the custom adapter. Just declare searchPrases to return `Observable<Result<List<Phrase>>`

**Comment by IgorGanapolsky** [comment]
@serj-lotutovici You are absolutely right.  You saved my day, and it parses the JSON now.  @changetip $1.

**Comment by changetip** [comment]
Hi @serj-lotutovici, @IgorGanapolsky sent you a tip worth 2,582 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/935625)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
