### ISSUE TITLE
How do I handle error data returned from the server?

### ISSUE THREAD

**Issue by skyCracks** [square/moshi#1264]
data class ResponseEntity<T>(
    val code: Int,
    val msg: String,
    val data: T?,
)

data class User(
   val userId: Int,
   val nickname: String
}

After the network request is executed ，Server return :  {"code":200,"msg":"","data":[]}

data values convert '[]' to 'null'，What should I do?

**Comment by ZacSweers** [comment]
Usage questions should be posted on stackoverflow, the issue tracker is for filing bugs or feature requests

**Comment by skyCracks** [comment]
OK, thank you.
