### ISSUE TITLE
How catch all serializing errors in single point?

### ISSUE THREAD

**Issue by beigirad** [square/moshi#1267]
I'm using Moshi convertor with Retrofit.

I need to catching all malformed or any other errors and send them for our log server. Now Moshi moshi prints them in logcat.

How can I gain all of this errors?

**Comment by ZacSweers** [comment]
Usage questions belong on stackoverflow

**Comment by beigirad** [comment]
@ZacSweers 
I thought it could be cause a feature request.

Is Moshi support this feature? (that referring me to Stackoverflow)
