### ISSUE TITLE
Manipulate Json before whole conversion to Kotlin DataClass's Object

### ISSUE THREAD

**Issue by Shabinder** [square/moshi#1268]
I want to manipulate incoming Json Body like following:

enclose every Json response into `"{"value":$IncomingResponseBody}" `for every Request being made using Retrofit and Moshi combined for json 2 object conversion.

As of Now , I am achieving the desired result at **okHttp interceptor** Level like:
```

val response = chain.proceed(chain.request())
            val responseBody = response.body
            val bodyString = responseBody?.string()
            Response.Builder()
                .code(response.code) // code(200.300) = successful else = unsuccessful
                .body("{\"value\":${bodyString}}".toResponseBody(responseBody?.contentType())) // Whatever body
                .protocol(response.protocol)
                .message(response.message)
                .request(chain.request())
                .build()

```
But clearly this is very **EXPENSIVE** , So How would I do this?

Background Info: 
I was using this earlier :
```
@GET("albums/{id}")
    suspend fun getAlbum(@Path("id") albumId: String?): Album? 
```
But sometimes **Server's responseBody is null** _(I dont Control Server)_, 
here **moshi doesnt return null but instead it throw an** _(which should be default working as getAlbum could return null (Album?) but it never does!)_
**_Exception: kotlin.KotlinNullPointerException: Response from ... was null but response body type was declared as non-null_**

So tackling this I am approaching this request as enclosing in **`Optional(val value:Album?)`** data class and here I retrieve value if its Null or Not without Raising an Exception.
```
@GET("albums/{id}")
    suspend fun getAlbum(@Path("id") albumId: String?): Optional<Album> 
```
I think this is possible by Using Custom Adapter in some Way, am I right? if I am please point to me in right Direction on how to do that?

**Comment by Shabinder** [comment]
class OptionalCustomAdapter {
    @FromJson fun<T> optionalFromJson(jsonObject:T):Optional<T> = Optional(value = jsonObject)

    @ToJson
    inline fun <reified T> optionalToJson(obj:Optional<T>): T? = obj.value
}


I am created this adapter and adding like this: fun getMoshi():Moshi{
        return Moshi.Builder()
            .add(OptionalCustomAdapter())
            .add(KotlinJsonAdapterFactory())
            .build()
    }

But its Not working

**Comment by ZacSweers** [comment]
Please close this and wait over there, the issue tracker is for filing bugs

**Comment by Shabinder** [comment]
Ohk ,Closing this , Will be Waiting for Help over there
