### ISSUE TITLE
Moshi generated proguard files slowing down Proguard

### ISSUE THREAD

**Issue by AndrewReitz** [square/moshi#1269]
With the addition of code gen creating proguard files on the fly there is a lot more .pro files that R8 needs to read which appears to be slowing it down. 

It would be nice to have a way to disable this feature both as a work around to this issue, and for projects that aren't using Proguard/R8.

Here is a link to the R8 issue. https://issuetracker.google.com/issues/172999904

**Comment by ZacSweers** [comment]
I think we're unlikely to add an option to disable the feature, but we could aggregate all proguard data into a final single file at the end. This would make it an aggregating processor though. Does that seem reasonable as an opt in?

Regardless I'd like to wait and see what the Google folks say first

**Comment by AndrewReitz** [comment]
@ZacSweers yeah that seems reasonable. I too would like to see what the Google team has to say before we make any decisions.

**Comment by ZacSweers** [comment]
Fix from the R8 team has landed, can you give it a try in your project per their instructions on the issue?

**Comment by AndrewReitz** [comment]
Works for me. Closing this issue, since I don't think anything needs to be done.

**Comment by yogurtearl** [comment]
Looks like this is fixed in AGP 4.1.2 
https://androidstudio.googleblog.com/2021/01/android-studio-412-available.html
