### ISSUE TITLE
`newParameterizedType` is not respected for a polymorphic adapter

### ISSUE THREAD

**Issue by knrybarczyk** [square/moshi#1270]
Hey guys,

I'm not 100% certain it's a bug, but it looks like it. I have a generic class, for which I want a PolymorphicJsonAdapterFactory, which contains an object, which also is generic (with its own PolymorphicJsonAdapterFactory): 

```kotlin
sealed class IReply<T : View> {
    abstract val view: T
    abstract override val receivers: List<UserId>
}

data class Reply<T : View>(override val view: T, override val receivers: List<UserId>) : IReply<T>()

data class DummyReply<T : View>(override val view: T, override val receivers: List<UserId>, val dummy: String) : IReply<T>()

sealed class View

data class FooView(val text: String) : View()

data class BarView(val number: Int) : View()

```

I'm trying to serialize reply like so: 

```kotlin
moshi.adapter(Types.newParameterizedType(IReply::class.java, View::class.java)).toJson(instance)

```
which fails with the following error:

```
JsonSerializationError(message=No JsonAdapter for T (with no annotations)
for T view
for class com.foobar.domain.model.Reply
for com.foobar.domain.model.IReply<com.foobar.domain.model.View>
```

It seems that this parameterized type created is not correctly passed in the polymorphic adapter, because `Reply` has the same generic `T` as `IReply`. If I specify the type of `IReply`, then the object is serialized, but I'm missing the `__typename` label:

```kotlin
moshi.adapter(Types.newParameterizedType(Reply::class.java, View::class.java)).toJson(instance)
```

Of course I have polymorphic adapters registered for both classes : 

```kotlin
.add(
	PolymorphicJsonAdapterFactory.of(View::class.java, "__typename")
            .withSubtype(FooView::class.java)
            .withSubtype(BarView::class.java)
)
.add(
	PolymorphicJsonAdapterFactory.of(IReply::class.java, "__typename")
    	        .withSubtype(Reply::class.java)
        	    .withSubtype(DummyReply::class.java)
)
```

**Comment by ZacSweers** [comment]
This isn't supported at the moment and I'm not sure there's a simple way to do so. In this case, the generic type really belongs to the subtype, but you are requesting it in the context of the base type. Even if we somehow pass down this type information from the base type to the subtype at adapter creation, it would only work if the subtype declared the same generics. If the subtype declared more or different generics, it would have no way of getting that information.

Happy to be corrected if there's a feasible way for this, but I think the only support for any generics right now would be generics on the base type and not on the subtypes.
