### ISSUE TITLE
SwipeRefreshLayout stop swing for a little time

### ISSUE THREAD

**Issue by Ali-Rezaei** [square/moshi#1271]
I am using moshi-kotlin in my Android app. I set it up for retrofit as follow 

private val moshi = Moshi.Builder()
    .add(KotlinJsonAdapterFactory())
    .build()

@Singleton
    @Provides
    fun retrofit(): Retrofit = Retrofit.Builder()
        .baseUrl(BuildConfig.BASE_URL)
        .client(
            OkHttpClient.Builder()
                .addInterceptor(getLoggerInterceptor())
                .build()
        )
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
        .build()

When I Refresh the list for the very first time, SwipeRefreshLayout stops for a little time and then start to swing. 

If I remove moshi from MoshiConverterFactory.create, it works as expected, but I want to use moshi-kotlin.

**Comment by Ali-Rezaei** [comment]
Source code of my sample is : https://github.com/Ali-Rezaei/SavingGoals-Cache

**Comment by Ali-Rezaei** [comment]
Here is a recorded video from the issue that I described : https://drive.google.com/file/d/1_1yPyoy-6cofksUPQehtqz-sbnQ9z7oo/view?usp=sharing

**Comment by JakeWharton** [comment]
As far as I can tell it has something to do with the countdownlatch in your repository which is waiting for a synchronous observerable returned from retrofit.

At the very least, switch to RxJavaCallAdapterFactory.createAsync() and remove any usage of blocking APIs like CountDownLatch.await().

Ultimately, as far as I can tell this isn't a problem with Moshi.

**Comment by Ali-Rezaei** [comment]
Thank you JakeWharton for your swift answer. I made changes that you mentioned and removed CountDownLatch and use RxJava Single and Observable instead but problem still exist. You can even check the repository.

**Comment by Ali-Rezaei** [comment]
I just use Gson instead of Moshi and problem resolved. If it is not related to Moshi, why it resolved by using Gson instead?

**Comment by Ali-Rezaei** [comment]
I just found a reason to the issue that I described . Here is how I resolved the problem : 

    fun getSavingsGoals(): Observable<List<SavingsGoal>> =
        Observable.fromCallable { cacheIsDirty }
            .flatMap {
                if (it) {
                    getGoalsFromRemoteDataSource()
                } else {
                    localDataSource.getSavingsGoals()
                        .observeOn(schedulerProvider.io())
                        .toObservable()
                        .onErrorResumeNext(getGoalsFromRemoteDataSource())
                }
            }
