### ISSUE TITLE
Codegen causes compile error for Array field

### ISSUE THREAD

**Issue by DeKaN** [square/moshi#1272]
I get a compiler error if I use Array for a field in my class

```kotlin
@JsonClass(generateAdapter = true)
data class User (
    val name: String? = null,
    val email: String? = null,
    val date: Date? = null,
    val flag: Boolean? = null,
    val customFields: Array<Map<String, Any>>? = null,
)
```
It gives me error `Only classes are allowed on the left hand side of a class literal` at 
```kotlin
    val localConstructor: Constructor<User> = this.constructorRef ?:
        User::class.java.getDeclaredConstructor(String::class.java, String::class.java,
        Date::class.java, Boolean::class.javaObjectType, Array<Map<String, Any>>::class.java,
        Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef =
        it }
```

The workaround is "replace Array to List" and after that code will be

```kotlin
    val localConstructor: Constructor<User> = this.constructorRef ?:
        User::class.java.getDeclaredConstructor(String::class.java, String::class.java,
        Date::class.java, Boolean::class.javaObjectType, List::class.java,
        Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef =
        it }
```

I use Moshi 1.11.0

**Comment by ZacSweers** [comment]
You can't create arrays with generic component types. This type would be illegal in java for the same reason:

```java
Map<String, Object>[] arr = new Map<String, Object>[0];
```

Technically, you could do this:

```java
Map[] arr = new Map[0];
System.out.println(arr.getClass()); // prints 'class [Ljava.util.Map;'
```

Which is what your kotlin type above is eventually coming out to

```kotlin
val mapArray = arrayOfNulls<Map<String, String>>(0)

println(mapArray.javaClass) // prints 'class [Ljava.util.Map;'
```

Java 12 would let us do this

```kotlin
Map::class.java.arrayType()
```

But obviously that doesn't cover our needs here.

We could use the moshi `Types` utility though, then take the raw type of its returned type

```kotlin
val arrayType = Map::class.java.asArrayType()
val arrayClassType = arrayType.rawType
```

But that's a bit of a circus. We could shortcircuit to this though I think

```kotlin
Array.newInstance(<raw-type>, 0).getClass()
```

This does deal with an allocation, but I guess it's better than failing. You should really use a list though, Moshi under the hood just creates a list and then stores it into an array after.
