### ISSUE TITLE
AssertionError: Built-in class kotlin.Any is not found

### ISSUE THREAD

**Issue by os1249399459** [square/moshi#1276]
I have an exception cause app crash occasionally
All i have is just user moshi as retrofit gson convert, moshi version is 1.11.0 and kotlin version is 1.4.20

> 1 kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:113)
--
> 2 kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:108)
> 3 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
> 4 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:602)
> 5 kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getBuiltInClassByName(KotlinBuiltIns.java:363)
> 6 kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getAny(KotlinBuiltIns.java:368)
> 7 kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getAnyType(KotlinBuiltIns.java:663)
> 8 kotlin.reflect.jvm.internal.impl.descriptors.NotFoundClasses$MockClassDescriptor.<init>(NotFoundClasses.kt:61)
> 9 kotlin.reflect.jvm.internal.impl.descriptors.NotFoundClasses$classes$1.invoke(NotFoundClasses.kt:44)
> 10 kotlin.reflect.jvm.internal.impl.descriptors.NotFoundClasses$classes$1.invoke(NotFoundClasses.kt:22)
> 11 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
> 12 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:602)
> 13 kotlin.reflect.jvm.internal.impl.descriptors.NotFoundClasses.getClass(NotFoundClasses.kt:94)
> 14 kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer$typeConstructor$1.invoke(TypeDeserializer.kt:128)
> 15 kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.typeConstructor(TypeDeserializer.kt:132)
> 16 kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.simpleType(TypeDeserializer.kt:76)
> 17 kotlin.reflect.jvm.internal.impl.serialization.deserialization.TypeDeserializer.type(TypeDeserializer.kt:64)
> 18 kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.valueParameters(MemberDeserializer.kt:417)
> 19 kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer.loadConstructor(MemberDeserializer.kt:342)
> 20 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.computePrimaryConstructor(DeserializedClassDescriptor.kt:126)
> 21 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.access$computePrimaryConstructor(DeserializedClassDescriptor.kt:36)
> 22 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$primaryConstructor$1.invoke(DeserializedClassDescriptor.kt:67)
> 23 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$primaryConstructor$1.invoke(DeserializedClassDescriptor.kt:36)
> 24 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
> 25 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.getUnsubstitutedPrimaryConstructor(DeserializedClassDescriptor.kt:130)
> 26 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.computeConstructors(DeserializedClassDescriptor.kt:133)
> 27 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.access$computeConstructors(DeserializedClassDescriptor.kt:36)
> 28 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$constructors$1.invoke(DeserializedClassDescriptor.kt:68)
> 29 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$constructors$1.invoke(DeserializedClassDescriptor.kt:36)
> 30 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
> 31 kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:489)
> 32 kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor.getConstructors(DeserializedClassDescriptor.kt:141)
> 33 kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:202)
> 34 kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:93)
> 35 kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:46)
> 36 kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
> 37 kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
> 38 kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(Unknown Source:7)
> 39 kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:237)
> 40 kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
> 41 com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:221)
> 42 com.squareup.moshi.Moshi.adapter(Moshi.java:145)
> 43 com.squareup.moshi.Moshi.adapter(Moshi.java:105)
> 44 retrofit2.converter.moshi.MoshiConverterFactory.requestBodyConverter(MoshiConverterFactory.java:108)
> 45 retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:315)
> 46 retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
> 47 retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
> 48 retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
> 49 retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
> 50 retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
> 51 retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
> 52 retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
> 53 retrofit2.Retrofit$1.invoke(Retrofit.java:160)
> 54 java.lang.reflect.Proxy.invoke(Proxy.java:1006)

Do anyone has same question? when i look aroud, i found this

[KT-43438](https://youtrack.jetbrains.com/issue/KT-43438)

@ZacSweers

**Comment by SzymonCierniewski** [comment]
We have the same issue with Moshi version 1.9.1 and Kotlin version is 1.3.71

**Comment by ZacSweers** [comment]
Without a reproducible sample, this is not actionable. Feel free to revisit if you can provide one

**Comment by iswaniswan** [comment]
> We have the same issue after updating Moshi to version 1.9.1
> Kotlin version is 1.3.71.

i've had the same issue too, using moshi version 1.11.0
any suggestion ?

**Comment by ZacSweers** [comment]
Without a reproducible sample, this is not actionable.

**Comment by fluxxion82** [comment]
In case anyone comes acoss this, I had gotten basically the same exception (using kotlin 1.5.31) and after spending way too long tracking it down, I found that it was from having added `exclude("**/**.kotlin_builtins")` to the packaging options.
