### ISSUE TITLE
how to deal not exist key

### ISSUE THREAD

**Issue by zs1973** [square/moshi#1279]
data model is like this:
`data class ApiResponse<T>(
    val msg: String,
    val code: Int,
    val data: T
)`

json like this:
 1.
`{
        "code":200,
        "msg":"ok",
        "data":{}
 }`
2.
` {
        "code":200,
        "msg":"ok"
 }`
3.
 {
`        "code":200,
        "msg":"ok",
        "data":""
 }`
4.
` {
        "code":200,
        "msg":"ok",
        "data":null
 }`
5.
` {
        "code":200,
        "msg":"ok",
        "data":[]
 }`

**Comment by 287138531** [comment]
大佬，你是怎么解决的？？？
