### ISSUE TITLE
Moshi 1.11.0 and Data Binding crashes Kapt

### ISSUE THREAD

**Issue by houmie** [square/moshi#1280]
Hello,

There is a problem with this plugin.

```implementation 'com.squareup.moshi:moshi-kotlin-codegen:1.11.0'```

which is causing the error.  
```
Execution failed for task ':app:kaptDebugKotlin'.
```

I had to downgrade to ```1.9.3``` to get it working.

Please see for more details here: https://stackoverflow.com/questions/65265169/kotlin-missing-kotlin-jvm-internal-functionreferenceimpl-raised-for-kaptdebugko/65266705

Others have confirmed this too.

Many Thanks,
Houman

**Comment by JakeWharton** [comment]
Please provide a sample project that reproduces the issue reliably. The StackOverflow question contains no details as to the source of the problem and why you think Moshi is responsible.

**Comment by ZacSweers** [comment]
You're running Moshi 1.11 (built against kotlin 1.4) with a kotlin 1.3 runtime. Hard to say for sure without an actual repro project, but that's a common error to happen in that scenario. You need to update your version of kotlin or don't update Moshi if you can't.

**Comment by houmie** [comment]
Hi @ZacSweers 

Sorry, how do you see that it's running on a Kotlin 1.3 runtime?  I can't see that from the config that I had posted on StackOverflow. Here is also a screenshot that shows the runtime is on 1.4.

<img width="514" alt="Screenshot 2020-12-15 at 07 55 21" src="https://user-images.githubusercontent.com/1832933/102186990-4b625f80-3eab-11eb-8bb7-935a6430d9e4.png">

I'm able to update anything, if you could please point out my mistake, I'm happy to try it out.
Thank you

**Comment by ZacSweers** [comment]
Your IDE version is not necessarily the runtime version. Some environments force an older runtime, like Gradle plugins/scripts or Android lint checks. Again, if you're not willing to make a reproducible sample that proves otherwise then this isn't an issue with Moshi

**Comment by houmie** [comment]
Thank you for your reply. I will make a new project tonight to emulate this and share it with you.
In the meanwhile I'm trying to follow what you have said. Are you saying beyond the Gradle (project) and Gradle (App) configs that I had shared on StackOverflow, there is more configuration that could affect the Kotlin Runtime?  Where do I find them?

**Comment by houmie** [comment]
@ZacSweers @JakeWharton 

Hey guys,  

I have prepared the demo project: https://github.com/houmie/BadMoshi

The issue is right in ```Unlockjson.kt```.

If I comment out all lines there, it builds fine.
Otherwise it fails saying:

```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

Thank you for your help.

**Comment by gordonxy** [comment]
I looked at your repro project and got it working. The first thing I tried is to move it closer to the Kotlin version Moshi 1.11 was compiled with. You were using 1.4.21 and the next closest to 1.4.10, which Moshi 1.11 was compiled with, is 1.4.20. With this small change it worked. 

I assume this will probably resolve itself then with the next Moshi release when it is compiled closer to 1.4.21?

**Comment by houmie** [comment]
Hi @gordonxy 

No, I tried it and it still doesn't compile with 1.4.20.  After setting it to `1.4.20` and clicking on Sync Gradle, did you actually rebuild it too?  Sometimes in the past I have forgotten to build after syncing a gradle. Please try again, because it doesn't work for me.

Thank you

**Comment by gordonxy** [comment]
Hey, I did rebuild and it worked, but I did change two things actually, and I was mistaken which one resolved the error. When I removed `buildFeatures {
        dataBinding true
    }` it resolved the error. The Kotlin version does not seem to matter, my mistake.

**Comment by houmie** [comment]
Ahhh interesting.

But surely this can't be the answer to the problem. How can we make an app without data binding?
If I remove that what you have suggested, I lose things like:

```
import androidx.databinding.DataBindingUtil
```

So the question is what has changed from ```Moshi 1.9.3``` to ```1.10.0 (and 1.11.0)``` to cause this problem?

**Comment by gordonxy** [comment]
Data binding is deprecated and you should use view binding instead afaik. I do not know why the combination of Moshi 1.11 and Data Binding crashes Kapt though.

**Comment by gordonxy** [comment]
Okay, I found out that if you use `kapt('com.squareup.moshi:moshi-kotlin-codegen:1.11.0')` instead of `implementation 'com.squareup.moshi:moshi-kotlin-codegen:1.11.0'` it will also build with dataBinding enabled. This is also the recommended way of adding that dependency according to the Moshi github readme.

**Comment by houmie** [comment]
Thank you, yes that works. 

I tried to take it a step farther and changed all of them to Kapt:

```
    kapt('com.squareup.retrofit2:retrofit:2.9.0')
    kapt('com.squareup.retrofit2:converter-moshi:2.9.0')
    kapt('com.squareup.moshi:moshi-kotlin:1.11.0')
    kapt('com.squareup.moshi:moshi-kotlin-codegen:1.11.0')
```

But this fails too. I think this is because we can only use kapt for pure Kotlin projects, is that correct? 
I'm still new to Android, so it's sometimes all magic to me. 

But I'm very happy I can at least proceed with my project. Although I hope someone looks into this, since I think this is still a bug.

**Comment by ZacSweers** [comment]
This is no longer a Moshi issue and should be moved to more appropriate forums.

**Comment by JakeWharton** [comment]
Also data binding is not deprecated. View binding exists between `findViewById` and data binding.

**Comment by mariciv** [comment]
I had the same problem recently trying to upgrade dependencies on a project. It was not the issue with DataBinding nor ViewBinding. The problem occurs when you try to build the application with both **reflect** and **codegen** dependencies added. Even though in the Readme it is stated you can use both. 

> When you use Kotlin with Moshi you may use reflection, codegen, or both.

 After removing one of these dependencies the build worked as expected. So to include Moshi you should use something like this:

```  
implementation('com.squareup.moshi:moshi:1.11.0')
// Choose only one of the approaches bellow
implementation('com.squareup.moshi:moshi-kotlin:1.11.0') // Reflect
kapt('com.squareup.moshi:moshi-kotlin-codegen:1.11.0') // Codegen
```
