### ISSUE TITLE
Issue with PolymorphicJsonAdapterFactory while using Moshi and Apollo Android

### ISSUE THREAD

**Issue by AnkitPatanaik** [square/moshi#1281]
Hi, I am using Apollo-Android to fetch data from my backend and Moshi to parse that JSON Response in my unit test.

I'm running into a `com.squareup.moshi.JsonDataException: Missing label for interfaceName`(code below) error while using `PolymorphicJsonAdapterFactory`.

Below is the code I'm using to parse this data in my unit test. `ValueQuery.AsType1`, `ValueQuery.AsType2`, `ValueQuery.AsType3`, and `ValueQuery.AsType4` are concrete implementations of `ValueQuery.InterfaceName` that were generated by Apollo.

The goal is to parse a Json object, turn it into an object to use in a mock.

```
val graphQLResponseString = this::class.java.getResource("sampleresponse.json").readText()
val moshi = Moshi.Builder()
    .add(
        PolymorphicJsonAdapterFactory.of(ValueQuery.InterfaceName::class.java, "interfaceName")
            .withSubtype(ValueQuery.AsType1::class.java, "type1")
            .withSubtype(ValueQuery.AsType2::class.java, "type2")
            .withSubtype(ValueQuery.AsType3::class.java, "type3")
            .withSubtype(ValueQuery.AsType4::class.java, "type4"))
    .add(KotlinJsonAdapterFactory())
    .build()
        
val jsonAdapter: JsonAdapter<ValueQuery.Data> = moshi.adapter(ValueQuery.Data::class.java) //error comes here
val data: ValueQuery.Data? = jsonAdapter.fromJson(graphQLResponseString)

```

I'm not sure if I'm misunderstanding how to use PolymorphicJsonAdapterFactory, or if there is some other underlying issue? For reference, I've run into no problems with Moshi+Apollo-Android before, however they did require mapping to an Interface implementation. I feel like Apollo-Android is not the issue, but I thought I would mention it just in case it made a difference.

Let me know if there is any information I can provide/missed that would be helpful.

Edit: Forgot to include the JSON being converted:
```{
  "a": {
    "b": {
      "c": {
        "d": {
          "encompassingObject": {
            "p": null,
            "r": null,
            "u": null,
            "interfaceName": [
              {
                "color": "#f79349",
                "date": "04/16/2017",
                "formattedDate": "04/16/2017"
              },
              {
                "color": "#388ee5",
                "date": "04/15/2017",
                "formattedDate": "04/15/2017"
              }
            ]
          }
        }
      }
    }
  }
}

**Comment by ZacSweers** [comment]
Usage questions should go on stackoverflow and use the `moshi` tag
