### ISSUE TITLE
How to parse a single object with dynamic keys.

### ISSUE THREAD

**Issue by eloyesp** [square/moshi#1282]
I need to parse a json like this one:

``` json 
{
  "key": 12,
  "kay": 15
}
```

Obviously, I don't know what will the keys look like, I need to fetch the full map as a `Map<String, Integer>` or something like that. Is that possible? The examples on the readme always have a root element like `{"foo": {"key": 12,"kay": 15}}`, that this example lacks, and discard the known keys (where this example requires those unknown keys).

**Comment by eloyesp** [comment]
Ok, seems that not having a root element force the use of:

``` java
import com.squareup.moshi.Types;
import java.lang.reflect.Type;

Type type = Types.newParameterizedType(Map.class, String.class, String.class);
JsonAdapter<Map<String,String>> adapter = moshi.adapter(type);
Map<String,String> foo = adapter.fromJson(source);
```

Having a bit better documented that could help a bit.

**Comment by rharter** [comment]
This is a pretty minor modification of the [array parsing example](https://github.com/square/moshi#parse-json-arrays) in the readme. Moshi's primary purpose is to parse JSON your model objects, so most of the documentation focuses on that use case. If you see deficiencies in the documentation, a better approach would be to submit a PR.

**Comment by JakeWharton** [comment]
You can also use `JsonReader` directly and loop. Or have it give you a value (which will be a `Map` in the case of objects).
