### ISSUE TITLE
Does R8 "full mode" require any additional proguard rules?

### ISSUE THREAD

**Issue by ColtonIdle** [square/moshi#1285]
This doc says https://developer.android.com/studio/build/shrink-code?authuser=1

> However, when using “full mode”, R8 does not make this assumption and, if R8 asserts that your code otherwise never uses the class at runtime, it removes the class from your app’s final DEX. That is, if you want to keep the class and its static initializer, you need to include a keep rule in your rules file to do that.
> 
> If you encounter any issues while using R8’s “full mode”, refer to the R8 FAQ page for a possible solution. If you are unable to resolve the issue, please report a bug.

Clicking "R8 FAQ" takes you here https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md

which mentions GSON. Since "moshi" has been thought of as gson3, does anyone know if these same rules apply?

I'm just enabling R8 on my project and I found this full mode and now I'm getting a few cryptic stacktraces (that dont actually mention moshi directly), and I'm not sure if it's _maybe_ due to this? Would appreciate if someone smarter than me in terms of moshi knew if this type of care had to be taken for moshi. Thank you (this makes me wish that github discussions were a thing for moshi)

**Comment by ZacSweers** [comment]
No

**Comment by ColtonIdle** [comment]
Thanks
