### ISSUE TITLE
Nullable properties no longer working in generated adapters since 1.9?

### ISSUE THREAD

**Issue by tdrp** [square/moshi#1292]
Hi - I inherited a project running with moshi 1.8 that uses generated adapters. When trying to upgrade it to moshi 1.9 (or 1.11) I get a bunch of errors like these in the auto-generated adapter:

**Expression in a class literal has a nullable type 'Date?', use !! to make the type non-nullable**

@JsonClass(generateAdapter = true)
data class MyClass
    (
    @Json(name = "dd") val Date: Date? = null
}

A quick look at the adapter shows this:

 val localConstructor: Constructor<Message> = this.constructorRef ?:
// other stuff
        Message::class.java.getDeclaredConstructor(Long::class.javaPrimitiveType,
        Long::class.javaPrimitiveType, Long::class.javaPrimitiveType, String::class.java,
        Boolean::class.javaPrimitiveType, Date::class.java // <-- error is here.

Is there a fix for this? The "Date" field is made nullable so that if it is not specified in the data returned by the server, it is set to null. It was working as expect in 1.8 without any extra changes.

Thank you

**Comment by ZacSweers** [comment]
That doesn't make sense, that is passed into a java reflection API and is separate from the nullability of the property. Can you reproduce with your sample in an isolated, reproducing project? I cannot repro

**Comment by tdrp** [comment]
Thanks for the reply - I'm attaching a minimum repro I just put together. Please let me know if it doesn't repro for you.
[MyApplication2.zip](https://github.com/square/moshi/files/5899107/MyApplication2.zip)

**Comment by tdrp** [comment]
Thanks for the response - here is the minimal repro I could get. [MyApplication4.zip](https://github.com/square/moshi/files/5899123/MyApplication4.zip)

**Comment by ZacSweers** [comment]
This is because your property is confusingly also called `Date`, which conflicts with the `Date` type. While we could try to capture these cases and know when to fully qualify the type, this is pretty unconventional code and can be avoided by just writing idiomatic Kotlin code (i.e. lower camel case property names, avoiding conflicts with types, etc). I don't think Moshi should try to solve this problem

**Comment by tdrp** [comment]
Thank you - a quick look at the original source does confirm that this only seems to happen when the property name is the same name as the class so your hypothesis appears to be correct. I will rename them on my end.
