### ISSUE TITLE
kotlin: can't normal toJson and fromJson

### ISSUE THREAD

**Issue by a173012907** [square/moshi#1297]
`val moshi = Moshi.Builder()
            .addLast(KotlinJsonAdapterFactory())
            .build()`
**toJson**:
`  class A() {
        val e: E = E.FALSE
        val name = ""
    }`
`enum class E{
        TRUE,
        FALSE
    }`
` @Test
    fun test1() {
        val a = A()
        val adapter = moshi.adapter(Any::class.java)
        println(adapter.toJson(a))
        println(Gson().toJson(a))
    }`
unit test result:
{}
{"e":"FALSE","name":""}

in this case, we can't toJson ,but formJson is normal,such as
`@Test
    fun test2() {
        val json = "{\"e\":\"FALSE\",\"name\":\"\"}"
        val adapter = moshi.adapter(A::class.java)
        println(adapter.fromJson(json))
    }`

**fromJson**
`data class AA(
            val e: E = E.FALSE,
            val name:String = "SS"
    )`
`enum class E{
        TRUE,
        FALSE
    }`
`class BB {
        val e: E = E.FALSE
        val name:String = "SS"
    }`
`@Test
    fun test3() {
        val json = "{\"e\":\"FALSE1\",\"name\":\"\"}"
        val adapterB = moshi.adapter(BB::class.java)
        println(adapterB.fromJson(json))
        val adapterA = moshi.adapter(AA::class.java)
        println(adapterA.fromJson(json))
    }`
in this case,wo can success fromJson when class is BB, AA is fail
but when we change BB type 'val' to 'var'，it will fail to fromJson too!

**Comment by ZacSweers** [comment]
Please use stackoverflow for usage questions, this is the issue tracker. Your question was also quite hard to read, I would recommend cleaning it up a bit before posting on SO
