### ISSUE TITLE
Custom converter get stucked if no value is read.

### ISSUE THREAD

**Issue by rephiscorth** [square/moshi#130]
This one took us sometime to narrow down. So while stubbing out a custom converter class for a fast setup before starting with TDD, I wrote the implementation as the following:

```java
@FromJson
public MyClass read(JsonReader reader) throws IOException {
    // TODO: write actual implementation
    return new MyClass();
}
```

The program crashed with an OOM exception and we had no idea why until we tried adding the following:

```java
@FromJson
public MyClass read(JsonReader reader) throws IOException {
    // TODO: write actual implementation
    while(reader.hasNext()) {
        reader.skipValue();
    }
    return new MyClass();
}
```

Seems like the class that calls this converter via reflection, is waiting for it to consume it all while continuously allocating memory(?). I might be wrong, but I believe this is a bug.

**Comment by swankjesse** [comment]
I don’t think there’s an action for us to take on this. When a JsonAdapter produces data without consuming JSON, a lot of data ends up being produced.
