### ISSUE TITLE
Allow to deserialize kotlin object in codegen

### ISSUE THREAD

**Issue by ursusursus** [square/moshi#1304]
I use codegen & I often find myself writing sealed class hierarchies like
```
sealed class Validity {
   object Always : Validity()
   data class Sometimes(val ifValue: Int) : Validity()
   object Never: Validity()
}
```
I'm aware of https://github.com/ZacSweers/MoshiX/tree/main/moshi-sealed, but It only uses objects as default values

What I'd expect the api to allow is this
```
sealed class Validity {
   @JsonClass(generateAdapter = false)
   object Always : Validity()
   
   @JsonClass(generateAdapter = true)
   data class Sometimes(val ifValue: Int) : Validity()
   
   @JsonClass(generateAdapter = false)
   object Never: Validity()
}

PolymorphicJsonAdapterFactory.of(Validity::class.java, "type")
	.withSubtype(Always::class.java, "always")
	.withSubtype(Sometimes::class.java, "sometimes")
	.withSubtype(Never::class.java, "never")
```

Thus making it symetrical with enums

Currently I cant do that, and I need to change the objects to param less classes, and that might be a footgun if equals is used (and equals/hashmap not overriden)

**Comment by ZacSweers** [comment]
> It only uses objects as default values

This is not true and detailed near the top of the README: https://github.com/ZacSweers/MoshiX/tree/main/moshi-sealed#object-subtypes
