### ISSUE TITLE
Add a convenient function to process generic list with correct types instead of defaulting to LinkedHashTreeMap

### ISSUE THREAD

**Issue by adamsz-lume** [square/moshi#1315]
Hi,
I would be nice to have a function which could do following/similar with reified types in Kotlin:
```kotlin                    
val mainType = typeOf<T>()
val finalType = Types.newParameterizedType(
    T::class.java,
    *mainType.arguments.map { it.type!!.javaType }.toTypedArray()
)
return Serializer.moshi.adapter<T>(finalType).fromJson(bodyContent)
```
That would make the usage nicer for generic collections deserialisation.
Right now, it can be quite a surprise to get
```
class com.squareup.moshi.LinkedHashTreeMap cannot be cast to class uk.lume.models.Quiz (com.squareup.moshi.LinkedHashTreeMap and uk.lume.models.Quiz are in unnamed module of loader 'app')
java.lang.ClassCastException: class com.squareup.moshi.LinkedHashTreeMap cannot be cast to class uk.lume.models.Quiz (com.squareup.moshi.LinkedHashTreeMap and uk.lume.models.Quiz are in unnamed module of loader 'app')
	at MyTests$1$3.invokeSuspend(Tests.kt:38)

```
Wasted quite some time trying to figure out how to get that sorted in my code where I have to relay on reified values. Gson and Jackson have similar convenient functions.

**Comment by ZacSweers** [comment]
I don't follow what the ask is here, you can already do this via [reified `adapter()` extensions](https://github.com/square/moshi/blob/6df66b81dce3d2151e90d01535742cfef2cae6b9/moshi/src/main/java/com/squareup/moshi/-MoshiKotlinExtensions.kt#L29), assuming `T` is reified or a known type of your choosing

```kotlin
import com.squareup.moshi.adapter

return Serializer.moshi.adapter<T>(finalType).fromJson(bodyContent)
```

**Comment by adamsz-lume** [comment]
This method makes me set the finalType manually by myself.
I am talking about a method like:
```
@OptIn(ExperimentalStdlibApi::class)
inline fun <reified T> Moshi.genericAdapter(): JsonAdapter<T> {
    val mainType = typeOf<T>()
    if (mainType.arguments.isEmpty()) {
        return this.adapter(mainType.javaType)
    } else {
        val finalType = Types.newParameterizedType(
            T::class.java,
            *mainType.arguments.map { it.type!!.javaType }.toTypedArray()
        )

        return this.adapter(finalType)
    }
}
```
So I can do:
```
protected inline fun <reified T: Any?> responseBody(bodyContent: String): T? {
    // DO SOMETHING HERE
    // ...
    return Serializer.moshi.adapter<T>().fromJson(bodyContent)
}

// ...
class Entity {}

val listOfEntities = responseBody<List<Entity>>(/* some json string */)
```
and listOfEntities will be of type List<Entity> and not a list of LinkedHashTreeMaps

**Comment by ZacSweers** [comment]
I still don't know what the ask is, the function I linked achieves that.

**Comment by adamsz-lume** [comment]
The method I am proposing does not require to pass a finalType manually to the adapter method.

**Comment by ZacSweers** [comment]
Neither does the one I linked. Please provide a real world example that you cannot achieve with the adapter function I linked that your proposal does cover?

**Comment by adamsz-lume** [comment]
Will do, in meantime in your example it says:
```
import com.squareup.moshi.adapter

return Serializer.moshi.adapter<T>(finalType).fromJson(bodyContent)
```

finalType is passed as argument, in my example genericAdaptor method does not require a finalType as it is derived from the T

**Comment by ZacSweers** [comment]
Sorry remove that param, it was leftover

```
return Serializer.moshi.adapter<T>().fromJson(bodyContent)

```

**Comment by adamsz-lume** [comment]
Nice one, got it working. Was just missing the @OptIn on a method. Thanks for the help!
