### ISSUE TITLE
Moshi is initializing an object that not exist by default 

### ISSUE THREAD

**Issue by mr-gil** [square/moshi#1316]
This is my response:
```
[{
        "id": 1154653,
        "key": "N8Qpm04kGCVGa8dx",
        "ticket": 5830
         ... (tracking object not exist but is initialized by moshi)
 }]
```
 This is my kotlin object, as you can see there is a key called   `val tracking: Tracking?` , this object is not included in the response but it's initialzied by mosho 
 
```
 @JsonClass(generateAdapter = true)
data class OrderDetail(
        val id: Int,
        val key: String,
        val ticket: Int
        val tracking: Tracking?,
)

@JsonClass(generateAdapter = true)
data class Tracking(
        val status: TrackingStatus? ,
        val events: List<TrackingEvent>? 
)

@JsonClass(generateAdapter = true)
data class TrackingStatus(
        val detail: List<TrackingDetail>? 
)

@JsonClass(generateAdapter = true)
data class TrackingDetail(
        val name: String? ,
        val time: String? ,
        val date: String? ,
        val description: String? 
)
```

And the output is :

![image](https://user-images.githubusercontent.com/5429538/111108628-ddb3e700-851e-11eb-983f-c8c03b06f694.png)

As you can see ,  `val tracking: Tracking?,`. its initialized , and the final object is filled with null values.

**Comment by ZacSweers** [comment]
Can you give a bit more context? Is this with reflection? Code gen? What version of Moshi? Can you paste the generated adapter if using the code gen? Can you paste the full json or offer a reprising sample project?

**Comment by mr-gil** [comment]
I resolve the problem cleaning the project,  maybe it was just a mistake of the build generator when I was changing the constants
