### ISSUE TITLE
@JsonQualifier annotation class can not be accessed from another module

### ISSUE THREAD

**Issue by diousk** [square/moshi#1318]
Hi @ZacSweers 
This issue is related to https://github.com/square/moshi/issues/1290

I'm facing the same problem in my Android project and I found out the cause to reproduce this issue.

When a data class contains a JsonQualifier annotation in another module like this
```
// in app module
@JsonClass(generateAdapter = true)
data class TestDataClass(
    @TestQualifier val type: TestType
)
```

and the annotation is defined in **data** module
```
// in data module
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class TestQualifier

enum class TestType(val type: String) {
    Main("main");
}

class TestTypeAdapter {
    @FromJson
    @TestQualifier
    fun fromJson(type: String): TestType {
        return when (type) {
            else -> TestType.Main
        }
    }

    @ToJson
    fun toJson(@TestQualifier type: TestType): String {
        return when (type) {
            else -> "main"
        }
    }
}
```

and NPE error is thrown during compile time
```
Caused by: java.lang.NullPointerException
	at com.squareup.moshi.kotlin.codegen.MetadataKt.qualifiers(metadata.kt:486)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.primaryConstructor(metadata.kt:96)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:210)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
```

and here is the reproducible sample: https://github.com/diousk/MoshiErrorSample

Note:
moshi version: 1.11.0
epoxy processor version: 4.4.2 (which **update the KotlinPoet to 1.7.2**)
if I change to use epoxy version 4.2.0, the error is gone
(changelog of epoxy: https://github.com/airbnb/epoxy/blob/master/CHANGELOG.md)

**Comment by ZacSweers** [comment]
Please add to that issue rather than making a new one next time. Thanks for the repro, I'll take a look soon

**Comment by ZacSweers** [comment]
This was resolved by #1287

**Comment by diousk** [comment]
Great! Any plan to release the fixed version?

**Comment by ZacSweers** [comment]
No, we're working on 2.0. you can use a snapshot or build locally for now
