### ISSUE TITLE
Document how to use Moshi with java.io.OutputStream & java.io.InputStream

### ISSUE THREAD

**Issue by mleonhard** [square/moshi#1328]
I'm writing code to serialize JSON objects to [`java.io.OutputStream`](https://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html) and deserialize from [`java.io.InputStream`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html).

I searched for 20 mins for the way to pass an `OutputStream` to `JsonAdapter<?>::toJson()`.  Let's put the answer in the docs to help others:

```java
import com.squareup.moshi.JsonAdapter;
import com.squareup.moshi.Moshi;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import okio.BufferedSink;
import okio.Okio;

static <T> T fromJson(Class<T> clazz, InputStream inputStream) throws IOException {
  Moshi moshi = new Moshi.Builder().build();
  JsonAdapter<T> adapter = moshi.adapter(clazz);
  return adapter.fromJson(Okio.buffer(Okio.source(inputStream)));
}

static <T> void toJson(T obj, OutputStream outputStream) throws IOException {
  Moshi moshi = new Moshi.Builder().build();
  @SuppressWarnings("unchecked")
  JsonAdapter<T> adapter = moshi.adapter((Class<T>) obj.getClass());
  BufferedSink out = Okio.buffer(Okio.sink(outputStream));
  adapter.toJson(out, obj);
  out.flush();  // Also flushes `outputStream`.
}
```

**Comment by ZacSweers** [comment]
Moshi uses Okio and Okio has plenty of docs on how to interop with those types 👍

**Comment by mleonhard** [comment]
Can you please point me to the "plenty of docs on how to interop with those types"?

https://square.github.io/okio/ has no code showing how to use Okio types with InputStream or OutputStream.  There is a little snippet showing reading from a Socket.

Are there some other docs I could have found during my search?

**Comment by ZacSweers** [comment]
Did you try the search on the site? It's pretty handy and points to here https://square.github.io/okio/#sources-and-sinks. If you then look at the `Source` and `Sink` APIs + extensions, it's the first one on both  [source](https://square.github.io/okio/2.x/okio/okio/source.html) and [sink](https://square.github.io/okio/2.x/okio/okio/sink.html).

![image](https://user-images.githubusercontent.com/1361086/113378625-792dc000-9345-11eb-98ee-0f5652f1256a.png)

![image](https://user-images.githubusercontent.com/1361086/113378603-6e732b00-9345-11eb-8046-fecc967a3971.png)

**Comment by mleonhard** [comment]
I filed this issue to tell you about my problem as a new user of Moshi.  The purpose of the documentation is to help people like me.  It seems to me that you're not interested in iterating on your documentation to make it better meet the needs of its users.  That's ok.  Maintaining an open source project is tiring.  Most people burn out quickly while doing that job.  How about searching for someone else to help maintain it?  You could take a break.

**Comment by shalva97** [comment]
`Okio.buffer(Okio.source(inputStream))` is now deprecated. Instead use extension functions from Okio
```kotlin
adapter.fromJson(inputStream.source().buffer())
```

**Comment by jderijke** [comment]
I ran into this as well and i second to the request of including a simple example reading to/from a file to the docs.
With gson i can just pass in a bufferedreader and I'm done. With Moshi I need to know the internals and be aware that it only eats Okio ??
