### ISSUE TITLE
Link to updated javadocs and remove out-dated javadocs

### ISSUE THREAD

**Issue by mleonhard** [square/moshi#1331]
I need to know if my software can safely share [`com.squareup.moshi.Moshi`](https://square.github.io/moshi/1.x/moshi/) and [`com.squareup.moshi. JsonAdapter<T>`](https://square.github.io/moshi/1.x/moshi/) objects between threads.  I want to store them in `static final` class members.

I found nothing about concurrent access or thread-safety in the javadocs.  None of the [`examples`](https://github.com/square/moshi/search?p=2&q=static+com.squareup.moshi.recipes) store a `Moshi` or `JsonAdapter` object in a `static final` class member.

Let's answer this question for new users.

**Comment by mleonhard** [comment]
Thread-safety is documented in this version of the javadocs
- https://javadoc.io/doc/com.squareup.moshi/moshi/latest/moshi/com.squareup.moshi/-json-adapter/index.html
- https://javadoc.io/doc/com.squareup.moshi/moshi/latest/moshi/com.squareup.moshi/-moshi/index.html

There are two problems to fix:
1. Remove the out-dated javadocs at https://square.github.io/moshi/1.x/
1. Update the GitHub project URL at https://github.com/square/moshi to point to https://javadoc.io/doc/com.squareup.moshi/ :
   ![Screen Shot 2021-04-04 at 13 11 24](https://user-images.githubusercontent.com/520739/113520379-874b2e80-9547-11eb-9711-20bef2bb6711.png)

**Comment by ZacSweers** [comment]
The `gh-pages` branch was a little out of date, I've updated it now. We aren't going to point at an arbitrary external site for javadocs.

For reference, thread safety is covered in the following places.
* `Moshi` https://github.com/square/moshi/blob/850dc206cfd2f831823c2071e586cb1355060983/moshi/src/main/java/com/squareup/moshi/Moshi.java#L43
* `JsonAdapter`
https://github.com/square/moshi/blob/797140c5cf0e376387b99fcaa8cc00988d1ffbb5/moshi/src/main/java/com/squareup/moshi/JsonAdapter.java#L34-L37
* `JsonWriter` https://github.com/square/moshi/blob/850dc206cfd2f831823c2071e586cb1355060983/moshi/src/main/java/com/squareup/moshi/JsonWriter.java#L132-L134
* `JsonReader` https://github.com/square/moshi/blob/850dc206cfd2f831823c2071e586cb1355060983/moshi/src/main/java/com/squareup/moshi/JsonReader.java#L183-L184
