### ISSUE TITLE
Required value 'firstName' (JSON name 'first_name') missing at $

### ISSUE THREAD

**Issue by rakshitsoni02** [square/moshi#1335]
**@JsonClass(generateAdapter = true)
data class UserProfileDto(
    @Json(name = "first_name") val firstName: String,
    @Json(name = "last_name") val lastName: String,
    @Json(name = "profile") val profile: Map<String, String>,
)**

    @PUT("profile")
    suspend fun updateProfile(
        @Body profileUpdateRequest: UserProfileDto
    ): Response<UserProfileDto?>

if I change from @PUT to @POST error is gone, don't know the reason, any clue?

**Comment by ZacSweers** [comment]
Usage questions should go on stackoverflow
