### ISSUE TITLE
Type adapters with `@JsonQualifier` need both methods annotated `@ToJson` and `@FromJson` when creating JsonAdapter

### ISSUE THREAD

**Issue by floating-cat** [square/moshi#134]
Type adapters with `@JsonQualifier` need both methods annotated `@ToJson` and `@FromJson` when creating JsonAdapter. If we only want to serialize or deserialize and create a type adapters with either method annotated `@ToJson` or `@FromJson`  (not both), `Moshi#adapter(Class<T>)` would throw an IllegalArgumentException: No @ToJson (or @FromJson) adapter for int annotated XXX.

Example:
```java
import com.squareup.moshi.*;

import java.io.IOException;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class Test {

    public static void main(String[] args) throws IOException {
        Moshi moshi = new Moshi.Builder().add(new ColorAdapter()).build();
        JsonAdapter<Rectangle> jsonAdapter = moshi.adapter(Rectangle.class);

        Rectangle rectangle = jsonAdapter.fromJson("{\"color\": 16711680}");
        System.out.println(rectangle.color);
    }

    static class Rectangle {

        @HexColor
        int color;
    }

    @Retention(RetentionPolicy.RUNTIME)
    @JsonQualifier
    @interface HexColor {
    }

    static class ColorAdapter {

        @FromJson
        @HexColor
        int fromJson(String rgb) {
            return Integer.parseInt(rgb.substring(1), 16);
        }
    }
}
```
```
Exception in thread "main" java.lang.IllegalArgumentException: No @ToJson adapter for int annotated [@Test$HexColor()]
	at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:48)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:80)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:64)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:61)
	at Test.main(Test.java:11)
```

If we use a custom type adapters without `@JsonQualifier`, we only need either method annotated `@ToJson` or `@FromJson`:
```java
// this code works if we don't use the type adapter with @JsonQualifier
static class Rectangle {

    // @HexColor
    int color;
}

static class ColorAdapter {

    @FromJson
    // @HexColor
    int fromJson(String rgb) {
        return Integer.parseInt(rgb.substring(1), 16);
    }
}
```

Edit: fix typos and simplify example.

**Comment by swankjesse** [comment]
Not sure if it’s ideal, but it’s deliberate. Moshi can build a default type adapter for any type using reflection. But it refuses to build default type adapters for qualified types.

The problem with the lone annotation case is that Moshi knows how to encode the type but not to decode it.

I’m unsure what the right fix is. Should we just require both `@ToJson` and `@FromJson` in all cases? That seems unnecessarily strict. Or should we succeed at building the annotated case and fail at runtime when attempting to decode?

**Comment by floating-cat** [comment]
Thanks for you quick reply.
Require both `@ToJson` and `@FromJson` in all cases is too strict IMHO, and I prefer failing at runtime when attempting to decode.

Though current behavior (need both `@ToJson` and `@FromJson`) is a bit verbose to me, feel free to close this issue if you prefer current behavior (because it is deliberate).

**Comment by swankjesse** [comment]
Your workaround is pretty straightforward. Just add this:

```
        @FromJson @HexColor String toJson(int rgb) {
            throw new UnsupportedOperationException();
        }

```

**Comment by floating-cat** [comment]
I did same workaround yesterday :)
After rethinking just now, I feel this workaround it OK to me, so I close this issue.
Thanks for your help. Feel free to open this issue if you want to do something.

**Comment by swankjesse** [comment]
Works for me.
