### ISSUE TITLE
moshi Json Multiple name 

### ISSUE THREAD

**Issue by Yinzeyu** [square/moshi#1344]
Gson 
  @SerializedName(value = "teamName",  alternate = {"name"})
    @Expose
    public String teamName;

moshi ？
   @Json(name = "teamName")
    @Expose
    public String teamName;
如何支持多个别名

**Comment by ZacSweers** [comment]
Moshi tries to stay simple and the expectations are unclear if multiple keys defined in such an annotation are present. It's better for you do define properties for both as internal and then expose your own computed property separately and handle their logic accordingly
