### ISSUE TITLE
Proposal: Add Kotlin examples to the README.md 

### ISSUE THREAD

**Issue by sangeetds** [square/moshi#1345]
The README.md file lacks any Kotlin example for anyone to begin with. It would be nice if it would include examples like it already has for Java. 
Will be happy to add the examples if this sounds good.

**Comment by Egorand** [comment]
Sounds good, feel free to send us a PR! A good place to start might be converting the existing examples into Kotlin, similar to what we did for Okio: https://square.github.io/okio/

@ZacSweers any other Kotlin examples that you think we should add to README?

**Comment by ZacSweers** [comment]
Not that I can think of, just a simple example should suffice

**Comment by sangeetds** [comment]
I went through the examples on the Okia website. Java/Kotlin codes were written in tabsets there. How do you suggest I write it here. Would Java code followed by Kotlin work? Or will collapsible sections be better?

**Comment by Egorand** [comment]
Both options sound good to me! We can try collapsible sections with the Java section being revealed by default while the Kotlin one would be collapsed by default.

**Comment by sangeetds** [comment]
Hey @ZacSweers @Egorand! Bumping this thread for visibility cause I forgot to mention that I have raised a PR for the same.
