### ISSUE TITLE
moshi-kotlin 1.12 pulls in kotlin-reflect 1.4.x

### ISSUE THREAD

**Issue by mttkay** [square/moshi#1348]
This has been a problem for a while now (even prior to the Kotlin 1.5 update), but it appears that `moshi-kotlin` is pulling in outdated versions of `kotlin-reflect`. I am targeting Kotlin 1.5.10 and I declare the moshi dependency as follows:

```
implementation "com.squareup.moshi:moshi-kotlin:1.12.0"
```

Here is what `gradle dependencies` says:

```
+--- com.squareup.moshi:moshi-kotlin:1.12.0
|    +--- com.squareup.moshi:moshi:1.12.0
|    |    +--- com.squareup.okio:okio:2.10.0
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.20 -> 1.5.10 (*)
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.20 -> 1.5.10
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.10 (*)
|    +--- org.jetbrains.kotlin:kotlin-reflect:1.4.31
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.10 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.10 (*)
```

Gradle ignored the dependency on kotlin-* 1.4.31 and replaced it with the one I target, however, it results in build warnings:

```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/mk/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.10/da6a904b132f0402fa4d79169a3c1770598d4702/kotlin-stdlib-1.5.10.jar (version 1.5)
    /home/mk/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.10/6b84d926e28493be69daf673e40076f89492ef7/kotlin-stdlib-common-1.5.10.jar (version 1.5)
    /home/mk/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.31/63db9d66c3d20f7b8f66196e7ba86969daae8b8a/kotlin-reflect-1.4.31.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.5 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

The advice given in the warning resolves the issue:

```
w: Consider providing an explicit dependency on kotlin-reflect 1.5 to prevent strange errors
```

However, I would expect moshi-kotlin to sort this out for me since my application does not directly depend on kotlin-reflect, and I would consider declaring dependencies on library-internals to be an anti-pattern.

The expected behavior would be for the top-level dependency on `moshi-kotlin` to depend on the correct version of `kotlin-reflect`, which should be 1.15.x as of recently.

**Comment by ZacSweers** [comment]
moshi 1.12 is compiled against Kotlin 1.4.31 so I don't see anything particularly surprising there.

The problem is that KGP (Kotlin Gradle Plugin) is understandably applying a newer kotlin stdlib version in your project than the version of kotlin-reflect that Moshi pulls along. This isn't really a Moshi issue though, our only options would be to either make `kotlin-reflect` a `compileOnly` dependency (which is annoying to consumers that they have to then manually declare kotlin-reflect) or release a new version with an updated dependency every time Kotlin releases a new version.

Kotlin offers a bom artifact, I would recommend using that to force same-versions for common dependencies. I tend to think KGP should apply this by default and give folks an opt-out, but that's outside the scope of this :).

Does that make sense?

**Comment by mttkay** [comment]
> Does that make sense?

It does! Thanks for clarifying. I wasn't aware of the BOM artifacts either. I will close this as expected behavior then.

**Comment by theapache64** [comment]
@ZacSweers but the [official doc](https://kotlinlang.org/docs/compatibility-modes.html#binary-compatibility-warnings) suggests using an explicit dependency on the 1.1 reflection library 🤔 

> This means that you have a dependency on libraries of different versions, for example the 1.1 standard library and the 1.0 reflection library. To prevent subtle errors at runtime, we recommend you to use the same version of all Kotlin libraries. In this case, consider adding an explicit dependency on the 1.1 reflection library.

![image](https://user-images.githubusercontent.com/9678279/132644232-b6be7676-cb09-44c7-8824-7b7aa479143d.png)

Any idea which one is better and why?

**Comment by ZacSweers** [comment]
which one is better between an explicit dependency vs a bom?

**Comment by theapache64** [comment]
of course BOM, but wondering why suggesting to use explicit dependency in the official doc.

**Comment by ZacSweers** [comment]
BOM isn't always what people want, I imagine they're just recommending the option that introduces the least amount of change. I wouldn't overthink it
