### ISSUE TITLE
Parse YQL query with Moshi

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/moshi#135]
I am trying to parse a YQL query that returns a JSON response like this: 
`query: {
   results: {
      channel: [
         {
            item: {
               condition: {
                  code: "11",
                  date: "Tue, 23 Feb 2016 2:30 am JST",
                  temp: "43",
                  text: "Light Rain"
               }
            }
         },   
         {
            item: {
               condition: {
                  code: "14",
                  date: "Mon, 22 Feb 2016 8:29 pm MSK",
                  temp: "30",
                  text: "Snow Shower"
               }
            }
         }
      ]
   }
}      `

You can see this query in action here: 
> https://query.yahooapis.com/v1/public/yql?q=select%20item.condition%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%20in(%27tokyo%27%2C%20%27moscow%27%2C%20%27new%20york%27%2C%20%27los%20angeles%27%2C%20%27san%20diego%27%2C%20%27san%20francisco%27%2C%20%27fort%20lee%27%2C%20%27jersey%20city%27%2C%20%27seattle%27%2C%20%27vancouver%27))&format=json&diagnostics=false&callback=

I created model classes, starting from **query** all the way down to **condition** objects, but Retrofit isn't parsing this data into Moshi for me.  What did I do wrong?

Thanks,
Igor

**Comment by JakeWharton** [comment]
What exception is thrown? Or can you provide a test case that demonstrates the problem?

**Comment by IgorGanapolsky** [comment]
I am getting 
> IllegalArgumentException: Unable to create converter for class org.json.JSONObject

Here is the code that demonstrates this problem: https://github.com/IgorGanapolsky/YQL-Retrofit2/tree/master

**Comment by IgorGanapolsky** [comment]
Update, I resolved the IllegalArgumentException by adding a top-level YQLResponse model object.  Now I am getting a Retrofit2 error for `Result` Observable.  But I'll post that issue in the Retrofit repo.  Thanks!
