### ISSUE TITLE
Make proguard optional during creating jsonadapter

### ISSUE THREAD

**Issue by SeongUgJung** [square/moshi#1351]
https://github.com/square/moshi/pull/1067 In this MR,

It made that codegen generates always proguard rules for class of `@JsonClass` annotated

My production should do obfuscating all classes. But This feature, codegen of proguard, blocks `@JsonClass` annotated data class. 

Can we have an option to make codegen-proguard disable?

**Comment by ZacSweers** [comment]
If you obfuscate the class names with generated adapters, Moshi won't be able to find them at runtime.

**Comment by SeongUgJung** [comment]
@ZacSweers Yes. for that, I actually built our own JsonAdapterFactory to assign proper adapters

**Comment by ZacSweers** [comment]
I see. And the ask in this case is just to be able to disable proguard rule generation?

**Comment by SeongUgJung** [comment]
@ZacSweers yes exactly.

I think that is enough to have env-option data

```kotlin
// JsonClassCodegenProcessor.kt
override fun init(processingEnv: ProcessingEnvironment) {
    super.init(processingEnv)
    proguardEnable = processingEnv.options[OPTION_PROGUARD_ENABLED] ?: true
}

#1
override fun process() {  
  if (proguardEnable) preparedAdapter.proguardConfig?.writeTo(filer, type)
}


// #2
override fun process() {
   val generator = adapterGenerator(type, cachedClassInspector, proguardEnable) // generator.proguardConfig can be null
}
```
^ isn't it?

**Comment by ZacSweers** [comment]
I think that's reasonable. Do you want to send a PR?

**Comment by SeongUgJung** [comment]
okay, I will do create PR  soon :)

**Comment by seongug-jung** [comment]
We can close this once merging #1353 😄  Thanks for your all actions, @ZacSweers
