### ISSUE TITLE
Expected an int but was BOOLEAN with proguard enabled

### ISSUE THREAD

**Issue by h-sanimeh-af** [square/moshi#1359]
I have this json

```json
{
  ...
  "is_new_payment_flow": true
  ...
}
```

And I have this kotlin class
```kotlin
@JsonClass(generateAdapter = true)
data class Example(
    ...
    @Json(name = "is_new_payment_flow")
    val isNewPaymentFlow: Boolean
    ...
)
```
Now if I try to map the json with the class it will give me `Expected an int but was BOOLEAN` error, I have checked the bytecode and it's boolean even after proguard obfuscation.

This is how the bytecode will look like `isNewPaymentFlow : Z` as far as I know the `Z` in bytecode means `boolean`. the bytecode taken from the apk using `Build -> Analyse APK` option in Android Studio

At the end when I change the `Boolean` to `Boolean?` in the kotlin class it will work normal

**Note: this issue only happens in release build type with proguard enabled only**

**Comment by ZacSweers** [comment]
Usage questions belong on stackoverflow, this is not a bug.
