### ISSUE TITLE
Ability To Skip Invalid Objects When Parsing a List

### ISSUE THREAD

**Issue by JohnBueno** [square/moshi#1366]
We are currently in the process of migrating an app from Jackson to Moshi and for the most part, have been pretty pleased with Moshi.  One major sticking point we have run into is that we require the ability to throw out invalid objects in a List without throwing out the entire response.  

For example, if we have a model:
```
@JsonClass(generateAdapter = true)
data class CatalogResponse(val products: List<Product>) {
    
    @JsonClass(generateAdapter = true)
    data class Product(val productName: String, 
                       val productId: String, 
                       val productPrice: Double, 
                       val isMarkdown: Boolean)
}
```

And we try to parse the following response:

```
{
  "catalogResponse": [
    {
      "productName": "Shirt",
      "productId": "12345",
      "productPrice": 15.99,
      "isMarkdown": false
    },
    {
      "productName": "Dress",
      "productId": "12346",
      "productPrice": 10.99,
      "isMarkdown": false
    },
    {
      "productName": "Pants",
      "productId": "12347",
      "isMarkdown": false
    },
    {
      "productName": "Dress",
      "productId": "12348",
      "productPrice": 10.99,
      "isMarkdown": false
    }
  ]
}
```

The `productPrice` attribute is required on the `CatalogResponse.Product` model which means that the Pants in this example are invalid.  With the default Moshi implementation, the entire `CatalogResponse` will be invalid and Moshi with throw an error.  The feature we need is the ability to "skip" the pants entry in the list and parse the rest of the response without throwing an exception. I have seen a few examples using custom JSONAdapter.Factory but I have yet to find one that works for us.  I think this would be a super valuable feature for a lot of users.

Thanks!

**Comment by ZacSweers** [comment]
Please post usage questions on stackoverflow with the Moshi tag
