### ISSUE TITLE
JsonDataException with raw json data

### ISSUE THREAD

**Issue by onurkoncaoglu** [square/moshi#1369]
Hi there,

With using Retrofit, If I catch an HttpException, I have a chance to take the raw response from it and use it then to show error for example. (httpException.response()) However JsonDataException does not include to origin json source (or response) so I cannot take an action to take usable areas of it. In fact, In an API call finished successfully the response comes and exist but I cannot reach the raw format.

Does it make sense to you too that adding the original raw format of json to the JsonDataException like HttpException? I think, It may be useful

**Comment by ZacSweers** [comment]
No, you should try to access this from retrofit directly (delegating converter factory, for example) rather than from a Moshi exception.

**Comment by bqv** [comment]
Would be nice, tbqh. Not the whole document, just context of 3 lines or so?
