### ISSUE TITLE
Anyone can helpme with post-initalization?

### ISSUE THREAD

**Issue by burakkilic** [square/moshi#137]
Hello;

We are using Moshi to parse JSON strings to our objects. 

In some objects, we have imageUrl fields. These fields should be stored in a list for prefetching images before the app has loaded.

    `public class EntityAdapter{
    @FromJson
    Entity entityFromJson(EntityJson entity) {
        Media.getInstance().imagesToLoad.add(entity.getLargeImageUrl());
        Media.getInstance().imagesToLoad.add(entity.getMediumImageUrl());
        Media.getInstance().imagesToLoad.add(entity.getSmallImageUrl());
        Media.getInstance().imagesToLoad.add(entity.getBackgroundImageUrl());
        Media.getInstance().videosToLoad.add(entity.getVideoUrl());

        return entity;
    }

    @ToJson Entity eventToJson(Entity entity) {
        return null;
    }

    private class EntityJson {
        String imageUrl;
    }
     }`

We think about something like that. Is there a better way for that?

**Comment by swankjesse** [comment]
Not sure what action to take here.
