### ISSUE TITLE
error @JsonClass can't be applied to com.app.FooClass supertype androidx.databinding.BaseObservable is not a Kotlin type

### ISSUE THREAD

**Issue by onuryurtturk** [square/moshi#1370]
error @JsonClass can't be applied to com.app.FooClass supertype androidx.databinding.BaseObservable is not a Kotlin type

Hi! How can we use @JsonClass(generateAdapter = true) annotation with BaseObservable supertype? I get the above error when I use it together.

**Comment by ZacSweers** [comment]
As the message says, you cannot extend non-kotlin types in JsonClass-annotated types. Moshi can't reason about the nullability, properties, etc
