### ISSUE TITLE
Allow Number as a valid return type of a @ToJson function

### ISSUE THREAD

**Issue by BraisGabin** [square/moshi#1391]
Maybe this is not an issue but working as expected but it seems a bit extrange from outside. I need a `BigDecimalAdapter`. I was using this one from Eric Cochran https://stackoverflow.com/a/54993136/842697

```kotlin
object BigDecimalAdapter {
  @FromJson fun fromJson(string: String) = BigDecimal(string)

  @ToJson fun toJson(value: BigDecimal) = value.toString()
}
```

The problem is that I don't want to serialize a BigDecimal as `"10.00"`. I want to serialize it like a number: `10.00`. I found that `JsonWriter` allows `Number` as a valid value so I change the code to this:

```kotlin
object BigDecimalAdapter {
  @FromJson fun fromJson(string: String) = BigDecimal(string)

  @ToJson fun toJson(value: BigDecimal): Number = value
}
```

But I got this exception message:

```
Platform class java.lang.Number requires explicit JsonAdapter to be registered
```

Then I changed my adapter to this: 

```kotlin
object BigDecimalAdapter {
    @FromJson
    fun fromJson(string: String) = BigDecimal(string)

    @ToJson
    fun toJson(writer: JsonWriter, value: BigDecimal) {
        writer.value(value)
    }
}
```

And it works like a charm but I don't understand why Moshi doesn't allow me to use: `@ToJson fun toJson(value: BigDecimal): Number = value` directly.

**Comment by ZacSweers** [comment]
Number is a bit of a special case as only `JsonWriter` has native support for it like you mention. Moshi doesn't have a built-in standard adapter for it. Like the error message says, you'll need to write your own.
