### ISSUE TITLE
"Unable to create converter ..." after upgrade to JDK 11 & AGP 7.0.0

### ISSUE THREAD

**Issue by BlackHornet** [square/moshi#1395]
Hi,

after we upgraded our app to JDK 11 & AGP 7.0.0 we encountered a problem with our data classes not being able to be used like before.

In additional to that, we had to update to `com.android.tools:desugar_jdk_libs:1.1.5` to prevent startup issues (maybe this is worth to mention as well).

After these changes we noticed an issue with our entity classes.
``` 
java.lang.IllegalArgumentException: Unable to create converter for class RemoteArticles
...
Caused by: java.lang.IllegalArgumentException: No property for required constructor parameter #0 articles of fun <init>(kotlin.collections.List<RemoteArticle>?): RemoteArticles
```

with the following data class being used
```
data class Image(
    @Json(name = "alt")
    val alt: String,
    @Json(name = "url")
    val url: String,
    @Json(name = "height")
    val height: Int,
    @Json(name = "width")
    val width: Int,
)

data class RemoteArticle(
    @Json(name = "icon")
    val icon: List<String>?,
    @Json(name = "image")
    val image: Image?,
    @Json(name = "link")
    val link: Link?,
    @Json(name = "text")
    val text: String?,
    @Json(name = "type")
    val type: String?,
)

data class RemoteArticles(
    @Json(name = "articles")
    val articles: List<RemoteArticle>?
)
```

This worked before, when we used JDK 1.8 and AGP 4.2.1 and desugaring library 1.0.9, so I assume this to be an issue either with an incompatibility of the used dependencies ... or something I missed in my setup?

Would be nice if you can point me to the right direction.

Regards

**Comment by BlackHornet** [comment]
Note: Going back to AGP 4.2.1 and JDK 1.8 (keeping desugaring library 1.1.5) and Moshi could successfully parse the RemoteArticles json received from the backend again.

**Comment by ZacSweers** [comment]
Unless you can provide a minimally reproducing sample project, not much we can do

**Comment by BlackHornet** [comment]
I will provide an example today, but after some testing it looks like the KotlinJsonAdapterFactory together with reflection is the source of the issue when AGP 7.0+ is used.

Using Moshi codeGen and not using the KotlinJsonAdapterFactory was successful.

Maybe R8 now does more than before.

**Comment by BlackHornet** [comment]
@ZacSweers 
here is the sample application that demonstrate the issue.
App crashes when release build is being started.
[Issue-Sample.zip](https://github.com/square/moshi/files/7202017/Issue-Sample.zip)

**Comment by ZacSweers** [comment]
I don't see any proguard rules there to keep your models for reflective serialization. Like any other reflection, you need to add rules to keep things you intend to introspect at runtime, otherwise a shrinker like R8 can remove them

**Comment by jemshit** [comment]
Normally, with both Gson and Moshi, this rule would work:
```
-keepclassmembers class package.of.models.** {
    public synthetic <methods>;
    <fields>;
}
```

Now, i had to do one of this:
```
-keepclassmembers class package.of.models.** {
    public  <methods>;
    <fields>;
}

// or

-keep public class package.of.models.** {*;} 
```

**Comment by aaaamirabbas** [comment]
I also have this problem for **codegen** Is there a solution?
