### ISSUE TITLE
java.lang.IllegalStateException: No type argument found for 1!  Compilation Issue

### ISSUE THREAD

**Issue by osquitoOfTheNorth** [square/moshi#1399]
I was in the process of upgrading our project to AGP 7.0 and as a result was required to update a few libraries to the latest + greatest including Moshi.  After upgrading to v 1.12.0, I was no longer able to compile my project with a gradle error that included the error mentioned in the title along with a moshi stacktrace. 

I was able to isolate the problem in a sample project which I have uploaded here. 

The issue looks related to my use of generics and I was wondering if my use case is even supported and/or are you already aware of this issue? (The offending class in the sample project I have provided is `Test2` )

Thanks
[MyApplication2.zip](https://github.com/square/moshi/files/7313758/MyApplication2.zip)

**Comment by ZacSweers** [comment]
This is fixed on `master` and will be available in the next release. Can you verify by testing with the latest snapshot?
