### ISSUE TITLE
De/Serialize scope

### ISSUE THREAD

**Issue by adauvalter** [square/moshi#141]
Suggestion: Make a scope custom annotation to support de/serialize fields `@Json`such like a `@Json(name = "lucky number", scope=Scope.read_only)` to support only serialization/deserialization by this field?

**Comment by vanniktech** [comment]
@JakeWharton & @swankjesse are you guys open for a PR here?

**Comment by swankjesse** [comment]
I’m not sure. Seems hostile to testing at a minimum.

**Comment by david-perez** [comment]
This would be really nice.

**Comment by swankjesse** [comment]
How do y’all test this?

**Comment by vanniktech** [comment]
Serialize and deserialize tests for each model object.

**Comment by swankjesse** [comment]
I still think this is a modeling problem. Presumably your class looks like this, where the API client doesn’t know the price but the server does:

```
class PizzaOrder {
  Size size;
  List<Topping> toppings;
  @Json(scope=read_only) Money price;
}
```

I think what you actually want is two classes, `UnpricedPizzaOrder` and `PricedPizzaOrder`. Or something.

**Comment by vanniktech** [comment]
Lazy adapters are now [able](https://github.com/serj-lotutovici/moshi-lazy-adapters/pull/18) to do this by using a custom Adapter.

**Comment by swankjesse** [comment]
No action for us to take on this.
