### ISSUE TITLE
@ToJson and @FromJson should permit any number of JsonAdapters

### ISSUE THREAD

**Issue by szurbrigg** [square/moshi#142]
That way we can make building custom delegating type adapters easier.

Also, cut & paste error on the `@ToJson` bad signature exception message.

**Comment by maxandron** [comment]
Do you mean having different adapters for different json types?
e.g: use one adapter if encountering a `BEGIN_OBJECT` and another if encountering a `STRING` - both producing the same type

If this is what you mean, is there a way to do this currently?

**Comment by swankjesse** [comment]
The goal here is to make composition easier:

```java
class CardAdapter {
  @ToJson String toJson(Card card, JsonAdapter<Suit> suitAdapter) {
    ...
  }

  @FromJson Card fromJson(String card, JsonAdapter<Suit> suitAdapter) {
    ..
  }
}
```
