### ISSUE TITLE
Changing the suffix of generated adapters

### ISSUE THREAD

**Issue by andre-vm** [square/moshi#1421]
I have an issue due to generated JSON adapters being always named `${className}JsonAdapter`.

I need to generate unit test coverage reports using JaCoCo. When setting it up, I must provide a set of patterns of class paths to exclude from those reports. Example in an Android project with Gradle:

```groovy
def excludes = [
    '**/R.class',
    '**/R$*.class',
    '**/BuildConfig.*',
    '**/Manifest*.*',
    '**/*Test*.*',
    'android/**/*.*',
    '**/databinding/*Binding.class',
    '**/*Dao_Impl.class',
    '**/Nav*Directions.class',
]
```

I'd like to exclude the JSON adapters generated by Moshi codegen, but I already have some custom adapters of my own, so I can't just add a pattern like `**/*JsonAdapter.class`. The most convenient solution to this problem would be to change the suffix of generated adapters to something like `_JsonAdapter`, so I can distinguish generated adapters from my custom ones.

Is it viable to make it configurable?

**Comment by ZacSweers** [comment]
We're not going to change this for a code coverage tool. I would recommend instead moving generated code to a custom known package or into a subproject that is excluded from code coverage.

**Comment by andre-vm** [comment]
I understand. Thank you for your prompt reply!

**Comment by swankjesse** [comment]
There's also an option to tag these with `@Generated` which your coverage tool should be able to process.

**Comment by andre-vm** [comment]
@swankjesse That's interesting! I'll take a closer look. Thank you!
