### ISSUE TITLE
Kotlin 1.6 with target version 1.5 : Annotation class cannot be instantiated

### ISSUE THREAD

**Issue by Tolriq** [square/moshi#1423]
Doing a quick test with Kotlin 1.6 and KSP 1.6.0-1.0.1 I get a bunch of those failures on all my Custom annotations on generated adapters.

```
    @Retention(AnnotationRetention.RUNTIME)
    @JsonQualifier
    annotation class IgnoreInvalidArray
```

This is caused by a config on that project with a:
```
allprojects {
    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "1.8"
            apiVersion = "1.5"
            languageVersion = "1.5"
            freeCompilerArgs = listOf("-Xno-param-assertions", "-Xno-call-assertions", "-Xno-receiver-assertions", "-Xjvm-default=all")
        }
    }
}
```
So targeting 1.5.

When reading the PR that introduce annotation instantiation on 1.6 it says:
`This also implements it gated on the target type's language version, which allows this to seamlessly work in a backward-compatible way.` So I would have assumed it should have still worked the old way in this case.
Hence the bug report.

Edit: For completion, changing api and target to 1.6 does work perfectly.

**Comment by rhonyabdullah** [comment]
I think my build failure is similar with that bug above, here's how i reproduce:
1. upgrade IDE kotlin plugin to 1.6.0 
2. upgrade classpath dependency `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0`
3. upgrade **all** module and sub-module dependency `implementation "org.jetbrains.kotlin:kotlin-stdlib:1.6.0"`

Then add codegen `kapt "com.squareup.moshi:moshi-kotlin-codegen:1.12.0"`

Rebuild the project then error, if i remove codegen kapt build success.

**Comment by Tolriq** [comment]
@rhonyabdullah Version 1.12 does not work with Kotlin 1.6 you need to use a snapshot version for now.

**Comment by ZacSweers** [comment]
We are going to remove that control and just require kotlin 1.6 in the next release
