### ISSUE TITLE
Expand available adapters to common platform types

### ISSUE THREAD

**Issue by rollie42** [square/moshi#1428]
I tried to use moshi to serialize a type from Google's Places API ([PlacesSearchResponse](https://googlemaps.github.io/google-maps-services-java/v0.1.10/javadoc/com/google/maps/model/PlacesSearchResponse.html)) using the kotlin-reflect based approach. It almost worked, but required custom adapters for java.net.URL and java.time.LocalTime. 

Can adapters be included for the most common such types? I know there is a specific adapters artifact in maven, but it only has a few adapters. IMO, these should be automatically apply-able, maybe via something like

```
val moshi = Moshi
  .Builder()
  .add(JVMPlatformAdapters())
  .build()
```

which would add default handlers for all the most common JVM types. If a user wanted this functionality but wanted to customize one type, I think they could do so by just inserting their custom adapter earlier in the chain. But as it is, each time you want to serialize these types, it seems you need to roll your own version of these adapters.

If I'm wrong, I'm happy to be corrected and learn an easier way to get this working!

**Comment by ZacSweers** [comment]
Moshi tries to be lightweight and not offer a kitchen sink of supported adapters. Instead it offers a flexible API for you to bring your own. There's nothing preventing the community from offering adapters for extra types like this 👍

**Comment by rollie42** [comment]
Isn't that what [this section](https://github.com/square/moshi/tree/master/adapters/src/main/java/com/squareup/moshi/adapters) caters to? If moshi should have nothing specific, should this not be there? If it does choose to have support for types, would it not make sense to expand this?

**Comment by rollie42** [comment]
It's also true that you can have both 'lightweight' and 'rich support' - dependency 'com.squareup.moshi:moshi-adapters' could hold default adapters, which 'com.squareup.moshi:moshi' remains lean, allowing you to have your cake and eat it too.

**Comment by JakeWharton** [comment]
I'm strongly opposed to including anything for LocalTime. A user should have to pick the serialization format for this type since there are multiple.

URL is very simple to write yourself using `@ToJson` and `@FromJson` functions. I'm not sure we gain much by shipping it.

**Comment by rollie42** [comment]
@JakeWharton my uninformed assumption is that most often, people just want to be able to serialize and deserialize either using the same library (e.g., it doesn't matter what the intermediate representation is), or in any format that is understandable (if I saw `{timeOfDay: '14.25.32'}`, I would know what it meant, even if it isn't how I might choose to write it). Even with defaults, there is still always the option to offer a different adapter if it is important that the serialized format be '14:25:32', for example.

I think that at least is a slightly better argument to not include, I think URL is pretty much universally going to be represented the same way by everyone. Granted, it's easy to write, but it feels like you want to provide as much support as is reasonable; for example, if I am serializing a Float 100.0, how should it look? `value: 100`? `value: 100.0`? `value: 1.0E+2`?  There are many ways to write the same number in valid json; does that mean you _shouldn't_ provide default support for Float/Double, just because there exists a possibility someone will prefer one serialized format over another?

It sounds like my opinion is the minority though, so.../shrug. Thanks all the same :)

**Comment by JakeWharton** [comment]
The available shapes of how a float can be defined in JSON are detailed by the spec, and we will choose whichever format retains the precision required for the person who has to parse the output to exactly reproduce the value.

The JSON spec does not define a representation for a date or time which is why we do not support it out of the box.

In general, the behavior you describe is what Gson did. Moshi was created by Gson maintainers to correct behaviors like this which are user-friendly in the short term but disastrous in the long term.

We strongly prefer making the first-use of the library harder than it needs to be by pushing decisions to the user so that we can ensure that the behavior Moshi exhibits is what they want. And that any long-term implications of how serialization occurs are because of their choices, not implicit library defaults.
