### ISSUE TITLE
android.util types as built in type adapters

### ISSUE THREAD

**Issue by ersin-ertan** [square/moshi#145]
I know that moshi serves both as an android and java json library, and that "Moshi has fewer built-in type adapters...to prevent you from accidentally locking yourself to a specific JDK or Android release," however there is no love for 'android's core data types' from [android.util](http://developer.android.com/reference/android/util/package-summary.html).

**Comment by JakeWharton** [comment]
At best this would be a sibling artifact and you have to deal with both the
platform ones and support library ones. I'm still not even convinced it
should be maintained as part of this library vs. separately.
