### ISSUE TITLE
1.13.0: Annotation class cannot be instantiated

### ISSUE THREAD

**Issue by Uorlak** [square/moshi#1453]
In work project we use `@JsonQualifier`, after updating moshi to version 1.13.0 I received this error when run building:

```
> Task :backend-model-jvm:compileKotlin FAILED
e: /Users/test/Documents/Projects/work-app-android/backend-model-jvm/build/generated/source/kapt/main/com/work/backend/model/entity/response/RawTemplateActionJsonAdapter.kt: (46, 34): Annotation class cannot be instantiated

> Task :app:processGmsDebugResources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend-model-jvm:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

I investigated this, and think that error happens because Moshi switched to Kotlin 1.6, but my project uses Kotlin 1.5.32.

If there is a way to fix this error, other than to switch to Kotlin 1.6 (at the moment this is not possible due to the incompatibility of other libraries with it)?

**Comment by ZacSweers** [comment]
Moshi 1.13.0 requires kotlin 1.6.0 or later
