### ISSUE TITLE
Add a note that Moshi 1.13.0 does not work with older versions of AGP due to supporting Multi-Release JAR Files

### ISSUE THREAD

**Issue by nokite** [square/moshi#1454]
I want to use Kotlin 1.6.0 with my current dependencies, which include AGP 4.2.2 and Gradle 6.9.1, and Jetifier enabled.

Using Kotlin 1.6.0 means I have to use Moshi 1.13.0, which means I have to use the latest version of AGP (edit: supposedly it has been fixed in a 7.* version).

While this is mostly a problem of AGP 4.*, as it does not support "Multi-Release JAR Files", it would be very helpful if the release notes of Moshi 1.13.0 (where Multi-Release JAR Files support is added) mention this limitation. This way people won't have to debug the problem to reach the same conclusion.

**Comment by ZacSweers** [comment]
Where are you getting 7.2 from? There was an issue with the Firebase performance plugin that AGP effectively fixes in 7.0.4, but otherwise not sure what you're referring to.

**Comment by nokite** [comment]
@ZacSweers I saw 7.2 in a comment, I just assumed it exists. (apparently not) 
https://issuetracker.google.com/u/1/issues/206655905#comment2

I haven't verified in what version it works, I've just seen in what versions it doesn't.

**Comment by nokite** [comment]
I see now that I may have got this wrong... 

Do you know if Moshi 1.13.0 works with Jetifier, and on what versions of AGP and Gradle (+Kotlin 1.6.0)? I'm interested in AGP 4.* and Gradle 6.9.*, of course.

Thanks 🙂

**Comment by ZacSweers** [comment]
That's a very specific edge case (using firebase's performance gradle plugin, which erroneously parses classes in meta-inf) and not something Moshi has control over. You should be able to work around it via filtering out classes in meta-inf files manually before the plugin runs, the plugin itself should also fix this behavior.

Your original issue does not mention this plugin and only mentions "it does not support "Multi-Release JAR Files"... this way people won't have to debug the problem". What issue are you referring to?

**Comment by nokite** [comment]
My goal is to use Kotlin 1.6.0 without upgrading to Gradle 7 + AGP 7, and without disabling Jetifier.

Moshi 1.13.0 supports Kotlin 1.6.0 (thanks btw!), but when I update Moshi, I get a build error (see below).

My understanding is that Moshi does not work well with my version of Jetifier and AGP 4.2.2 (Gradle 6.9.1).

`Failed to transform moshi-1.13.0.jar using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60`

I opened this ticket: https://issuetracker.google.com/u/1/issues/209825727

**Comment by ZacSweers** [comment]
That seems like a bug in jetifier (for similar reasons to the firebase one). Sorry, but I don't think it makes sense for us to add extensive notes about bugs in other tools that may have compatibility issues, especially when it's down to using multiple outdated versions of build tools.

**Comment by nokite** [comment]
I saw it as a compatibility note, not a note about bugs in other tools. 

OK, that's fair. Thanks!

**Comment by Jean-Daniel** [comment]
> That's a very specific edge case (using firebase's performance gradle plugin, which erroneously parses classes in meta-inf) and not something Moshi has control over. You should be able to work around it via filtering out classes in meta-inf files manually before the plugin runs, the plugin itself should also fix this behavior.

Have you any pointer about how to effectively do that (code snippet). I'm using AGP 7.0.4 and the last version of performance plugin, and can't build release version because of this specific issue.

**Comment by Pero122** [comment]
Checkout this Stackoverflow question. It might help. I am the author of the question and for the sake of not duplicating text I just linked to it.
