### ISSUE TITLE
lintAnalyze java.lang.IllegalArgumentException: Unsupported class file major version 60

### ISSUE THREAD

**Issue by G00fY2** [square/moshi#1457]
Hi everyone, we just switched to Moshi 1.13 and we see the following Gradle warnings when `lintAnalyze` (AndroidLintAnalysisTask) gets executed in the build.

Looks like some classes are only intended for Java 16 and can therefore not be analyzed by lint? Shall we just ignore these warnings or is there any way to suppress them?

This is how our log looks like:
```
> Task :app:lintAnalyzeDebug
Error processing /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar:META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter.class: broken class file? (java.lang.IllegalArgumentException: Unsupported class file major version 60)
Error processing /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar:META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter$1.class: broken class file? (java.lang.IllegalArgumentException: Unsupported class file major version 60)
Error processing /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar:META-INF/versions/16/com/squareup/moshi/RecordJsonAdapter$ComponentBinding.class: broken class file? (java.lang.IllegalArgumentException: Unsupported class file major version 60)
```

Our project:

- Moshi 1.13.0 (with kotlin-codegen)
- Kotlin 1.6.10-RC
- Gradle 7.3.1
- AGP 7.0.4
- OpenJDK 11.0.11

**Comment by ZacSweers** [comment]
Also to answer your question - as the release notes cover, we ship an MR-Jar now to support record classes in Java 16+. They should not be loaded on older Java versions.

**Comment by G00fY2** [comment]
For everyone that is interested, I created this issue over here: https://issuetracker.google.com/issues/209957322

**Comment by roman-n1** [comment]
We have the same issue. Any ideas to fix it?

**Comment by ZacSweers** [comment]
@roman-n1 pleade keep discussion to the android issue and avoid duplicating to here. Will be locking this
