### ISSUE TITLE
How to replace $ref values in JSON to their corresponding repeated Java objects

### ISSUE THREAD

**Issue by ahmadalibaloch** [square/moshi#146]
I am using Microsoft.Net with Breeze for APIs and the results I get using Retrofit have nested repeated same objects. For example EmployeeJob has Customer navigation property so the APIs result looks like this

```
 {
   Id:1,
   "Customer_Id": 39,
    "Customer": {
        "$id": "1",
        "CourtesyTitle": "Mr",
        "FirstName": "Ahmad"
    }
}
{
  Id:2
  "Customer_Id": 39,
    "Customer": {
        "$ref": "1" //here same customer Ahmad
    },
}
```
Now the Java List I get of these EmployeeJobs has only one copy of each customer and others are replaced with $refs. How can I map the $ref:"2" to its original value instead of this $ref.

I don't want my server APIs to send the complete objects for network and performance reasons, that's why I want to deserialize these $refs on client side just like Angularjs $resource service does for us.

**Comment by swankjesse** [comment]
You’re going to have to write some custom code. Here’s a type adapter for Gson that does something similar:

https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/graph/GraphAdapterBuilder.java
https://github.com/google/gson/blob/master/extras/src/test/java/com/google/gson/graph/GraphAdapterBuilderTest.java

Gson and Moshi have similar APIs for type adapters, so it should be straightforward to start here.

**Comment by ahmadalibaloch** [comment]
It should not be the part of Moshi or these libraries?

**Comment by swankjesse** [comment]
Agreed.

**Comment by ahmadalibaloch** [comment]
Agreed on what? This should be or not part of deserializing library?

**Comment by swankjesse** [comment]
Yes, agreed it should not be a part of Moshi or these libraries.
