### ISSUE TITLE
@Nullable annotation does not work with records

### ISSUE THREAD

**Issue by jylin** [square/moshi#1465]
Thanks for closing #1278!

It seems that with records, the "@Nullable" annotation does not work. For example, with

`record Data(@Nullable String field)`

The field ends up still being required. There may need to be some more handling for records needed around here: https://github.com/square/moshi/blob/dfc075515dc255f072b5f78ebc524edd47a72576/kotlin/src/main/java/com/squareup/moshi/kotlin/KotlinJsonAdapter.kt#L87

**Comment by jylin** [comment]
Nevermind, please delete. This works as expected.

**Comment by ZacSweers** [comment]
Moshi doesn't respect nullability annotations in Java currently, what's expected in light of that?
