### ISSUE TITLE
Typo in README example?

### ISSUE THREAD

**Issue by vstollen** [square/moshi#1478]
While reading the README I came across this code block:
https://github.com/square/moshi/blob/82cf56ab7686779f6c87452a6f5c01ce652c8b4b/README.md?plain=1#L385-L390

I believe the expression `.builder` in line 388 to be a typo. Should it be `.build()`  instead?:
https://github.com/square/moshi/blob/82cf56ab7686779f6c87452a6f5c01ce652c8b4b/README.md?plain=1#L388

Since I am new to moshi, I am not entirely sure if this is intended or not. Otherwise, I would have created a PR myself.

**Comment by ZacSweers** [comment]
yes it should be `build()`, want to send a PR?
