### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by yamin8000** [square/moshi#1498]
I'm using Moshi `1.13.0` with Kotlin `1.6.10` and KSP `1.6.10-1.0.2` with Gradle `7.3` and android Gradle plugin `7.0.4`.
In the build process somehow `mergeExtDexDebug` will fail with these detail:

```
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=25, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for AsmClassesTransform: C:\Users\YaMiN\.gradle\caches\transforms-3\c2424b7ae4eee6968acc7e15586359e3\transformed\jetified-moshi-1.13.0.jar.
         > Unsupported class file major version 60
```

I know [major version 60 refers to Java 16](https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers) but nowhere in Moshi docs, I see any indication that Moshi requires Java 16 or Java 13 which is my next point. During the build process this warning caught my attention:
```
Jetifier skipped processing 'C:\Users\YaMiN\.gradle\caches\modules-2\files-2.1\com.squareup.moshi\moshi\1.13.0\da685586facab9eb5c4fb630ce248be14e7da21b\moshi-1.13.0.jar' as it contains Java 13+ bytecode (root cause: "Unsupported class file major version 60").
If you still want Jetifier to process that artifact, try updating ASM in your buildscript classpath as described at https://issuetracker.google.com/issues/159151549#comment7.
To suppress this warning, add android.jetifier.ignorelist=moshi-1.13.0.jar to gradle.properties (or set android.enableJetifier=false if you don't need Jetifier).
```
So I tried adding `android.jetifier.ignorelist=moshi-1.13.0.jar` to my `gradle.properties` but nothing changed.
Also, #1457 and #1454 look related but I didn't find any fix or workaround in those issues which surprisingly are closed despite not fixing the problem.

**Comment by ZacSweers** [comment]
Please use the search: https://github.com/square/moshi/issues/1454#issuecomment-989981705

**Comment by Pero122** [comment]
Checkout [this Stackoverflow question](https://stackoverflow.com/questions/70878643/failed-to-transform-moshi-1-13-0-jar-failed-for-task-biometric-storagekaptgene/70878644#70878644). It might help. I am the author of the question and for the sake of not duplicating text I just linked to it.

**Comment by jenniupdates** [comment]
THANK YOU!! Solution 3 worked for me :)
