### ISSUE TITLE
Website link on Square Open Source page to Moshi broken

### ISSUE THREAD

**Issue by anthonymonori** [square/moshi#151]
I can see the Moshi repo doesn't have a proper page, like the other OSS here at Square. Instead the Javadoc is put up in the gh-pages branches. That's all fine, but I suggest **fixing the Website link** on the
http://square.github.io/
where moshi is listed. It points to nowhere. 

Or maybe this Issue could be used to implement a simple landing page for it as well? 👍

**Comment by JakeWharton** [comment]
Fixed
