### ISSUE TITLE
open class not serialized, only parent values serialized

### ISSUE THREAD

**Issue by kenargo** [square/moshi#1518]
MOSHI will not serialize this class structure.  It serializes the values in the parent data class but nothing from the base.  I found one closed issue, but it appears unrelated as it relates an issue with deserializing only.

    implementation 'com.squareup.moshi:moshi:1.13.0'
    kapt 'com.squareup.moshi:moshi-kotlin-codegen:1.13.0'

@JsonClass(generateAdapter = true)
// https://developer.android.com/kotlin/parcelize
@Parcelize
data class CameraSettingsZoom(

    @Transient
    private val readFromJsonParam: Boolean = false,

    val mode: Int? = 10,

) : Parcelable, CameraSettingsBase(readFromJsonParam)

@JsonClass(generateAdapter = true)
// https://developer.android.com/kotlin/parcelize
@Parcelize
open class CameraSettingsBase(

    // Not serialized, if I want to save a default then I need to instance this class
    @Transient
    val readFromJson: Boolean? = true,

    // These are the settings acceptable for different lenses.  Global values remain in the root

    val cameraZoom: Double? = 180.0,
    val contrast: Int? = 0,

) : Parcelable

**Comment by ZacSweers** [comment]
The base class constructor is not accessible from the subclass. Only mutable properties in superclasses can be set.

Also in the future please tidy up the formatting in these, it's hard to read at a glance when the markdown formatting is all over the place
