### ISSUE TITLE
`ClassJsonAdapter` throws `AssertionError` without wrapping `IllegalAccessException`

### ISSUE THREAD

**Issue by dvmarcilio** [square/moshi#1523]
I'm getting an `AssertionError` _without any message_ from `ClassJsonAdapter.fromJson()` in Java.
I would like to investigate the root cause of the issue, but unfortunately, the exception message doesn't provide any hints.

`ClassJsonAdapter` (and others classes) throws an `AssertionError` when an `IllegalAccessException` is caught.

https://github.com/square/moshi/blob/fd128875c308a90288e705162e03a835220a74d9/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.kt#L64-L66
https://github.com/square/moshi/blob/fd128875c308a90288e705162e03a835220a74d9/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.kt#L81-L83

Should the `IllegalAccessException` be wrapped in the `AssertionError` like, for instance, in `RecordJsonAdapter`?
https://github.com/square/moshi/blob/fd128875c308a90288e705162e03a835220a74d9/moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.kt#L146-L148

**Comment by ZacSweers** [comment]
Please link a minimally reproducible sample project

**Comment by dvmarcilio** [comment]
I have it working on my original project now.
Thanks.


A short description to maybe help others in the future.
The `AssertionError` was only happening when executing my application through an uber jar generated by [maven-assembly-plugin](https://maven.apache.org/plugins/maven-assembly-plugin/) (`jar-with-dependencies`).
The fix was to generate the uber jar with [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) instead.

**Comment by Puccet** [comment]
I have the issue but already generating the uber jar with shade, do you have any specific option to use?
