### ISSUE TITLE
After updating ksp to 1.6.20-1.0.5, Moshi generates error code for `typealias` of class with type parameters

### ISSUE THREAD

**Issue by efemoney** [square/moshi#1530]
This may as well be a bug in ksp but after updating kotlin & ksp to 1.6.20-1.0.5, given:

```kotlin
typealias EventMetadata = Map<String, String>

@JsonClass(generateAdapter = true) 
data class ClassUnderTest(
  val metadata: EventMetadata,
)
```

in the generated code, the `Map` loses its type arguments and is therefore a compile error.

**Comment by yigit** [comment]
This might be related to: https://github.com/google/ksp/issues/881

**Comment by ting-yuan** [comment]
The above change was introduced in KSP 1.0.5, where type arguments are now returned for the reference, instead of the complete, underlying type. In this case, it is a reference to an alias and therefore the arguments defined in declaration of the alias are not included.

KotlinPoet [relies on the original behavior](https://github.com/square/kotlinpoet/blob/master/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/ksTypes.kt#L78). [This test](https://github.com/square/kotlinpoet/blob/master/interop/ksp/test-processor/src/test/kotlin/com/squareup/kotlinpoet/ksp/test/processor/TestProcessorTest.kt#L260) caught the issue when I tried to bump KSP to 1.0.5.

**Comment by Egorand** [comment]
Hey @ting-yuan, I'm trying to upgrade KotlinPoet to 1.6.20-1.0.5 and bumped into this issue. Any suggestions on how to migrate the logic? Here's what I've got at this point:

For the following declaration:

```kotlin
genericMapAlias: GenericMapTypeAlias<String, Int>,
```

where

```kotlin
typealias GenericMapTypeAlias<V, K> = Map<K, V>
```

I can access:

- `KSTypeReference.element.typeArguments` = `[String, Int]`
- `KSTypeAlias.typeParameters` = `[V, K]`
- `KSTypeAlias.type.declaration.typeParameters` = `[K, V]`

I can match parameter names manually and put the type arguments in the right order, but wondering if there's a simpler way to do this.

**Comment by ting-yuan** [comment]
I think what you mentioned (match parameter names and put type arguments in the right order, which is how KotlinPoet worked with KSP 1.0.4, right?) is probably the simplest/best way. 

Thanks for fixing this. My apology for not noticing and announcing the behavior change in KSP.

**Comment by Egorand** [comment]
> which is how KotlinPoet worked with KSP 1.0.4, right?

KotlinPoet was behind by a couple major versions, so we're migrating only now.

Here's the commit, would appreciate a review! https://github.com/square/kotlinpoet/pull/1240/commits/abbcc178857ef4956d0c6cff883a9790cd6a9c58

**Comment by ting-yuan** [comment]
@Egorand I left a comment for a corner case. Otherwise LGTM.

**Comment by ZacSweers** [comment]
@Egorand has fixed this upstream in KP, will keep this open until we update here

**Comment by adauvalter** [comment]
I figure the same situation after update kotlin to 1.70 and ksp to 1.0.6 with List which returns `One type argument expected for interface List<out E>`. Any plans to roll out a new release?

**Comment by yogurtearl** [comment]
I think this is fixed by #1543

**Comment by ZacSweers** [comment]
Sorry for the delay, we are in the middle of a significant 2.0 migration so it's not easy to squeak out a simple next release at the moment

**Comment by mannodermaus** [comment]
Shading of the transitive dependency might make this tough, but is there a way to update Kotlinpoet while sticking with Moshi 1.13 and get around this problem? A first trivial attempt didn't work:

```kotlin
dependencies {
  implementation("com.squareup.moshi:moshi:1.13.0")
  ksp("com.squareup.moshi:moshi-kotlin-codegen:1.13.0")

  // nope
  ksp("com.squareup:kotlinpoet:1.12.0")
  ksp("com.squareup:kotlinpoet-metadata:1.12.0")
  ksp("com.squareup:kotlinpoet-ksp:1.12.0")
}
```
