### ISSUE TITLE
Can't get an example from README.md to work

### ISSUE THREAD

**Issue by LeafyLappa** [square/moshi#1532]
Hello!

I can't get this example code to work (the very first example in README.md):

```kotlin
val blackjackHand = BlackjackHand(
    Card('6', SPADES),
    listOf(Card('4', CLUBS), Card('A', HEARTS))
  )

val moshi: Moshi = Moshi.Builder().build()
val jsonAdapter: JsonAdapter<BlackjackHand> = moshi.adapter<BlackjackHand>()

val json: String = jsonAdapter.toJson(blackjackHand)
println(json)
```

```kotlin
class BlackjackHand(
  val hidden_card: Card,
  val visible_cards: List<Card>,
  ...
)
```

If I create a scratch file and put the following in there:

```kotlin
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi

class BlackjackHand(val someInt: Int = 0)

val moshi: Moshi = Moshi.Builder().build()
val jsonAdapter: JsonAdapter<BlackjackHand> = moshi.adapter<BlackjackHand>()
```

I get this error:

<img width="800" alt="Screenshot 2022-04-18 at 5 30 20 PM" src="https://user-images.githubusercontent.com/31704619/163823074-b980d4bf-56f3-45c9-9802-023878ed6903.png">

I'm not sure if I'm missing something or it's actually an issue with readme

**Comment by ZacSweers** [comment]
You need to import the reified extension function, not sure why your autocomplete is not suggesting that

```
import com.squareup.moshi.adapter
```

**Comment by ZacSweers** [comment]
Next time please use the discussions feature for questions like this
