### ISSUE TITLE
Whether separate serialization and deserialization controls can be added?

### ISSUE THREAD

**Issue by yizems** [square/moshi#1535]
like this:

```

data class A(
 @Json(serialize = false,deserialize = true)
  val name : String?=null,

)
```

I know this may defeat the purpose, But this logic exists in many older projects, And sometimes we have to use it; 

Not all companies are so standard, hope you can get some advice, thank you;

**Comment by JakeWharton** [comment]
You already proposed this in #1140. See also #1150 and #1123 where similar features were also rejected.

For different forms I would recommend two objects with a function to convert between the two. Or you could write an adapter for your type which does the conversion to the serialization form automatically.
