### ISSUE TITLE
Cannot access class 'org.gradle.accessors.dm.LibrariesForLibs'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by yizems** [square/moshi#1540]
I don't know gradle very well, there should be something wrong with this configuration

![image](https://user-images.githubusercontent.com/16949474/169355621-87c4041c-2355-4f17-b339-a50d917d2963.png)

**Comment by yizems** [comment]
sory.. just user jdk 1.8

**Comment by Gnywin** [comment]
i have this problem too,do you resolve it?

**Comment by yizems** [comment]
just user jdk 1.8 @Gnywin

**Comment by yizems** [comment]
@Gnywin use jdk 1.8, dont use jdk11
