### ISSUE TITLE
Support mapping int to enum

### ISSUE THREAD

**Issue by bytecho** [square/moshi#1541]
Some our apis defined enum with Int. Like:

```
 Gender:
     female: 1
     male: 2
```

But moshi only support mapping String to enum. Then I must write customed adapter for each enum.

Hope moshi will support this case. Thanks!

**Comment by JakeWharton** [comment]
You can write a general-purpose adapter which will work for any enum through the use of a marker annotation like `@ByOrdinal` or something. Please ask on StackOverflow with the 'moshi' tag or our own Discussions here on GitHub for help on how to build one.

**Comment by bytecho** [comment]
@JakeWharton Got it. Thanks!
