### ISSUE TITLE
Moshi KSP fails with type aliases that use generics

### ISSUE THREAD

**Issue by zsperske** [square/moshi#1559]
Moshi Version: 1.13.0
Kotlin version: 1.7.0
KSP Version: 1.7.0-1.0.6

Repro project: https://github.com/zsperske/moshiKspBug

Or alternatively this test will fail:

```
import com.squareup.moshi.JsonClass
import org.junit.Test

class MoshiBugReport {

  @Test fun test() {
    //doesn't need to do anything
  }

}

sealed class Either<out A, out B> {
  data class Left<A>(val value: A) : Either<A, Nothing>()
  data class Right<B>(val value: B) : Either<Nothing, B>()
}

typealias StringOrInt = Either<String, Int>

@JsonClass(generateAdapter = true)
data class MyDataClass(val value: StringOrInt?)
```

Error looks like: 

```
e: MyDataClassJsonAdapter.kt: (24, 50): 2 type arguments expected for class Either<out A, out B>
```

**Comment by mannodermaus** [comment]
This has been raised and discussed previously in #1530. The current consensus is for the maintainers to check the possibility of a patch release of Moshi where the transitive dependency on Kotlinpoet is updated. We're currently awaiting their investigation 🙏

**Comment by ZacSweers** [comment]
Please don't duplicate issues, thanks
