### ISSUE TITLE
Serialization of enum yields escaped string when adapter is added with add(Object adapter)

### ISSUE THREAD

**Issue by julioromano** [square/moshi#1560]
Not sure if this is a bug, but I noticed that when I nest an `EnumJsonAdapter` inside a class annotated with `@FromJson` and `@ToJson` its output is escaped differently than when I use it with just `moshi.add(MyEnum::class.java,EnumJsonAdapter.create(MyEnum::class.java))`.

```
package test

import com.squareup.moshi.FromJson
import com.squareup.moshi.Json
import com.squareup.moshi.Moshi
import com.squareup.moshi.ToJson
import com.squareup.moshi.adapter
import com.squareup.moshi.adapters.EnumJsonAdapter
import org.junit.Test
import kotlin.test.assertEquals

@OptIn(ExperimentalStdlibApi::class)
class MoshiBugReport {

  @Test
  fun expected() {
    val moshi = Moshi.Builder()
      .add(
        MyEnum::class.java,
        EnumJsonAdapter.create(MyEnum::class.java)
      )
      .build()
    val adapter = moshi.adapter<MyEnum>()
    val json = adapter.toJson(MyEnum.FOO)!!

    assertEquals("\"Foo\"", json)
  }

  @Test
  fun notReallyExpected() {
    val moshi = Moshi.Builder()
      .add(MyEnumAdapter())
      .build()
    val adapter = moshi.adapter<MyEnum>()
    val json = adapter.toJson(MyEnum.FOO)!!

    assertEquals("\"\\\"Foo\\\"\"", json)
  }
}

enum class MyEnum {
  @Json(name = "Foo") FOO,
}

class MyEnumAdapter {
  private val adapter = EnumJsonAdapter.create(MyEnum::class.java)

  @FromJson
  fun fromJson(string: String): MyEnum = adapter.fromJson(string)!!

  @ToJson
  fun toJson(value: MyEnum): String = adapter.toJson(value)
}

```

**Comment by JakeWharton** [comment]
This looks to be working as intended if not expected.

You're double encoding the JSON by creating two adapters. The first is the class with the `@ToJson` function which returns a `String`. This value is encoded (wrapped with quotes). But then you delegate to another adapter for the enum which also is going to return a quoted string. Thus, the quoted string is re-quoted.

You either should call `toString()` and `valueOf()` in your adapter class directly on the enum, or you should delete your `MyEnumAdapter` class completely and rely on the `EnumJsonAdapter`.
