### ISSUE TITLE
Json to Java POJO's not working. second class null

### ISSUE THREAD

**Issue by adanecito** [square/moshi#1565]
When reading json file and converting to POJO array in first pojo is null. Data is present in json file. No exception is thrown for json file  or for pojo conversion. Attached is the json and pojo files used. Not sure why exception is not thrown. The class that is null is EventParameters.
Also, do you throw execeptions or provide a way to debug issues? That would save us all time if you do.
[marsquake.zip](https://github.com/square/moshi/files/9332004/marsquake.zip)

**Comment by adanecito** [comment]
How I use Moshi is listed below: Inside the Quakeml is the class that contains an array of Events named EventParameters it is null after using the Moshi adaptor class to get quakeml object.

Quakeml quakeml=null;
 Moshi moshi = new Moshi.Builder().build();
    JsonAdapter<Quakeml> jsonAdapter = moshi.adapter(Quakeml.class);
 try {
                quakeml = jsonAdapter.fromJson(content);
            }catch (java.io.IOException ex){
                System.out.println("debug MarsquakeCloudService.execute() ex:" + ex.getMessage());
            }

**Comment by adanecito** [comment]
I am using 1.13.0 of Moshi. I am using android studio.

**Comment by ZacSweers** [comment]
This is the issue tracker, please use the discussions feature for questions

**Comment by adanecito** [comment]
Hmmmm says bug in the title and when is getting a null when reading a json not a bug? Especially when there are values???

**Comment by ZacSweers** [comment]
Hi @adanecito, you're being a bit rude here. You're having a usage problem and looking for an explanation, that belongs in discussions (there is a whole Q&A section). Your issue is pretty obvious at a glance, happy to explain it in a discussions question if you politely ask there like requested above.
