### ISSUE TITLE
kotlin-reflect crash after adding minifyEnabled = true

### ISSUE THREAD

**Issue by yul13th** [square/moshi#1568]
HI!!

so I am using Moshi to convert Json to an Object with the following generic method -> 

`  inline fun <reified T> fromJsonToObject(json: String): T? {
            val moshi = Moshi.Builder()
                .add(KotlinJsonAdapterFactory())
                .build()
            val jsonAdapter: JsonAdapter<T> = moshi.adapter(T::class.java)
            return jsonAdapter.fromJson(json)
        }`

it worked great until I added `minifyEnabled true` 
My app started crashing with the following error ->

java.lang.IllegalArgumentException: Cannot serialize Kotlin type com.mypackage.model Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:98)
at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
at com.squareup.moshi.Moshi.adapter(Moshi.java:80).....

I tried adding the recommended rules in my proguard file. --> [this](https://github.com/square/moshi/blob/master/moshi/src/main/resources/META-INF/proguard/moshi.pro)

however it did not change the outcome.

I found similar issues i [#1388](https://github.com/square/moshi/issues/1388) and [#1170](https://github.com/square/moshi/issues/1170) but they are all closed 

for reference I am using Moshi '1.13.0'

**Comment by ZacSweers** [comment]
You need to add keep rules for your own models on top of moshi's built-in rules, moshi's built-in rules can't account for your own model classes going through a shrinker. The two issues you linked are not related unless you're also trying to decode value classes, which #1170 indicates is not supported (and still an open issue).
