### ISSUE TITLE
Custom builds via jitpack?

### ISSUE THREAD

**Issue by tmm1** [square/moshi#1571]
I have been using custom builds via jitpack, but it doesn't appear to work any more after upgrading to master.

For example, my `app/build.gradle` includes:

```
    implementation 'com.github.fancybits:moshi:0d4d83d88'
    kapt 'com.github.fancybits.moshi:moshi-kotlin-codegen:0d4d83d88'
```

which triggers a build here:

https://jitpack.io/#fancybits/moshi

but it fails:

https://jitpack.io/com/github/fancybits/moshi/0d4d83d88/build.log

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/examples/build.gradle.kts' line: 24

* What went wrong:
Script compilation errors:

  Line 24: apply plugin: 'maven-publish'
                       ^ Expecting an element

  Line 26: def ver = version
                   ^ Expecting an element
```

---

If jitpack is not supported, perhaps someone can tell me how to build and use a custom version of the code in my app?

I ran `./gradlew build` and see new jars created:

```
$ ls -1 {moshi,moshi-kotlin-codegen}/build/libs/*SNAPSHOT.jar
moshi-kotlin-codegen/build/libs/moshi-kotlin-codegen-2.0.0-SNAPSHOT.jar
moshi/build/libs/moshi-2.0.0-SNAPSHOT.jar
```

I can copy these over to my `app/libs`, but I'm stuck trying to figure out what to put in my `app/build.gradle`:

```
    implementation fileTree(include: ['moshi-2*.jar'], dir: 'libs')
    kapt fileTree(include: ['moshi-kotlin-*.jar'], dir: 'libs')
```

**Comment by tmm1** [comment]
> I'm stuck trying to figure out what to put in my `app/build.gradle`:

This worked:

```
    //implementation 'com.github.fancybits:moshi:0d4d83d88'
    //kapt 'com.github.fancybits.moshi:moshi-kotlin-codegen:0d4d83d88'
    implementation 'com.squareup:kotlinpoet:1.12.0'
    implementation 'com.google.guava:guava:28.2-jre'
    implementation 'org.ow2.asm:asm:9.3'
    implementation fileTree(include: ['moshi-2*.jar'], dir: 'libs')
    kapt fileTree(include: ['moshi-kotlin-*.jar'], dir: 'libs')
```

Seems quite brittle though, so I would love to be able to use jitpack builds again with a git sha.

**Comment by ZacSweers** [comment]
We don't support jitpack, this is not the place to ask for help with it. Sorry.
