### ISSUE TITLE
Casting with Type crashed in 1.14.0

### ISSUE THREAD

**Issue by ArcherEmiya05** [square/moshi#1577]
After updating from 1.13.0 converting String to data class no longer works.

Custom class for parsing
```
class MoshiParser(private val moshi: Moshi) : JsonParser {

    override fun <T> fromJsonString(jsonString: String?, type: Type): T? {

        if (jsonString.isNullOrBlank())
            return null

        return try {
            moshi.adapter<T>(type).fromJson(jsonString)
        }
        catch (e: Exception) {
            null
        }

    }

}
```

Usage
```
// Convert JSON String to this data class
            parser.fromJsonString<AppConfig.Remote>(it, AppConfig.Remote::class.java)?.let { config ->
                    // Initialize
                    AppConfig.remote = config
                }
```

It seems there is a bug with JNI native code.

The log is too long so here is a file instead.
[Moshi-Crash.txt](https://github.com/square/moshi/files/9693065/Moshi-Crash.txt)

**Comment by ArcherEmiya05** [comment]
I tried to roll back in 1.13.0 but the still there, maybe the bug is with AGP `8.0.0-alpha02`?

```
kotlin_version = '1.7.10'

plugins {
    id 'com.android.application' version '8.0.0-alpha02' apply false
    id 'com.android.library' version '8.0.0-alpha02' apply false
    id 'org.jetbrains.kotlin.android' version "${kotlin_version}" apply false
}
```

**Comment by ZacSweers** [comment]
This isn't related to Moshi

**Comment by ArcherEmiya05** [comment]
> This isn't a Moshi issue

Any idea where is the root cause of this issue? Thanks

**Comment by ArcherEmiya05** [comment]
I found the issue, it was R8. Setting the full mode to false explicitly is now required with the latest AGP.

`android.enableR8.fullMode=false`
![image](https://user-images.githubusercontent.com/38008900/193470935-1fa6b326-fbfa-4ec9-ba12-a1d1c78f4919.png)


But I wonder if we just need to add a proguard rule to solve this issue with Moshi.
