### ISSUE TITLE
 Casting with Type crashed with Full Mode R8

### ISSUE THREAD

**Issue by ArcherEmiya05** [square/moshi#1578]
What rules should be added explicitly in consumer module when working with full mode R8?

Casting with type is not working when full mode R8 is enabled.

Custom class for parsing
```
class MoshiParser(private val moshi: Moshi) : JsonParser {

    override fun <T> fromJsonString(jsonString: String?, type: Type): T? {

        if (jsonString.isNullOrBlank())
            return null

        return try {
            moshi.adapter<T>(type).fromJson(jsonString)
        }
        catch (e: Exception) {
            null
        }

    }

}

```

Usage

```
// Convert JSON String to this data class
            parser.fromJsonString<AppConfig.Remote>(it, AppConfig.Remote::class.java)?.let { config ->
                    // Initialize
                    AppConfig.remote = config
                }
```

Stacktrace:
[Moshi-Crash.txt](https://github.com/square/moshi/files/9693261/Moshi-Crash.txt)

Currently the only way to fix this is setting full mode to false explicitly since the new AGP seems to have it enable by default.

![image](https://user-images.githubusercontent.com/38008900/193471242-6a9581ad-9d8a-4440-b772-1d23dcddeadf.png)

`android.enableR8.fullMode=false`

Reference: https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode

**Comment by ZacSweers** [comment]
Hey, we've already closed your previous issue about this. Please don't duplicate issues and use the discussions tab to ask usage questions like this.
