### ISSUE TITLE
Conflict with RealmObject

### ISSUE THREAD

**Issue by ppamorim** [square/moshi#159]
Hi Square.

I cannot convert my files because it has some conflicts between Realm and Moshi.
The code of the application is:

```kotlin
val moshi = Moshi.Builder().build()
val result: Array<Foo> = moshi
  .adapter(Array<Foo>::class.java)
  .fromJson(it)
```

The model is:

```kotlin

open class Foo(open var id : Int, open var name : String) : RealmObject(),  Parcelable {

  companion object {
    @JvmField final val CREATOR: Parcelable.Creator<Foo> =
        object : Parcelable.Creator<Foo> {
      override fun createFromParcel(source: Parcel): Foo= Foo(source)
      override fun newArray(size: Int): Array<Foo?> = arrayOfNulls(size)
    }
  }

  constructor() : this(0, "")

  constructor(parcel: Parcel) : this(parcel.readInt(), parcel.readString())

  override fun writeToParcel(parcel: Parcel, flag: Int) {
    parcel.writeInt(id)
    parcel.writeString(name)
  }

  override fun describeContents(): Int = 0

}
```

After the request with `OkHttp`, I return the `BufferedSource` to be parsed to an Array of `Foo`, but the log returns this exception:

```
java.lang.IllegalArgumentException: No JsonAdapter for interface io.realm.RealmChangeListener annotated []
```

The error happens on the line `.adapter(Array<Line>::class.java)`.

I'm using:

- Moshi:1.1.0
- Realm-gradle-plugin:0.89.1
- Okhttp:3.2.0
- Kotlin: 1.0.1-2

Thanks.

**Comment by JakeWharton** [comment]
Your model contains a field with RealmChangeListener somewhere. Either
exclude it, mark it as transient, or register an adapter which can
serialize it to/from JSON.

**Comment by ppamorim** [comment]
I'm not using `RealmChangeListener `, but `RealmObject()` uses. Have we any relation in that? I don't know what Moshi does.

**Comment by JakeWharton** [comment]
Sounds like Realm needs to provide a JSON adapter for Moshi then.

**Comment by ppamorim** [comment]
If I remove the extends ```RealmObject()``` of my model, it works perfectly. :)

**Comment by JakeWharton** [comment]
This was apparently fixed in Realm.
