### ISSUE TITLE
@ToJson character escaping problem

### ISSUE THREAD

**Issue by danielgoncharov** [square/moshi#162]
The problem is the following: when you create a JsonAdapter using the annotations api and return a valid escaped string with the method annotated with @ToJson moshi additionally escapes the characters, making the json invalid.  The illustration test is below:

`public class MoshiTest {

    private Moshi moshi;

    @Before
    public void setUp() throws Exception {
        moshi = new Moshi.Builder()
              .add(new ServerResponseAdapter())
              .build();
    }

    @Test
    public void shouldNotEscapeValidJson() {
        Message message = new Message();
        message.type = "any";
        message.payload = "{\"status\":\"ok\",\"response\":{}}";
        try {
            new JSONObject(message.payload);
        } catch (JSONException e) {
            e.printStackTrace();
            Assert.fail();
        }
        JsonAdapter<Message> jsonAdapter = moshi.adapter(Message.class);
        String json = jsonAdapter.toJson(message);
        try {
            System.out.println(json);
            new JSONObject(json);
        } catch (JSONException e) {
            e.printStackTrace();
            Assert.fail();
        }
    }

    public static class ServerResponseAdapter {

        @SuppressWarnings("MethodMayBeStatic")
        @ToJson
        public String toJson(Message message) throws JSONException {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("type", message.type);
            jsonObject.put("payload", message.payload);
            return jsonObject.toString();
        }

        @SuppressWarnings("MethodMayBeStatic")
        @Nullable
        @FromJson
        public Message fromJson(String json) throws JSONException {
            //should never be called in the test
            Assert.fail();
            return null;
        }
    }

    private static class Message {
        String type;

        String payload;
    }
}`

**Comment by JakeWharton** [comment]
We don't support raw JSON. #65.
