### ISSUE TITLE
[Feature Request] JsonReader.nextBuffer() or JsonReader.nextReader()

### ISSUE THREAD

**Issue by serj-lotutovici** [square/moshi#163]
Currently there is no way to retrieve a `Buffer` or a sub-`JsonReader` of a json object embedded inside another json object. Gson allows to parse something in a `JsonElement`. Although `JsonReader` tries to parse everything efficiently as possible, but there is a case, when this would be very helpful.

Example:

``` json
{
  "type": "msg_type",
  "payload": { }
}
```

In the case when a custom `JsonAdapter` needs to parse the `payload` differently based on the `type` there is no way to buffer the payload contents in case if it's the first token in the json.
`JsonReader.nextReader()` would be the prefect solution for this, because the reader could already keep the portion which contains the json object, and the "master" `JsonReader` could just continue with the next token.

**Comment by swankjesse** [comment]
Isn’t that just the JsonReader itself?

**Comment by swankjesse** [comment]
Ahh, you’re thinking about this case:
```
{
  "payload": { },
  "type": "msg_type"
}
```
We’re working on this here:
https://github.com/square/moshi/issues/89

**Comment by swankjesse** [comment]
(Lemme know if JSON values isn’t the solution you wanted!)
