### ISSUE TITLE
[ReadMe error]

### ISSUE THREAD

**Issue by sunreview** [square/moshi#1643]
line 193 should be `substring(0,2)`
not  `substring(0,1)`

**Comment by tomridder** [comment]
![image](https://user-images.githubusercontent.com/13205117/227248262-f1bacab7-6807-41c6-bc08-694818bb6cd2.png)

the array 's length should be two ,not one

**Comment by JakeWharton** [comment]
The rank is one character, the suit is one character. The resulting string is 2 characters.

**Comment by tomridder** [comment]
> The rank is one character, the suit is one character. The resulting string is 2 characters.

sorry...
thanks for reply...God of Android
