### ISSUE TITLE
Expose JsonReader.selectName

### ISSUE THREAD

**Issue by adriancole** [square/moshi#165]
In zipkin, we have a custom json adapter for reading and writing trace spans. I did an experiment moving from switching on key names to `reader.selectName(OPTIONS)`. This was very little work and resulted in performance improvements in our read benchmarks. It would be nice to have a way to access `JsonReader.selectName` method without sharing Moshi's package

Here are improvements measured in ops/microsecond from my laptop:

reading a client-only span: 106 -> 118
reading a local span: 173 -> 201
reading a client + server span: 107 -> 127

**Comment by adriancole** [comment]
ps the implementation change looks something like this. Costs a little indirection, but since the struct hasn't changed in ages, not a biggie.

```java
// Add the universe of known fields
JsonReader.Options FIELDS = JsonReader.Options.of("serviceName", "ipv4", "port");

// later instead of something like this:
switch (reader.nextName()) {
  case "serviceName":

// do something like this:
switch (reader.selectName(FIELDS)) {
  case 0:
```

**Comment by swankjesse** [comment]
Yeah, we can open it up. Gotta figure out if options if the top level type, and how graceful we are when the encoding isn't canonical.

**Comment by serj-lotutovici** [comment]
This can be closed.
