### ISSUE TITLE
"Remote" annotation for moshi-codegen

### ISSUE THREAD

**Issue by eneim** [square/moshi#1655]
### The scenario:

- My app consumes the API from a 3rd party, and the model (JsonClass) definition comes from another 3rd party. The assumption is their model definition is based on Gson, or Jackson, or just non-annotated POJO. And they use a legacy HTTP stack to consume the API.
- Our App is fully integrate with Moshi and Retrofit eco-system so we just want to use it. The POJO in the 3rd party is Moshi-compatible (i.e., field names matches exactly what the API returns), but we don't want to use their HTTP stack, as well as use Moshi-reflection in our implementation.

### The idea:

- The idea is to have a way to inject the `@JsonClass(generateAdapter = true)` annotation _into_ the POJO, so that moshi-codegen will generate the Adapter for that class (hence the name is "Remote annotation").
- A reference for this idea is `Jackson`'s Mixin annotation.

Example

```kotlin
// The POJO from 3rd party library
data class Repository(val id: String, val owner: User, val url: String, val issueCount: Int)

// The Adapter in my app
@RemoteJsonClass(classes = [Repository::class.java]) // Instructs moshi-codegen to generate the Adapter for Repository.
class RemoteRepositoryJsonAdapter(moshi: Moshi) {
    private val realAdapter = moshi.adapter(Repository::class.java)
    fun fromJson(json: String): Repository? = realAdapter.fromJson(json)
    fun toJson(repository: Repository): String = realAdapter.toJson(repository)
}
```

I would like to ask if
- The Moshi library would support this idea and implement it?
- If not, can you advise if it is technically feasible for me to do it by myself, using what `moshi-codegen` has already. Some kind of codegen plugin I can build by myself and hook into the current moshi-codegen pipeline.

**Comment by ZacSweers** [comment]
I think we won't do this. This would make annotation processing an aggregating processor at best, and at worst cause strange compiler bugs if the target class is not in your compilation unit.
