### ISSUE TITLE
Update shaded Kotinpoet to 1.13.0

### ISSUE THREAD

**Issue by orospakr** [square/moshi#1657]
Repro steps:

1. Add Moshi to a project using Kotlin 1.8 (btw happens to be needed for Compose 1.4)
2. Attempt to build project
3. See the dreaded "Could not parse metadata! Try bumping kotlinpoet and/or kotlinx-metadata version." message because of a failing null check

Last week, kotlinpoet shipped https://github.com/square/kotlinpoet/releases/tag/1.13.0 which should support Kotlin 1.8.

Cheers and thank you!

**Comment by ZacSweers** [comment]
Moshi 1.14.0 uses kotlinx-metadata 0.5.0, which supports reading kotlin 1.9 APIs. Are you saying it doesn't?

**Comment by orospakr** [comment]
Hey @ZacSweers indeed, I think I lead myself up the garden path on this one. Apologies for the nuisance ticket. Closing.
