### ISSUE TITLE
No JsonAdapter for interface kotlin.properties.ReadOnlyProperty

### ISSUE THREAD

**Issue by fab1an** [square/moshi#167]
I tried serializing a kotlin object with moshi:

```kotlin
data class AppState(
    val currentScene: Scene = LoginScreen()
) {}
```

`Scene` is an interface. The first issue that popped up is that Moshi didn't know how to serialize the interface, so I registered a type-adapter like this:

```kotlin
val moshi2 = Moshi.Builder().build();

val moshi = Moshi.Builder().add(object {
    @ToJson fun toJson(scene: Scene): String {
        return moshi2.adapter(scene.javaClass).toJson(scene)
    }

    @FromJson fun fromJson(scene: String): Scene {
        /* for testing */
        return LoginScreen();
    }
).build();
```

I used the `moshi2` instance, because I didn't know how to get default serialization in an adapter. What I wanted to do, basically is get whatever `Scene` is actually serialized and then add a type-field which I can use to specify the class upon deserialization.

Now I'm getting the following error:

````
com.squareup.moshi.JsonDataException: java.lang.IllegalArgumentException: <NEWLINE INSERTED> 
No JsonAdapter for interface kotlin.properties.ReadOnlyProperty annotated [] at $.currentScene

	at com.squareup.moshi.AdapterMethodsFactory$1.toJson(AdapterMethodsFactory.java:68)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:190)
	at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:161)
	at com.squareup.moshi.JsonAdapter$1.toJson(JsonAdapter.java:75)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:44)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:50)
	at at.feibra.mobileqm.MoshiTest.serialization(MoshiTest.kt:41)
....
````

**Comment by swankjesse** [comment]
Sounds like Kotlin code uses library classes that Moshi doesn't understand. We should put `kotlin.*` on the platform blacklist, and consider adding a type adapters package specifically for Kotlin.

**Comment by fab1an** [comment]
Hm, okay…
And in general: What is the idiomatic way of (de)serializing an interface? It feels weird to use two moshi instances.

**Comment by swankjesse** [comment]
This issue comes close:
https://github.com/square/moshi/issues/133

**Comment by swankjesse** [comment]
No further action to take on this.
