### ISSUE TITLE
Build failing on kotlin 1.8.21 targeting kotlin 1.9 language version

### ISSUE THREAD

**Issue by savvasdalkitsis** [square/moshi#1670]
Re-raising https://github.com/square/moshi/issues/1669 with a reproducible build.

The latest (as of the writing of this) commit of my project fails with the error mentioned in the linked issue: https://github.com/savvasdalkitsis/uhuruphotos-android/commit/621a1bf4d411d6951e90094956475d6f04f8eb34

Hopefully that provides enough information to troubleshoot?

**Comment by ZacSweers** [comment]
Yes that's relevant info. This requires kotlinx-metadata 0.6.0, which is fixed on main but not released yet
