### ISSUE TITLE
RegularExpression

### ISSUE THREAD

**Issue by KarthikSESA** [square/moshi#1682]
I am getting api response of regularExpression is (?=.*[a-z].*)(?=.*[A-Z].*)^[\\w !\"#$%&'()*+,-.\\/:;<=>?@\\[\\\\\\]\\^_`\\{\\|\\}~]{6,32}$ but in the model object, I am getting some escaped string like (?=.*[a-z].*)(?=.*[A-Z].*)^[\w !"#$%&'()*+,-.\/:;<=>?@\[\\\]\^_`\{\|\}~]{6,32}$  because of this my validation is failing.

**Comment by ZacSweers** [comment]
Sorry I don't understand what the question is here. Please revisit with specific details of the issue and a repro case.
