### ISSUE TITLE
Concat two json strings to form one property

### ISSUE THREAD

**Issue by bmutinda** [square/moshi#171]
I have a class 
```java
public class Song {
    @Json(name="song_id") long remoteId;
    String location;
    @Json(name="song") String name;
    String artistId;
    @Json(name="artist") String artistName;
    @Json(name="album") String albumName;
    String albumId;
    @Json(name="songArt") String profilePicture;
    int duration = 0;
    boolean isLocal = true;

    public Song(){
    }
}
```
Now the problem is `profilePicture` is supposed to be a combination of `www.example.com/images/` and the `songArt` such that if the songArt is "image1.png" profilePicture is supposed to be `www.example.com/images/image1.png`.

How do I achieve that?
Thanks

**Comment by serj-lotutovici** [comment]
You can create a custom adapter that will parse the response into one string. See the samples included in the repo.

*Jake Mode:*  Please ask usage questions on Stackoverflow.

**Comment by bmutinda** [comment]
@serj-lotutovici I haven't seen an example that does that and thats the reason as to why I am asking.

From this *..parse the response into one string...* do you mean I get the json string, loop through the json objects I have changing the value of songArt ? and then use default adapters to get Song object?

**Comment by serj-lotutovici** [comment]
You can create a custom annotation, like `@ProfilePicture` and annotate the profioePicture field. Create a custom JsonAdapter wich will be selected for fields annotated with that annotation. Parse it there.

**Comment by swankjesse** [comment]
I think your best bet is to do something like the EventJson example here.
https://github.com/square/moshi/blob/master/README.md#another-example
