### ISSUE TITLE
Old guava version has security issues

### ISSUE THREAD

**Issue by JWvanV** [square/moshi#1712]
Hi,

the bug is more of a concern:  It appears that the current version of com.squareup.moshi:moshi-kotlin-codegen:1.15.0 has a dependency on com.google.guava:guava:30.1.1-jre, which has a know security issue:
https://www.cvedetails.com/vulnerability-list/vendor_id-1224/product_id-52274/Google-Guava.html

Could you update it to version 32.x ?

**Comment by ZacSweers** [comment]
Send a PR?

**Comment by ZacSweers** [comment]
Seems we've actually been on 32.x for awhile. Just updated another patch here: #1713

**Comment by ZacSweers** [comment]
We don't use the problematic APIs
