### ISSUE TITLE
Parsing json reading from java.io.Reader object.

### ISSUE THREAD

**Issue by DikenMaharjan** [square/moshi#1716]
Is there plan to include a function in JsonAdapter that accepts java.io.Reader object for parsing json?

**Comment by ZacSweers** [comment]
We would not. If there was anything for this, it would exist at the okio layer and allow you to constructed a BufferedSource from a Reader

**Comment by DikenMaharjan** [comment]
I was wondering what if the BufferedSource is UTF-16 encoded. The JsonReader.of(BufferedSource source) is expecting UTF-8 encoded stream. Should I be converting UTF-16 encoded stream to UTF-8 encoding?

**Comment by JakeWharton** [comment]
Yes. Moshi only operates on UTF-8 encoded bytes. You can write a decorating `Source` that does the conversion on-the-fly, or do it as one large operation depending on the size of your data.

**Comment by manoj19** [comment]
var coroutineScope: Job? = null
inline fun handleCoroutineExceptionWithoutCallBack(
    crossinline execute: suspend () -> Unit
) {
    val handler = CoroutineExceptionHandler { _, _ ->

    }
    coroutineScope?.let {
        if (!it.isCancelled) {
            it.cancel()
        }
    }
    coroutineScope = CoroutineScope(Dispatchers.IO + Job() + handler).launch {
        execute()
    }
}

inline fun <T> ApiResponse<T>.handleCoroutineException(
    crossinline execute: suspend () -> T
) {

    val handler = CoroutineExceptionHandler { _, exception ->
        CoroutineScope(Dispatchers.Main).launch {
            val exceptionHandler = when (exception) {
                is UnknownHostException -> {
                    ApiException.NetWorkException
                }

                else -> {
                    ApiException.ApiCoreException(exception.message ?: "")
                }
            }
            this@handleCoroutineException.onError(exceptionHandler)
        }
    }
    CoroutineScope(Dispatchers.IO + handler).launch {
        this@handleCoroutineException.onSuccess(execute())
    }

}
