### ISSUE TITLE
Deserialize a parameterized object without knowing its associated type. 

### ISSUE THREAD

**Issue by VictorAlbertos** [square/moshi#172]
Given these classes:

```java
public class Mock {

}

public class MockParameterized<T> {
  private final T t;

  public MockParameterized(T t) {
    this.t = t;
  }

}
```

Is it possible to deserialize a `MockParameterized` object wihtout supplying its associated `Type`?

```java
JsonAdapter<T> jsonAdapter = moshi.adapter(MockParameterized.class)
jsonAdapter.fromJson(jsonString)
```

With the previous snippet Moshi throws this `IllegalArgumentException`:

> Platform T annotated [] requires explicit JsonAdapter to be registered.

But, using Gson, when supplying only the `MockParameterized`.class, it ends up instantiating an object which its generic field is a type of [com.google.gson.internal.LinkedTreeMap](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java)

With Jackson, the unknown type will be mapped to a [java.util.LinkedHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html). 

So, is there any specifyc reasson for this behaviour? Is there a way using Moshi to instantiate a parameterized object without knowing its type?

It seems a detail, but for me is a really big issue. I'm trying to give support to Moshi for my cache library, but, because some internal details, I need to instantie an object without knowing its type, so I'll be glad if you could give me some advice.

**Comment by JakeWharton** [comment]
I am working on this.... slowly

**Comment by swankjesse** [comment]
Does this work?

```
Type type = Types.newParameterizedType(MockParameterized.class, Object.class);
JsonAdapter<MockParameterized<?>> jsonAdapter = moshi.adapter(type);
```

**Comment by VictorAlbertos** [comment]
It does, thanks :)

Actually, the 3 libraries behaviour similarly adopting this approach. 

I don't close the issue because it seems that this feature is planing to be implemented, eventually.

**Comment by swankjesse** [comment]
I'm unsure what else we’d implement actually.

**Comment by swankjesse** [comment]
Tracking here: https://github.com/square/moshi/issues/89
