### ISSUE TITLE
Moshi's performance issues

### ISSUE THREAD

**Issue by CrowForKotlin** [square/moshi#1734]
First point
Moshi uses a lot of reflection when initializing the adapter, and secondly, the operation of creating the adapter is very time-consuming! Based on the number of entity parameters of the bean, at least 20MS slower than gson, and while the adapter cache is similar to gson, it just wastes too much time initializing the adapter! If there are too many entity parameters, the Codegen-generated adapter will have n+1 instances of reflection!

Second point
Moshi is better at handling nullity judgments than Gson, which is one of the reasons I use Moshi a lot

Third point
The second time Moshi uses Codegen to parse the data a little faster than Gson, but is actually almost identical to entity parameter-based processing, often in milliseconds

Fourth point
I don't know why it is recommended to use Kotlin Reflect to make adapters, first of all, Kotlin Reflect occupies 2.5MB
Secondly, the performance is far inferior to Codegen, not as good as Gson, I think using Kotlin Reflect is the worst performance, and the unstable parsing time is very unstable!

**Comment by ZacSweers** [comment]
First point
- adapter lookups are cached and amortized over the course of an application's run time. If you really need reflection less initialization, nothing is stopping you from writing or generating your own `JsonAdapter.Factory` that instantiates them. That said, no one is measuring performance by how fast it to create an adapter, just the execution of the encoding/decoding. All this usually would happen on a background thread in any meaningful application scenario anyway.

Fourth point
- performance isn't a concern for everyone. For simple cases, tests, scripts, etc it's fine to use reflect to simplify setup.

Closing this issue as there isn't anything super actionable here.

**Comment by CrowForKotlin** [comment]
> 第一点
> 
> * 适配器查找在应用程序的运行期间被缓存和摊销。如果您确实需要少反射初始化，那么没有什么可以阻止您编写或生成自己的`JsonAdapter.Factory`实例化它们。也就是说，没有人通过创建适配器的速度来衡量性能，而只是通过编码/解码的执行来衡量性能。无论如何，所有这些通常都会发生在任何有意义的应用场景中的后台线程上。
> 
> 第四点
> 
> * 性能并不是每个人都关心的问题。对于简单的情况、测试、脚本等，可以使用反射来简化设置。
> 
> 关闭这个问题，因为这里没有任何超级可操作的东西。

Thank you, what you said does make sense,
It's just that sometimes the scene doesn't have to be handled in a background thread, taking the Android main thread as an example

**Comment by ZacSweers** [comment]
You shouldn't be doing serialization on the Android main thread.
