### ISSUE TITLE
Platform java.util.ArrayList<...> annotated [] requires explicit JsonAdapter to be registered

### ISSUE THREAD

**Issue by flawyte** [square/moshi#174]
Hi,

I'm refactoring an old piece of code that uses Moshi & Retrofit. For the moment I'm working on an adapter to switch between JSON and Model objects. However when I call the method that involves this particular adapter [an `IllegalArgumentException` is thrown](http://pastebin.com/PpcqD1NU).

And here is the [`ChatMessage` class](http://pastebin.com/kfDcQjVq). I tried to comment all code in my adapter and it still throws and error, so I guess the problem is in the model, not in the adapter.

Any ideas what's wrong in my code please?

**Comment by serj-lotutovici** [comment]
That's expected behaviour. Use `List<>` instead of `ArrayList<>` or, write an explicit adapter for that type (see `com.squareup.moshi.CollectionJsonAdapter<>` for inspiration).

BTW, this tracked is for issues and feature requests only. Please address general usage questions on StackOverflow.

**Comment by flawyte** [comment]
Ok thanks!
