### ISSUE TITLE
0x

### ISSUE THREAD

**Issue by Hawkins37** [square/moshi#1750]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/ZacSweers/0ef2c5f0e3f61f82063dd8c67d75879f

**Comment by JakeWharton** [comment]
Oh you're just making spam. Cool.

**Comment by andersonguermo** [comment]
#salve mais quem você é

Em seg., 23 de out. de 2023 16:13, Jake Wharton ***@***.***>
escreveu:
