### ISSUE TITLE
Option/config to force/require `@Json(name = "…")` annotations on all fields ("Strict mode")

### ISSUE THREAD

**Issue by mfederczuk** [square/moshi#1758]
I'd like to propose an option/config to enable a sort-of "strict mode" for `@JsonClass` model classes that forces/requires adding an `@Json(name = "…")` annotation to every field.

The main use case I have in mind is safely renaming the field names of model classes without changing the actual JSON object property name.
It's common to have the field name and the JSON name be different, either because you're working with an API that has bad names for it's JSON properties or because backwards compatibility needs to be preserved.
When renaming fields of model classes that *don't* have an `@Json` annotation it's easy to break compatibility by simply forgetting to add the annotation.
Obviously that can't happen if you're forced to have the annotation everywhere in the first place, so it's safer to do refactors/renames without breaking anything

This would also help with turning on R8, ProGuard or any other processor that minifies or mangles identifiers, though, naturally, this could be solved by adding proguard rules.

Now since Moshi doesn't make use of a Gradle plugin, the only way I know that such an option could be made available is through the `gradle.properties` file?
I wouldn't know what the Maven equivalent would be.

**Comment by ZacSweers** [comment]
This is better suited for a lint check than annotation processing

**Comment by andersonguermo** [comment]
salve
