### ISSUE TITLE
[Feature Request] Support for JsonAdapter that is aware of the json elements path

### ISSUE THREAD

**Issue by serj-lotutovici** [square/moshi#176]
This was mentioned in #113, but was discarded due to a lack of reasoning regarding custom type support.

Assuming we have a payload:
```json
{
  "response" : {
  }
}
``` 
And we need only the object under the  `"response"` key. A custom `JsonAdapter` would do the trick, but in our case, we have tons of json objects that are returning the same models that are wrapped around  such constructs (and with different keys). This makes the the custom adapter solution unfeasible, because we have to write adapters, for each variation. We also would like to avoid creating object for each request response.

With `moshi-1.1.0` I've managed to overcome this by creating a custom `ParameterizedType` that would store an array containing the path to the desired object and a custom adapter that would complement that type and handle the parsing. But from `1.2.0` `Moshi#adapter(Type, Set<Annotation>)` calls `Types.canonicalize(Type)` which results in the loss of the initial instance of my custom `ParameterizedType`.

My request would be:

- Add `path: String[]` to `@Json` 
- Create a `JsonAdapter` that would traverse the json keys, un-wrapping the desired object.
- Add possibility to retrieve the specific adapter from `moshi` by passing the desired type, and the path to the object.

I understand that this may not be desired as a first class citizen feature, but it would be a huge help for a lot of developers, and would save a ton of lines of coding.

**Comment by swankjesse** [comment]
Can you just make a parameterized type like `Box<T>` ?

**Comment by swankjesse** [comment]
```
class Box<T> {
  T response;
}```

**Comment by serj-lotutovici** [comment]
Thats an option we've considered... but for some responses we would get `Box<List<Box<Box<T>>>`
 ¯\_(ツ)_/¯

**Comment by swankjesse** [comment]
If that’s your datamodel, that’s what you gotta do.

**Comment by serj-lotutovici** [comment]
Ok... sorry for waisting your time.
