### ISSUE TITLE
Per class adapters

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/moshi#179]
It would be great if Moshi could provide a way to define custom adapters on a per-class level.

My use case is that I have two different server endpoints that each expect a different date format.
So I can't just configure a single adapter as my serialisation ends wrong.

**Comment by vanniktech** [comment]
Can't you use [Custom Type Adapters](https://github.com/square/moshi#custom-type-adapters)?

**Comment by PaulWoitaschek** [comment]
I'm using a custom type adapter already. But wouldn't that require setting up multiple instances of Moshi for each type adapter and in my case Multiple Instances of Retrofit for each different serialization strategy?

**Comment by serj-lotutovici** [comment]
Why not just tie the type adapter to an annotation, moshi allows you to declare multiple adapters, for the same type but with different `@JsonQualifier` annotations.

Another solution, would be to create an adapter factory, that returns the appropriate adapter, based on your endpoint (assuming that your app works only with one endpoint at a time).

**Comment by vanniktech** [comment]
Are you using the same model class for both end points? If so Custom Type Adapters won't work AFAIK.

**Comment by PaulWoitaschek** [comment]
The `@JsonQualifier` solution works, thanks!
