### ISSUE TITLE
Add an option to fail deserialization when some keys are not present in the JSON

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#180]
I have a backend that gives me some bad payloads sometimes, and I'd rather fail deserialization than do anything with the partial values with default values for the missing fields.
This is almost the opposite of `setFailOnUnknown`.
Ideally, I'd really love to fail only when specified keys (perhaps marked with a field annotation) are missing.

**Comment by NightlyNexus** [comment]
Ah, it looks like this was [possibly previously proposed](https://github.com/square/moshi/issues/143) as `@Json(required=true)`.

**Comment by swankjesse** [comment]
Yeah, will close as duplicate.
