### ISSUE TITLE
Root name unwrapping

### ISSUE THREAD

**Issue by Antrakos** [square/moshi#182]
I have json with such structure, where needed object is wrapped into `data` field:
`{
  "data": {
    "id": 279121,
    "rating": "TV-14",
    "siteRating": 8.7,
    "siteRatingCount": 186
  }
}`
Can you add feature for easy unwrapping such data?

The only solution I found is to create an additional class and always pass `Type.newParameterizedType()` of it and desired object to `adapter()` method. 
`class Page<T> {
        T data;
    }`
It's very inconvenient and hard to scale. Suppose we need wrapped list of objects:
`moshi.<Page<List<DesiredObject>>>adapter(Types.newParameterizedType(Page.class, Types.newParameterizedType(List.class, DesiredObject.class))).fromJson(json).data`

**Comment by serj-lotutovici** [comment]
There where a few tickets related to this question: #113 and #176, both where rejected.

You can try this for now: [UnwrapJsonAdapter](https://github.com/serj-lotutovici/moshi-lazy-adapters/blob/master/src/main/java/com/serjltt/moshi/adapters/UnwrapJsonAdapter.java). It's part of a pet project I'm working on (but very slowly).

**Comment by Antrakos** [comment]
Thank you, but I expect something like `moshi.adapter(DesiderObject.class).withRootName("data").fromJson(json)`
This is more convenient and obvious. Therefore this can't be done by custom type adapter. It applies to core functionality.

**Comment by serj-lotutovici** [comment]
That would require to add a new wrapping method to the `JsonAdapter<>`. And actually sounds like a good idea. If @swankjesse is fine with this api addition, I can come-up with a PR today.

**Comment by swankjesse** [comment]
I recommend either getting an adapter for `Box` or using @serj-lotutovici’s UnwrapJsonAdapter.
