### ISSUE TITLE
Checked Exceptions?

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/moshi#187]
Is it really wise that `fromJson` throws a checked `IOException` rather than a runtime exception?

I think it encourages bad software design that `fromJson` throws a checked exception.
For example I use moshi to temporarily persist small objects in my SharedPreferences and all my calls are wrapped like this:

```java
try {
  return tokenAdapter.fromJson(value);
} catch (IOException e) {
  throw new RuntimeException(e);
}
```

I definately do not expect that to happen and if it happens I want my app to blow up because I messed something up.

**Comment by swankjesse** [comment]
This is thrown if the string you supply is not well-formed JSON. I have opinions on checked exceptions.
https://publicobject.com/2015/04/25/checked-exceptions-vs-api-design/

**Comment by PaulWoitaschek** [comment]
Okay, so the conclusion is? You can always try-catch an unchecked exception but you can never emit a try-catch on a checked exception.

I think the `good programs` you mention know when parsing a json is safe and when it's not.

**Comment by swankjesse** [comment]
The conclusion is that exceptions are sad. In this case I think you're right to retrieve as an unchecked exception. It’s safer to punish you by making you catch an impossible exception than to punish someone whose JSON could be bad by crashing their app.
