### ISSUE TITLE
KSP2 throws `NoSuchElementException` for data classes with `@JsonAdapter(generateAdapter = true)`

### ISSUE THREAD

**Issue by Hiraev** [square/moshi#1870]
### Issue

When the `ksp.useKSP2` flag is enabled, KSP2 throws a `java.util.NoSuchElementException` under two specific 
cases:
- when **data** classes are annotated with `@JsonAdapter(generateAdapter = true)`
- when enum classes are annotated with `@JsonAdapter(generateAdapter = false)` (notwithstanding their lack of necessity)

### Environment
- Kotlin 2.0.0
- KSP 2.0.0-1.0.23
- Moshi 1.15.1
- Java 17
- Gradle 8.5
- macOS Sonoma 14.1

### Example
To recreate the issue, follow these instructions:
1. Prepare directories for project
```bash
mkdir -p k2 k2/gradle k2/src/main/kotlin/org/example; cd k2
```
2. Create `libs.versions.toml`
```bash
echo '
[versions]
kotlin = "2.0.0"
ksp = "2.0.0-1.0.23"
moshi = "1.15.1"

[libraries]
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
' > gradle/libs.versions.toml
```

3. Create `build.gradle.kts`
```bash
echo '
plugins {
    alias(libs.plugins.jvm)
    alias(libs.plugins.ksp)
}

repositories {
    mavenCentral()
}

dependencies {
    ksp(libs.moshi.codegen)
    implementation(libs.moshi)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
' > build.gradle.kts
```

4. Create Kotlin file
```bash
echo '
package org.example

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Person(val a: Int)

@JsonClass(generateAdapter = false)
enum class Cell {
    BLACK,
    WHITE,
}
' > src/main/kotlin/org/example/Example.kt
```

6. Add Gradle wrapper
```bash
gradle wrapper --gradle-version 8.5 --distribution-type all
```

7. Build project without KSP2
```bash
./gradlew build -Pksp.useKSP2=false
```
This build finishes successfully. 

8. Build project with ksp2
```bash
./gradlew build -Pksp.useKSP2=true
```
This build fails with exception
```stacktrace
> Task :kspKotlin FAILED
e: [ksp] java.util.NoSuchElementException: Collection contains no element matching the predicate.
```

Removing the data modifier from the `Person` class and the annotation from the enum class allows the KSP processor to complete its task without encountering any issues.

Interesting point. Next test in `JsonClassSymbolProcessorTest` passes successfully.

```Kotlin
  @Test
  fun generateAdapterForDataClass() {
    val result = compile(
      kotlin(
        "source.kt",
        """
          package test
          import com.squareup.moshi.JsonClass

          @JsonClass(generateAdapter = true)
          data class Person(val a: Int)
          """,
      ),
    )

    assertThat(result.exitCode).isEqualTo(KotlinCompilation.ExitCode.OK)
  }
```

**Comment by ZacSweers** [comment]
Upstream bug https://github.com/google/ksp/issues/1998
