### ISSUE TITLE
Making parsing more lenient

### ISSUE THREAD

**Issue by lyptt** [square/moshi#188]
Currently if the format of the value doesn't match what was expected, a JsonDataException is thrown. Ideally it'd be nice to resume parsing the rest of the data, but set that value to null.

We don't have any control over the data we're being sent, and we -do- need to be able to parse whatever's valid.

If there's any advice on how to approach this, it would be greatly appreciated.

**Comment by swankjesse** [comment]
That’s pretty tough to do generally. You might be able to do something with a JsonAdapter.Factory to use `peek()` and `skip()` if the types don’t match.

**Comment by lyptt** [comment]
Yeah, so looking at the exception further it seems it's the StandardTypeAdapter's ObjectTypeAdapter that's throwing the exception. It sees an object but it's supposed to return a string in my case. 

I've experimented with doing this with GSON using skip and it forever complains about that original issue on every object - it seems like it's not possible to get it to move onto the next field in the class, only the next entry in the JSON object.

Since this library is based on GSON I assume this would have the same issue? If there's any insight here you could provide that'd be incredibly helpful. I'm happy to work on a PR if necessary.

**Comment by swankjesse** [comment]
Not sure what action to take here. Seems difficult to do in general.

**Comment by NightlyNexus** [comment]
@lyptt 
This is now possible in 1.4:
https://github.com/square/moshi/blob/49092ece9623c8acd10cd509755b459460a5a40e/examples/src/main/java/com/squareup/moshi/recipes/DefaultOnDataMismatchAdapter.java

**Comment by lyptt** [comment]
Wow that's awesome! I'll give that a go, thanks!

**Comment by lyptt** [comment]
This worked absolutely perfectly. Thanks a lot for making this possible! 😀
