### ISSUE TITLE
Support ArrayList by default for Quality of life

### ISSUE THREAD

**Issue by yd4011439** [square/moshi#1897]
Hi Moshi Developers, 
While migrating from gson to moshi, I was stunned that there is no support for basic types like ArrayList. Digging into the [source code](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.kt#L127) found out that there is more code to not support ArrayList than to support it. List type is already supported and conversion will just take a simple call to ArrayList constructor. 

If it were performance issue then most custom adapter will call the ArrayList constructor nonetheless. Please support to increase quality of life for developers.

**Comment by JakeWharton** [comment]
This is an intentional design decision. See: https://github.com/square/moshi/issues/409#issuecomment-351064233

You can hook up a simple delegating adapter for `ArrayList` if you _really_ need it, but I also would consider switching to using `List` for the type.

**Comment by cj-marius-duna** [comment]
So sad...
