### ISSUE TITLE
How do I ignore properties of a parsed object's superclass

### ISSUE THREAD

**Issue by lalunamel** [square/moshi#190]
I have a class `Dog` that inherits from class `Model`, which comes from my database library and is required if I want to treat Dog as an object that I can perform CRUD operations on.

Dog also represents a remote JSON resource somewhere, so it's being parsed by Moshi.

When Moshi goes to turn my JSON into a Dog, it chokes on some fields on Model, it's superclass. I don't want Moshi to parse those fields.

I'd mark those fields `transient`, except I don't have access to that library.
I'd write an adapter, except I'd have to create one for each of my models, which defeats the purpose of Moshi.
An ideal solution would be to provide an annotation with a list of fields I _do_ want, though I can't find any documentation about that.

How can I tell Moshi I don't want it to parse any fields from an object's superclass?

**Comment by swankjesse** [comment]
There’s nothing built in.

**Comment by lalunamel** [comment]
For those that come looking with a similar problem, I decided to use GSON, which does support excluding an object's superclass:

You can apply the [`excludeFieldsWithoutExposeAnnotation()`](https://google.github.io/gson/apidocs/com/google/gson/GsonBuilder.html#excludeFieldsWithoutExposeAnnotation--) method when building your GSON object and then annotate each field in your object with `@Expose`. 
It's slightly tedious but fixes the problem.
