### ISSUE TITLE
Serializing nested generic members

### ISSUE THREAD

**Issue by rakshakhegde** [square/moshi#191]
Given these classes:

```
import android.databinding.ObservableField
import com.squareup.moshi.Moshi
import org.junit.Test

class ExampleUnitTest {
	@Test
	fun observableMoshi() {
		val myMoshi = Moshi.Builder().build()
		val jsonStr = myMoshi.adapter(ABC::class.java).toJson(ABC())

		assertEquals(jsonStr, """{"str":{"lat":"mString!"}}""")
	}
}

class MyLoc {
	val lat = ObservableField("mString!")
}

class ABC {
	val str = ObservableField(MyLoc())
}
```

In the above Android Kotlin code, I expect jsonStr to finally print this JSON output (in not-pretty obviously):
```
{
	"str": {
		"lat": "mString!"
	}
}
```

But instead I'm getting the following error:
```
java.lang.IllegalArgumentException: Platform android.databinding.ObservableField<com.instavans.instavansshippers.MyLoc> annotated [] requires explicit JsonAdapter to be registered
```

If instead, I had just `ObservableField<String>` in `ABC` class, then I could use **Custom Type Adapter** to get this working, but with this nested Generic structure, I'm unable to get the expected output. I'm trying to use this Moshi along with Retrofit.

So please help me to get the expected output using Moshi.

**Comment by swankjesse** [comment]
Make your nested classes static?

**Comment by rakshakhegde** [comment]
In Kotlin, there's no concept of `static`, but if you mean make those classes outer, that doesn't work too. I'm supposing this problem requires `JsonAdapter` or `Type` in some way, but I'm not sure how exactly.

**Comment by swankjesse** [comment]
Can you define these types outside of a method? That's likely to cause an implicit reference to the enclosing class to sneak in.

**Comment by rakshakhegde** [comment]
I've made the changes as you suggested. The code and the exception has been modified accordingly. The exception is essentially the same, I don't think this issue has anything to do with implicit reference.

**Comment by JakeWharton** [comment]
Moshi will not serialize platform types. You need to register a json adapter for `ObservableField` to read/write its inner value for serialization.

See "Moshi has fewer built-in type adapters" from https://github.com/square/moshi#borrows-from-gson for where this is documented.

**Comment by rakshakhegde** [comment]
Yes, I've seen that and understood that. As mentioned in the question, when I use `ObservableField<String>` directly in class `ABC`, I coud use a custom type adapter (using `@ToJson` and `@FromJson`) to get it working. But in this case, I'm not sure how to write the same type adapter for my given class structure.

**Comment by rakshakhegde** [comment]
Is it documented anywhere on how exactly this `Type` works?
```
Type type = Types.newParameterizedType(MockParameterized.class, Object.class);
```
Got the snippet from https://github.com/square/moshi/issues/172

**Comment by swankjesse** [comment]
Can you offer a Java test case demonstrating the problem?

**Comment by swankjesse** [comment]
Can you offer a Java test case demonstrating the problem?

**Comment by rakshakhegde** [comment]
Here it isn't really the issue of Kotlin or Java.

I've solved the issue neatly (IMO) :P

<img width="1241" alt="screen shot 2016-09-23" src="https://cloud.githubusercontent.com/assets/8101796/18775784/f0a532d8-8181-11e6-9198-e535d067e06b.png">

Obviously my data/class structures are a bit different from my Issue. But the most interesting part is `ObservablesCompatMoshi` (X) is using `ObservableArrayListLocationMoshiAdapter` (Y) as a type adapter and in turn Y is using X by lazy-loading (as X won't be initialized before Y is) for the `Location`.

Now, two things I learnt the hard way in Moshi are:
- Though `ObservableArrayList` is indirectly a subclass of `List`, Moshi doesn't pick that up automatically and generate JSON like it's a `List`
- I had to create a new Type Adapter for every different Generic parameter. For eg: ObservableList<String> and ObservableList<Int> will be treated differently and I'd have to create different Type Adapters for each of them. It would be nice to define a Type Adapter like ObservableList<*> and be able to handle all data types.

**Comment by rakshakhegde** [comment]
Please suggest any alternative shorter/efficient'er way to achieve the same thing, if it exists, in Moshi.

**Comment by swankjesse** [comment]
You can use a `JsonAdapter.Factory` to handle the related types on demand.

**Comment by rakshakhegde** [comment]
Please add samples for `JsonAdapter.Factory`.

**Comment by swankjesse** [comment]
Good idea. Can do.
https://github.com/square/moshi/issues/136

**Comment by schatzdesigns** [comment]
Still no documentation for this? @rakshakhegde , did you solve the issue? Am having the same issue when I nest generic classes
