### ISSUE TITLE
Moshi generated Proguard rules avoid -if rules for -keepnames rules

### ISSUE THREAD

**Issue by christofferqa** [square/moshi#1911]
Moshi appears to be generating Proguard rules on the form `-if class T -keepnames class T`. The `-keepnames` directive is an alias for `-keep,allowshrinking`, which means that the `-if class T` precondition is redundant. The generated rules should ideally be changed to `-keepnames class T`.

Conditional `-if` rules are generally more expensive to evaluate than non `-if` rules, which leads to higher build speeds. In an app that had thousands of Moshi generated `-if class T -keepnames class T` rules, removing the `-if class T` part from these rules improved build speed by ~8 %.

**Comment by ZacSweers** [comment]
FYI we have around ~1400 models and found virtually no perf change when benchmarking before/after. Confirmed the updated rules do have the `-if` removed as well
