### ISSUE TITLE
Cater for different models on the same Response

### ISSUE THREAD

**Issue by renclav** [square/moshi#193]
Hi,

Background:
Android
okhttp
90% of our web responses return a status code of 200 with the 'true' code inside the body as json.

Use case:
Fetch a product
response status code is 200
response body could either contain a product dto or differently formatted error response

Problem:
The model to deserialize the response is unknown without inspecting the response itself.

I see two solutions
1. Cast the body to native json and inspect response, then cast with Moshi (hate this due to unessary object creation)
2. Use JsonAdapter.Factory to peek at the contents and convert to correct model

Solution 2 seems optimal, just not sure how to go about this? Or maybe there is a third option?

Thank You

**Comment by swankjesse** [comment]
This is a better question for StackOverflow. This tracker is for bug reports and feature requests only.
