### ISSUE TITLE
Parse JSON which can be either an array or a single item

### ISSUE THREAD

**Issue by fhucho** [square/moshi#205]
Hey, I'm trying to parse a list of objects, where the source JSON datastructure is either an array of objects or a single object. Is there some way to do this?

**Comment by swankjesse** [comment]
Preferably questions go to StackOverflow. Regardless you'll want an adapter that uses JsonReader.peek() to inspect the value’s type.

**Comment by fhucho** [comment]
Thanks, here's the SO question: http://stackoverflow.com/questions/40110184/parse-json-key-thats-an-object-or-a-list-of-objects-of-the-same-type
