### ISSUE TITLE
Escaped slashes fail to be deserialized with Moshi 1.3.0

### ISSUE THREAD

**Issue by vanniktech** [square/moshi#209]
Deserializing an escaped slash fails with version 1.3.0 of moshi where as with version 1.2.0 everything worked.

Test case that works for 1.2.0 but not for 1.3.0:

```java
@Test public void escapedSlash() throws Exception {
  Moshi moshi = new Moshi.Builder().build();
  JsonAdapter<String[]> adapter = moshi.adapter(String[].class);
  assertThat(adapter.fromJson("[\"\\/a\",\"b\"]")).containsExactly("/a", "b");
}
```

Is this a desirable regression? As far as I know this is a valid JSON and should work.

**Comment by swankjesse** [comment]
Nope, this is an unintended regression. I’ll fix and release ASAP.

**Comment by swankjesse** [comment]
Regression is introduced here: https://github.com/square/moshi/pull/166

**Comment by cbruegg** [comment]
Not sure if you need it, but here's the smallest PR I ever made to fix this: https://github.com/square/moshi/pull/210

**Comment by anthonyst91** [comment]
This issue is still occuring with Moshi 1.5.0 and 1.6.0.
Moshi wont deserialize things like that : 
"rtsp":"rtsp:\/\/192.168.1.30\/streaming\/stream?flavour=sd"

**Comment by swankjesse** [comment]
@anthonyst91 could ya provide an executable test case?
