### ISSUE TITLE
Returning unknown enum values as null

### ISSUE THREAD

**Issue by edenman** [square/moshi#218]
I have an enum that represents the various different types of errors i could get for a particular server endpoint.  If i get back a value that isn’t in that enum (say, the server adds a new error type and I’m on an old client that doesn’t know about it), `EnumJsonAdapter` blows up.  I'd like to add an option to have it just return null in that case.  Thoughts?  How would I go about adding this? (I don't see any customization of the `StandardJsonAdapters` but I might just be missing it)

**Comment by edenman** [comment]
Or is the answer just "add your own enum adapter Factory"?

**Comment by swankjesse** [comment]
That's the easiest. We should probably include that as a standard extra adapter.

**Comment by edenman** [comment]
Cool, I'll just roll my own for now, thanks!

**Comment by serj-lotutovici** [comment]
Sorry for bragging, but there is a [`@FallbackEnum` annotation](https://github.com/serj-lotutovici/moshi-lazy-adapters/blob/master/src/main/java/com/serjltt/moshi/adapters/FallbackEnum.java) in a small extension I've wrote. It allows to specify a fallback value (spares a null check). The used adapter is a fork of the internal one.

**Comment by NightlyNexus** [comment]
for posterity:
https://github.com/square/moshi/pull/248

**Comment by NightlyNexus** [comment]
@edenman and everybody else,
Is this okay to close, given the above sample? Is it alright not to have this fallback in the JsonAdapter API?

**Comment by edenman** [comment]
I'm ok with the "roll your own"/"use the sample" approach, but it does still seem like something that is a common enough occurrence that it'd be good to build in (at least as an option).  Not a big deal either way though, I'm already using my own bespoke adapter.

**Comment by swankjesse** [comment]
Yep. I think we want something specifically for enums.

**Comment by naturalwarren** [comment]
FWIW I currently roll my own "enum fallback adapters". Would love to see this get added.

**Comment by NightlyNexus** [comment]
@swankjesse Are you thinking something like `Moshi.Builder.add(Class<T> enumType, T defaultValue)`? That would be trivial to implement, but maybe there's a better API I'm not thinking of yet.

**Comment by NightlyNexus** [comment]
Or, `Builder.enumFallback(T fallbackValue)` and skip the class parameter?

You wouldn't be able to fall back to null, then, but that might be okay. Force people who need a fallback to define a default or a special "UNKNOWN" type instead of null.

**Comment by NightlyNexus** [comment]
https://github.com/square/moshi/pull/480#issuecomment-385218125

**Comment by NightlyNexus** [comment]
Done in #607. An EnumJsonAdapter will be in the `adapters` artifact in the next release.
