### ISSUE TITLE
java.lang.ClassCastException: com.squareup.moshi.LinkedHashTreeMap cannot be cast to ...

### ISSUE THREAD

**Issue by abler98** [square/moshi#221]
I have the method:
```java
public PaginationData<T> call(String response) {
    try {
        Log.d(TAG, "call: " + response);
        Moshi moshi = new Moshi.Builder().build();
        Type type = Types.newParameterizedType(PaginationData.class, Object.class);
        JsonAdapter<PaginationData<T>> adapter = moshi.adapter(type);
        return adapter.fromJson(response);
    } catch (IOException e) {
        throw Exceptions.propagate(e);
    }
}
```

PaginationData:
```java
class PaginationData<T>
{
    @Json(name = "total")
    public int total;
    @Json(name = "per_page")
    public int perPage;
    @Json(name = "current_page")
    public int currentPage;
    @Json(name = "last_page")
    public int lastPage;
    @Json(name = "next_page_url")
    public String nextPageUrl;
    @Json(name = "prev_page_url")
    public String prevPageUrl;
    @Json(name = "from")
    public int from;
    @Json(name = "to")
    public int to;
    @Json(name = "data")
    public List<T> data;
}
```

How can I specify the type for a list?

When I try to get the item from list I get the error:
`java.lang.ClassCastException: com.squareup.moshi.LinkedHashTreeMap cannot be cast to ...`

**Comment by abler98** [comment]
I got rid of the error by specifying the correct parameter class:
`Type type = Types.newParameterizedType(PaginationData.class, User.class);`
Сan not do without it?

**Comment by swankjesse** [comment]
It'd be impossible to guess what T is.

**Comment by schatzdesigns** [comment]
This makes performance on the app to really cringe, when you have a complex generic type, where you have to convert the LinkedHashTreeMap to Json first then back to the Type you want it to return.

**Comment by ZacSweers** [comment]
@schatzdesigns I don't really understand where that flow could happen in Moshi. As mentioned in the other issue - please post on stackoverflow with the Moshi tag and full code samples if you're having usage issues. Comments like the above with missing context are not very constructive and make it difficult for anyone to help.
