### ISSUE TITLE
Right way for a generic adapter?

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/moshi#224]
I just created an adapter for a generic type. I could not really find documentation about this and I think this is something that should be documented with examples as it acutally was quite hard to figure out.

I first started writing an adapter for `SparseArrayCompat`:
```kotlin
class SparseArrayCompatAdapter<T>(private val adapter: JsonAdapter<T>) : JsonAdapter<SparseArrayCompat<T>>() {

  override fun toJson(writer: JsonWriter, sparseArray: SparseArrayCompat<T>) {
  ....
  }

  override fun fromJson(reader: JsonReader): SparseArrayCompat<T> {
   ...
  }
}
```

However when registering this adapter, I got an exception that I need to register a specific type adapter for `SparseArrayCompat<Double>`.

Then I tried a lot and came up with a factory that delegates to the adapter:

```kotlin
object SparseArrayFactory : JsonAdapter.Factory {

  override fun create(type: Type, annotations: MutableSet<out Annotation>, moshi: Moshi): JsonAdapter<*>? {
    val rawType = Types.getRawType(type)
    if (rawType == SparseArrayCompat::class.java && type is ParameterizedType) {
      val subType = type.actualTypeArguments.first()
      val adapter: JsonAdapter<Any> = moshi.adapter(subType)
      return SparseArrayCompatAdapter(adapter)

    }
    return null
  }

}
```

Is this the way moshi intended to do this?

**Comment by swankjesse** [comment]
Yep, you did it perfectly. I'll get some more docs.

**Comment by NightlyNexus** [comment]
fold this into https://github.com/square/moshi/issues/136?

**Comment by swankjesse** [comment]
Yep.

**Comment by schatzdesigns** [comment]
No documentation yet?
