### ISSUE TITLE
RFC 3339 date adapter

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#26]
Installed by default; user-replaceable by default.
https://www.ietf.org/rfc/rfc3339.txt

**Comment by inder123** [comment]
Why not install UTC Date Type adapter by default?
https://github.com/google-gson/google-gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/UtcDateTypeAdapter.java

**Comment by swankjesse** [comment]
Yup, that's what we're going to do.

**Comment by swankjesse** [comment]
(RFC 3339 format, with UTC zone)

**Comment by inder123** [comment]
Ok, is the UtcDateTypeAdapter fitting the bill? If you need to change it, do let me know so that I update the original.

**Comment by swankjesse** [comment]
Yeah, the Jackson parser is a great place to start. I have a PR outstanding with some fixes for that:
https://github.com/FasterXML/jackson-databind/pull/948/files
