### ISSUE TITLE
How can I parse a dynamic Json #HelpWanted

### ISSUE THREAD

**Issue by cesarnorena** [square/moshi#261]
I'm using Retrofit with MoshiConverterFactory, and I have an endpoint that response me with dynamic values. I could receive it in a object with a lot of null values, but I don't want this solution.

I have a interface A which is implemented by B and C. I like to receive the type 0 with Object B and type 1 with object C.

If type is 0 I receive a Json like this:
```
{
  "type": 0,
  "service": {
    "a": "asdf",
    "b": "asdf",
    "c": "asdf"
  }
}
```

but if type is 1 I receive a Json like this:
```
{
  "type": 1,
  "service": {
    "a": "asdf",
    "b": "asdf",
    "c": "asdf"
    "d": "asdf"
    "e": "asdf"
    "f": "asdf"
  }
}
```
Thanks!

**Comment by NightlyNexus** [comment]
https://github.com/square/moshi/pull/256/files will give you the idea.
Hopefully, we'll have a good pluggable sample in the near future.
I'm subscribed to the `moshi` tag on StackOverflow, so I can answer specific usage questions there, if the linked code gets confusing.
