### ISSUE TITLE
Allow delegates for non-qualified types into adapter methods.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#271]
```java
final class PointJsonAdapter {
  @FromJson Point fromJson(JsonReader reader, JsonAdapter<Point> delegate) throws Exception {
    reader.beginObject();
    reader.nextName();
    Point point = delegate.fromJson(reader);
    reader.endObject();
    return point;
  }
}
```
For the above to work, I would need a `@JsonQualifier` on all of my application-layer `Point`s, or I would need to write the `JsonAdapter.Factory` manually.

Should Moshi support the above?

**Comment by swankjesse** [comment]
Yeah, let's do it. If the parameter’s type + annotations match the current method, we should supply a delegate.
