### ISSUE TITLE
Support magical toJson(), fromJson() methods

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#29]
Classes can declare the following methods:
```
 <any access modifier> Object toJson();
 <any access modifier> public static Object fromJson(Object json);
```
If they do, Moshi honors ‘em. The returned objects are then themselves converted to JSON. The idea is that if you’re implementing a library class (say OkHttp’s Request) it can define it’s own JSON form without a compile-time dependency on Moshi. If this works I’ll talk to Tatu (Jackson) and Inder/Joel (gson) to try to make it a universally-supported pattern.

**Comment by inder123** [comment]
Shouldn't the returned object be String?

**Comment by swankjesse** [comment]
This returns an object that can be converted to JSON, not a JSON object itself. Example:

```
class Point {
  double x;
  double y;

  public Object toJson() {
    return Arrays.asList(x, y);
  }
  public static Object fromJson(Object json) {
    List list = (List) json;
    return new Point((Double) list.get(0), (Double) list.get(1));
  }
}
```

**Comment by inder123** [comment]
and what is the advantage of that over returning a String?

**Comment by swankjesse** [comment]
The advantage is in how the data looks in the finished JSON document. Imagine we have this:

```
  {
    "path": [[1,2],[3,4],[3,2],[1,4]]
  }
```

You could marshall this with this code, without registering any type adapters:

```
  class Shape {
    List<Point> path;
  }
```

**Comment by iNoles** [comment]
even 
```java
class Shape {
    Point[] path;
}
```
?

**Comment by swankjesse** [comment]
Yup; that too.

**Comment by inder123** [comment]
I am dense, need more explanation. How is the same not achieved if toJson() returned a String instead.

**Comment by inder123** [comment]
toJson() is meant to customize JSON output to be different from the default representation based on the fields. I presume you meant that Shape class would not need to define toJson() because List<Point> and Point[] will automatically get serialized correctly. Well, that is no different from the default behavior based on fields.

**Comment by pforhan** [comment]
Maybe the names could be a bit clearer?  I don't have a good recommendation, though.

**Comment by swankjesse** [comment]
It’s in, and the final version looks a lot like `@Provider` methods.

```
  static class PointAsListOfIntegersJsonAdapter {
    @ToJson List<Integer> pointToJson(Point point) {
      return Arrays.asList(point.x, point.y);
    }

    @FromJson Point pointFromJson(List<Integer> o) throws Exception {
      if (o.size() != 2) throw new Exception("Expected 2 elements but was " + o);
      return new Point(o.get(0), o.get(1));
    }
  }
```

**Comment by johnjohndoe** [comment]
@swankjesse Thanks for sharing the adapter snippet!
