### ISSUE TITLE
Deserializing to an object implementing List fails.

### ISSUE THREAD

**Issue by saiimons** [square/moshi#294]
When trying to serialize to :
```java
public class MyListOfStuff extends ArrayList<Stuff> {
// Not even members, just a few methods
}
```
Gives me a JsonDataException with the following reason : com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $

Though when using the documented example, it works. Drawback is I have to create MyListOfStuff with the received list instead of getting it directly.

**Comment by swankjesse** [comment]
Yep. I recommend writing a `@ToJson` adapter for this.

**Comment by saiimons** [comment]
Too bad, this works out of the box with Gson :(

**Comment by JakeWharton** [comment]
Yep. That's why we fixed the bug in Moshi. It's unclear as to whether that
should be serialized as an object or a list.
