### ISSUE TITLE
Date not being mapped

### ISSUE THREAD

**Issue by ppamorim** [square/moshi#310]
I migrated from `1.4.0` to `1.5.0` and now the date of my model is not being mapped. I did this simple test for you:

```kotlin
open class Model(var created: Date? = null)

fun mapDateCredential() {

  val json = "{\"anotherData\":\"Data0\",\"created\":\"2017-05-18T14:32:42.000Z\"}"

  val result = Moshi.Builder()
      .add(Date::class.java, Rfc3339DateJsonAdapter())
      .build()
      .adapter(Model::class.java)
      .fromJson(json)

  println("result $result") //not null
  println("result.created ${result?.created}") //<-- Return null

}
```

Any idea?

Edit 1:

There's no difference if I set `Date?` or `Date? = null`.

Thank you.

**Comment by swankjesse** [comment]
Don’t forget the `KotlinJsonAdapterFactory()` which is in the optional `moshi-kotlin` extension.
```
  val moshi = Moshi.Builder()
      .add(KotlinJsonAdapterFactory())
      .add(Date::class.java, Rfc3339DateJsonAdapter().nullSafe())
      .build()
```

**Comment by ppamorim** [comment]
Would be amazing to include it on README.

**Comment by swankjesse** [comment]
Yeah, good idea.

**Comment by PaulWoitaschek** [comment]
What is the reason that it does not work any longer without the kotlin adapter? In 1.4.0 it was working fine. I can't add the kotlin adapter as the reflect library is so huge I'd hit the 64k dex method even with proguard enabled.

**Comment by ppamorim** [comment]
Now `KotlinJsonAdapterFactory` is stopping my code, the process stops during the `Moshi` building, doing this: `val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()`. The model that uses this `Moshi` instance is completed mapped. Any idea?

**Comment by ppamorim** [comment]
It also is happening with a String field. If I add `KotlinJsonAdapterFactory` it works, but if I remove it, it starts mapping null in a non null field. Very annoying. :(

**Comment by NightlyNexus** [comment]
@ppamorim Can you post a test case to demonstrate the problem when adding the KotlinJsonAdapterFactory?

**Comment by NightlyNexus** [comment]
I ran exactly (without the KotlinJsonAdapter) the `mapDateCredential` function above on Moshi 1.5.0 and moshi-adapter 1.5.0 and did not get null like the original comment says.

This seems to be an issue about broken functionality between 1.4.0 and 1.5.0, but I can't reproduce this.

If anybody can make a test, I'll take a look!
