### ISSUE TITLE
Feature Request: Apply kotlin sealed class adapter to its children

### ISSUE THREAD

**Issue by consp1racy** [square/moshi#311]
Consider the following hierarchy:

    sealed class Credit {
        object Infinite : Credit
        data class Discrete(val value: Int) : Credit
    }

I registered an adapter for type `Credit` and put a property of type `Credit.Discrete` in the model.

### Actual result

Adapter for type `Credit` was not used throwing `expected OBJECT but was NUMBER` exception.

### Expected result

Adapter for parent sealed class would be used.

### Feature request

Would it make sense that an adapter registered for a sealed class would be used for said class' children (unless a more specific adapter is registered as well)?

**Comment by swankjesse** [comment]
What would the encoded JSON look like? Particularly if fields aren’t sufficient:

```
sealed class Pet {
  data class Dog(val name: String) : Pet
  data class Cat(val name: String) : Pet
}
```

**Comment by consp1racy** [comment]
JSON wouldn't be affected. The idea was that I could use

    @FromJson
    fun fromJson(value: Int): Credit = Credit.fromScalar(value)

for deserializing `Credit.Discrete` instead of having to explicitly define e.g.

    @FromJson
    fun fromJsonDiscrete(value: Int): Credit.Discrete = 
        Credit.fromScalar(value) as Credit.Discrete
        // or Credit.Discrete(value)

but now I see that `fromJson(Int): Credit` is not guaranteed to return the right type (`Credit.Discrete` in this case).

Withdrawing this request, sorry to bother you.
