### ISSUE TITLE
Moshi Adapter and Proguard

### ISSUE THREAD

**Issue by mirono** [square/moshi#313]
We wrote an adapter that maps the same class to itself (i.e. String -> String):

_File: MultiLineString.java_
```
@JsonQualifier
@Retention(RetentionPolicy.RUNTIME)
public @interface MultilineString {}
```

_File: MultiStringAdpater.java_
```
public class MultilineStringAdapter {
    private static final Pattern TO_PATTERN = Pattern.compile("\n", Pattern.LITERAL);
    private static final Pattern FROM_PATTERN = Pattern.compile("~~~", Pattern.LITERAL);

    @Nullable
    @ToJson String toJson(@MultilineString String value) {
        if(Strings.isNullOrEmpty(value)) {
            return "";
        }
        return TO_PATTERN.matcher(value).replaceAll("~~~");
    }

    @Nullable
    @FromJson @MultilineString String fromJson(String value) {
        if(Strings.isNullOrEmpty(value)) {
            return "";
        }
        return FROM_PATTERN.matcher(value).replaceAll("\n");
    }
}
```
Everything worked fine in dev builds. On production we were getting StackOverflow exception in: 
```
java.lang.StackOverflowError: stack size 1038KB
     at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(Unknown Source)
     at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(Unknown Source)
     at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Unknown Source)
     at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(Unknown Source)
...
```
It seems the adapters factory initialization is running into an endless loop. Being only in production we suspected Proguard. We tried several options but the one that worked was:
```
@Keep
@JsonQualifier
@Retention(RetentionPolicy.RUNTIME)
public @interface MultilineString {}
```
We suspect the Proguard removed the attribute @Retention(RetensionPolicy.RUNTIME) causing the the run-time infinite mapping of this adapter to itself.

Maybe adding some documentaion regarding the recommended Proguard setting would help?

Miron

**Comment by OleksandrKucherenko** [comment]
```
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
```

**Comment by mirono** [comment]
This is not enough as the annotation for the interface is removed by proguard, thus it is not retained and Moshi will not find the adapter at run time. The documentation should state the the interface should be annotated with @Keep

**Comment by NightlyNexus** [comment]
@mirono Is this what you want? (Sorry, I'm not a ProGuard user.)
`-keep @com.squareup.moshi.JsonQualifier interface *`

**Comment by vanniktech** [comment]
This does the job:

```
# Moshi
-keepclassmembers class ** {
  @com.squareup.moshi.FromJson *;
  @com.squareup.moshi.ToJson *;
}
```

**Comment by mirono** [comment]
@NightlyNexys that might do the trick - I need to check.
@vanniktech  this will not help, because if the annotation is removed by proguard, even if the FromJson/ToJson are there - they are not annotated and the conflict could cause problems.
For example adapter 1 - the "regular" Moshi String adapter. Adapter 2 - another Moshi String adapter:
```
Adapter1 {
    @ToJson String toJson(String value)
    @FromJson String fromJson(String value)
}

Adapter2 {
    @ToJson String toJson(@MultilineString String value)
    @FromJson @MultilineString String fromJson(String value)
}
```
If the annotation ```@MultiString``` is stripped by proguard - you end up with 2 adapters for String. Moshi will then run into an endless loop in run-time (this was our case). The problem here is not retaining the adapter functions -  BUT RETAINING THEIR ANNOTATIONS!

**Comment by vanniktech** [comment]
Well you can tell proguard to keep your custom annotations. I don't use those hence the configuration above works.

**Comment by OleksandrKucherenko** [comment]
I solve the issue by start using @Keep annotation from proguard-annotations library.

i add @Keep to our own annotations, and to all adapter methods.

**Comment by NightlyNexus** [comment]
The above PR resolved this. Check here for the documented configuration: https://github.com/square/moshi#proguard
Feel free to open a new issue or send a PR if something there isn't up to date!
