### ISSUE TITLE
Cannot parse lists in Android. 

### ISSUE THREAD

**Issue by arose13** [square/moshi#317]
I'm using retrofit2 on Android and very simply put this is my error. 
```
 com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
```

This is what the object looks like.
```
[
  {
    "name":  "CYYZ",
    "stats": {
      "alpha_site": 3.02694942012802,
      "bravo_site": 2.1345854614700666,
      "charlie_site": 2.523820208346396
    },
    "timestamp": "29-05-2017"
  },
  {
    "name": "REFF",
    "stats": {
      "alpha_site": 3.194241145373508,
      "bravo_site": 3.805304445772527,
      "charlie_site": 1.2301857417188184
    },
    "timestamp": "27-05-2017"
  }
]
```

interface for the API looks like this (in kotlin)
```
interface API {
        @POST("/basic")
        fun basicResponseCall(@Body call: BasicCall): Call<List<BasicSummary>>
    }
```

POJO looks like this  (again in kotlin)
```
data class BasicSummary(val name: String, val timestamp: String, val stats: StatsObject)
```

Is there something obvious I'm missing or is this a bug because anything that isn't using a `List` works.

**Comment by JakeWharton** [comment]
Your API is returning a top-level object and not an array. Use the OkHttp
logging interceptor or Charles proxy to inspect the actual response,
because it's not what you posted.

**Comment by arose13** [comment]
OkHttp logging was the key to debugging it thank you very much. I bow to the Android god!
