### ISSUE TITLE
@Json can target a method but is never used this way

### ISSUE THREAD

**Issue by saiimons** [square/moshi#319]
The ```@Json``` Annotation allows a method to be annotated.

Though it does not serialize the result of the call, because the ```ClassJsonAdapter``` only takes care of fields.

This would be an awesome feature to really consider the annotated methods :

- for custom serialization without the need for an adapter (pretty straightforward)
- for custom deserialization, for example on a void method taking a single parameter

If this was not intended to be used on methods, is there a reason for having methods as targets in this annotation ?

**Comment by JakeWharton** [comment]
For use with auto-value-moshi.

**Comment by NightlyNexus** [comment]
Yep, and Jesse added this to the doc: https://github.com/square/moshi/blob/76f50df2ccb59c72c647bfa5feea953ccf457be8/moshi/src/main/java/com/squareup/moshi/Json.java#L36
