### ISSUE TITLE
Deserialize json depending on field value

### ISSUE THREAD

**Issue by marc97** [square/moshi#325]
Hi,

I need to deserialize json to a specific class depending on a field value but I can't found any documentation about how to do it.  

In my case I have this json response: 

```
{
  "data": [
    {
      "id": "",
      "type": "new_follower",
      "createdAt": 124342323425,
      "read": false,
      "content": {
        "followedByViewer": true,
        "follower": {
          "id": "",
          "profilePicUrl": "",
          "username": "marc97",
          "name": "Marc Pacheco Garcia"
        }
      }
    },
    {
      "id": "",
      "type": "product_price_down",
      "createdAt": 124342323425,
      "read": false,
      "content": {
        "user": {
          "id": "",
          "profilePicUrl": "",
          "username": "marc97",
          "name": "Marc Pacheco Garcia"
        },
        "product": {
          "id": "",
          "title": "One Plus 5",
          "pricing": {
            "amount": 560,
            "currencyCode": "EUR"
          }
        }
      }
  ],
  "paging": {
    "after": ""
  }
}
```

What I need is deserialize the `content` depending of the `type` field.
Thanks!

**Comment by NightlyNexus** [comment]
You'll want to use `JsonReader.readJsonValue` in a custom JsonAdapter. https://github.com/square/moshi/pull/264/files is an example of the general idea.

You'll read in the map, find the value of `type`, and delegate the map value of `content` to the correct JsonAdapter's `fromJsonValue`.

**Comment by marc97** [comment]
@NightlyNexus Thank you so much! I'm going to use your `RuntimeJsonAdapterFactory` class.

Apart from that, could something like this work?

```java
@FromJson
Content fromJson(Map<String, Object> map) {
    Moshi moshi = new Moshi.Builder().build();

    final String type = ((String) map.get("type"));
    final Object content = map.get("content");

    switch (type) {
        case "new_follower":
        default:
            return moshi.adapter(NewFollower.class).fromJsonValue(content);
    }
}

```
I've also noticed that both annotations `@ToJson` and `@FromJson` must be declared, but I don't understand why is that mandatory if I in some cases (for example in my case) is useless.

**Comment by NightlyNexus** [comment]
Don't make new Moshi instances. You'll then be creating new adapters every single time `fromJson` is called. You can add delegate adapters to your `fromJson` method parameters.

I can't think of a reason this kind of adapter wouldn't work.
I would use something like this (untested) thing:
```java
@FromJson Content fromJson(JsonReader reader, JsonAdapter<NewFollower> newFollowerAdapter) {
  @SuppressLint("unchecked") Map<String, Object> value = (Map<String, Object>) reader.readJsonValue();
  // TODO: Deserialize.
}
```

As for why `@ToJson` must be included, a `JsonAdapter` is created internally, so would you rather the created `JsonAdapter.toJson` implementation throw an UnsupportedOperationException there? That might be too surprising to do implicitly. You can simply add an `@ToJson` method that throws the UOE to your adapter object.

**Comment by marc97** [comment]
@NightlyNexus A concise and clear answer. Thank you for your attention, you have saved me a lot of time.
