### ISSUE TITLE
Moshi jsonValue performance

### ISSUE THREAD

**Issue by AlexFrost** [square/moshi#326]
I read than moshi is faster than gson https://www.reddit.com/r/androiddev/comments/684flw/why_use_moshi_over_gson/dgvm35v/ and try to test it for my case

I have to load and parse json config for lib. Test code is here https://github.com/AlexFrost/TestMoshi/blob/master/app/src/test/java/frost/alex/testmoshi/ConfigCreatorTest.java I used JsonObject for gson and readJsonValue and Map Adapter for moshi

I have runned test and get average time 
gson ~3ms
moshi readJsonValue ~16ms
moshi map adapter ~ 2ms

but when I was commenting  readJsonValue test I have
gson ~3ms
moshi map adapter ~ 16ms so maybe okio cache something... but I read config once, so cache doesn't help me

I have runned same tests on android device and get
gson ~2ms
moshi readJsonValue  ~3ms (map adapter test commented)
moshi map adapter ~4ms (read json value test commented)

It is better result but maybe I used moshi in wrong way. How can I get same performance as for gson  JsonObject?
Thanks

**Comment by swankjesse** [comment]
Tough to say. If you’d like to use a sampling profiler you might be able to find a performance problem that is slowing Moshi down for your particular dataset. It’s quite surprising to me that readJsonValue and the map adapter are so different in performance; the code they execute is quite similar.

If you can figure out the place Moshi is slow, please let me know. No further action for us is planned here.
