### ISSUE TITLE
Default value in kotlin's data class

### ISSUE THREAD

**Issue by prithvibhola** [square/moshi#334]
Moshi doesn't seem to be using default value of data class when parsing JSON

    data class OrderItems(
            @Json(name = "id") val id: String,
            @Json(name = "name") val name: String,
            @Json(name = "rack") val rack: String,
            @Json(name = "quantity") val quantity: Int = 0,
            @Json(name = "pack_size") val packSize: Int = 5,
            @Json(name = "sku") val sku: String,
            @Json(name = "mrp") val mrp: Double,
            @Json(name = "tax") val tax: Double?,
            @Json(name = "discount_percentage") val discountPercentage: Double?,
            @Json(name = "classification") val classification: String?,
            @Json(name = "created_at") val createdAt: Long,
            @Json(name = "updated_at") val updatedAt: Long,
            @Json(name = "sale_price") val salePrice: Double?,
            @Json(name = "type") val type: String?,
            @Json(name = "storage") val storage: String?
    )

JSON:

	{
		"id": 11,
		"order_id": 3,
		"order_item_id": 214478,
		"status": "NEW",
		"state": "NEW",
		"sku": "253909",
		"name": "GLIMISAVE MV 2.3 TAB",
		"sale_price": 116.025,
		"mrp": 136.5,
		"tax": 0.0,
		"discount_percentage": 20.475,
		"created_at": 1498684362000,
		"updated_at": 1500554729000,
		"created_by": "",
		"updated_by": ""
	}

I get an error

> com.squareup.moshi.JsonDataException: Expected an int but was NULL at path $.payload[0].order_items[0].quantity

**Comment by swankjesse** [comment]
I couldn’t reproduce this.

```
  @Test fun dataClass() {
    val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
    val jsonAdapter = moshi.adapter(OrderItems::class.java)

    val decoded = jsonAdapter.fromJson("""
        |{
        |	"id": 11,
        |	"order_id": 3,
        |	"order_item_id": 214478,
        |	"status": "NEW",
        |	"state": "NEW",
        |	"sku": "253909",
        |	"name": "GLIMISAVE MV 2.3 TAB",
        |	"sale_price": 116.025,
        |	"mrp": 136.5,
        |	"tax": 0.0,
        |	"discount_percentage": 20.475,
        |	"created_at": 1498684362000,
        |	"updated_at": 1500554729000,
        |	"created_by": "",
        |	"updated_by": "",
        |	"rack": ""
        |}
        |""".trimMargin())!!
    assertThat(decoded.quantity).isEqualTo(0)
  }

  data class OrderItems(
      @Json(name = "id") val id: String,
      @Json(name = "name") val name: String,
      @Json(name = "rack") val rack: String,
      @Json(name = "quantity") val quantity: Int = 0,
      @Json(name = "pack_size") val packSize: Int = 5,
      @Json(name = "sku") val sku: String,
      @Json(name = "mrp") val mrp: Double,
      @Json(name = "tax") val tax: Double?,
      @Json(name = "discount_percentage") val discountPercentage: Double?,
      @Json(name = "classification") val classification: String?,
      @Json(name = "created_at") val createdAt: Long,
      @Json(name = "updated_at") val updatedAt: Long,
      @Json(name = "sale_price") val salePrice: Double?,
      @Json(name = "type") val type: String?,
      @Json(name = "storage") val storage: String?
  )
```

**Comment by swankjesse** [comment]
(I did add the `"rack"` property, which is required but absent.)

**Comment by sourabhv** [comment]
I am facing the same issue `com.squareup.moshi.JsonDataException: Required value foo missing at $.bar.content[0].baz[1]`

I am using `moshi-kotlin:1.5.0` and retrofit version `2.3.0`

Dagger module which provides moshi:

```
@Provides
@Singleton
fun providesMoshi(): Moshi {
    return Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
}

@Provides
@Singleton
fun provideRetrofit(okHttpClient: OkHttpClient, moshi: Moshi): Retrofit {
    return Retrofit.Builder()
            .baseUrl(Constants.apiUrl)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .build()
}
```
The item foo is `List<String>` and has default value `listof()`

**Comment by NightlyNexus** [comment]
@sourabhv Can you make a failing test case? It's hard to know what could be wrong without seeing your JSON and your Kotlin model.

**Comment by linghp** [comment]
I encounter the same problem.add ? after the variate,resolved

**Comment by blackberry2016** [comment]
How to deal with absent properties in kotlin data class?
