### ISSUE TITLE
Sealed classes don't convert to JSON properly

### ISSUE THREAD

**Issue by joshafeinberg** [square/moshi#343]
Parent fields are not converted into json in a sealed class

    sealed class ParentClass(val parentField: String) {
        class ChildClass(val childField: String) : ParentClass("This is the parent field")
    }

And Tests

    @Test fun testSealedClass() {
        val moshi = Moshi.Builder()
                .add(KotlinJsonAdapterFactory())
                .build()

        val adapter = moshi.adapter(ParentClass.ChildClass::class.java)

        val childClass = ParentClass.ChildClass("This is inside a child")

        val moshiJson = adapter.toJson(childClass)

        // this passes
        val badJson = "{\"childField\":\"This is inside a child\"}"
        assertThat(moshiJson, IsEqual(badJson))

        // this fails
        val expectedJson = "{\"parentField\":\"This is the parent field\", \"childField\":\"This is inside a child\"}"
        assertThat(moshiJson, IsEqual(expectedJson))
    }

**Comment by JakeWharton** [comment]
This is by design. Adapters are not polymorphic–they serialize on the explicit type and its hierarchy that you asked for. We should probably add an easy means of achieving polymorphic serialization (deserialization is harder).

**Comment by joshafeinberg** [comment]
So should I change this to an enhancement? Currently I'm just using an adapter to hand make this json response

**Comment by JakeWharton** [comment]
It's something like this:
```java
public final class PolymorphicAdapterFactory implements JsonAdapter.Factory {
  private final Class<?> target;

  public PolymorphicAdapterFactory(Class<?> target) {
    this.target = target;
  }

  @Nullable @Override
  public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, final Moshi moshi) {
    if (!target.equals(type)) {
      return null;
    }
    final JsonAdapter<Object> delegate = moshi.nextAdapter(this, target, annotations);
    return new JsonAdapter<Object>() {
      @Nullable @Override public Object fromJson(JsonReader reader) throws IOException {
        return delegate.fromJson(reader);
      }

      @Override public void toJson(JsonWriter writer, @Nullable Object value) throws IOException {
        if (value == null) {
          writer.nullValue();
          return;
        }
        Class<?> runtimeType = value.getClass();
        if (target.equals(runtimeType)) {
          // Avoid infinite recursion if you serialize 'target' directly.
          delegate.toJson(writer, value);
        } else {
          // Perform runtime lookup of the adapter for the actual class for 'value'.
          moshi.<Object>adapter(runtimeType).toJson(writer, value);
        }
      }
    };
  }
}
```
(note: i didn't test this)

**Comment by NightlyNexus** [comment]
This may be surprising behavior because the Java ClassJsonAdapter serializes supertypes' fields but the KotlinJsonAdapter does not look at the super class.

This seems like something the KotlinJsonAdapter should support; Jesse or Jake will have better opinions here.

the workaround would be redefining your constructor :/
```kotlin
sealed class ParentClass(val parentField: String) {
  class ChildClass(parentField: String = "This is the parent field", val childField: String) : ParentClass(parentField)
}
```

**Comment by NightlyNexus** [comment]
oh, wait, sorry. i just looked at this again.

This is expected behavior.
The property is a `val`, read-only and has no way to be set by deserializing. If it should be a `var` if it should be set.

This is the same behavior as class `Foo { val a = "hello" }` (a won't be serialized or deserialized) and not specific to subclasses, sealed classes, or polymorphism.
