### ISSUE TITLE
Expected a boolean but was STRING ("true" or "false")

### ISSUE THREAD

**Issue by jcaracciolo** [square/moshi#344]
Some APIs are bad implemented or old and instead of sending true or false, they send "true" or "false". I ve seen in other desearalizers accept "true" and "false" as a valid option for a Boolean. 

Maybe this is something to take into consideration for future, or maybe not and it should be noted why.

**Comment by JakeWharton** [comment]
You can write a delegating adapter that does this yourself.

```java
final class LenientBooleanAdapter extends JsonAdapter<Boolean> {
  @Override
  public Boolean fromJson(JsonReader reader) throws IOException {
    return reader.peek() == JsonReader.Token.STRING
        ? Boolean.parseBoolean(reader.nextString())
        : reader.nextBoolean();
  }

  @Override
  public void toJson(JsonWriter writer, @Nullable Boolean value) throws IOException {
    writer.value(value);
  }
}

public final class Example {
  static class Test {
    boolean broken;
  }

  public static void main(String[] args) throws IOException {
    String brokenJson = "{\"broken\":\"true\"}";
    Moshi moshi = new Moshi.Builder()
        .add(boolean.class, new LenientBooleanAdapter())
        .build();
    Test test = moshi.adapter(Test.class).fromJson(brokenJson);
    System.out.println("Allow broken? " + test.broken);
  }
}
```

Moshi is a nice reset from libraries like Gson where a bunch of legacy and lenient behavior has been accrued so we don't intend to be lenient by default, but rather empower you to customize Moshi to be lenient where needed.
