### ISSUE TITLE
@JsonFormat(shape=JsonFormat.Shape.ARRAY) support in moshi

### ISSUE THREAD

**Issue by lfarkas** [square/moshi#357]
In jackson one can write:
```
@JsonPropertyOrder({"x", "y"})
public class Point {
  public int x, y;
}
```
by adding annotation
```
@JsonFormat(shape=JsonFormat.Shape.ARRAY)
```
and get serialization like:
```
[12,35]
```
instead of
```
{ "x":12,"y":35}
```

How can I do same with moshi? 
Is it possible to add this feature to moshi?
Thanks in advance.

**Comment by swankjesse** [comment]
You’ll need to use `@ToJson` and `@FromJson` to do this.

**Comment by lfarkas** [comment]
OK but I wouldn't like to do it all the time...that's the reason why there is an annotation for this. eg I've got a few such class where I'd like this behaviour. Is there any way to write a common adapter, base class, annotation etc which can i use for all of my such class?

**Comment by swankjesse** [comment]
Definitely. Take a look at JsonAdapter.Factory.
http://square.github.io/moshi/1.x/moshi/com/squareup/moshi/JsonAdapter.Factory.html

It can be used to implement `@JsonPropertyOrder` completely in your own code.

**Comment by lfarkas** [comment]
is there any such example? wouldn't be useful add such to moshi (at least those which are in jackson) at least JsonFormat and JsonPropertyOrder or something like this eg:
```
@JsonFormat(shape=JsonFormat.Shape.ARRAY)
@JsonPropertyOrder({"x", "y"})
```
since these 2 line used to used together may one adapter or something would be useful.

**Comment by swankjesse** [comment]
Here's one example. The factory lets you inspect each type, and return a JsonAdapter for the types you want to support.

You'd need to look over all of the fields to get delegate adapters, then return an adapter that calls them in sequence to build an array.

https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/Unwrap.java

**Comment by NightlyNexus** [comment]
>I wouldn't like to do it all the time...that's the reason why there is an annotation for this

Moshi uses JsonQualifier annotations to differ behavior within the same Java types.
You can add a `@Retention(RUNTIME) @JsonQualifier @interface JsonArray {}`.

Combined with JsonAdapter.Factory, JsonQualifiers should let you implement what you want here.
Feel free to post on StackOverflow with the `moshi` tag if you still need help after the example above.
