### ISSUE TITLE
Normal Kotlin Classes not working properly as data models when using  KotlinJsonAdapterFactory()

### ISSUE THREAD

**Issue by droidluv** [square/moshi#365]
This issue originally was [asked](https://stackoverflow.com/questions/46634793/getting-class-not-found-exception-when-using-kotlinjsonadapterfactory-in-moshi) in SO, I am just copy pasting it here now, with some more addditional info

The problem I'm facing is a little strange because when I have a normal model class which I use as a responsebody model for retrofit 2 I get some unexpected error, suppose

open class Example : RealmObject(){
    @Json(name = "token")
    var token: String? = null
    @Json(name = "data")
    var data: RealmList<Data>? = null
}
and Data class is

open class Data : RealmObject(){
    @Json(name = "info")
    var info: String? = null
}
My code crashes showing a ClassNotFoundException, in this case it would say Data class not found **(I'm running in debug mode, and proguard is not enabled for debug builds)**, and if I remove KotlinJsonAdapterFactory() the crash doesn't happen, but data value becomes absent, ie in debug mode it appear's as if it doesn't exist, ie an object of Example will show only token value, data doesn't exist not even as null, but I need the KotlinJsonAdapterFactory() because I use annonations so the above was just an experiment.

The only solution I found is **convert both classes to data classes and it works perfectly(ofcourse I've to remove the RealmObject extension and make RealmList a normal list)** (why?), but I need to extend RealmObject() class and data classes cannot be open which is needed by Realm db for the model.

So I reverted back to 1.4 removed the KotlinJsonAdapterFactory(), and everything works, even after proguard it seems, so what should I do to upgrade to Moshi 1.5.

Further info: For my release builds I am using proguard and it has been configured as per the documentation, but I am not going to the release part yet as the issue is happening in the debug builds without proguard, so finally my question is there no way for me to use a normal class with moshi 1.5? 

Also I have updated something in my example code the data object is a RealmList and probably why it was ignored/not there when the response came was possibly because my RealmListAdapter for Moshi was ignored???

I'll attach snippets of my moshi and retrofit instances

Moshi.Builder()
                .add(KotlinJsonAdapterFactory())
                .add(RealmListAdapter.FACTORY)
                .build()

//====Retrofit====

Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(MoshiConverterFactory.create(moshi))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(okHttpClient)
                .build()

I

**Comment by NightlyNexus** [comment]
Thanks for the info.
If you can make a minimum failing test case, I can take a look sooner, or else maybe someone else can figure out what's happening there.

**Comment by NightlyNexus** [comment]
Sorry for the delay.

1. Can you share your code for your `RealmListAdapter`?

2. You mentioned your code works on 1.4.0. Without using the KotlinJsonAdapter, does 1.5.0 still work?

**Comment by droidluv** [comment]
Oh wow I completely forgot about this thing, until I saw my email today, and to answer your question nope 1.5.0 doesn't work, it works perfectly in 1.4.0 though, my RealmListAdapter class is like below

    class RealmListAdapter<T : RealmModel>(
        val elementAdapter: JsonAdapter<T>) : JsonAdapter<RealmList<T>>() {

    companion object {

        val FACTORY: Factory = Factory { type, _, moshi ->
            val rawType: Class<*> = Types.getRawType(type)

            if (rawType == RealmList::class.java) {
                val elementType = Types.collectionElementType(type, RealmList::class.java)
                val elementAdapter = moshi.adapter<RealmModel>(elementType)
                return@Factory RealmListAdapter(elementAdapter).nullSafe()
            }
            null
        }
    }

    override fun fromJson(reader: JsonReader): RealmList<T> {

        val result = RealmList<T>()
        reader.beginArray()
        while (reader.hasNext()) {
            result.add(elementAdapter.fromJson(reader))
        }
        reader.endArray()
        return result
    }

    override fun toJson(writer: JsonWriter?, value: RealmList<T>?) {
        if(writer != null && value!=null) {
            writer.beginArray()
            for (element in value) {
                elementAdapter.toJson(writer, element)
            }
            writer.endArray()
        }
    }
    }

**Comment by NightlyNexus** [comment]
Thanks. You mentioned you're getting a ClassNotFoundException.
Sorry, I forgot to ask for a stack trace.
Can you post the stack trace?

**Comment by droidluv** [comment]
I can't give you the stacktrace now because the server is down for that particular project and it's been like that for a while now, but the issue was that it was not able to see Data or whatever class acted as a Data class, its exactly how I mentioned if I removed KotlinJsonAdapterFactory() the field just becomes null or as if it doesn't exist.

**Comment by swankjesse** [comment]
Not sure what will happen when you attempt to use a special type like RealmObject with Moshi, but I don’t expect it to work reliably. There’s likely Realm-implementation details in that class, and Moshi may do something bad encoding or decoding those implementation details.

Much simpler to have separate Realm vs. JSON objects. It’s more code, but simpler.
