### ISSUE TITLE
Deserialize field that can have more than 1 type from jsonString

### ISSUE THREAD

**Issue by iad24** [square/moshi#368]
Sample Json:
```

[
	{	
		field : "String here"
	},
	{	
		field : 123.09 // can be double
	}
]


```

How to define the fields in POJO?

```
class SampleModel {

@Json(name = "field")
    var field: Double? = null

    @Json(name = "field")
    var field: Double? = null

}

```

**Comment by serj-lotutovici** [comment]
I saw a similar question on StackOverflow, please refer to [that](https://stackoverflow.com/questions/46725784/gson-or-mosh-field-in-pojo-could-have-2-types-how-to-save-to-any-of-the-fields). This forum is for issues and feature requests.
