### ISSUE TITLE
Java: Deserialize from json to POJO with different structure by annotation

### ISSUE THREAD

**Issue by lmdic** [square/moshi#369]
I has incoming json that I need to deserialize to POJO. I use external lib and it work fine when structure of json and POJO is same:

```
{
    "ogranization": {
        "id": 1,
        "name": "Org name",
        "url": "http://someurl_2.com",
        "address": "Company address",
        "phone": "123456",
        "email": "email@email.com"
    }
}

public class Organization {
  @SerializedName("id") 
  private long id;
  @SerializedName("name") 
  private String name;
  @SerializedName("url") 
  private String url;
  @SerializedName("address") 
  private String address;
  @SerializedName("email") 
  private String email;
  @SerializedName("phone") 
  private String phone;
}
```
OK. It's work fine. But if json has no same structure like POJO like this:

```
{
    "ogranization": {
        "id": 1,
        "name": "Org name",
        "avatar": {
            "reference": {
                "url": "http://someurl.com",
                "width": 536,
                "height": 379
            },
            "average": {
                "url": "http://someurl_2.com",
                "width": 239,
                "height": 169
            }
        },
        "contact": {
            "address": "Company address",
            "phone": "123456",
            "email": "email@email.com"
        }
    }
}

```
I need to write custom deserializator. OK. It's work.

The question is: Is it possible to do deserialize more simple (when POJO and Json has different structure)?

Something like this (path separate by dot):

```
public class Organization {
  @SerializedName("id") 
  private long id;
  @SerializedName("name") 
  private String name;
  @SerializedName("avatar.reference.url") 
  private String url;
  @SerializedName("contact.address") 
  private String address;
  @SerializedName("contact.email") 
  private String email;
  @SerializedName("contact.phone") 
  private String phone;
}
```
Is it possible on Moshi?

**Comment by NightlyNexus** [comment]
You might be looking for custom type adapters. There are examples in the examples directory and in the README.
https://github.com/square/moshi#custom-type-adapters
Make a model that is structured like the JSON, and you can convert it to your flat model in a few lines of code, without your application-layer code needing to know about the conversion.

Feel free to post on StackOverflow with the Moshi tag if you get stuck after reading the examples.

**Comment by lmdic** [comment]
It's not that I need. In **Custom Type Adapters** I need to code some custom logic. But I want' to write any code. Only by annotation.

**Comment by kukuhyoniatmoko** [comment]
Maybe you can use this @lmdic 
[https://github.com/serj-lotutovici/moshi-lazy-adapters](url)

**Comment by serj-lotutovici** [comment]
@lmdic @kukuhyoniatmoko That will not work because moshi parses the data in a read and forget manner to optimize for speed. And even if you could have declared something like this:

```
public class Organization {
    @Json(name = "id") long id;
    @Json(name = "name") String name;
    @Json(name = "avatar") @Wrapped(path = {"reference", "url"})  String url;
    @Json(name = "contact") @Wrapped(path = "address") String address;
    @Json(name = "contact") @Wrapped(path = "email") String email;
    @Json(name = "contact") @Wrapped(path = "phone") String phone;
  }
```

the code would fail on initial adapter creation because you have more than one field with the same JSON name.

I would suggest following Eric's advice, and create a custom adapter, and ask on StackOverflow if you get stuck.
