### ISSUE TITLE
Moshi-Kotlin: @Json is ignored for constructor only parameters

### ISSUE THREAD

**Issue by Syex** [square/moshi#370]
I have a simple Model:
```
class UserProfile(
        @Json(name = "username") val nickname: String?,
        @Json(name = "birthdate") birthdateString: String?
) {
    @Transient
    val birthdate = birthdateString?.let { dateFormat.parse(birthdateString) }
}
```

My JSON looks like
```
{
  "username": "RandomUserName",
  "birthdate": "1987-02-09T02:30:00"
}
```

So basically I need the `birthdateString` only as a constructor parameter and then parse it to a `Date` object `birthdate` with a `DateFormat`.

I wrote a simple test for this:

```
val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()

@Test
fun `parses Json correctly to UserProfile`() {
  val userProfile = moshi.adapter(UserProfile::class.java).fromJson(testJson)
  assert...
}
```

where `testJson` is the JSON from above.

It fails with
```
java.lang.IllegalArgumentException: No property for required constructor parameter #1 birthdateString of fun <init>(kotlin.String?, kotlin.String?): net.test.UserProfile

	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:196)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:62)
```

So apparently it tries to parse the variable name from the JSON. If I change my model to

```
class UserProfile(
        @Json(name = "username") val nickname: String?,
        @Json(name = "birthdate") private val birthdateString: String?
) {
    @Transient
    val birthdate = birthdateString?.let { dateFormat.parse(birthdateString) }
}
```

adding `private val` to `birthdateString`, the test succeeds.

**Comment by NightlyNexus** [comment]
Having a required parameter that's effectively transient is an error. (You've marked the property as transient.)
Transient properties and constructor parameters won't be considered for deserialization or serialization.

You can provide a default value for that constructor parameter.

Maybe Moshi could provide a better error message for this case...

**Comment by NightlyNexus** [comment]
Oh, actually this error message for transient has already been updated.

**Comment by NightlyNexus** [comment]
And, now I see your constructor parameter and property are named differently, so that's a different error, not related to your transient property. Sorry for misspeaking.

This is by design. Without a property of the same name, you can't serialize the same way you deserialized.

**Comment by swankjesse** [comment]
Not sure what action to take here. We could make it so that we read the `val` and write the constructor parameter, but that seems complicated. I think in cases like this the simplest thing is to create a separate object for the JSON form and to map between the types.

**Comment by swankjesse** [comment]
More explicitly, you can create two types: a model type, and a JSON type, and write a Moshi JSON adapter to convert between ’em. This is a little bit more code but it keeps the machinery simple.

```
  class UserProfile(
          val nickname: String?,
          birthdateString: String?
  ) {
    val birthdate = Date(birthdateString)
  }

  data class UserProfileJson(val username: String?, val birthdate: String?)

  object UserProfileAdapter {
    @ToJson fun userProfileToJson(model: UserProfile)
            = UserProfileJson(model.nickname, model.birthdate.toGMTString())

    @FromJson fun userProfileFromJson(json: UserProfileJson)
            = UserProfile(json.username, json.birthdate)
  }

  @Test fun customJsonObject() {
    val moshi = Moshi.Builder()
            .add(UserProfileAdapter)
            .add(KotlinJsonAdapterFactory())
            .build()
    val jsonAdapter = moshi.adapter(UserProfile::class.java)

    val encoded = UserProfile(
            "RandomUserName", "12 Aug 1995 09:00:00 GMT")
    val json = """{"username":"RandomUserName","birthdate":"12 Aug 1995 09:00:00 GMT"}"""

    assertThat(jsonAdapter.toJson(encoded)).isEqualTo(json)
  }
```
