### ISSUE TITLE
Set field naming convention when deserialising 

### ISSUE THREAD

**Issue by iad24** [square/moshi#371]
all my fields in my pojo follows the camelcase naming convention:

val fieldName: String? = null

I have a long list of fields in my pojos. like around 500 fields.

But the json from my php server will return in snake case convention:
"field_name" : "value"

How do I tell the deserialiser to parse like this without using the @Json(name = "field_name") for each field

**Comment by swankjesse** [comment]
We won't be implementing that because I think it's a very bad idea. In particular it breaks grep. Never break grep.
https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/

**Comment by swankjesse** [comment]
If you don't care, you can copy and paste Moshi’s type adapter and do whatever you like. Type adapters are all powerful in Moshi and don't have to listen to even my own advice.

**Comment by iad24** [comment]
Hi @swankjesse. Thanks for the reply. If I follow ur advise to use the type adapter, will I just be doing few codes or less effort to solve my problem? Sorry noob here. Dont know how to apply the type adapter for this situation of mine

**Comment by iad24** [comment]
@swankjesse I read ur article above, you really stressed your point there on why not to support this. I am just thinking on some projects that the developer is really sure that no one will inherit his code. That he will just be one touching them; even in the future. Im just saying you guys could support this and thus make it flexible for any naming convention and just put the risk on the developers who will use it. 
It will be up to us to handle that kind of issue; rather than limiting the power of Moshi.

**Comment by swankjesse** [comment]
This is the file you'll copy and paste into your project that you can use to implement case mapping.
https://github.com/square/moshi/blob/master/kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt

My advice will continue to be that you should just name the Kotlin fields to match the network.
