### ISSUE TITLE
Question: how to write this in Moshi ?

### ISSUE THREAD

**Issue by blackberry2016** [square/moshi#378]
How to write this in Moshi ?
```java
  public static <T> List<T> fromJsonToList(String json, Gson gson) {
    Type typeOfT = new TypeToken<List<T>>() {
    }.getType();
    return gson.fromJson(json, typeOfT);
  }
```

**Comment by JakeWharton** [comment]
That `T` gets erased to `Object` so the equivalent would be `adapter(List.class)`. You probably want something like `Types.newParameterizedType(List.class, TheListItemType.class)` though...

Care you ask this on StackOverflow?

**Comment by blackberry2016** [comment]
@JakeWharton Thanks , it works.
