### ISSUE TITLE
How to serialize / deserialize @Json fields only without using "transient"

### ISSUE THREAD

**Issue by ursusursus** [square/moshi#379]
Hi, I'm a Realm user and transient keyword excludes the field from database and bundles too. I'd like for Moshi to only serialize say @Json annotated fields, as I already do that for every field anyways. 

How would I go about doing that? Thanks

**Comment by NightlyNexus** [comment]
I don't think that'd be an option that Moshi would support. (side note: I tend to like separating out the models for different layers of my projects, as they tend to have different structures.)

That said, it wouldn't be too hard to copy the Java [ClassJsonAdapter](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java) into your project, modify it to that requirement, and install it as the last factory in your Moshi.Builder.

**Comment by ursusursus** [comment]
Oh man .. how about @Transient annotation on a field?

**Comment by NightlyNexus** [comment]
@ursusursus What about it?

**Comment by ursusursus** [comment]
Well, I dont like copy pasting, so maybe I could it around from whitelisting @Json fields to blacklisting @Transient fields (without using java transient as that causes problems in other libraries)

What do you think?

**Comment by NightlyNexus** [comment]
You would still need to modify the ClassJsonAdapter to allow the volatile modifier not to have an effect and to add an effect for your Transient annotation.

**Comment by ursusursus** [comment]
this should be easier to do with moshi imo, same as it uses okio not to create copies of buffers, I should be able to use the same model for json and app

**Comment by silviahisham** [comment]
I second that! I use [objectbox](https://github.com/objectbox/objectbox-java) and same models for json and db. `transient` excludes fields from the database and I don't want that.

**Comment by swankjesse** [comment]
Best advice is separate objects for DB and JSON. No clear action for us to take here.
