### ISSUE TITLE
Failed to deserialise an empty object array

### ISSUE THREAD

**Issue by wenyang9319** [square/moshi#380]
This is the error message shown up: 
> com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.classspace.grp.members.teacher

The expected json returned by the server should be : 
```
{
  "teacher": {
    "123": {
      "_id": "389",
      "name": "test_fast_teacher1"
    }
  }
}
```
However, the array returned by server is empty
```
{
  "teacher": [
    
  ]
}
```
Is this an expected result from Moshi?
Before I switching from Gson, the teacher object will still be deserialised, just that it will be null. By using Moshi, the error would be threw and I can't proceed with the other json which is serialised correctly.

**Comment by NightlyNexus** [comment]
Yes, this is expected in Moshi and sounds like a legacy leniency bug that can't be fixed now in Gson.

If you ask on StackOverflow with the `moshi` tag, somebody can help you work around your broken server response, probably by using a custom JsonAdapter.

**Comment by wenyang9319** [comment]
Alright, thanks for your response, I will be posting this on StackOverFlow

**Comment by CoolMind** [comment]
@wenyang9319, have you gotten a solution?
