### ISSUE TITLE
Should JsonReader.selectString() understand numbers?

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#389]
```java
@Test public void selectStringWithNumbers() throws IOException {
  JsonReader.Options numbers = JsonReader.Options.of("9223372036854775807", "0", "1", "2.0");

  JsonReader reader = newReader("[9223372036854775807, 0, 1, 2.0]");
  reader.beginArray();
  assertThat(reader.selectString(numbers)).isEqualTo(0);
  assertThat(reader.selectString(numbers)).isEqualTo(1);
  assertThat(reader.selectString(numbers)).isEqualTo(2);
  assertThat(reader.selectString(numbers)).isEqualTo(3);
  reader.endArray();
}
```

This test currently fails on a JsonUtf8Reader because the result of `selectString` is -1.
(This test currently fails on a JsonValueReader with the same message as #388.)

Should `selectString` let you do this?

<br/>
Use case:

Right now, if you comment out [this line](https://github.com/square/moshi/blob/b7a91e05576c293053fc042c53e45707c3f5f053/moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java#L615), all the tests pass. :0 (should probably add a test one way or the other.)
Also, if you comment out that line, #263 works (with the utf8 reader).
That is, this passes:
```kotlin
enum class Foo { @Json(name = "1") A }

@Test fun integersAsEnums() {
  val moshi = Moshi.Builder().build()
  val adapter = moshi.adapter(Foo::class.java)
  assertThat(adapter.fromJson("1")!!).isEqualTo(Foo.A)
}
```

**Comment by NightlyNexus** [comment]
that use case isn't great, since toJson will of course still fail.
i'll try to think of a real use case.

**Comment by swankjesse** [comment]
Yeah, I think it’s unlikely to cause a problem in practice. That said, the lack of symmetry sucks.

**Comment by NightlyNexus** [comment]
Added symmetry in #399.

**Comment by NightlyNexus** [comment]
The test in #399 will also fail if [the line](https://github.com/square/moshi/blob/b7a91e05576c293053fc042c53e45707c3f5f053/moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java#L615) mentioned above is commented out.

**Comment by NightlyNexus** [comment]
Closing this in favor of the above!
