### ISSUE TITLE
ParameterizedTypeImpl hashCode is different on device vs unit tests

### ISSUE THREAD

**Issue by kpgalligan** [square/moshi#395]
I'm not sure where this type of comparison will be a concern, but it would fail in certain cases, so here goes.

In com.squareup.moshi.Types, ParameterizedTypeImpl defines hashCode thus:

The Moshi version
https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/Types.java#L539

```java
@Override public int hashCode() {
      return Arrays.hashCode(typeArguments)
          ^ rawType.hashCode()
          ^ hashCodeOrZero(ownerType);
    }
```

Looking at openjdk, we get something very similar:

https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/sun/reflect/generics/reflectiveObjects/ParameterizedTypeImpl.java#L207

```java
@Override
    public int hashCode() {
        return
            Arrays.hashCode(actualTypeArguments) ^
            (ownerType == null ? 0 : ownerType.hashCode() ) ^
            (rawType == null   ? 0 : rawType.hashCode() );
    }
```

libcore, however, does soemthing very different

https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/reflect/ParameterizedTypeImpl.java#93

```java
@Override
  public int hashCode() {
    return 31 * (31 * Objects.hashCode(getRawType()) + Objects.hashCode(getOwnerType())) +
    Arrays.hashCode(args.getResolvedTypes());
  }
```

In summary, this test will pass as a unit test but will fail running on a device. The lines that compare hash codes specifically.

```java
@Test public void newParameterizedTypeObjectMethods() throws Exception {
        Type mapOfStringIntegerType = getClass().getDeclaredField(
                "mapOfStringInteger").getGenericType();
        ParameterizedType newMapType = Types.newParameterizedType(Map.class, String.class, Integer.class);
        assertThat(newMapType).isEqualTo(mapOfStringIntegerType);
        assertThat(newMapType.hashCode()).isEqualTo(mapOfStringIntegerType.hashCode());
        assertThat(newMapType.toString()).isEqualTo(mapOfStringIntegerType.toString());

        Type arrayListOfMapOfStringIntegerType = getClass().getDeclaredField(
                "arrayListOfMapOfStringInteger").getGenericType();
        ParameterizedType newListType = Types.newParameterizedType(ArrayList.class, newMapType);
        assertThat(newListType).isEqualTo(arrayListOfMapOfStringIntegerType);
        assertThat(newListType.hashCode()).isEqualTo(arrayListOfMapOfStringIntegerType.hashCode());
        assertThat(newListType.toString()).isEqualTo(arrayListOfMapOfStringIntegerType.toString());
    }
```

The equals compare works, though.

**Comment by NightlyNexus** [comment]
Correct me if I'm wrong, but it's a known issue that libcore has broken equals/hashCode implementations. (I personally don't know the history and details.)

You should `Types.canonicalize(Type)` these types if they are external inputs.

Also, `canonicalize` standardizes the type of arrays because an array could be represented as either a Class or a GenericArrayType, sadly.

**Comment by kpgalligan** [comment]
canonicalize looks like it would address the test issue. I guess my concern is with the implication of the test, as in would there be a place in the non-test code where this discrepancy might present a problem? I have no idea.

**Comment by NightlyNexus** [comment]
In Moshi, not that I know of: Types passed in by consumers are canonicalized, and `Types.equals` does the right thing in comparison usages.

In other code (if you're copying Types into another library, for example), I guess make sure to do the same. Don't trust java.lang.Types that aren't Classes.

**Comment by kpgalligan** [comment]
If everything passed in is getting canonicalized, I'll just close this as it shouldn't be an issue.

**Comment by swankjesse** [comment]
The way types are modeled really annoys me. Definitely should have been value objects and not interfaces.
