### ISSUE TITLE
Empty json when using `KotlinJsonAdapterFactory`

### ISSUE THREAD

**Issue by holgerbrandl** [square/moshi#396]
Running
```
class Foo() {
    val name = "hi moshi"
    val bar = listOf(1, 2, 3)
}

fun main(args: Array<String>) {

    val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    println(moshi.adapter(Foo::class.java).toJson(Foo()))
}
```
gives an empty empty json (ie.just `{}`) result.

Both
```
compile 'com.squareup.moshi:moshi:1.5.0'
compile 'com.squareup.moshi:moshi-kotlin:1.5.0'
```
are listed in build.gradle.

Interestingly, if the `KotlinJsonAdapterFactory` serialization works correctly.

**Comment by NightlyNexus** [comment]
Working as intended.
Unsettable vals aren't considered for deserialization or serialization in the KotlinJsonAdapter.

How about `class Foo(val name: String = "hi moshi", val bar: List<Int> = listOf(1, 2, 3))`?

For past cases when I've needed extra serialization but didn't want my application code to control it, I separated out the models and hid the "Foo" serializable type from the application-layer code, in case that helps.

**Comment by NightlyNexus** [comment]
to clarify, the properties need to be `var`s or constructor parameters. default constructor parameters seem like a good "workaround" if you'd like to keep the same model.

**Comment by holgerbrandl** [comment]
Thanks for the feedback.

1. The docs under https://github.com/square/moshi#kotlin-support could be more clear. They just state that the `KotlinJsonAdapterFactory` adds annotation support, but do not indicate that the serialization behavior would change when using it.

2. IMHO excluding unsettable vals from serialization does not make sense in many situations. E.g. consider mutable collections:
```
class Foo {
    val name = "hi moshi"
    val bar = listOf<String>().toMutableList()
}

fun main(args: Array<String>) {

    val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    val myFoo = Foo()
    myFoo.bar.addAll(listOf("this", "should", "be", "jsonized"))

    println(moshi.adapter(Foo::class.java).toJson(Foo()))
}
```
Instance of `Foo` clearly have a state that is not constant, but still the json is empty.

Also what about versions flags in data classes which tend to be val-only but should end up the in the json? 
Is there a way to force serialization (e.g. via an annotation, or by configuring the factory accordingly?

**Comment by swankjesse** [comment]
To explain why – in Java Moshi uses reflection to set fields that cannot be set otherwise. In Kotlin Moshi uses constructors and var assignment only. Ie., Kotlin can’ t set anything that can't be set programmatically.

This might be surprising behavior but it has benefits. It’s more testable. It's more encapsulated.

I think we want to document this behavior. We’ll discourage users from using unsettable vals in their Moshi types.

**Comment by holgerbrandl** [comment]
Sorry, but I'm lost now: Without the `KotlinJsonAdapterFactory` serialization of kotlin class instances works just fine including `private val` fields. But when using the factory to allow for some more fine tuning of the de/serialization process via annotations, it breaks completely (at least with respect to my example from above). 

So as reflective access to kotlin class fields is obviously possible and working correctly, it's not used for after enabling annotation support via the factory? 

Is there an alternative way to enable custom annotation-driver adapter support without switching to the kotlin-constructor-fields-only mode?

**Comment by swankjesse** [comment]
Yeah, we can get it all to work with JVM reflection and `setAccessible(true)` My hope was to avoid that for Kotlin.

**Comment by holgerbrandl** [comment]
Looking forward to it! Thanks.

**Comment by swankjesse** [comment]
I might have misspoken. I meant to convey that although we _could_ do it, I would prefer to _not_ support private vals for Kotlin.

It’s pretty much essential for Java but my theory is that Kotlin constructors are sufficiently powerful that we shouldn’t need this.

I should also disclaim that we don’t really intend to have strict compatibility between Kotlin types serialized with `KotlinJsonAdapterFactory` and those serialized without it. The way that Kotlin types get mapped into Java types has lots of subtle implementation details (default values, nulls, etc.) and we’d need to reverse engineer the Kotlin compiler to make that work predictably.

**Comment by swankjesse** [comment]
No further action planned for this. But please continue the discussion; I can be convinced!

**Comment by Tolriq** [comment]
@swankjesse Just lost a tons of time on this :( It would be nice to have something visible in the docs.

I tried to switch from codegen to reflect for debug builds and could not understand why all the things that do not use reflect/codegen were not working as intended after adding the factory but without any clear errors just some what appeared random field no more present both in serialisation / deserialisation.
