### ISSUE TITLE
Unable to parse received html content

### ISSUE THREAD

**Issue by vasimihalca** [square/moshi#415]
Hello, 
All the methods from retrofit are returning json, except one that's returning html
I have added @Headers("Accept: text/html") to that method, the request is performed ok, I can see the response in the logging interceptor that I've set on the OkHttpClient, but I get the following error
`com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $`

Set leninent does not help, since its not a json...
How can I tell moshi that I want just text?

**Comment by JakeWharton** [comment]
Install the [scalars converter](https://github.com/square/retrofit/tree/master/retrofit-converters/scalars) _before_ the moshi converter and use `String` as the body type. A text/plain response should never reach Moshi.
