### ISSUE TITLE
Allow overwriting values in MapJsonAdapter.fromJson

### ISSUE THREAD

**Issue by Shiph** [square/moshi#416]
I have a JSON object like this:
`{"id": "first", "place": "1", "id": "second", "place": "2"}`
which I want to parse as a `Map<String,Any>`.

Is it possible to just overwrite the old keys `id` and `place` with the new values (`second` and `2`) without MapJsonAdapter throwing JsonDataExeption due to duplicate keys?

I know that the JSON structure is weird but I can't change it and it would be nice to be able to continue parsing without exception.

**Comment by JakeWharton** [comment]
You can write a custom `JsonAdapter` to do this which pulls keys and values from a `JsonReader`. I don't think we want to allow this by default as it typically indicates a programming bug on the server.

**Comment by Shiph** [comment]
Thanks for the quick reply. I tried to make a custom `JsonAdapter` but couldn't figure out how to use it instead of the default `MapJsonAdapter`. The faulty JSON object is nested inside two other objects which already use a custom adapter. Maybe I should just ask the data provider to clean the data in the first place :)

**Comment by swankjesse** [comment]
This might help you to get started:
https://gist.github.com/swankjesse/4a3f955bdc4702f634e1fa497e38b835
