### ISSUE TITLE
Create Built-In Adapter for Iterable

### ISSUE THREAD

**Issue by feinstein** [square/moshi#421]
There are already built-in adapters for `Arrays, Collections, Lists, Sets, and Maps`, it would be useful to have one for `Iterable` as well.

**Comment by NightlyNexus** [comment]
I'm not sure there's a vast use case. Do you have details on your use case?
I think Collection and Set are already generous.

**Comment by feinstein** [comment]
I at first thought about creating my `Retrofit` service returning `Iterable<Report>`, since this will better model the REST response. My rationale is that `List` and `Collection` can be altered, but `Iterable` can't `add` or `remove` items, which mirrors an array response from a service. The service returned some data and no one should be altering the data.

I converted to `List` so everything is working right now, I think the work for making a whole `Iterable` adapter doesn't justify the "correctness" of using `Iterable`, since no one will be actually modifying the `List` anyway, it was more for the sake of correctness.

**Comment by swankjesse** [comment]
I don’t think we should support `Iterable` and further, I don’t think you should use Iterable in fields of value objects. The biggest problem with `Iterable` is that it doesn’t promise to be an in-memory model of anything: iterables can be functions (iterable of all integers), or make remote API calls (iterable of search results).

Instead use List or Set, which at least define `equals()`+`hashCode()` semantics. It’s weird and bad to have a JSON model type that doesn’t have these. JSON model objects should be value objects, and value objects should only use value types.

**Comment by feinstein** [comment]
Excellent points, I didn't thought about them. Agreed.
