### ISSUE TITLE
Custom types can't be used for keys for deserializing Maps.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#427]
This doesn't work, even with my adapter to make my type (MapKey) a String.

```java
@Test public void mapWithCustomTypeKey() throws Exception {
  JsonAdapter<Map<MapKey, Integer>> adapter = new Moshi.Builder().add(new Object() {
    @FromJson MapKey fromJson(String json) {
      return new MapKey(json);
    }
  }).build().adapter(Types.newParameterizedType(Map.class, MapKey.class, Integer.class));
  assertThat(adapter.fromJson("{\"a\":1,\"b\":2}")).containsExactly(
      MapEntry.entry(new MapKey("a"), 1), MapEntry.entry(new MapKey("b"), 2));
}
```

`java.lang.ClassCastException: com.squareup.moshi.MapJsonAdapterTest$MapKey is not Comparable` when the MapKey is being put into the LinkedHashTreeMap.

**Comment by swankjesse** [comment]
Making MapKey comparable will fix, but yeah this is weak.

**Comment by swankjesse** [comment]
Forcing map keys to be both hashable and comparable is what makes LinkedHashTreeMap work. Not sure fixes for this will be worth the cost.

**Comment by NightlyNexus** [comment]
Oh, I forgot to close this request. I don't have a need for it anymore, and I agree it's not worth it.

**Comment by ursusursus** [comment]
I ran into this. I create the map in kotlin just fine, serialize it, no problems -- and then it blows up in runtime at next app run on deserialization
