### ISSUE TITLE
moshi.adapter(**.class) too slow

### ISSUE THREAD

**Issue by cuichanghao** [square/moshi#433]
I found moshi.adapter(...) first execute too slow.
taken 0.1~0.2s first time. 
may be reflection?
After the first time will be fast。(cache?)

so my application put all moshi.adapter to application level singleton class.

var map = ....
async{
map["A"] = moshi.adapter(A.class)
map["B"] = moshi.adapter(B.class)
map["C"] = moshi.adapter(C.class)
}

Any suggestions?

**EDIT**
even that class just include one field its also taken 0.2-0.4s in galaxy note3.

**Comment by JakeWharton** [comment]
Moshi is lazy and uses reflection, yes. The cost of first use is only a problem if you initialize on the main thread instead of on a background thread as part of your serialization.

**Comment by cuichanghao** [comment]
OK.

even that class just include one field its also taken 0.2-0.4s in galaxy note3.

In my case read json file from local.
put all adapter load functions to application level  hit performance even work on background.

Any plan?

**Comment by swankjesse** [comment]
Not much we can do. It's not just reflection but also class loading – when you ask Moshi for an adapter it may need to initialize the corresponding classes.

**Comment by cuichanghao** [comment]
thank you
