### ISSUE TITLE
Dealing with one field that is sometimes boolean and sometimes int

### ISSUE THREAD

**Issue by fbis251** [square/moshi#445]
I'm trying to work with the reddit JSON API. There are post data objects that contain a field called `edited` which may contain a boolean `false` if the post hasn't been edited, or a timestamp `int` if the post was edited.

Sometimes a boolean:
```json
{
    "edited": false,
    "title": "Title 1"
}
```

Sometimes an int:
```json
{
    "edited": 1234567890,
    "title": "Title 2"
}
```

When trying to parse the JSON where the POJO has the field set to int, I get an error: `JsonDataException: Expected an int but was BOOLEAN...`

How can I deal with this using Moshi?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'moshi' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.

You should also check out all the samples we have checked into the repository for how to do this with JSON qualifiers.
