### ISSUE TITLE
@Json does not work whereas changing property name works

### ISSUE THREAD

**Issue by dgngulcan** [square/moshi#446]
Hey there, I am not able to parse my Json with Moshi when I define `@Json(name)`. 
Is it an expected behavior?  

#### The way Moshi is implemented
```kotlin
val moshi = Moshi.Builder().build()
val jsonAdapter = moshi.adapter<Route>(Route::class.java)
val route = jsonAdapter.fromJson(it)
```

#### The Json
```json
{
   "sourceLocation": [
        -73.9654327,
        40.7794406
   ]
}
```
#### Parameter is not null after parsing
```kotlin
data class Route(
    var sourceLocation: List<Double>
)
```

#### Parameter is null after parsing
```kotlin   
import com.squareup.moshi.Json

data class Route(
    @Json(name = "sourceLocation")
    var originLocation: List<Double>
)

```

**Comment by JakeWharton** [comment]
You need to target the annotation with `@field:Json`.
```kotlin
fun main(vararg args: String) {
  val moshi = Moshi.Builder().build()
  val adapter = moshi.adapter<Route>(Route::class.java)
  val actual = adapter.fromJson("""
    {
      "sourceLocation": [
        -73.9654327,
        40.7794406
      ]
    }
    """.trimIndent())
  println(actual)
}

data class Route(
    @field:Json(name = "sourceLocation")
    var originLocation: List<Double>
)
```
```
Route(originLocation=[-73.9654327, 40.7794406])
```

**Comment by NightlyNexus** [comment]
Or add the KotlinJsonAdapterFactory from the Kotlin artifact to your Moshi.Builder.

**Comment by nowakweronika** [comment]
> Or add the KotlinJsonAdapterFactory from the Kotlin artifact to your Moshi.Builder.

I have KotlinJsonAdapterFactory in my Moshi.Builder and it still doesn't work. I had to add `@field:Json` instead `@Json`.

**Comment by ShreyashKore** [comment]
Add `@field:Json` makes it work on the release APK but starts breaking on the debug one. I am adding both `@field:Json` and `@Json`.
