### ISSUE TITLE
Document that precedence really matters

### ISSUE THREAD

**Issue by rongi** [square/moshi#455]
KotlinJsonAdapterFactory doesn't work with Custom Type Adapters:

```kotlin
data class EventJson(
  val title: String
)

data class Event(
  val title: String
)

class EventJsonAdapter {
  @FromJson
  fun eventFromJson(eventJson: EventJson): Event {
    return Event(
      title = eventJson.title.toUpperCase()
    )
  }

  @ToJson
  fun eventToJson(event: Event): EventJson {
    return EventJson(
      title = event.title.toLowerCase()
    )
  }
}

private fun test() {
  val moshi = Moshi.Builder()
    .add(KotlinJsonAdapterFactory())
    .add(EventJsonAdapter())
    .build()

  val jsonAdapter = moshi.adapter(Event::class.java)
  val json = """
                {
                  "title": "Blackjack tournament"
                }
             """
  Assert.assertEquals(
    Event(title = "BLACKJACK TOURNAMENT"),
    jsonAdapter.fromJson(json)
  )
}
```

If you change previous example like this:

```kotlin
  val moshi = Moshi.Builder()
    .add(EventJsonAdapter())
    .add(KotlinJsonAdapterFactory())
    .build()
```

Then it works.

It's a nasty issue. It's very hard to find the workaround and it's so easy to break it like that. It's not very nice if every new developer in our project will spend several hours trying to fight this issue.

moshi: 'com.squareup.moshi:moshi:1.5.0',
moshikotlin: 'com.squareup.moshi:moshi-kotlin:1.5.0',

**Comment by swankjesse** [comment]
Yeah, precedence matters. We could improve our docs here.

**Comment by swankjesse** [comment]
The docs are actually pretty clear. From our readme:

> Add it last to allow other installed Kotlin type factories to be used, since factories are called in order.

**Comment by rongi** [comment]
Thank you Jesse. I think this can be further improved by adding a small note about it to the "Custom Type Adapters" section. I've read that section thoroughly when I was trying to solve that. It didn't crossed my mind to read the "Kotlin Support" section again though.

It was hard to find out why this wasn't working. The result was just wrong, no crashes, nothing to google, etc.

**Comment by swankjesse** [comment]
Yeah I can imagine how frustrating that is!

**Comment by luaz** [comment]
I just got hit :(

**Comment by swankjesse** [comment]
Added a note to the Kotlin section of the doc!
