### ISSUE TITLE
Which classes are thread-safe?

### ISSUE THREAD

**Issue by bennoleslie** [square/moshi#468]
Apologies in advance if this is not the right place for this question.

It is not clear form the documentation (and not clear on an quick glance at the source code) which classes are thread-safe.

Can I share a single `Moshi` instance between multiple threads?

What about `JsonAdapter` objects?

**Comment by swankjesse** [comment]
Moshi and JsonAdapter instances are both immutable and safe for concurrent use.

JsonReader and JsonWriter are not safe for concurrent use.

**Comment by onacit** [comment]
It will be much better if property documented.
