### ISSUE TITLE
Bug parsing @Json(name="2")

### ISSUE THREAD

**Issue by Z-13** [square/moshi#470]
```
data class MyDataResponse(
	@Json(name="2")
	val content: MyContent
)
```
This code is working good for version _2.3.0_ and **content = null** if version _2.4.0_!
Why is it so?

**Comment by NightlyNexus** [comment]
Kotlin classes were never officially supported in Moshi until 1.4.0 with the KotlinJsonAdapterFactory.

The target changed on the `@Json` annotation.
You can change to target the field with `@field:Json(name="2")`, use the KotlinJsonAdapterFacoty, or use an adapter generator like Kotshi.

**Comment by Z-13** [comment]
@NightlyNexus thx for answer!
Maybe I misunderstood, 
`"com.squareup.retrofit2:converter-moshi:2.3.0"`

```
data class MyContent(
	@Json(name="data")
	val data: MyDataResponse

	@Json(name="duration")
	val duration: List<Int>
)
...
data class MyDataResponse(
	@Json(name="2")
	val content: MyContent
)
```

If version **2.3.0** is good working:
```
myData.duration = List<Int>
myData.data.content = MyContent()
```


But, if version **2.4.0** then:
```
myData.duration = List<Int>
myData.data.content is NULL
```

I think is that by reason of the number-name(**_@Json(name="2")_**). But I can be wrong.

**Comment by swankjesse** [comment]
Ya gotta follow the advice from @NightlyNexus. Replace `@Json` with `@field:Json` everywhere.

**Comment by NightlyNexus** [comment]
By the way, yes, the reason Retrofit 2.3.0's converter and Retrofit 2.4.0's converter are different is because Retrofit 2.4.0 brought the transitive dependency update to Moshi 1.5.0.
