### ISSUE TITLE
Add an example of using a JsonQualifier that has elements.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#479]
If anybody uses qualifiers like the following, post your use case.
```java
@Retention(RUNTIME)
@JsonQualifier
public @interface MyQualifier {
  String someValueToUse();
}
```
It would be cool to have a sample to add for this use case.

**Comment by vanniktech** [comment]
I'm pretty sure one of the lazy Moshi adapters is using that mechanism. I'm on mobile and can't search properly.

**Comment by NightlyNexus** [comment]
I saw a fallback enum one in there. I like that idea.

**Comment by NightlyNexus** [comment]
#481 for specifying a fallback enum value in the qualifier.
