### ISSUE TITLE
Deserializing extended Kotlin class 

### ISSUE THREAD

**Issue by LukasVykuka** [square/moshi#495]
I'm trying to deserialize this JSON

```
{
  "derived_value": "foo",
  "parent_value": "bar"
}
```
with these classes
```
data class DerivedEntity(
    @Json(name = "derived_value") val derivedValue: String? = null
) : ParentEntity()
```
```
abstract class ParentEntity(
    @Json(name = "parent_value") val parentValue: String? = null
)
```
Result is instance of DerivedEntity class with values set to `derivedValue = "foo"` and `parentValue = null`.
It's possible to have `parentValue` also set to value from JSON?

(I'm able to achieve it by changing `parentValue` to `var` but I feel it's not correct solution.)

**Comment by NightlyNexus** [comment]
Working as intended.
Vals are read-only, so you probably want the parent_value as a constructor parameter or a var.
(Aside: Inheritance with value types is strange, and I'm surprised Kotlin data classes allow this behavior.)

**Comment by LukasVykuka** [comment]
Unfortunately our API send some common parameters in every response so inheritance was natural choice for me. At least `var` is working.

Thanks for answer, I think you can close this issue.

**Comment by SpaceBison** [comment]
@LukasVykuka could you post a code example that worked for you?

**Comment by SpaceBison** [comment]
@LukasVykuka do you use codegen to generate adapters or do you use the reflection-based runtime adapter factory?

**Comment by LukasVykuka** [comment]
@SpaceBison codegen

**Comment by SpaceBison** [comment]
I'm surprised that this worked for you. In my case, for classes such as these:
```
@JsonClass(generateAdapter = true)
class Subclass(@Json(name="subclassPropertyJsonName") val subclassProperty: String? = null) : Superclass()
```
codegen ignored the annotations on `Superclass`. It started working when I specified the annotation target in the constructor:
```
abstract class Superclass(@property:Json(name="superclassPropertyJsonName") var superclassProperty: String? = null)
```
or moved the property to the class' body:
```
abstract class Superclass {
    @Json(name="superclassPropertyJsonName") var superclassProperty: String? = null
}
```

Thanks anyway!

**Comment by LukasVykuka** [comment]
@SpaceBison ups, sorry, I forgot that in production code I don't use anotations because JSON parameters have same names ParentEntity. That's why it worked.

But thanks for your hints, they are useful.

**Comment by NightlyNexus** [comment]
@SpaceBison

I filed https://github.com/square/moshi/issues/700 for that.
