### ISSUE TITLE
Using RealmList<CustomObject> with moshi

### ISSUE THREAD

**Issue by asknask** [square/moshi#527]
Here is my class:

`public class MenuModel implements RealmModel
{
    @Json(name = "menugroups")
    private RealmList<MenuGroupModel> menugroups = null;
}`

When I run the app, I get:

> Caused by: java.lang.IllegalArgumentException: Platform java.lang.Class annotated [] requires explicit JsonAdapter to be registered

I've looked into custom adapters but I couldn't figure out how to write one for a custom object with RealmList.

Any idea how to proceed?

**Comment by JakeWharton** [comment]
Can you ask on StackOverflow? This issue tracker is used for feature requests and bugs only. There's a Moshi tag that we and others monitor. Feel free to link the question back here.

**Comment by asknask** [comment]
@JakeWharton I asked it there too. Sorry for posting a question here rather than a bug/request.

https://stackoverflow.com/questions/50220315/error-using-realmlist-with-moshi

**Comment by asknask** [comment]
https://github.com/Commit451/Regalia/tree/master/regalia-moshi

Copy both **RealmListAdapter** and **RealmListAdapterJsonFactory** to your project (or use the linked project). Add the adapter to your moshi like this:

    Moshi moshi = new Moshi.Builder()
    .add(new RealmListJsonAdapterFactory())
    .build();

Further usage, if you're using Retrofit:

    Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(API.ENDPOINT)
                .addConverterFactory(MoshiConverterFactory.create(moshi))
                .build();
