### ISSUE TITLE
One-way adapters with code generation

### ISSUE THREAD

**Issue by toxxmeister** [square/moshi#545]
I have a number of custom type adapters which don't provide both `@FromJson` and `@ToJson` methods, but only the actually required one.

Previously, while using the reflection-based approach, this posed no issues as the `KotlinJsonAdapterFactory` provided the missing adapters.

Is there any way to avoid writing dummy implementations with the code generation approach?

**Comment by swankjesse** [comment]
It should work the exact same way. If it doesn’t, we’ve introduced a bug.

**Comment by toxxmeister** [comment]
@swankjesse 
I should've clarified a bit more. I no longer have the reflection-based module as a dependency, and therefore no `KotlinJsonAdapterFactory` registered with Moshi.

Here's the exact error message I'm receiving (note that the class in question is never converted to JSON, only from):

```
Caused by: java.lang.IllegalArgumentException: No @ToJson adapter for class com.something.SomeClass (with no annotations)
    at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:56)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
```

As for my Moshi configuration, I'm only registering my own custom adapters.

For now, I've had to implement dummy implementations to get around this issue.

**Comment by swankjesse** [comment]
@toxxmeister I added a test and I couldn’t reproduce your bug. Could you clarify what you were seeing? Executable test cases work best.

**Comment by NightlyNexus** [comment]
Unsure if this is the case here, but there is a case where this exception is a little confusing.

```java
static final class Foo {
  ArrayList<String> bar;
}

@Test public void foo() {
  new Moshi.Builder().add(new Object() {
    @FromJson Foo fromJson(JsonReader reader) {
      throw new AssertionError();
    }
  }).build().adapter(Foo.class);
}
```

The error message masks the real problem.
```
java.lang.IllegalArgumentException: No @ToJson adapter for class Foo (with no annotations)
	at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:56)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
```
The real problem is that there is an IllegalArgumentException for trying to get an adapter for a platform type.
The cause is [swallowed](https://github.com/square/moshi/blob/d1c2cf9c6ce9911e04f08f8c684aa5948f464b67/moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java#L55) to avoid duplication in the common case.

**Comment by swankjesse** [comment]
Oh, good find. Lets fix the swallowed exception!

**Comment by NightlyNexus** [comment]
#659

**Comment by swankjesse** [comment]
No further action to take here.
