### ISSUE TITLE
Support for updating an object from a keypath/value?

### ISSUE THREAD

**Issue by ryankennedyio** [square/moshi#55]
I have a project where it's necessary to be able to modify a client-side object based on a JSON keypath/value pair that's sent over a persistent websocket. Is this something that's on the roadmap with Moshi?

Use case:

Say we have (excuse the useless example)

    {
    "kitchen": {
        "fridge": {
            "apple": {
                "status": "ok"
            },
            "pear": {
                "status": "ok"
            },
            "curry": {
                "status": "ok"
            }
        },
        "pantry": {
            "biscuit": {
                "status": "ok"
            },
            "chocolate": {
                "status": "ok"
            }
        }
    }
}

At some point, the server says that the apples have gone out of date. Instead of sending over the whole kitchen, it'll do something like :

    {"kitchen.fridge.apple.status": "moldy"}

Based on the server sending that over, the client side `kitchen` should be updated to have a moldy apple.

Here's another explanation & accompanying library (which doesn't actually work out of the box).
http://www.arg3.com/blog/2014/02/20/java-key-path-json-objects/

I modified that library a little, and have cobbled together an ugly working solution, but essentially it works by

*. Parse (with Gson) my object into `JSONObject kitchen`.
*. Do `kitchen.putKeyPath("fridge.apple.status", "moldy")`
*. Parse the `kitchen` back into it's proper class with Gson

It feels very wrong, but I haven't been able to think of anything cleaner.

Is this something within the same problem domain as Moshi, or should it be a more standalone thing?

**Comment by swankjesse** [comment]
It should be a standalone thing!

**Comment by swankjesse** [comment]
(Neat though!)

**Comment by sddamico** [comment]
@ryankennedyio if you're looking for something that might work better out of the box, I've used json-patch before in a similar application.

https://github.com/fge/json-patch

**Comment by ryankennedyio** [comment]
@sddamico Thanks, I have had that in mind for quite a while. Will bring up with the rest of the team, but they keypath encoding is nice because it's very compact (it's a system which needs to deal with pretty massive traffic spikes, so as few characters as possible for the network's sake is nice).

Thanks @swankjesse. After reading the initial docs from today, I was less hopeful about this magic bullet. I was hoping never to deal with `org.JSONObject` again :)

Could fork and have a go at implementing - but as you said, I don't think it's in line with the idea of this library.

**Comment by swankjesse** [comment]
Yup. You might experiment with TypeAdapters by adding APIs like this:

```
  public Object get(JsonPath path);
  public void set(JsonPath path, Object value);
```

For example, the map adapter would use the first segment of the path as its key, and then make a recursive call on that entry's value.
