### ISSUE TITLE
Filtering-out null values when using Kotlin Codegen

### ISSUE THREAD

**Issue by technoir42** [square/moshi#552]
I'm using a 3rd party API which sometimes returns `null` in place of primitives:
```json
{
    "primitive": null
}
```
I'd like to create a custom adapter to filter-out `null` values and let the generated adapters use default values I've specified in my models:
```json
@JsonClass(generateAdapter = true)
data class Foo(
    val primitive: Boolean = false
)
```
Right now it seems impossible to make such custom adapter since the generated adapters use `.nonNull()` internally to read non-nullable fields and I get the following exception before execution reaches my adapter:
`com.squareup.moshi.JsonDataException: Unexpected null at $.primitive`

**Comment by NightlyNexus** [comment]
Yeah, works with the reflective adapter, but I can't swap to codegen super easily.

There are a couple other related cases in a test case I have:

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by NightlyNexus** [comment]
Looks like this moved to #586.

**Comment by or-dvir** [comment]
i dont understand... how do i fix this issue?
i am using moshi 1.6.0 and annotated my kotlin class with `@JsonClass(generateAdapter = true)`

**Comment by ArcherEmiya05** [comment]
Check my answer [here](https://stackoverflow.com/a/66962109/10053046) and see if it will help you
