### ISSUE TITLE
[ver 1.6.0] FieldArrays don't match with data class 

### ISSUE THREAD

**Issue by khatv911** [square/moshi#556]
My code worked fine with moshi 1.4. But it doesn't when I upgraded to 1.5 and 1.6. Checked fieldArrays and found the difference as below:
moshi 1.4: 
<img width="1160" alt="screen shot 2018-05-19 at 9 58 41 pm" src="https://user-images.githubusercontent.com/4799209/40269405-95978b60-5bb0-11e8-9c2f-ffc69ca1195a.png">
moshi 1.5 & 1.6: 
<img width="1271" alt="screen shot 2018-05-19 at 9 54 20 pm" src="https://user-images.githubusercontent.com/4799209/40269407-a284a63c-5bb0-11e8-88f3-39831de9732d.png">

Anything I need to add up? Thanks.

**Comment by swankjesse** [comment]
You'll be to install the KotlinJsonAdapter. Kotlin wasn't supported in Moshi 1.4 and it had some severe limitations.

**Comment by khatv911** [comment]
@swankjesse Thanks! Solved by using codegen
