### ISSUE TITLE
JsonDataException when JSON child node has a field with the same name as a field in the parent

### ISSUE THREAD

**Issue by RacZo** [square/moshi#562]
Hello all, I bumped into a problem using Moshi KotlinJsonAdapter yesterday.

Here are the details:

I have this JSON structure where the parent node and some child nodes have JSON fields with the same name at multiple levels:

```{
  "name": "John Smith",
  "meta": {
    "confidence": 90
  },
  "locations": [
    {
      "city": "New York",
      "state": "NY",
      "meta": {
        "first_seen": "11-11-2013",
        "last_seen": "05-05-2018"
      }
    },
    {
      "city": "Miami",
      "state": "FL",
      "meta": {
        "first_seen": "08-05-2011",
        "last_seen": "11-11-2013"
      }
    },
    {
      "city": "Washington",
      "state": "DC",
      "meta": {
        "first_seen": "08-09-2009",
        "last_seen": "03-03-2011"
      }
    }
  ]
}
```

Gson parses the JSON structure above without issues.

The error I got is: > com.squareup.moshi.JsonDataException: Multiple values for meta at $.meta.

It also happens when the child with the "meta" field is a single object (not an array). 

The exception seems to be thrown from line 79 of the KotlinJsonAdapter:

```
if (values[index] !== ABSENT_VALUE) {
        throw JsonDataException(
            "Multiple values for '${constructor.parameters[index].name}' at ${reader.path}")
      }
```

You can test this by putting the JSON in the `repeatedValue` and/or the `duplicatedValue` tests methods in KotlinJsonAdapterTest.

The Kotlin data class in the model is annotated with @Json(name = "meta") annotations with the names of the JSON fields and the metadata classes are 2 different classes, `PersonMeta` with only the `conficence` field and `LocationMeta` with fields `first_seen` and `last_seen`. I tried with having a generic Metadata data class with nullable fields. I also tried renaming the Kotlin data class fields differently, `@Json(name="meta") val personMeta: PersonMeta` in the parent level and `@Json(name="meta") val locationMeta: LocationMeta` in the locations node child nodes but got the same error. I got the same error because the issue seems to happen when parsing the JSON in the KotlinJsonAdapter before it even gets converted into a class. 

Please take a look and let me know if I can be of more help. Thanks!

**Comment by NightlyNexus** [comment]
Thanks for the report. Seems very strange!
Can you provide your minimal Kotlin model classes? An executable test case would be even better.

```kotlin
@Test fun foo() {
  val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
  val adapter = moshi.adapter(Foo::class.java)
  val json = """
    {
      "meta": {
      },
      "locations": [
        {
          "meta": {
          }
        }
      ]
    }
  """.trimIndent()
  assertThat(adapter.fromJson(json)).isEqualTo(Foo(emptyMap(), listOf(Foo.Location(emptyMap()))))
}

data class Foo(val meta: Map<String, Any>, val locations: List<Location>) {
  data class Location(val meta: Map<String, Any>)
}
```
passes.

**Comment by swankjesse** [comment]
@RacZo please provide an executable test case?
