### ISSUE TITLE
Codegen generates redundant adapters

### ISSUE THREAD

**Issue by Tolriq** [square/moshi#563]
I have to deal with a broken API that can return strings or arrays for fields ....

I'm using custom annotations https://github.com/square/moshi/issues/295 to manage that.

Now I want to convert those classes to Kotlin and waited for the codegen to avoid kotlin-reflect but it seems the custom annotations are not taken in account in that case :(

Is there a solution to have both without reflection?

**Comment by swankjesse** [comment]
I think our codegen retains annotations. Could you isolate this into a test case?

**Comment by Tolriq** [comment]
I'll try start of next week, but Kotlin annotation seems to require kotlin-reflect in all cases so even if they were retained they would still require the kotlinfactory.

**Comment by micHar** [comment]
I have a similar issue

```
@JsonClass(generateAdapter = true)
data class ReturnChartEntry(
        @DefaultZero @Json(name = "return_rate") val returnRate: Float
) : ChartEntry
```

```
@Retention(RUNTIME)
@JsonQualifier
annotation class DefaultZero

@Retention(RUNTIME)
internal annotation class Nullable

class DefaultZeroAdapter {

    @FromJson
    @DefaultZero
    fun fromJson(@Nullable jsonFloat: Float?): Float {
        return jsonFloat ?: 0f
    }

    @ToJson
    fun toJson(@DefaultZero jsonFloat: Float) = jsonFloat

}
```

On reflection it works great, but in codegen, the `returnRate` holds null. But maybe it's due to this issue? https://github.com/square/moshi/issues/552

**Comment by swankjesse** [comment]
@micHar I opened a separate issue. https://github.com/square/moshi/issues/586
