### ISSUE TITLE
kotlin non constructor properties not serialized

### ISSUE THREAD

**Issue by saied89** [square/moshi#568]
I have a class defined like this:
```
data class Medicalnfo(
            @Json(name = "allergies") val allergies: List<Allergy>? = null
    ): ProfileModel(){
        @Json(name = "has_allergies") val hasAllergies: Boolean = allergies != null && allergies.isNotEmpty()
    }
```
The problem is that `hasAllergies` is not included in the json serialization generated by Moshi.

Here is the test:
```
@Test
fun medicalInfoJsonContainsFlags(){
    val adapter = moshi.adapter(Medicalnfo::class.java)
    val jsonStr = adapter.toJson(Medicalnfo(allergies = listOf())) //value is {"allergies":[]}
    assert(jsonStr.contains("has_allergies"))
}
```

**Comment by swankjesse** [comment]
Moshi only serializes read/write properties. You’ll need to write a custom adapter for this.

**Comment by saied89** [comment]
ok.thanks for the insight

**Comment by gmk57** [comment]
Is Moshi designed like this to preserve serialize/deserialize symmetry? Could it be configured? `val` properties seem natural for request classes which don't need to be deserialized back.
