### ISSUE TITLE
Kotlin codegen: Support sealed classes for write-only operations

### ISSUE THREAD

**Issue by matejdro** [square/moshi#572]
Often time, JSON generation needs to be dynamic, writing different types at different times. Kotlin's sealed classes seems to be perfect fit for that:

```kotlin
sealed class Data

@JsonClass(generateAdapter = true)
data class DataA (val a : String) : Data()

@JsonClass(generateAdapter = true)
data class DataB (val b : Int) : Data()

@JsonClass(generateAdapter = true)
class Test(val someData : Data)

fun main(args: Array<String>) {
    val moshi = Moshi.Builder().build()
    val adapter = moshi.adapter(Test::class.java)

    val jsonA = adapter.toJson(Test(DataA("Text")))
    val jsonB = adapter.toJson(Test(DataB(10)))

    println(jsonA)
    println(jsonB)
}
```

Unfortunately that code errors out with `Cannot serialize abstract class Data`, since sealed class's adapter cannot be generated. However, we know in advance that `Data` class can be either `DataA` or `DataB` and we have adapters for both. 

That is why write-only adapter could be generated for the `Data` class that would check which class has been passed to `Test` instance at runtime and select proper adapter for it.

**Comment by sbaar** [comment]
Is there any interest or merit for a feature to inspect the json to determine which sealed subclass it represents, or, if the json only contains the members from the abstract sealed parent class, to deserialize it as a subclass marked with some type of @default annotation? I would like to do so if this is the right approach and it would be accepted.

**Comment by matejdro** [comment]
That would be ideal, but it would require pretty complex generation algorithm to determine which of the sub-classes is input JSON, that is why I marked this ticket as write-only. I think you might be better off creating your own adapter for that where you manually check what type of JSON is and then call appropriate adapter.

**Comment by swankjesse** [comment]
We’re working on polymorphic adapters here:
https://github.com/square/moshi/issues/133

I don’t think write-only is a good idea because it’s so awkward to test.
