### ISSUE TITLE
Handling and and storing unknown properties

### ISSUE THREAD

**Issue by mattbdean** [square/moshi#575]
There's [an open issue](https://github.com/rharter/auto-value-moshi/issues/109) in the auto-value-moshi repo on handling and storing unknown properties.

Should the responsibility for handling and storing unknown properties fall on Moshi or Moshi extensions (like auto-value-moshi)?

**Comment by NightlyNexus** [comment]
it wouldn't be performant (would need to read and allocate the keys and values that used to be skipped), and the API addition for opting into such a feature would be big for a very specific use case.
if needed, a user could copy the ClassJsonAdapter and add this functionality himself.

i'd say this is not a great fit for Moshi.
