### ISSUE TITLE
Kotlin codegen ignoring fields from parent class and non-constructor fields

### ISSUE THREAD

**Issue by rmeissner** [square/moshi#577]
If I specify a value in a parent class I would expect that the generated adapter is taking this int account. The same applies to fields in the object.

The following code shows an example:
```
sealed class Parent(
    @Json(name = "type") val type: String
) {
    @JsonClass(generateAdapter = true)
    data class Sub(
        @Json(name = "text") val text: String
    ) : Parent("coolMessage") {
        @Json(name = "encoding") val encoding = "utf8"
    }
}
```

In this example the generated adapter does not include the `type` or `encoding` field

The generated adapter has the following method to write the json:
```
    override fun toJson(writer: JsonWriter, value: Parent.Sub?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("text")
        stringAdapter.toJson(writer, value.text)
        writer.endObject()
    }
```

**Comment by swankjesse** [comment]
Our Kotlin support doesn’t support properties that cannot be set. In this case there’s no way to set `type`.

**Comment by rmeissner** [comment]
Is there any plan to change that? Was just a little unexpected when we upgraded from 1.4.0 to 1.6.0 with code generation, as this worked before.

**Comment by swankjesse** [comment]
Sorry about that.

We didn't intend to support Kotlin at all until 1.5.0. Stuff that worked in prior releases was working only by accident.

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by gekoramy** [comment]
I see this behaviour still happening in version `1.9.2`

Is it supposed to ignore parent's fields?
If so, are there any workarounds?
