### ISSUE TITLE
Kotlin codegen - allows null into collection with non-nullable generic type

### ISSUE THREAD

**Issue by paulblessing** [square/moshi#578]
Using the Kotlin codegen, if the model object has a list of a non-nullable generic type, null is allowed in when reading from JSON. Example below shown with String for simplicity, but is not limited to just String.

```
@JsonClass(generateAdapter = true)
data class MyModel(val nonNullStrings: List<String>)

class MoshiTest {

  @Test fun driver() {
    val moshi = Moshi.Builder().build()

    val json = """
      {
        "nonNullStrings" : ["1", null, "3"]
      }
    """

    val adapter = moshi.adapter(MyModel::class.java)
    println(adapter.fromJson(json)) // prints MyModel(nonNullStrings=[1, null, 3])
  }

}
```

While hopefully not a common case, could this be made to fail instead of letting null creep in to a collection that isn't meant to contain null objects? Looking at the generated code I can see how this might be tricky to pull off, since it's just delegating to a `moshi.adapter<List<String>>(Types.newParameterizedType(List::class.java, String::class.java)).nonNull()` which rejects a null List itself, but has no knowledge of the nullability of the String type parameter.

**Comment by naturalwarren** [comment]
IIRC this is also a limitation of the reflective adapter which can be solved with codegen.

**Comment by swankjesse** [comment]
Not sure if we’ll be able to fix it without some dramatic changes. But worth tracking!

**Comment by swankjesse** [comment]
Folding into this: https://github.com/square/moshi/issues/634
