### ISSUE TITLE
@Json is ignored when proguarding

### ISSUE THREAD

**Issue by kelmer44** [square/moshi#579]
Both
        @field:Json(name = "phone") val phoneNumber: String,
        @Json(name = "phone") val phoneNumber: String

are ignored after proguarding.

This are my proguard rules:

```
-dontnote android.net.http.*
-dontnote org.apache.commons.codec.**
-dontnote org.apache.http.**


-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn retrofit2.Platform$Java8


-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**


-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**

-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
-keep @com.squareup.moshi.JsonQualifier interface *
-keepclassmembers class kotlin.Metadata {
    public <methods>;
}
-keep class **JsonAdapter {
    <init>(...);
    <fields>;
}
-keepnames @com.squareup.moshi.JsonClass class *

-keepnames @kotlin.Metadata class com.myapp.model.api.**
-keep class com.myapp.model.api.** { *; }
-keepclassmembers class com.myapp.model.api.** { *; }

-keep class kotlin.reflect.**
-keep class org.threeten.bp.**
-keep class kotlin.Boolean
-keep class java.math.BigDecimal

```

Also had to give up on proguarding my model classes cause it was impossible to get it working.

**Comment by mdeandrea-mrmilu** [comment]
This still a issue. When build a app to release mode with [Flutter](https://github.com/square/in-app-payments-flutter-plugin), app crash when try save credit card

**Comment by ZacSweers** [comment]
I'm closing this issue as there have been no concrete repro projects offered and we've significantly improved what proguard rules we both embed and generate. Any followups will need a reproducing project. The above information in both comments have not been actionable.
