### ISSUE TITLE
Implements field naming strategy

### ISSUE THREAD

**Issue by hotchemi** [square/moshi#58]
Of course I understand there is no field naming strategy in moshi, but what is the reason?
I mean it seems very critical stuff for ordinary android or java developer because we don't want to create exceptional naming rule.

**Comment by JakeWharton** [comment]
The reason is documented under "Moshi is less configurable." at https://github.com/square/moshi#borrows-from-gson

**Comment by hotchemi** [comment]
Of course I've read it but...
Alright, I'm gonna chack #28 .
Thx.

**Comment by raderio** [comment]
@JakeWharton but this library is for Java & Kotlin, and in both code convention is to use camel case.
And sometimes we implement API's there is used snake case style.

Maybe this can be implemented in future?

```
Moshi moshi = new Moshi.Builder()
 .setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES)
.build();
```

**Comment by swankjesse** [comment]
https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/
