### ISSUE TITLE
Adapters that convert null to non-null don’t work with codegen

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#586]
From [this issue](https://github.com/square/moshi/issues/563#issuecomment-399373718) we have an adapter that converts an explicit null to non-null:

```
class DefaultZeroAdapter {
    @FromJson
    @DefaultZero
    fun fromJson(@Nullable jsonFloat: Float?): Float {
        return jsonFloat ?: 0f
    }

    @ToJson
    fun toJson(@DefaultZero jsonFloat: Float) = jsonFloat
}
```

Unfortunately our generated code forces the _source_ data to be non-null before it is passed to the adapter.

```
    private val floatAtDefaultZeroAdapter: JsonAdapter<Float> =
            moshi.adapter<Float>(Float::class.java, Types.getFieldJsonQualifierAnnotations(javaClass, "floatAtDefaultZeroAdapter")).nonNull()
```

This is a bug. I’m not completely convinced it’s worth fixing, however. The cost in complexity here is pretty high.

**Comment by or-dvir** [comment]
Not worth fixing? I don't mean to be rude but if you guys aren't gonna fix this then what do you mean when you state 
"Moshi is a great JSON library for Kotlin. It understands Kotlin’s non-nullable types and default parameter values"???

**Comment by swankjesse** [comment]
@or-dvir my assumption is that most users don’t write adapters that coalesce null to non-null. I might be wrong about this!

**Comment by PaulWoitaschek** [comment]
I really need null values.
I have annotation called  `@SerializeNulls`. 

When that is present, in my factory I call `serializeNulls()` upon that adapter:

```kotlin
val nextAnnotations = Types.nextAnnotations(annotations, SerializeNulls::class.java)
        ?: return null
return moshi.adapter<Any>(type, nextAnnotations).serializeNulls()
```

What now happens in the code gen is, it appends `nullSafe()` to the end so the `serializeNulls` effect is gone.

```kotlin
@field:SerializeNulls
private val nullableStringAtSerializeNullsAdapter: JsonAdapter<String?> =
            moshi.adapter<String?>(String::class.java, Types.getFieldJsonQualifierAnnotations(javaClass, "nullableStringAtSerializeNullsAdapter")).nullSafe()
```

Now my application is buggy because the backend assumes that values that are absent in patches just don't get updated.

**Comment by Shakezulla57** [comment]
So codegen doesn't work with nulls in the json? What's the point of default values other than insulating yourself from messy apis?

**Comment by amglhit** [comment]
Custom adapter works, when string value is json is null, returns "".

class NullableStringJsonAdapter : JsonAdapter<String>() {
    override fun fromJson(reader: JsonReader): String? {
        return if (reader.hasNext()) {
            reader.readJsonValue()?.toString() ?: ""
        } else {
            ""
        }
    }
}

**Comment by ArcherEmiya05** [comment]
Check my answer [here](https://stackoverflow.com/a/66962109/10053046) and see if it will help you
