### ISSUE TITLE
Allow null value from server but use default of class

### ISSUE THREAD

**Issue by defaultbr** [square/moshi#588]
my stacktrace: ```java.lang.IllegalArgumentException: field models.Realm.ActivityLog.end_time has type long, got null```

my class:

```
open class ActivityLog...
...
var end_time:Long = 0L,
...
```

my moshi and factory:
```
    val moshi = Moshi.Builder()
            .add(DefaultLongAdapter())
            .build()


    val converter = MoshiConverterFactory.create(moshi)
```

the DefaultLongAdapter

```
    class DefaultLongAdapter {
        @FromJson
        fun fromJson(@Nullable jsonLong: Long?): Long? {
            return jsonLong ?: 0L
        }

        @ToJson
        fun toJson(jsonFloat: Float?) = jsonFloat
    }
```

and how i use it:

```
   val retrofit = Retrofit.Builder()
                .....
                .addConverterFactory(converter)
                .....
                .build()
```

is there any method/way to disable this failing and allow the serialization to IGNORE null from server and use the class DEFAULT?

**Comment by defaultbr** [comment]
not working, same error

gradle:
```
    implementation 'com.squareup.moshi:moshi-kotlin:1.6.0'
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: '1.2.50'
```


moshi builder:

```
    val moshi = Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()

```

**Comment by NightlyNexus** [comment]
looks like you still want to add your custom adapter to your Moshi instance.
if you can make a test case, i can take a look tonight.

**Comment by defaultbr** [comment]
Hi @NightlyNexus  no, i dont want a custom adapter, i was only trying to ignore null values from server.

I changed the code to:

```
    val moshi = Moshi.Builder()
            .build()
```

but nothing changed

**Comment by NightlyNexus** [comment]
```
@FromJson
fun fromJson(@Nullable jsonLong: Long?): Long? {
  return jsonLong ?: 0L
}
```
should be
```
@FromJson
fun fromJson(@Nullable jsonLong: Long?): Long { // Returns non-null default value.
  return jsonLong ?: 0L
}
```
The Jetbrains `@Nullable` annotation ends up on that return value, and you don't want that. Remove the nullable part, and your adapter will be correct.

**Comment by defaultbr** [comment]
```
 val moshi = Moshi.Builder()
            .add(DefaultLongAdapter())
            .build()
```

```
    class DefaultLongAdapter {
        @FromJson
        fun fromJson(jsonLong: Long?): Long { // Returns non-null default value.
            return jsonLong ?: 0L
        }

        @ToJson
        fun toJson(jsonFloat: Float?) = jsonFloat
    }
```

give me:

```java.lang.IllegalArgumentException: field lar21.pontotel.models.Realm.ActivityLog.end_time has type long, got null```




if i add the kotlin reflect:

```
    val moshi = Moshi.Builder()
            .add(DefaultLongAdapter())
            .add(KotlinJsonAdapterFactory())
            .build()
```



the error change to : ``` com.squareup.moshi.JsonDataException: Non-null value 'end_time' was null at $.activitylogs[0].end_time ```

**Comment by NightlyNexus** [comment]
```kotlin
@FromJson
fun fromJson(@Nullable jsonLong: Long?): Long? {
  return jsonLong ?: 0L
}
```
missing the nullable annotation on the parameter.

**Comment by defaultbr** [comment]
nothing changed using ```@Nullable```

i solved in another way, changed the server to not return null, instead return 0

**Comment by NightlyNexus** [comment]
ensure your Nullable annotation has runtime retention.
