### ISSUE TITLE
Do incremental annotation processing if possible

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#589]
Should make things faster.
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by hzsweers** [comment]
Unfortunately that only applies to java right now. No kotlin support any time soon :/

**Comment by yayaa** [comment]
Sooo... It's on its way for Kotlin 🙄

https://youtrack.jetbrains.com/issue/KT-23880#focus=streamItem-27-3344755.0-0

Now we need Moshi to be incremental even more 🤗

**Comment by ZacSweers** [comment]
Work's started :). Need KotlinPoet support first https://github.com/square/kotlinpoet/pull/647

**Comment by ber4444** [comment]
It seems to be broken now. I'm getting
```
[INFO] Incremental KAPT support is disabled. Processors that are not incremental: com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor, javaslang.match.PatternsProcessor.
```

**Comment by technoir42** [comment]
@ber4444 you need to use `1.9.0-SNAPSHOT` for now because there was no stable release of Moshi with incremental apt.

**Comment by ber4444** [comment]
when are you releasing an alpha/beta/RC?

really inconvenient to reference a snapshot in a prod app

**Comment by ZacSweers** [comment]
When it's ready and once we have confirmation that using a Filer. This will
require Kotlin 1.3.40 as the kapt support for it is targeting that. At the
moment, this would break compilation in Gradle builds with a pure Kotlin
codebase :/

**Comment by ber4444** [comment]
Android Studio just updated to support 1.3.40 in the Kotlin plugin. At least in the beta channel. Hopefully you will release soon.

**Comment by ZacSweers** [comment]
Jetbrains did not include the final fix for us to safely use Filers in Android projects in 1.3.40, so we will need to wait. Hopefully a fast following 1.3.41.

https://github.com/JetBrains/kotlin/pull/2410

**Comment by technoir42** [comment]
The vast majority of Android project would be unaffected by that bug since it's triggered by disabling BuildConfig generation when no other Java sources are present. The rest can work around it pretty easily by:
1. Re-enabling BuildConfig generation for the affected modules
2. Adding a dummy .java file to the affected modules
3. Staying on Moshi 1.8.0 until a new version of Kotlin with the fix is released

Since we've got a confirmation that Filer API will be supported I don't see why we have to wait any longer.

**Comment by ZacSweers** [comment]
I'd prefer to wait until jetbrains gets this over the finish line to be sure. Shipping a release with caveats isn't a great way to build trust, especially when those caveats are counting on something that has now slipped once. In the meantime if it works for you I think it's reasonable to just build from source and use that locally.

**Comment by yayaa** [comment]
Kotlin 1.3.41 is released - can we expect a new release now? :)

**Comment by swankjesse** [comment]
@ZacSweers ?

**Comment by ZacSweers** [comment]
It the final fix didn't make 1.3.41 either, but it's been merged. New target is 1.3.50

**Comment by ZacSweers** [comment]
But we've talked about doing an RC in the meantime :). Want to get the final metadata changes into kotlinpoet so we can cut over to them and use the RC to incubate that as well

**Comment by ber4444** [comment]
any news on this now that 1.3.50 is released

**Comment by swankjesse** [comment]
Yes, I think we can roll it all out soon.

**Comment by ursusursus** [comment]
https://github.com/gradle/gradle/issues/5277

**Comment by headsvk** [comment]
any updates? @swankjesse

**Comment by GuilhE** [comment]
With:
```
Gradle: 3.5.1
Kotlin: 1.3.50
Moshi: 1.8.0

```

Still getting:

> [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor (NON_INCREMENTAL), javaslang.match.PatternsProcessor (NON_INCREMENTAL). |  
> -- | --

**Comment by emartynov** [comment]
It should land in Moshi 1.9.0. We use 1.9.0 snapshot version and don't see this warning.

**Comment by robpridham-bbc** [comment]
I'm on 1.9.0 and I'm still seeing:

> [WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: javaslang.match.PatternsProcessor (NON_INCREMENTAL).

I can't be sure that Moshi is the one that introduces this processor, but obviously a search points me here. Any ideas?

**Comment by robpridham-bbc** [comment]
Update: I think I ran into a KAPT bug (https://youtrack.jetbrains.com/issue/KT-33056) that was invoked by using `kapt.use.worker.api=true`. Without this it seems fine.

**Comment by ZacSweers** [comment]
Shouldn't be Moshi. Could be another dependency bringing the kotlin
embeddable compiler as a dependency though?
