### ISSUE TITLE
Kotlin: Is serializing static fields declared within a data class supported?

### ISSUE THREAD

**Issue by SeptimusX75** [square/moshi#590]
I'm attempting something to the effect of the following:
```
@JsonClass(generateAdapter = true)
data class SomeOutgoingClass(
    @field:Json(name = "some_name") val name: String
){
    @field:Json(name = "some_type") val type: Int = 0 // I want to keep this value out of the interface 
}
```
Is this something that is currently achievable with Moshi?

**Comment by SeptimusX75** [comment]
Sweet! It works! (But you knew that already}

It might be a bit over my head but why is that the case? If it's a public field and declared up front why can't it be serialized when using `val`? I'm just curious. :thinking:

**Comment by swankjesse** [comment]
For simplicity Moshi only writes what it can read.
