### ISSUE TITLE
IllegalArgumentException when attempting to serialize output of Kotlin's `listOf()` function

### ISSUE THREAD

**Issue by dptsolutions** [square/moshi#594]
I'm attempting to use Kotlin's syntactic sugar to make Moshi work a little more like Jackson's ObjectMapper, by adding an extension method to the Moshi class that will take in any object and serialize it.

It works if I pass it a single object. But if I pass it a list of objects created using Kotlin's `listOf()` function, I get an  `java.lang.IllegalArgumentException: Platform class java.util.Arrays$ArrayList (with no annotations) requires explicit JsonAdapter to be registered`

I am confused by this, since the Readme states that Moshi has support for Arrays, Collections, Lists, Sets, and Maps. Is this a bug, or am I doing something wrong? Given what the Readme states, it's not what I expect.

Example Code: https://github.com/dptsolutions/list-illegal-argument-exception

**Comment by JakeWharton** [comment]
You probably want to change your function to be inline and reified so you
capture the compile-time type and not the runtime type. This will result in
List instead of some JDK implementation type which Moshi doesn't know about.

**Comment by dptsolutions** [comment]
Updated the example code. Still didnt work :(
