### ISSUE TITLE
Same type of fields, but different String format in Json

### ISSUE THREAD

**Issue by SBacquartBT** [square/moshi#597]
I work with Java. And I have the following class (simple example, but true classes contains this case):
public class Data
{
     LocalDate date1; // Format in Json: "YYYY-MM-DD"
     LocalDate date2; // Format in Json: "DDMMYYYY"
}

I'd like to create an annotation LocalDateFormat to specify the format of the string:
public class Data
{
     @LocalDateFormat("YYYY-MM-DD")
     LocalDate date1; // Format: YYYY-MM-DD
     @LocalDateFormat("DDMMYYYY")
     LocalDate date2; // Format: DDMMYYYY
}

I have same cases with LocalDateTime, and as I have multiple classes of this type (multiple http services/resources) from different companies), the number of different format is very important, so I'm looking for a solution avoiding dozens of specific annotations and adapters to be used with @JsonQualifier. 
But, I can't see how to implement a "multi-format" adapter that could use the value of the LocalDateFormat. I don't even know if it's possible.

Is there a way to do it?

**Comment by JakeWharton** [comment]
If you need to read an annotation value dynamically you'll have to use a `JsonAdapter.Factory` and then inject that value into a `JsonAdapter` for the type which uses it as a format.

Can you ask this on StackOverflow so we can answer there (and it will be archived and searchable for future users)? Feel free to link the question on this issue though.
