### ISSUE TITLE
Codegen not considering super type fields?

### ISSUE THREAD

**Issue by pedromvu** [square/moshi#601]
From my testing, when using the following hierarchy:

```Kotlin
open class BaseResponse(val error: String? = null)

@JsonClass(generateAdapter = true)
data class TestResponse(val result: String? = null) : BaseResponse()
```

The generated TestResponseJsonAdapter.kt file doesn't take in consideration anything related to BaseResponse fields the error field is always null, I also tried Making BaseResponse an abstract class or adding it's own @JsonClass without success.

I don't recall seeing this as a limitation of code gen, as this is something Gson and Jackson support, I assume it also works with Moshi reflection.

**Comment by pedromvu** [comment]
Ahh nevermind, I see there was a previous issue about this and the problem is that the fields are val, changing them to var fixes the problem

**Comment by Rissmon** [comment]
That helped. Thanks @pedromvu  .
