### ISSUE TITLE
Codegen @Json wrong name generation when using special characters

### ISSUE THREAD

**Issue by pedromvu** [square/moshi#602]
When using something like:

```Kotlin
data class TimeStamp(@Json(name = "\$date") val millis: Long)
```

In the generated adapter the name gets converted to:

```Kotlin
JsonReader.Options.of("$date")
```

Which causes an Unresolved reference error when compiling, since the compiler is looking for a variable named 'date'

**Comment by NightlyNexus** [comment]
Good find. Seems like a KotlinPoet bug.
filed https://github.com/square/kotlinpoet/issues/427
