### ISSUE TITLE
JsonQualifier with collections

### ISSUE THREAD

**Issue by rabidaudio** [square/moshi#605]
I'm having trouble using `@JsonQualifier` with collections.

We use `okio.ByteString` that we serialize as hex strings. I have an adapter with a `@HexString` qualifier (so we can also have `ByteString` in other formats, like base64), and it works fine. But when I needed a list of them, it wasn't able to find the adapter. I assumed this was because the `HexString` annotation was applying to the list, and not the bytestring, so I added more adapter methods to handle the list case explicitly, but I still get:

    java.lang.IllegalArgumentException: No @ToJson adapter for java.util.List<okio.ByteString> annotated [@HexString()]

```kotlin
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class HexString

object HexStringAdapter {

    @ToJson
    fun toJson(@HexString byteString: ByteString): String = byteString.hex().toUpperCase()

    @FromJson
    @HexString
    fun fromJson(json: String): ByteString = ByteString.decodeHex(json)

    @ToJson
    fun toJson(@HexString byteStrings: List<ByteString>): List<String> = byteStrings.map { it.hex().toUpperCase() }

    @FromJson
    @HexString
    fun fromJson(json: List<String>): List<ByteString> = json.map { ByteString.decodeHex(it) }
}

data class Foo(@field:HexString val hexStrings: List<ByteString>)

val moshi = Moshi.Builder().add(HexStringAdapter).build()

val foo = Foo(listOf(ByteString.decodeHex("DEADBEEF")))
moshi.adapter<Foo>(Foo::class.java).toJson(foo)
```

Worst case, I can write a manual `JsonAdapter` for this, but am I doing something wrong, or is this a bug in Moshi?

**Comment by NightlyNexus** [comment]
uh, is this one of those where you need `@JvmSuppressWildcards`?

replace `List<ByteString>` with `List<@JvmSuppressWildcards ByteString>)` in the fromJson and toJson functions.
maybe we need a Kotlin usage section or something.

**Comment by rabidaudio** [comment]
That was it! I forget about that quirk because it doesn't come up very much. Thanks.
