### ISSUE TITLE
Allow @JsonClass to be applied to package. 

### ISSUE THREAD

**Issue by gerardogtn** [square/moshi#610]
Currently `JsonClass` can only be applied to Kotlin classes. It would be nice if the annotation could be applied to a package that holds many classes that are intended to work only for JSON serialization. Not only would this keep code DRYer (you don't have to add the annotation in every single class) but also less bug-prone (a couple of times I forget to add the annotation only to see my app crash :(). 

Although it might be awkward to apply `@JsonClass` to a package rather than a class, a new annotation could be named `@JsonPackage` to have accurate names.

**Comment by swankjesse** [comment]
I’m reluctant to do this. The `@JsonClass` is supposed to signal to the reader “hey this class is special” and putting it on the package hides that.

Also I’m not particularly fond of doing this for an entire package. I expect most packages to have a mix of JSON model classes and other classes.

**Comment by gerardogtn** [comment]
I understand that reluctance. Let me share a bit of my use case to see why it would help. We typically have a package named `network.models` where we store all data classes that we send/receive over the network via our API. In general they are very simple models just to serialize or deserialize. It also helps knowing that everything on this package is intended for network communication so basically represent JSON objects. In that sense, the package conveys the "hey this class is special" meaning, as that its what it is intended to do. 

However, it makes sense that this is specific to the way we structure our app and it might not make sense for projects that mix JSON model classes and other classes. I'd point out that allowing the annotation to be applied to a package doesn't mean that you cannot mix different types of classes, but it would incur in maintenance costs and I understand not implementing it if there's very few people using the feature out there. Maybe we can keep this issue open and if more people need this feature they can thumbs up this comment or something like that so that we can gauge if it's worth it or not?

**Comment by NightlyNexus** [comment]
Fwiw, my Java projects have feature packages (little libraries) instead of packages of types.

Configuration that is applied far away from what the configuration affects is hidden behavior and dangerous in my mind. Duplication is a benefit and a small cost for clarity.

**Comment by JakeWharton** [comment]
Even in my packages which are dedicated to serialization models I tend to have `@ToJson`/`@FromJson` classes, qualifier annotations, and other helpers.
