### ISSUE TITLE
Any documents for @FromJson and @ToJson?

### ISSUE THREAD

**Issue by jaychang0917** [square/moshi#617]
I was wondering what the **signatures for method annotated `@FromJson` or `ToJson`** are. Are there any documents for them? When I was looking at the [MultipleFormats adapter](https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/MultipleFormats.java) parsing multiple formats of JSON, I have no clue what parameter type I can use and in what order.

Thanks in advanced.
```java
/** Handles cards either as strings "5D" or as objects {"suit": "SPADES", "rank": 5}. */
  public final class MultipleFormatsCardAdapter {
    @ToJson void toJson(JsonWriter writer, Card value,
        @CardString JsonAdapter<Card> stringAdapter) throws IOException {
      stringAdapter.toJson(writer, value);
    }

    @FromJson Card fromJson(JsonReader reader, @CardString JsonAdapter<Card> stringAdapter,
        JsonAdapter<Card> defaultAdapter) throws IOException {
      if (reader.peek() == JsonReader.Token.STRING) {
        return stringAdapter.fromJson(reader);
      } else {
        return defaultAdapter.fromJson(reader);
      }
    }
  }

  /** Handles cards as strings only. */
  public final class CardStringAdapter {
    @ToJson String toJson(@CardString Card card) {
      return card.rank + card.suit.name().substring(0, 1);
    }

    @FromJson @CardString Card fromJson(String card) {
      if (card.length() != 2) throw new JsonDataException("Unknown card: " + card);

      char rank = card.charAt(0);
      switch (card.charAt(1)) {
        case 'C': return new Card(rank, Suit.CLUBS);
        case 'D': return new Card(rank, Suit.DIAMONDS);
        case 'H': return new Card(rank, Suit.HEARTS);
        case 'S': return new Card(rank, Suit.SPADES);
        default: throw new JsonDataException("unknown suit: " + card);
      }
    }
  }
```

**Comment by NightlyNexus** [comment]
The name of the method does not matter, as long as the method has the annotation.
The parameter possibilities are listed in the error messages. See here: [`@ToJson`](https://github.com/square/moshi/blob/29bdc0aa45cc80569c2524b2f8e370d0649bdd80/moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java#L194) [`@FromJson`](https://github.com/square/moshi/blob/29bdc0aa45cc80569c2524b2f8e370d0649bdd80/moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java#L262)

We should document these better.

**Comment by NightlyNexus** [comment]
Tracking documentation in #620.
