### ISSUE TITLE
The Pair serialization

### ISSUE THREAD

**Issue by RuslanTroshkov** [square/moshi#618]
val type = Types.newParameterizedType(Pair::class.java, Any::class.java, Integer::class.java)
val moshi = Moshi.Builder()
//.add(KotlinJsonAdapterFactory())
.build()
val jsonAdapter = moshi.adapter<Pair<Any, Long>>(type)

I get an exception :
java.lang.IllegalArgumentException: Platform kotlin.Pair<java.lang.Object, java.lang.Integer> (with no annotations) requires explicit JsonAdapter to be registered

What am I doing wrong?

**Comment by NightlyNexus** [comment]
See #508.
