### ISSUE TITLE
[kotlin/code-gen] adding support for handling unknown names / types

### ISSUE THREAD

**Issue by dpnolte** [square/moshi#619]
Dear Maintainers,

First of all, thank you for the awesome library :) 

I'm using the kotlin mob gen and have two requests:

- At this moment, unknown names and types are skipped in auto generated adapters, see: [AdapterGenerator.kt](https://github.com/square/moshi/blob/master/kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt#L215#L217). It would be great if handling of unknowns can become configurable. That is, setting `reader.setFailOnUnknown` to true if you want a more strict parsing. Perhaps through an additional parameter in the @JsonClass annotation constructor or having an additional annotation so that you can set it per adapter?

- Currently, the generated adapters have no interfaces. I would be nice if you could distinguish among generated adapters, adapters that are created with the Moshi Builder, or adapters that still need to be build IMHO, in particular if you have collection of adapters.  Would it be an idea of adding an interface to the generated adapter? 

I'd be happy to contribute to a PR. Cheers, Derk

**Comment by hzsweers** [comment]
For the second case, you can configure Moshi to generate `@Generated` annotations on adapters to denote them

**Comment by dpnolte** [comment]
Aha! Thanks for the pointers and the nice solution with the factory. That helped  👍 
If i'm not mistaken,`@Generated`'s retention is set to source. But I could potentially use `Types.getRawType(Type).getAnnotation(Generated::class.java).generateAdapter`during run time.  I'll close it, cheers.

Some more background why I opened this request (if anyone reads this after the last line ;-):
What I basically had in mind, was something like:
```
AgnosticService.registerAdapter(type, IAdapter)
```
My intention is to encapsulate moshi into a component/service. I struggle(d) a bit on how to implement this method with auto generated adapters. It works by checking if the class is derived from JsonAdapter and then applying the right factory.  But now I am thinking this is the wrong direction all together. It is probably better to adjust the processor to my specific needs.  Cheers guys, keep up the good work
