### ISSUE TITLE
Moshi with Kotlin codegen ignores custom adapters?

### ISSUE THREAD

**Issue by marcosalis** [square/moshi#626]
I'm using Moshi 1.6 with the new codegen processor with Retrofit to parse Json response models.
I have a Kotlin data class annotated with `@JsonClass(generateAdapter = true)`, and a simple custom type adapter to convert some string properties to longs:

```
public class StringLongMoshiAdapter {
    @ToJson @NonNull String toJson(@Nullable Long aLong) {
        return String.valueOf(aLong);
    }
    @FromJson @Nullable Long fromJson(@Nullable String longString) {
        if (longString == null || longString.isEmpty()) {
            return null;
        }
        return Long.parseLong(longString);
    }
}
```

This is how I initialize Moshi:
```
new Moshi.Builder()
                    .add(new StringLongMoshiAdapter())
                    .build();
```

And this is (part) of the data class:
```
@Keep
@JsonClass(generateAdapter = true)
internal data class MyResponse(
(...)
        @Json(name = "parent-id") val parentId: Long?,
```

However, when parsing I get this exception, which means that the custom adapter is not used (this was working before, with `KotlinJsonAdapterFactory` and `moshi-kotlin`):
```
com.squareup.moshi.JsonDataException: Expected a long but was  at path $.categories[0].parent-id
        at com.squareup.moshi.JsonUtf8Reader.nextLong(JsonUtf8Reader.java:788)
```

Is this expected behaviour? Shouldn't the generated type adapter for `MyResponse` use the custom type adapters specified when initialising Moshi?

**Comment by NightlyNexus** [comment]
Thanks for the report.
I ran into something like this a few months ago and forgot to file. IIRC there's a missing .javaObjectType, and it's tangentially related to #586.

**Comment by marcosalis** [comment]
Wow, that was quick! Thanks a lot guys, I appreciate it.
I can confirm that the issue is sorted in `1.7.0-SNAPSHOT`.
