### ISSUE TITLE
Problem by Jetifier

### ISSUE THREAD

**Issue by hkelidari** [square/moshi#630]
When use android.enableJetifier=true
Show error:
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
class com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory;, unresolved supertypes: Lcom.squareup.moshi.JsonAdapter.Factory;

**Comment by NightlyNexus** [comment]
Yep, same as this SO question, it seems.
https://stackoverflow.com/questions/51898803/cant-build-project-after-upgrading-to-3-3

**Comment by Benyuss** [comment]
Same here.

gradle.properties
android.useAndroidX=true
android.enableJetifier=true

with moshi and moshi-kotlin 1.6.0

**Comment by hkelidari** [comment]
Fixed in Android studio Canary 7
