### ISSUE TITLE
Kotlin Data Classes and Delegation

### ISSUE THREAD

**Issue by bd82** [square/moshi#631]
Hello.

I am combining Kotlin Data Classes with delegation for property reuse in Data classes:
```kotlin
interface IBase {
    var name: String?
    var title: String?
}

data class Base (override var name: String? = null,
                 override var title: String? = null) :IBase

data class Derived(
        var base: IBase = Base(),
        var age: Int
// delegation here! Derived instances now act as though they have Base properties.
) : IBase by base


val moshi = Moshi.Builder()
        // ... add your own JsonAdapters and factories ...
        .add(KotlinJsonAdapterFactory())
        .build()

val basedAdapter = moshi.adapter(Base::class.java)
val derivedAdapter = moshi.adapter(Derived::class.java)

fun main(args: Array<String>) {

    val baseInstance = Base(name = "John", title = "Mr")
    val baseJson = basedAdapter.toJson(baseInstance)
    println(baseJson)

    val derivedInstance = Derived(base = baseInstance, age = 33)
    val derivedJson = derivedAdapter.toJson(derivedInstance)
    println(derivedJson)
    
}
```

Generally I'd like to have the delegated properties serialized as though they
are inherited properties (no nesting), I suppose I would have to write a custom adapter for that...

But I get an earlier error:
Caused by: java.lang.IllegalArgumentException: No JsonAdapter for interface IBase (with no annotations)

So:
* How do I get around this issue?
* Should I use codegen instead of reflection?
* Can I tell Moshi to ignore the interface when it creates the adapter?  

Thanks.

**Comment by NightlyNexus** [comment]
Could you abuse `@Transient` on your delegate?

**Comment by bd82** [comment]
Thanks for the rapid reply @NightlyNexus 

I looked again at my data model and decided to suffer a little bit of duplication for now
to avoid additional complexity in the serialization (not my focus right now).
