### ISSUE TITLE
Release cycle improvements

### ISSUE THREAD

**Issue by warabei14** [square/moshi#636]
You guys are doing very great work. Thank you very much for it.
I have a little question: any chance to have more predictable / frequent release cycle?
Seems you do much work between releases and they are not very often appear to community.
Are you facing some difficulties with time spending for this project or something else?
The problem: I am not able to use any snapshot dependency in a big corporate project. I see some nice things to use, like Polymorphic Adapter, but these things are not released yet, and afaiu it can be released in the October, or May, maybe. Seems too long to wait for me. Sorry for inconvenience.

**Comment by JakeWharton** [comment]
This is not a product and as a result we do not promise or adhere to release cycles at any regular frequency. We ship when things are done. Whether that takes a week, a month, or a year, we're not going to rush something just to have a release. If you cannot use a snapshot dependency, you can check the jar into your repo or deploy it to a local Maven host to get a stable pre-release version.
