### ISSUE TITLE
No BuiltInsLoader implementation was found

### ISSUE THREAD

**Issue by blackberry2016** [square/moshi#637]
As I add all ProGuard rules, but still throwing
```
No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped " "from your application and that the Java virtual machine is not running under a security manager"
```

https://github.com/JetBrains/kotlin/blob/master/core/descriptors/src/org/jetbrains/kotlin/builtins/BuiltInsLoader.kt

**Comment by NightlyNexus** [comment]
How can I reproduce this?

**Comment by JakeWharton** [comment]
Dupe of #402. See https://github.com/square/moshi/issues/402#issuecomment-415247195.

**Comment by blackberry2016** [comment]
@JakeWharton Not working with  -keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl

**Comment by JakeWharton** [comment]
Please provide a sample that reproduces the problem

**Comment by kizitonwose** [comment]
@blackberry2016 I had this same issue.  

Using config `-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl` did not work.

Using config `-keep public class kotlin.reflect.jvm.internal.impl.builtins.* { public *; }` as suggested [here](https://github.com/square/moshi/issues/402#issuecomment-348886666) throws a different error.

What worked was `-keep public class kotlin.reflect.jvm.internal.impl.** { public *; }`

This increases the apk size by about 60KB which is insignificant.

**Comment by taxqwe** [comment]
https://github.qiwi.com/client-dev-android/vqw_android/pull/4495
