### ISSUE TITLE
How about a JSON parser code generator on top of Moshi?

### ISSUE THREAD

**Issue by serj-lotutovici** [square/moshi#64]
Some people are very concerned about speed... especially when it comes to JSON parsing and reflection. So my question would be:

Does it make sense for you guys to add a parser generator on top (something like [ig-json-parser](https://github.com/Instagram/ig-json-parser/) and [LoganSquare](https://github.com/bluelinelabs/LoganSquare))?

**Comment by swankjesse** [comment]
Yup, though it's a lot of work for marginal benefit!

**Comment by JakeWharton** [comment]
This can be implemented as a third-party library which just creates
JsonAdapter implementations. There's no need for it to be in the core or
even written by us.

**Comment by serj-lotutovici** [comment]
@JakeWharton but if it will be provided as a PR?

**Comment by JakeWharton** [comment]
It would have to be fairly comprehensive. I think we have high standards
for how this would behave (which neither of the linked libraries meet).

**Comment by serj-lotutovici** [comment]
Fair enough... thanks for you time :)

**Comment by serj-lotutovici** [comment]
I'm really sorry for waisting you time... but I can't get this idea out of my mind :)

I know it's out of your road map, but I would vote for such a solution to be present in every json parsing library. In my opinion for really fat objects it makes sense to use generated parsers with little reflection as possible. And why not make moshi even more faster? :)

So, how about such a hybrid approach (I think it's something similar as in butterknife):

* Add an annotation processor to Moshi
* Add an annotation for module classes which will tell the annotation processor that it should generate a JsonAdapter using the streaming api of Moshi (let say `@JsonModel`).
* When someone calls `moshi.adapter(Type)` for the particular class, moshi will use the generated adapter instead of the actual flow...

Would you guys agree to such an approach? assuming that who ever commits it, will try to make it as hight quality as possible. ;)

**Comment by swankjesse** [comment]
Benchmarks speak louder than words. We need to make some benchmarks for Moshi, and comparing codegen vs. reflection will be something that'll drive this.

**Comment by serj-lotutovici** [comment]
Agree... Will do that shortly...

**Comment by serj-lotutovici** [comment]
Hey... I did a small java application draft, that benchmarks reflection vs streaming approaches... I'm not sure if this is what @swankjesse meant. But at least it's a start... see the repo https://github.com/serj-lotutovici/moshi-benchmarking

From a few runs I made, values on average are 748255.0 vs 209944.0 nanoseconds (reflection vs streaming)...

**Comment by swankjesse** [comment]
I think you might wanna try JMH?

**Comment by serj-lotutovici** [comment]
"You learn something new everyday"...) will do

**Comment by elucash** [comment]
We ran some benchmarks with Gson code generation vs reflection. I would not say that results are overwhelmingly convincible in favor of code generation, but sometimes it faster. (http://immutables.github.io/json.html#gson-jackson)
Though would be interested to see what happening with Moshi (not gson) and on Android (not java)

**Comment by JakeWharton** [comment]
> including UTF-8 encoding handling, recycling of special buffers, DIY number parsing and formatting etc.

Funny. This quote verbatim could be about Okio, but underlying library on which Moshi is built as it does all of these things and more for speed.

**Comment by elucash** [comment]
Experimental support for `JsonAdapter.Factory` generation in Immutables immutables/immutables#137
Benchmark code [here](https://github.com/immutables/samples/tree/master/json/src/org/immutables/samples/json)

```
Benchmark                                       Mode  Samples     Score     Error  Units
o.i.s.j.JsonBenchmarks.autoJackson              avgt        7   698.307 ±  37.036  us/op
o.i.s.j.JsonBenchmarks.immutablesGson           avgt        7  1204.739 ±  60.058  us/op
o.i.s.j.JsonBenchmarks.immutablesGsonJackson    avgt        7   669.356 ±  23.812  us/op
o.i.s.j.JsonBenchmarks.immutablesMoshi          avgt        7  1755.568 ± 115.289  us/op
o.i.s.j.JsonBenchmarks.pojoGson                 avgt        7  1403.400 ±  33.398  us/op
o.i.s.j.JsonBenchmarks.pojoGsonJackson          avgt        7   940.697 ±  64.019  us/op
o.i.s.j.JsonBenchmarks.pojoJackson              avgt        7   707.178 ±  15.331  us/op
o.i.s.j.JsonBenchmarks.pojoMoshi                avgt        7  1907.779 ± 119.726  us/op
```
As it was run on java 8, I think it has little to do with performance on Android. There's certain workload, which may be not representative at all. (however I found score difference consistent and  proportionally changing when changing document size/ field sets)

**Comment by JakeWharton** [comment]
Ouch

**Comment by serj-lotutovici** [comment]
Don't know if this is still relevant, but here are my results:

```
Benchmark                    Mode  Cnt    Score   Error  Units
Benchmarker.moshiReflection  avgt   10  296.092 ± 5.454  us/op
Benchmarker.moshiStreaming   avgt   10  174.024 ± 4.055  us/op
```

You can checkout the source code, on https://github.com/serj-lotutovici/moshi-benchmarking

**Comment by JakeWharton** [comment]
@elucash Those benchmarks include things that are not part of serialization which is likely why you're seeing such drastic variance.

Calls to `Moshi.adapter` should be done once and then cached as we eagerly (and reflectively) do a ton of work in that method. As of v1.0 we now cache these instances internally so subsequent calls return instantly as the behavior was too surprising. Including this step in a benchmark is strange as the relative times for this one-time setup aren't really relevant across libraries.

**Comment by serj-lotutovici** [comment]
I'll just leave this here
```
Benchmark                      Mode  Cnt    Score    Error  Units
Benchmarker.gsonReflection     avgt   10  130.238 ± 14.227  us/op
Benchmarker.jacksonReflection  avgt   10   95.266 ± 26.433  us/op
Benchmarker.moshiReflection    avgt   10  160.126 ±  6.467  us/op
Benchmarker.moshiStreaming     avgt   10  173.832 ±  7.137  us/op
```

`Benchmarker.moshiReflection` is based on 1.0.0

But @JakeWharton / @swankjesse it seams that you where right, JsonAdapter generation probably will not give any real benefit.

P.S. Sorry for waisting your time on this.

**Comment by JakeWharton** [comment]
That still seems high, but better!

**Comment by elucash** [comment]
I've tried to archive relative fairness between toolkits, most important is that code generated binding provide marginal improvement if any (on java at least) which is observable across different benchmarks.

**Comment by serj-lotutovici** [comment]
No need for any action. As Jessy and Jake noted this can be done in a standalone library if needed.

**Comment by FabianTerhorst** [comment]
@serj-lotutovici have you tried to benchmark https://github.com/rharter/auto-value-moshi as well?

**Comment by serj-lotutovici** [comment]
@FabianTerhorst didn't have the time to actually try it... but from what I saw the **auto-value-moshi** uses a switch to select the appropriate adapter for the respective field, which proves to be slower in the long run versus the `Name -> JsonAdapter` map that moshi generated through reflection. At this point I think that moshi is fast enough, especially with the release of 1.2.0.

**Comment by serj-lotutovici** [comment]
@FabianTerhorst I've just realized that `switch` performs similarly to `HashMap` if an object has many fields... sorry for my previous comment.
