### ISSUE TITLE
Equivalent for inline JsonAdapter within Moshi

### ISSUE THREAD

**Issue by poldz123** [square/moshi#641]
GSON has the ability to have inline adapter bounded to the field within the class.

```
class Object {
  @JsonAdapter(CustomAdapter::class) val valueAndKey: String
}
```

This is good since I do not need to register the adapter within the GSON object for retrofit. I am wondering if there is a similar function within the Moshi library.

**Comment by NightlyNexus** [comment]
https://github.com/square/moshi#alternate-type-adapters-with-jsonqualifier
A custom JsonQualifier and register a custom JsonAdapter to handle the qualified type. Required registration is nice because the order that adapters are looked up is easy to reason about.
