### ISSUE TITLE
Automatic convertion of property names to/from snake case

### ISSUE THREAD

**Issue by vpratfr** [square/moshi#644]
Is there any way to automatically apply naming conventions to Moshi when serializing data using Moshi?

e.g.: I have this class which follows Kotlin naming conventions for properties (camel case)

```
class Player {
    var currentHealth: Int = 100
    var firstName = "John"
    var lastName = "Doe"
}
```

I would like to serialize it to something which will stick to the naming conventions we have on the server (snake case):
```

{ 
    current_health: 100,
    first_name: "John",
    last_name: "Doe"
} 
```

I already know we can customize column names on each property manually. Just looking for a way to do that automatically (for instance if we add properties to the POJO or on server side).

**Comment by vanniktech** [comment]
This will very likely not happen - https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/

**Comment by swankjesse** [comment]
Yep. You should just embrace the rebellious delight in breaking the Java naming convention in order to satisfy the JSON naming convention.

**Comment by vpratfr** [comment]
Thanks for the insight. Will use manual `@Json` annotations then.
