### ISSUE TITLE
Allow raw JSON values?

### ISSUE THREAD

**Issue by orip** [square/moshi#65]
I have raw JSON on disk that I want to embed in side a wrapper JSON. It would be awesome to do something like (explicitly choosing horrible names and hook points before and after)

```
File fileWithJson = ...;
JsonWriter json = new JsonWriter(sink);
json.beginObject();
json.name("foo").aboutToAddExternalValue();
sink.writeAll(Okio.source(fileWithJson));
json.valueAddedExternallyTrustMeItsFine();
json.closeObject();
```

Or even:

```
json.name("foo").value(Okio.source(...))
```

**Comment by JakeWharton** [comment]
`.aboutToAddExternalValue()` would just be `.writeDeferredName()` (private) and `.flush()`. A second method would not be needed.

I question the value something like would have in the public API.

**Comment by orip** [comment]
Fair enough regarding exposing it in the normal API.
It's a good technique to construct JSON API requests while streaming from disk, I wonder whether there's a way to allow reusing JsonWriter without forking that is inconvenient enough that people don't shoot themselves in the foot.

**Comment by JakeWharton** [comment]
We can probably come up with something. I definitely like the stream-from-disk intention vs a raw byte[] or String.

**Comment by adamtanner** [comment]
I just did this in https://github.com/google/gson/pull/667 if you want to port it over.

**Comment by mescortes** [comment]
CC @mescortes

**Comment by tmm1** [comment]
@NightlyNexus thanks for implementing this!

Is there an equivalent for `JsonReader`? i.e if I want to consume the contents of a specific field as a json blob with no additional parsing?

**Comment by JakeWharton** [comment]
That's #318
