### ISSUE TITLE
JsonReader.readJsonString

### ISSUE THREAD

**Issue by JakeWharton** [square/moshi#675]
The opposite of `JsonWriter.value(BufferedSource)` which allows you to read a value as raw JSON. It can return either a String or ByteString depending on the ergonomics you want.

It can be implemented by [`peek()`-ing][1] the source, calling `skipValue()`, and then taking the offset you stopped at and calling `readUtf8`/`readByteString` with that offset (as a length) on the original source.

 [1]: https://github.com/square/okio/issues/506

**Comment by NightlyNexus** [comment]
This could also be implemented today by implementing the skip methods to take in a BufferedSink and writing to the sink instead of skipping as the skip methods read.

The tricky part in either implementation case is that peeking goes ahead and disposes of the bytes for things like opening brackets, whitespace, and the like.

**Comment by NightlyNexus** [comment]
`ByteString JsonReader.readJsonString()` or `void JsonReader.readJsonValue(BufferedSink)`?
the former being the very common case, the latter being more flexible.

**Comment by JakeWharton** [comment]
Probably the first one

**Comment by a141199** [comment]
has this been implemented?

**Comment by ZacSweers** [comment]
From an API standpoint, should we offer something higher level to opt this in?

```kotlin 
class Foo(
  @JsonString val rawString: String // or ByteString
)
```

**Comment by JakeWharton** [comment]
I'm likely going to add `JsonReader.valueSource()` for symmetry with `JsonWriter.valueSink()` that's also coming. This means if you want an arbitrary JSON value you can do `valueSource().readByteString()` or `valueSource().readUtf8String()` or `JsonReader.of(valueSource())` for a `ByteString`, `String`, or `JsonReader`, respectively.

I don't think this is a common enough occurrence to warrant its own annotation. It can start as a sample, perhaps.

**Comment by ZacSweers** [comment]
👌 should we hold off on the existing jsonString() PRs in favor of that
then?

**Comment by tuliomagalhaes** [comment]
@JakeWharton as this issue is open since 2018, we have any solution to get a raw json from the `JsonReader`?

**Comment by tmm1** [comment]
> I'm likely going to add `JsonReader.valueSource()` for symmetry with `JsonWriter.valueSink()` that's also coming.

It looks like there was an implementation in https://github.com/square/moshi/pull/954 but it was never merged?

**Comment by ygnessin** [comment]
I really like the `@JsonString val rawString: String` suggestion above, it would perfectly solve the exact problem that I am running into now in my project. We are incrementally migrating from jackson to moshi and this is one of the things currently getting in our way.

Any updates on when this addition might be available?

Thanks for the wonderful library!

**Comment by JakeWharton** [comment]
That is perhaps a high-level interface to the underlying feature we need to build, but it's not strictly what this issue is tracking since half of the behavior needed to implement that has already landed.

**Comment by ZacSweers** [comment]
Should I re-kick the PR I started?

**Comment by JakeWharton** [comment]
If you want. My branch was on my Google computer which I burned in a dumpster behind the local Wendy's.

**Comment by ZacSweers** [comment]
Alright rehashed in #1219, reviews welcome!

**Comment by tuliopereirazup** [comment]
Thanks guys, this will be helpful.

**Comment by tuliomagalhaes** [comment]
Thanks guys, this will be helpful.

**Comment by tmm1** [comment]
This issue can be closed since `JsonReader.nextSource()` was implemented in #1224 

```
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class RawJson

class RawJsonMoshiAdapter: com.squareup.moshi.JsonAdapter<ByteString>() {
    override fun toJson(writer: com.squareup.moshi.JsonWriter, value: ByteString?) {
        writer.jsonValue(value)
    }
    override fun fromJson(reader: com.squareup.moshi.JsonReader): ByteString? {
        return reader.nextSource().readByteString()
    }
}

data class Foo(
  @RawJson Field: ByteString?
)

val moshi = Moshi.Builder().add(ByteString::class.java, RawJson::class.java, RawJsonMoshiAdapter()).build()
```

**Comment by tmm1** [comment]
> ```kotlin
> writer.value(ByteArrayInputStream(value.toByteArray()).source().buffer())
> ```

Is there a better way to go from `ByteString` to `BufferedSource`?

**Comment by JakeWharton** [comment]
Buffer().write(byteString)
