### ISSUE TITLE
Boolean always gets the wrong value

### ISSUE THREAD

**Issue by Dnakin** [square/moshi#678]
I request a simple check if an update is available. The api returns whether or not an update is available through the `update_available` flag. But Moshi parses the response to `false` every time

```Log
D/OkHttp: <-- 200 OK https://url.com/update_available (545ms)
D/OkHttp: Server: nginx/1.10.3
D/OkHttp: Date: Fri, 21 Sep 2018 20:43:39 GMT
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Transfer-Encoding: chunked
D/OkHttp: Connection: close
D/OkHttp: X-Frame-Options: SAMEORIGIN
D/OkHttp: X-XSS-Protection: 1; mode=block
D/OkHttp: X-Content-Type-Options: nosniff
D/OkHttp: X-Download-Options: noopen
D/OkHttp: X-Permitted-Cross-Domain-Policies: none
D/OkHttp: Referrer-Policy: strict-origin-when-cross-origin
D/OkHttp: ETag: W/"9dd68e6e0adacff3d3556d17f141663f"
D/OkHttp: Cache-Control: max-age=0, private, must-revalidate
D/OkHttp: X-Request-Id: 79b7d82f-6272-45c4-92ef-5ecd50ab3c00
D/OkHttp: X-Runtime: 0.089480
D/OkHttp: {"update_available":true}
```

```Kotlin
data class UpdateAvailableResponse(
        @Json(name = "update_available")
        var updateAvailable: Boolean = false
)
```
```Gradle
implementation ("com.squareup.moshi:moshi:1.6.0")
    
implementation("com.squareup.retrofit2:retrofit:2.4.0")
implementation("com.squareup.retrofit2:adapter-rxjava2:2.4.0")
implementation("com.squareup.retrofit2:converter-moshi:2.4.0")

implementation("com.squareup.okhttp3:logging-interceptor:3.11.0")
```

**Comment by Dnakin** [comment]
I just changed to GsonConverterFactory and it works just fine. I switched the @Json annotation with @Expose @SerializedName and changed the MoshiConverterFactory to GsonConverterFactory in my service and it works.

data class UpdateAvailableResponse(
        @Expose
        @SerializedName("update_available")
        //@Json(name = "update_available")
        var updateAvailable: Boolean = false
)

**Comment by NightlyNexus** [comment]
This is because `@Json` does not specify that it targets fields. The `@Json` is getting attached to the property and not the field.

Please use the Kotlin support in Moshi.
See here: https://github.com/square/moshi#kotlin

If you really can't use any of Moshi's official Kotlin support in the immediate future, you can hack this with `@field:Json(name = "update_available")`
