### ISSUE TITLE
JSON Qualifier doesn't work inside RuntimeJsonAdapterFactory

### ISSUE THREAD

**Issue by marlonbosse** [square/moshi#696]
Hey,
I got problem when using the `RuntimeJsonAdapterFactory` to parse a polymorphic list in conjunction with `@JsonQualifier`

Setup looks like following:

```
sealed class Element(
val id: String
val type: String? = null
)

class Asset(
id: String,
@Alignment gravity: Int
): Element(id)

class Label(
id: String
@Alignment textGravity: Int
): Element(id)
```

I got an adapter for the `@Alignment` qualifier to basically take string-input (like "top-left") to convert it to `Gravity.TOP |  Gravity.LEFT` which works fine in itself. The polymorphic adapter in itself also works fine.

But when I combine it and try to parse a 

`List<Element>` that includes `@JsonQualifier` it doesn't work anymore.

How my Moshi is setup:

```
Moshi.Builder()
          .add(AlignmentAdapter.create())
          .add(RuntimeJsonAdapterFactory.of(Element::class.java, "type")
              .registerSubtype(Asset::class.java, "asset")
              .registerSubtype(Label::class.java, "label")
          .build()
```

The exception when trying to parse the list with JsonQualifier:

```
java.lang.IllegalArgumentException: No JsonAdapter for class java.lang.Integer annotated [@com.test.parser.Alignment()]
        at com.squareup.moshi.Moshi.adapter(Moshi.java:115)
        at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:90)
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
        at com.test..parser.RuntimeJsonAdapterFactory.create(RuntimeJsonAdapterFactory.java:95)
```

**Comment by NightlyNexus** [comment]
can you post your AlignmentAdapter, preferably with an executable test case?

**Comment by marlonbosse** [comment]
Hey - while preparing the testcase I actually found the underlying issue on my side. 
The Adapter is written in Java, the models are in Kotlin and the `@JsonQualifier` is only working for `Int` but not `Int?`. 

If this behavior is intended  than feel free to close this issue, otherwise I can provide you the testcase anyway.

Thanks!

**Comment by swankjesse** [comment]
No clear action to take on this.
