### ISSUE TITLE
Serializing integers

### ISSUE THREAD

**Issue by stevesamknows** [square/moshi#699]
Our use case requires raw json files to be as human readable as possible, and the problem
has been that integers typically have either decimals or are in scientific notation.

In gson, it's easy to serialize json to a string which respects integer values e.g.
```
"
{
    "myIntVal": 42
}
"
```

but in moshi typically get instead e.g.
```
"
{
    "myIntVal": 42.0
}
"
```
or for large numbers e.g.
```
"
{
    "myIntVal": 4.5174704E7
}
"
```

Here's a moshi json pretty printer, which is known to store integers with the above issues
(decimal point or scientific notation):
```
    override fun prettifyJson(jsonAsStr: String) : String {
        // Ref: https://github.com/square/moshi/issues/288
        val source = Buffer().writeUtf8(jsonAsStr)
        val reader = JsonReader.of(source)
        val value = reader.readJsonValue()
        val adapter = Moshi.Builder().build().adapter(Any::class.java).indent("    ")
        val jsonAsStrPretty = adapter.toJson(value)
        return jsonAsStrPretty
    }
```

(Apologies if this has been asked before but haven't been able to find much information
and understand that this may be specific to java, where json
integers are "just numbers" and this sort of serialization behavior is not unexpected)

**Comment by swankjesse** [comment]
Yeah, with Moshi we follow [RFC 7159](https://tools.ietf.org/html/rfc7159#section-6) which says, 

> This specification allows implementations to set limits on the range and precision of numbers accepted. Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision.

Gson was created before that spec and we can't expect it to follow it.

**Comment by stevesamknows** [comment]
Solid point, thank you
