### ISSUE TITLE
Using ISO_DATE_TIME Format to represent dates

### ISSUE THREAD

**Issue by inder123** [square/moshi#70]
JDK 8 defines ISO_DATE_TIME format, and we should consider using that as the representation of Date/Time objects. JSR-367 is standardizing on this format as well.

**Comment by JakeWharton** [comment]
I might be already with this as long as user-specified adapters always win. Or, to put another way, these defaults are only conditionally applied for lack of a user-specified adapter.

A default that I love is that we do not serialize platform value types (in `java.*`, `javax.*`, or `android.*`) by default and you will receive an error message for such cases. This prevents awkward things like when you have something like a `File` in your model.

**Comment by swankjesse** [comment]
Rfc3339DateJsonAdapter lives!
