### ISSUE TITLE
Codegen not considering `@Json` annotation on superclass constructor parameters.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#700]
```kotlin
abstract class Superclass(@Json(name="superclassPropertyJsonName") var superclassProperty: String? = null)

@JsonClass(generateAdapter = true)
class Subclass(@Json(name="subclassPropertyJsonName") val subclassProperty: String? = null) : Superclass()

@Test fun subclass() {
  val moshi = Moshi.Builder().build()
  val jsonAdapter = moshi.adapter(Subclass::class.java)

  val encoded = Subclass("hello").apply { superclassProperty = "world" }
  assertThat(jsonAdapter.toJson(encoded)).isEqualTo("""{"subclassPropertyJsonName":"hello","superclassPropertyJsonName":"world"}""")

  val decoded = jsonAdapter.fromJson("""{"superclassPropertyJsonName":"world","subclassPropertyJsonName":"hello"}""")!!
  assertThat(decoded.subclassProperty).isEqualTo("hello")
  assertThat(decoded.superclassProperty).isEqualTo("world")
}
```
fails.

via https://github.com/square/moshi/issues/495#issuecomment-425401941

**Comment by NightlyNexus** [comment]
marking the target as `property` makes the test case above pass.
```kotlin
abstract class Superclass(@property:Json(name="superclassPropertyJsonName") var superclassProperty: String? = null)
```

seems inconsistent?

**Comment by swankjesse** [comment]
At no point can Moshi call the superclass‘ constructor. It doesn't use it, and it cannot use it. But it can set properties.

**Comment by NightlyNexus** [comment]
right.
i'm confused and curious why `@property:Json` vs `@Json` makes a difference. I would have expected the `@Json` to be applied to the `var` property, without needing the explicit `@property:Json`.

**Comment by swankjesse** [comment]
I think it’s cause `@property:Json` is visible to callers of subtypes; but the supertype constructor’s parameters are not.

**Comment by NightlyNexus** [comment]
yeah! got it, thank you.

**Comment by ligi** [comment]
Is there any way to make it work without defining the fields as var? Would still love to keep them a val
