### ISSUE TITLE
Access json model field annotations during [de]serialization

### ISSUE THREAD

**Issue by glenebob** [square/moshi#701]
Hi folks. I am considering migrating from Gson to Moshi because I was initially under the impression that Moshi would provide access to model field annotations to custom type adapters, but I am not finding such functionality.

Consider the following example code (which doesn't run, obviously, because the method signatures that I want are not supported). In particular, look at the annotation MoshiLongTimestampFormat, and how it is applied to a field in TestModel, and how it is used in MoshiLongTimestampAdapter to control the formatting of timestamp values.

There are many use cases that would benefit from being able to access the annotations attached to a field during [de]serialization of that field. Obviously, Moshi has access to such annotations, so it seems straight forward to pass them along to a customer adapter.

    public class MoshiLongTimestampAdapterTest {
        @Retention(RetentionPolicy.RUNTIME)
        @JsonQualifier
        public @interface MoshiLongTimestamp { }
    
        @Retention(RetentionPolicy.RUNTIME)
        public @interface MoshiLongTimestampFormat {
            String format();
        }
    
        public static class MoshiLongTimestampAdapter {
            @ToJson
            // Proposed method signature.
            String toJson(@MoshiLongTimestamp long fieldValue, Field field) {
                MoshiLongTimestampFormat annotation = field.getAnnotation(MoshiLongTimestampFormat.class);
    
                if (annotation != null) {
                    return new SimpleDateFormat(annotation.format()).format(new Date(fieldValue));
                } else {
                    // No format annotation found; revert to raw long-as-string.
                    return Long.toString(fieldValue);
                }
            }
    
            @FromJson
            // Proposed method signature.
            @MoshiLongTimestamp long fromJson(String fieldValue, Field field) {
                // Similar, implementation not useful for this example.
                return 0;
            }
        }
    
        public static class TestModel {
            @MoshiLongTimestamp
            public long timestamp1;
    
            @MoshiLongTimestamp
            @MoshiLongTimestampFormat(format = "MM/dd/yyyy")
            public long timestamp2;
        }
    
        @Test
        public void formatTest() {
            TestModel testModel = new TestModel();
    
            testModel.timestamp1 = System.currentTimeMillis();
            testModel.timestamp2 = testModel.timestamp1;
    
            Moshi moshi = new Moshi.Builder()
                .add(new MoshiLongTimestampAdapter())
                .build();
            JsonAdapter<TestModel> adapter = moshi.adapter(TestModel.class);
    
            String json = adapter.toJson(testModel);
    
            // Expected output: {"timestamp1":"1538257787379","timestamp2":"09/29/2018"}
            System.out.println(json);
        }
    }

**Comment by swankjesse** [comment]
Try combining the two annotations into one:

```
 @Retention(RetentionPolicy.RUNTIME) @JsonQualifier public @interface MoshiLongTimestamp { String format(); } 
```

**Comment by glenebob** [comment]
@swankjesse, I gave that a try, but it throws an exception here:
    JsonAdapter<TestModel> adapter = moshi.adapter(TestModel.class);

Interesting idea, but I'm also not sure how I would get access to the annotation at run time. That's the main issue.

**Comment by swankjesse** [comment]
You get it passed in to your JsonAdapter.Factory. Or you can use `@ToJson/@FromJson` with it.

**Comment by NightlyNexus** [comment]
Yeah, for the qualifiers with values, you'll need to implement a JsonAdapter.Factory to get the value.

There's an example [here](https://github.com/square/moshi/blob/bd2f2c4c28c9a3c9027507f51eda3c74bd769d63/examples/src/main/java/com/squareup/moshi/recipes/FallbackEnum.java).

**Comment by glenebob** [comment]
@swankjesse, I gave that a try, but it throws an exception here:
    JsonAdapter<TestModel> adapter = moshi.adapter(TestModel.class);

Interesting idea, but I'm also not sure how I would get access to the annotation at run time. That's the main issue.

**Comment by glenebob** [comment]
Thanks @NightlyNexus, the factory approach does the trick.
