### ISSUE TITLE
Fallback to kotlin-reflect when kapt is not used

### ISSUE THREAD

**Issue by remcomokveld** [square/moshi#715]
Accoring to the documentation, kotlin-reflect and kotlin-codegen should be equivalent feature wise. 

At this point moshi will always use the generated adapter if `JsonClass(generateAdapter = true)` is present on the class. If that generated class is then not present moshi crashes at runtime.

For build speed on developement builds it would be nice to fallback on reflection based if the generated class is not found. Then we can use `kaptRelease` and not depend on reflection based parsing in release builds. Depending on the amount of json classes you have this can be result in some pretty significant build speed improvements.

**Comment by swankjesse** [comment]
Yeah, good idea!

**Comment by remcomokveld** [comment]
Do you have any preference on how this should be implemented? I kinda like the crash when I do expect the class to be generated and it does not exist. I would think this should be some sort of global flag that can be set, but not sure where.
