### ISSUE TITLE
How expensive is a Moshi instance - can I use multiple instances in my app?

### ISSUE THREAD

**Issue by DavidMihola** [square/moshi#716]
We are currently moving our (Android) app to a more modular architecture, i. e. we have an increasing number of Gradle modules which together make up the app.

Since some of these are concerned with parsing network responses from different endpoints each of these needs a Moshi instance. This is currently accomplished by injecting a single Moshi instance which is provided in a central Dagger module.

However, some of the responses require custom type adapters which are defined in the (Gradle) modules where they are used. This of course makes it necessary that the central Dagger module knows about these requirements and adds all the type adapters to the Moshi instance when it is created.

This does not seem ideal, especially as the number of modules and custom type adapters is growing. To keep this manageable we have now defined setup functions in each of the Gradle modules that take a Moshi.Builder and add everything they need before returning it. These can be used by the central Dagger module to prepare the Moshi instance - so at least it has to only remember to call that method once for each Gradle module instead of keeping track of their specific requirements.

**But, what if we dropped all this complexity and just created a local Moshi instance in every place we need one - would that lead to unacceptable increases in RAM usage or would that be fine.** (At the moment this would probably mean about 5 Moshi instances instead of one but of course that number could grow as more "microservices" are added on the backend.)

Thanks for any advice!

**Comment by swankjesse** [comment]
A constant number is completely fine. Creating a Moshi instance on each encode or decode will be inefficient.

A good way to think about it: Moshi does a few milliseconds of reflection each time it creates a JSON adapter for a type it's never before seen. If you create many Moshi instances you potentially duplicate this work. But it only hurts you if the various Moshi instances are operating on the same model types.

One other option to consider: hook up your JsonAdapters with multibindings. We do this with Guice in Misk and it works nicely.

https://github.com/square/misk/blob/master/misk/src/main/kotlin/misk/moshi/MoshiModule.kt

**Comment by DavidMihola** [comment]
Hi @swankjesse, thanks a lot for the quick reply!

OK, I'll have a look at the multibindings method and otherwise just go with multiple Moshi instances.
