### ISSUE TITLE
EnumJsonAdapter throws JsonDataException on null

### ISSUE THREAD

**Issue by lukesleeman** [square/moshi#721]
We are using the `EnumJsonAdapter` from the `moshi-adapters` package.  The documentation for the `EnumJsonAdapter.withUnknownFallback()` says that the fallback value "will not be used when the JSON value is null, absent, or not a string.".   However if the value in the json is null, then a `JsonDataException` is thrown.

This is caused by the some extra code in the `EnumJsonAdapter`'s `fromJson` method.  It reads:

```
  @Override public @Nullable T fromJson(JsonReader reader) throws IOException {
    int index = reader.selectString(options);
    if (index != -1) return constants[index];

    String path = reader.getPath();
    if (!useFallbackValue) {
      String name = reader.nextString();
      throw new JsonDataException("Expected one of "
          + Arrays.asList(nameStrings) + " but was " + name + " at path " + path);
    }
    if (reader.peek() != JsonReader.Token.STRING) {
      throw new JsonDataException(
          "Expected a string but was " + reader.peek() + " at path " + path);
    }
    reader.skipValue();
    return fallbackValue;
  }
```

The `if (reader.peek() != JsonReader.Token.STRING) {` stuff should be removed, then everything works properly.

**Comment by lukesleeman** [comment]
Doh.  I just realised that I missed the not in "Note that this value will **not** be used when the JSON value is null...".  So I guess technically the documentation on `EnumJsonAdapter.withUnknownFallback()` is accurate.

Arguably the `EnumJsonAdapter` should return null, when it encounters null in the json, not throw an exception.  Perhaps it would be good to add a way to configure this behaviour.

**Comment by swankjesse** [comment]
Call .nullSafe() on the adapter?

**Comment by lukesleeman** [comment]
Ahhhh, you are right!   Once that is added it will deserialise null in the json.  I'll close this issue

**Comment by epicstar** [comment]
> Call .nullSafe() on the adapter?

Welp, this works great for me, too. Thank you @swankjesse. This is what happens when I don't manage to read the documentation.
