### ISSUE TITLE
Convert List<MyModel> to JSON

### ISSUE THREAD

**Issue by CorradoDev** [square/moshi#73]
I would like to have the ability to convert something like
List<MyModel> myModelList = new ArrayList();
To JSON.  The easiest way I can find and the GSON kind of way to do it is:
moshi.adapter(Types.newParameterizedType(List.class, MyModel.class);

The problem is the Types package is private.  Am I missing something or can we make this package or method public so I can easily convert a list to JSON.

**Comment by kedar1607** [comment]
@JakeWharton do have solution for this yet? This seems to be pretty common use case when using room with `TypeConverters` for `ArrayList`
