### ISSUE TITLE
No property for required constructor parameter #0 moshi of fun <init>

### ISSUE THREAD

**Issue by dmenne** [square/moshi#735]
Using the snapshot 1.8.0, but same with stable 1.7.0. Android Studio, all plugins current. Kotlin 1.3.
All builds clean.

```
@JsonClass(generateAdapter = true)
data class Foo(val bar: String = "Hello")

  @Test
  fun footest() {
    val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
    val adapter = moshi.adapter<Foo>(FooJsonAdapter::class.java)
  }
```

gives

`java.lang.IllegalArgumentException: No property for required constructor parameter #0 moshi of fun <init>(com.squareup.moshi.Moshi): de.mennebiomed.bahndb.FooJsonAdapter`

**Comment by NightlyNexus** [comment]
you want `val adapter = moshi.adapter(Foo::class.java)`

moshi.adapter(FooJsonAdapter::class.java) would try to get an adapter for the FooJsonAdapter type!

**Comment by dmenne** [comment]
Sorry and thanks
