### ISSUE TITLE
PolymorphicJsonAdapterFactory could have a fallback class like with enum

### ISSUE THREAD

**Issue by ganfra** [square/moshi#739]
Hi guys and thanks for the hard work.
It might be great to have an optional fallback value on the PolymorphicJsonAdapterFactory.

What do you think of that?
Thanks!

**Comment by NightlyNexus** [comment]
Seems reasonable to me. Document that it's shared and should be an immutable value.

**Comment by dbarwacz** [comment]
I had to implement two additional cases: when subtype flag/label is missing (requirement) or unknown subclass is met and base subclass should be used. I can contribute if you find those cases useful for others. 

Builder has additional method `withDefaultSubtype` that disables exception throwing when unrecognised label is found and initialises instance of type passed as argument. 
Builder has additional method `withFallbackSubtype` that disables exception throwing when type label is missing and initialises instance of type passed as argument.

**Comment by NightlyNexus** [comment]
Nice, sounds good to me.

**Comment by swankjesse** [comment]
@DeweyReed is this a feature request or a bug report? Can you create a new issue?

**Comment by DeweyReed** [comment]
@swankjesse I notice someone mentioned `withDefaultSubtype` and `withFallbackSubtype` but the PR doesn't provide similar functions. I probably misunderstood this issue.
