### ISSUE TITLE
@Json fields with dollar signs in name not getting parsed for moshi-kotlin

### ISSUE THREAD

**Issue by nihk** [square/moshi#743]
The JSON I have to fetch has a ton of keys with dollar signs in them and nested fields. I've been trying to write an adapter for my retrofit calls because of the latter point, but every JSON key with a dollar sign character in it is yielding `null` inside my `@FromJson` method. Every JSON key _without_ a dollar sign has its expected value, and if I use instead a `.java` file for the adapter, everything parses correctly regardless of dollar sign presence or not.

These are the gradle dependencies I've been using:
```
def moshi_version = "1.8.0"
implementation "com.squareup.moshi:moshi-kotlin:$moshi_version"
kapt "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"
implementation "com.squareup.retrofit2:converter-moshi:2.4.0"
```

Here's a simplified sample of the code I've been using for my adapter

```
    data class TpFeedJson(val entries: List<Entry>)
    data class Entry(
        val id: String,
        @Json(name = "plmedia\$defaultThumbnailUrl")
        val thumbnailUrl: String
    )
```
```
    @FromJson
    @JvmStatic
    fun fromJson(tpFeedJson: TpFeedJson) =
        with(tpFeedJson) {
            val id = entries.first().id  // this has a value
            val thumbUrl = entries.first().thumbnailUrl  // this is always null when adapter is a .kt file
// etc.
```

Here's a screenshot of my debugger hitting a breakpoint within my `@FromJson` method; you can see every field that had a dollar sign is null.

![screen shot 2018-11-13 at 4 04 50 pm](https://user-images.githubusercontent.com/10007101/48635842-46aee280-e997-11e8-962c-809465525c80.png)

This issue was first mentioned here (https://github.com/square/moshi/issues/602) and here (https://github.com/square/kotlinpoet/issues/427) and were both closed but I don't see it being fixed in my example, nor did I get an understanding of what a workaround to it might be, besides using a `.java` adapter.

**Comment by swankjesse** [comment]
We had it working with codegen. Maybe missing for reflection? Your class is missing the required ` @JsonClass(generateAdapter = true)` annotation so that could be your problem.
https://github.com/square/moshi/blob/master/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt#L63

**Comment by swankjesse** [comment]
One interesting thing we could build in is exploding on Kotlin types if neither the reflection nor codegen are present.

Today we treat them as Java types which work just enough to trick you. Encoding Kotlin types as Java is fatally broken ’cause annotations don’t work (unless you very carefully target them). Nullability annotations and constructor defaults are also super broken.

**Comment by NightlyNexus** [comment]
It sounds like you're using the reflection support. Are you adding the KotlinJsonAdapterFactory?

```kotlin
@Test fun jsonAnnotationWithDollarSign() {
  val moshi = Moshi.Builder()
      .add(KotlinJsonAdapterFactory())
      .build()
  val adapter = moshi.adapter(JsonAnnotationWithDollarSign::class.java)

  // Read
  val json = "{\"\$foo\": \"bar\"}"

  val instance = adapter.fromJson(json)!!
  assertThat(instance.bar).isEqualTo("bar")

  // Write
  val expectedJson = "{\"\$foo\":\"baz\"}"

  assertThat(adapter.toJson(JsonAnnotationWithDollarSign("baz"))).isEqualTo(expectedJson)
}

data class JsonAnnotationWithDollarSign(@Json(name = "\$foo") val bar: String)
```

This test passes for me.

**Comment by nihk** [comment]
Both of those solutions worked. Thank you very much, @swankjesse @NightlyNexus !
