### ISSUE TITLE
Require reflection or codegen for Kotlin types

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#748]
When you don’t have either installed things sort of work, but there are traps. It would be better to fail early with an obvious explanation of what’s wrong.

https://github.com/square/moshi/issues/743

**Comment by hzsweers** [comment]
Would this be just a case of looking for the `@Metadata` annotation in the built-in factories _after_ the `@JsonClass` annotation check gets a chance?

**Comment by NightlyNexus** [comment]
Yeah, check in the ClassJsonAdapter, like the platform type check.

This will break a bunch of people's usages, but it's the right call.
