### ISSUE TITLE
Order of fields is not preserved during serialization

### ISSUE THREAD

**Issue by feature** [square/moshi#753]
Given the following Kotlin code:
```kotlin
fun main() {
    val data = Data("first", "second", "third")

    val adapter = Moshi.Builder().build()
            .adapter<Data>(Data::class.java)

    println(adapter.toJson(data))
}

class Data(val c: String, val b: String, val a: String)
```
The serialized output is:
```json
{"a":"third","b":"second","c":"first"}
```
But I expected the following output:
```json
{"c":"first","b":"second","a":"third"}
```

The order of the serialized fields seems to have been sorted, but I expected them to appear in the order they are declared in the `Data` class. I've checked the bytecode of my class to assure the problem isn't somehow caused by my `Data` class. Is this intentional, or is it caused by something unexpected?

### Edit:
I've done some investigation into the issue, and it seems to stem from [line 88 in the ClassJsonAdapter](https://github.com/square/moshi/blob/c64138bf0ae3550a84810ae9a348ff358a038806/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java#L88) class. We're using a `TreeMap` which implicitly uses the natural ordering of `String`s and sorts them. If this behavior isn't intentional, we could switch to a `LinkedHashMap` if preserved ordering is desired, and if there's no particular reason for using a `TreeMap`.

**Comment by feature** [comment]
I've done some investigation into the issue, and it seems to stem from [line 88 in the ClassJsonAdapter](https://github.com/square/moshi/blob/c64138bf0ae3550a84810ae9a348ff358a038806/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java#L88) class. We're using a `TreeMap` which implicitly uses the natural ordering of `String`s and sorts them. If this behavior isn't intentional, we could switch to a `LinkedHashMap` if preserved ordering is desired, and if there's no particular reason for using a `TreeMap`.

**Comment by NightlyNexus** [comment]
Use the KotlinJsonAdapterFactory from the moshi-kotlin artifact. It uses the Kotlin property ordering.
Or, use the Kotlin codegen. Iirc, it also uses the property ordering from source code.

The Java ClassJsonAdapter is working as intended.

**Comment by feature** [comment]
Including the `moshi-reflect` dependency, and its transitive dependency on `kotlin-reflect` is too large to add, just to preserve the ordering. Thanks for clarifying, I wasn't sure if this was the intended behavior or not. :smile:

**Comment by swankjesse** [comment]
We're going to require either codegen or reflection in the next release.
