### ISSUE TITLE
How to handle new polymorphic label in backward compatible way?

### ISSUE THREAD

**Issue by ursusursus** [square/moshi#756]
Hi, I am using the PolymorphicJsonAdapterFactory to handle such json, however **if backend adds a new label, then the parser blows up with**  

`Expected one of [....] for key 'type' but found 'some_new_type'. Register a subtype for this label.`

This would obviously break all apps on previous version, I think the behaviour should be as that of usual json, where you just skip values you dont know

Any way to fix this for now other than changing the source? Or did I get something wrong?

**Comment by hzsweers** [comment]
Currently it's not supported, but there's an issue for tracking allowing fallbacks in #739. Folding into there

**Comment by ursusursus** [comment]
Is this even possible to hotfix via only copy pasting the PolymorphicJsonAdapterFactory and changing few lines? Could you point me quickly? This is what I have for now, but the parser just hangs and then OOMS

```
@Override public Object fromJson(JsonReader reader) throws IOException {
            int labelIndex = labelIndex(reader.peekJson());
            if (labelIndex < 0 || labelIndex >= jsonAdapters.size()) return null;

            return jsonAdapters.get(labelIndex).fromJson(reader);
        }

        private int labelIndex(JsonReader reader) throws IOException {
            reader.beginObject();
            while (reader.hasNext()) {
                if (reader.selectName(labelKeyOptions) == -1) {
                    reader.skipName();
                    reader.skipValue();
                    continue;
                }

                int labelIndex = reader.selectString(labelOptions);
                if (labelIndex == -1) {
                    reader.skipValue();
                    continue;
                }
                reader.close();
                return labelIndex;
            }

            //throw new JsonDataException("Missing label for " + labelKey);
            return -1;
        }
```

Btw Im digging deeper into suorces and I see 

```
// CollectionJsonAdapter
while (reader.hasNext()) {
      result.add(elementAdapter.fromJson(reader));
    }
```

so I would end up with nulls inside the list anyways right?

**Comment by hzsweers** [comment]
There's a demo implementation in #741 if you want to take a look!
