### ISSUE TITLE
"Expected a name but was BEGIN_OBJECT" when switching to KotlinJsonAdapterFactory + peekJson

### ISSUE THREAD

**Issue by edenman** [square/moshi#759]
I'm trying to start using `KotlinJsonAdapterFactory` and `reader.peekJson()` with moshi 1.8.0 and i'm getting a `Expected a name but was BEGIN_OBJECT at path $.entries[0].userCreditAdjustment.adjustment` JsonDataException.  here's what the beginning of that json looks like:
```
{"entries":[{"userCreditAdjustment":{"id":"...","userID":"...","adjustment":{"amount":4000,"unit":"usd"},
```
and the data object:
```
data class UserCreditAdjustment(
    override val id: String,
    override val userID: String,
    override val adjustment: Money,
...
) : UserCreditAdjustmentInterface, Parcelable
@Parcelize
data class Money(
    override val amount: Int,
    override val unit: String
) : MoneyInterface, Parcelable
```
anybody know what i'm doing wrong?  i'll work on creating a repro-able test case tomorrow but wanted to ask first in case it's something glaringly obvious.

**Comment by hzsweers** [comment]
on the face of it, that does seem strange. We'll probably need to see the repro case first to diagnose

**Comment by NightlyNexus** [comment]
yeah, i can't tell. where are you peeking?

**Comment by edenman** [comment]
Figured it out.  I was calling `kotlinReflectionAdapter.fromJson(reader.peekJson())` but then never actually consuming that json object if it parsed successfully.  Ended up with this:

```
class SafeKotlinJsonAdapter(
    private val kotlinReflectionAdapter: JsonAdapter<Any>,
    private val javaReflectionAdapter: JsonAdapter<Any>
) : JsonAdapter<Any>() {

  override fun fromJson(reader: JsonReader): Any? {
    try {
      kotlinReflectionAdapter.fromJson(reader.peekJson())
      // If the "peek" parsing worked, go ahead and re-parse, but consume the reader this time.
      return kotlinReflectionAdapter.fromJson(reader)
    } catch (e: Throwable) {
      try {
        return javaReflectionAdapter.fromJson(reader)
      } catch (e: Exception) {
        Timber.w(e, "WTF ${e.message}")
        throw e
      }
    }
  }

  override fun toJson(writer: JsonWriter, value: Any?) {
    try {
      return kotlinReflectionAdapter.toJson(writer, value)
    } catch (e: Throwable) {
      Timber.e(e)
      return javaReflectionAdapter.toJson(writer, value)
    }
  }
```
It's way slower than I'd like, but I was just trying to make sure it would even work to begin with.  Gonna try switching to the kotlin codegen adapter instead of the kotlin reflection one.

**Comment by NightlyNexus** [comment]
```kotlin
try {
  val result = kotlinReflectionAdapter.fromJson(reader.peekJson())
  // If the "peek" parsing worked, go ahead and consume the value.
  reader.skipValue()
  return result
 
}
```
@edenman do you need to call kotlinReflectionAdapter.fromJson twice? JsonReader.skipValue() is probably what you're looking for?

**Comment by edenman** [comment]
Oooh yeah, didn't realize that was a thing.  Thanks @NightlyNexus!
