### ISSUE TITLE
v0.10 release?

### ISSUE THREAD

**Issue by Turbo87** [square/moshi#76]
I would love to use the new `@Json` annotation introduced by #68, but aside from the snapshot releases it is not included in any official release yet. Would you consider publishing a v0.10 release from the current master until all remaining issues for v1.0 are resolved?

**Comment by serj-lotutovici** [comment]
Same question from my side... is there a big milestone(or bug) stoping you guys from releasing 0.10? or 1.0.0 for that mater :)

**Comment by swankjesse** [comment]
Eager to do 1.0.0. Just a few things blocking that.

**Comment by JakeWharton** [comment]
This was released.

**Comment by Turbo87** [comment]
Thanks!
