### ISSUE TITLE
@NonNull support for fields

### ISSUE THREAD

**Issue by Turbo87** [square/moshi#77]
It would be cool if Moshi would throw an exception if a field was annotated with `@NonNull` but `fromJson()` would assign `null` to it.

**Comment by JakeWharton** [comment]
You can do this yourself!

```java
public final class NonNullJsonAdapterFactory implements JsonAdapter.Factory {
  @Override
  public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
    for (Annotation annotation : annotations) {
      if ("NonNull".equals(annotation.getClass().getSimpleName())) { // Or NonNull.class.equals(..)
        JsonAdapter<Object> delegate = moshi.nextAdapter(this, type, annotations);
        return new NonNullJsonAdapter<>(delegate);
      }
    }
    return null;
  }
  
  static class NonNullJsonAdapter<T> extends JsonAdapter<T> {
    private final JsonAdapter<T> delagate;

    NonNullJsonAdapter(JsonAdapter<T> delagate) {
      this.delagate = delagate;
    }

    @Override public T fromJson(JsonReader reader) throws IOException {
      T value = delagate.fromJson(reader);
      if (value == null) {
        throw new IllegalStateException("value was null!");
      }
      return value;
    }

    @Override public void toJson(JsonWriter writer, T value) throws IOException {
      if (value == null) {
        throw new IllegalStateException("value was null!");
      }
      delagate.toJson(writer, value);
    }
  }
}
```

Putting validation inside Moshi is a dangerous precedent since it has no end to the types of validation people want.

**Comment by Turbo87** [comment]
Ah cool, I didn't know that was possible. I guess that's one more reason
for a recipe/samples project or webpage.

**Comment by JakeWharton** [comment]
Yep! That'd make for a good one. I don't think you're the first to ask
about it.

**Comment by Turbo87** [comment]
@JakeWharton I just tried your code but it didn't seem to work as I had expected. What I tried was roughly the following:

```java
public static class TestModel {
    @NonNull String a;
    String b;
}

Moshi moshi = new Moshi.Builder()
        .add(new NonNullJsonAdapterFactory())
        .build();

JsonAdapter<TestModel> adapter = moshi.adapter(TestModel.class);

// should work
assertThat(adapter.fromJson("{\"a\":\"test\"}").a).isEqualTo("test");

// should fail
adapter.fromJson("{}");
```

I was expecting that the second `fromJson()` call would throw the `IllegalStateException`, but it basically worked just like before. From my limited debugging it seems like the `NonNullJsonAdapterFactory#create()` method gets the annotations of the `TestModel` class itself (`annotations` parameter is empty), but not of its members, so annotating the members doesn't seem to have any effect. 

Am I missing something?

**Comment by swankjesse** [comment]
I think it's the difference between rejecting null values and requiring non-null values. The example doesn't do anything about absent keys!

**Comment by Turbo87** [comment]
```java
adapter.fromJson("{\"a\":null}")
```

the above call is not throwing anything either...

but you are right, what I actually want to test is whether the API response included the field and that it is non-null.
