### ISSUE TITLE
How to consume JSON and return InputStream or String?

### ISSUE THREAD

**Issue by DangOnGitHub** [square/moshi#774]
```
{
    "results":
    [
        { "name": "foo" },
        { "name": "bar" }
    ]
}
```
I have an `InputStream` JSON like the above. I'd like to consume the object **results** and return JSON array for my client. I can manually parse the JSON using `JsonReader` but I have no idea how to return the array in `InputStream` or `String`. The reason I don't want to return `JsonReader` is flexibility of my API.

**Comment by NightlyNexus** [comment]
#675 will let you do reader.readJsonString() for your array value. The you can convert the ByteString into a utf strong or put it into a ByteArrayInputStream.
If you need this now, StackOverflow might offer some help/workarounds.

**Comment by swankjesse** [comment]
No action to take on this.
