### ISSUE TITLE
Kotlin 1.3

### ISSUE THREAD

**Issue by ayedo** [square/moshi#777]
Hi!

Fist of all: thanks for your great work! I've really enjoyed using Moshi so far.

My question: are there any plans on upgrading to Kotlin version 1.3?

**Comment by hzsweers** [comment]
Is there anything in specific you need from Moshi updating to 1.3? We haven't implemented support for any experimental 1.3 features yet, but everything else should just work

**Comment by ayedo** [comment]
I'm having classpath problems, because of the kotlin-reflect 1.2 library which moshi includes that I somehow did not manage to resolve. I was just hoping that maybe there would be a release for 1.3 that would solve this problem.

**Comment by rekire** [comment]
I have the same class path issue, please upgrade soonish.

**Comment by JakeWharton** [comment]
You can force the use of kotlin-reflect 1.3 with a manual dependency to that version in modules using moshi-kotlin or with a Gradle resolution strategy that ensures all Kotlin artifacts in use are pinned to your desired version. In general, we never release libraries solely to update their transitive dependencies.
