### ISSUE TITLE
How to parse a list?

### ISSUE THREAD

**Issue by rephiscorth** [square/moshi#78]
I'm trying to parse a a list but I can't find docs on how to do that. I already made my custom adapter class, but when I do the following:

This doesn't work with lists
```
JsonAdapter<MyData> adapter = moshi.adapter(MyData.class)
```

This doesn't work
```
JsonAdapter<List> adapter = moshi.adapter(List.class)
```

How do I parse a `List<MyData>` ?

**Comment by JakeWharton** [comment]
```java
Type listMyData = Types.newParameterizedType(List.class, MyData.class);
JsonAdapter<List<MyData>> adapter = moshi.adapter(listMyData);
```

**Comment by janswist** [comment]
This should definitely be in documentation - I just searched for this for like hours.

**Comment by Kisty** [comment]
@janswist it is now :)

**Comment by bjornson** [comment]
I ran into the same problem and now I am having trouble on how to add this converter to moshi so that retrofit knows it. Is there any documentation about it that I am overlooking?

Similar to https://github.com/square/moshi/issues/881 but I cannot see the solution.

**Comment by manideepl** [comment]
How do I do the reverse? 

I already have an adapter generated for the class, but not sure how to use it to convert a list of objects to json.

**Comment by libern** [comment]
This should definitely be in documentation - I just searched for this for like hours.

**Comment by DaphnevdVeeke** [comment]
For Kotlin:
```  val listMyData = Types.newParameterizedType(List::class.java, MyData::class.java)
val jsonAdapter = moshi.adapter<List<Location>>(listMyData)```

**Comment by Hussienfahmy** [comment]
can this done with codegen plugin ?

**Comment by Zhuinden** [comment]
For Kotlin, this should work

``` kotlin
inline fun <reified T> Moshi.parseList(jsonString: String): List<T>? {
    return adapter<List<T>>(Types.newParameterizedType(List::class.java, T::class.java)).fromJson(jsonString)
}
```

**Comment by projectdelta6** [comment]
Here is the same from @Zhuinden with the reverse function

``` kotlin
inline fun <reified T> Moshi.listToJson(list: List<T>): String {
	return adapter<List<T>>(Types.newParameterizedType(List::class.java, T::class.java)).toJson(list)
}
inline fun <reified T> Moshi.parseList(jsonString: String): List<T>? {
	return adapter<List<T>>(Types.newParameterizedType(List::class.java, T::class.java)).fromJson(jsonString)
}
```

**Comment by juliohr** [comment]
+1 to add this to the documentation. This is from 8 years ago and I still had the same issue
