### ISSUE TITLE
Package not imported in generated file (moshi-kotlin-codegen)

### ISSUE THREAD

**Issue by iarpits** [square/moshi#781]
The generated file is not able to import package (I think it should import Class and not package itself). Any help is appreciated.

Code:
```kotlin
enum class StepType {
    @Json(name = "instruction") INSTRUCTION,
}

interface StepData

@JsonClass(generateAdapter = true)
data class InstructionStepData(
        @Json(name = "step") val type: StepType,
        val identifier: String,
        val title: String = "",
        val text: String = "",
        val isOptional: Boolean = false): StepData
```

Error:
>e:*/app/build/app/generated/source/kaptKotlin/debug/com/example/\*/RSWrapper/InstructionStepDataJsonAdapter.kt:
> (4, 44): Packages cannot be imported
> 
>e:*app/build/app/generated/source/kaptKotlin/debug/com/example/\*/RSWrapper/InstructionStepDataJsonAdapter.kt:
> (18, 46): Unresolved reference: RSWrapper

Generated File:
![ok7e4](https://user-images.githubusercontent.com/20975999/50601673-e3afd700-0e82-11e9-8328-96bb1ad3f521.png)

**Comment by swankjesse** [comment]
Can you isolate this into a test case? Does your package name have an uppercase letter in it?

**Comment by iarpits** [comment]
Thanks, it was because of uppercase letter.
