### ISSUE TITLE
Parsing fails on NULL field values

### ISSUE THREAD

**Issue by vhusnullin** [square/moshi#79]
This JSON
{
		"id":"2",
		"name":"glpi",
		"firstname":null
}

fails: Expected a value but was NULL at path $.firstname

class ObjectJsonAdapter  in  file StandardJsonAdapters.java
has switch (reader.peek()) {}
there are BEGIN_ARRAY, BEGIN_OBJECT, STRING, NUMBER, BOOLEAN
and noooooo  NULL value  among  cases !!!

**Comment by swankjesse** [comment]
Derp. Can fix.

**Comment by swankjesse** [comment]
(or send us a pull request!)

**Comment by vhusnullin** [comment]
Sorry, I don't know how to go with github stuff.  I fixed it just for myself, locally.
By the way ... Can you, please, tell me how can I parse a List<SomeClass> from JSON. I am trying to find out but have no idea. Would be great to have it on the description page.

**Comment by serj-lotutovici** [comment]
@vhusnullin see #78
