### ISSUE TITLE
peekJson()-created reader instance getting stuck in infinite while-loop

### ISSUE THREAD

**Issue by the-sauce** [square/moshi#795]
EDIT: I think my issue is getting fixed with commit 5bf14098d133b4642d631e228f0b0b45a604d58e
Based on the description of this commit, I assume there is still some potential that the underlying issue isn't fixed after all though.
___________________________________________________________________________________________________________
I managed to get the JsonUtf8Reader.skipValue()-function to infinitely repeat its do-while-loop.
The count-variable is stuck on -1 which means that the while(count!=0) condition never terminates.

What I have found out so far is that the p == PEEKED_END_OBJECT is responsible for it to be set to -1.

This happened when I was using a peekJson() representant of my reader.

This is my code; it's in the namespace of my original JsonReader and beginObject() is surface-level:
`        beginObject()
        var templateFinder = peekJson()
        while (templateFinder.hasNext()) {
            if (templateFinder.selectName(COLLECTION_FIELDS) == 0) {
                skipValue()
            } else skipValue()
        }`
The broken state is reached the fourth time the "} else skipValue()-line is reached.

This is my json:
{
  "template": {
    "domain": "/site/sector/system/sun"
  },
  "cards": [
    {
      "name": "Red Dwarf"
    },
    {
      "name": "Yellow Main Sequence Star"
    }
  ]
}

"0" is the representant of "template".

I will further look into this issue using my debugger and perhaps find more information.

**Comment by the-sauce** [comment]
UPDATE:
Eof (p == 18) is reached while (count == -1).
Because count stays unchanged for (p == 18) it is impossible for the loop to terminate.

**Comment by the-sauce** [comment]
I think I might use a dirty fix for now like a final
`else if (p == PEEKED_EOF) {
    count = 0
}`
and allow someone who is more familiar with the code to have a look at how to resolve this the right way.

However, I am open for questions and per haps might even look at the internals again when I am in the mood for it.

**Comment by the-sauce** [comment]
Okay to my embarrassment I just figured out that there already is a newer version of the code I struggle with. I will check if getting the newest version solves my problem.

**Comment by the-sauce** [comment]
It's not a release though, and now I have to figure out how to include a remote git branch as a gradle dependency.

**Comment by the-sauce** [comment]
It looks like my issue got fixed in commit 5bf14098d133b4642d631e228f0b0b45a604d58e

**Comment by NightlyNexus** [comment]
Thanks for the report. I'll take a look in a few days when I can. Looks like the commit on master will help debug faster, indeed.
Can you make a runnable, minimal code sample, preferably in the form of a test that demonstrates the expected behavior?

**Comment by the-sauce** [comment]
Through looking at it after a good night of sleep I have discovered that the unexpected behavior was caused by a malformed treatment of my reader and its peekJson()-instance:

If you look at my code sample again, I am accidentally calling `skipValue()` (doing all of this in an extension method of the original reader) instead of `templateFinder.skipValue()`.
This means that the next value of my templateFinder is never consumed, and that's why my entire code sample essentially amounts to
`val reader = JsonReader.of(Okio.buffer(Okio.source(File("file.json"))))`
`while (true) reader.skipValue()`

I have tested this assumption and the result indeed is exactly the same.

**Comment by NightlyNexus** [comment]
Ah, yes, beginObject() followed by skipValue() when there is no value (i.e. there should be a call to endObject()) is an error. Previously, it would get stuck in an endless loop. After the referenced commit (for next Moshi release), it will fail with a proper error message.
