### ISSUE TITLE
Using Moshi 1.8.0 with R8 does not work with Json Qualifiers

### ISSUE THREAD

**Issue by fmrsabino** [square/moshi#799]
When we converted our project to use R8 our project started using the wrong Json adapter.

We have two qualifiers:

```kotlin
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class HexNumber

@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class DecimalNumber
```

We then use these two qualifiers for the JsonAdapters:

```kotlin
class HexNumberAdapter {
    @ToJson
    fun toJson(@HexNumber hexNumber: BigInteger): String = hexNumber.toHexString()

    @FromJson
    @HexNumber
    fun fromJson(hexNumber: String): BigInteger = hexNumber.hexAsBigInteger()
}

class DecimalNumberAdapter {
    @ToJson
    fun toJson(@DecimalNumber bigInteger: BigInteger): String = bigInteger.toString()

    @FromJson
    @DecimalNumber
    fun fromJson(decimalNumber: String): BigInteger = decimalNumber.toBigInteger()
}
```

This is the class that specifies that the field is a `DecimalNumber` so `DecimalNumberAdapter` should be the one converting the field.

```kotlin
@JsonClass(generateAdapter = true)
data class Test(
    @Json(name = "payment") @field:DecimalNumber val payment: BigInteger,
)
```

When we switched to R8 (from ProGuard) the adapter that is triggered is `HexNumberAdapter`. My theory is that `@field:DecimalNumber` is removed when R8 kicks in thus Moshi will use the first adapter added (`HexNumberAdapter`).

We have the rules defined in [this file](https://github.com/square/moshi/blob/master/moshi/src/main/resources/META-INF/proguard/moshi.pro).

Moshi Version 1.8.0 (using codegen).

**Comment by rmeissner** [comment]
We are creating moshi the following way:
```
return Moshi.Builder()
            .add(HexNumberAdapter())
            .add(DecimalNumberAdapter())
            .build()
```

also after adding the `keep` for the annotations explicitly it worked again (this was not required by proguard):

```
-keep @interface pm.gnosis.heimdall.data.adapters.HexNumber
-keep @interface pm.gnosis.heimdall.data.adapters.DecimalNumber
```

**Comment by ZacSweers** [comment]
Nothing else to be done here I think. These are used at runtime, so they need to be retained. Not sure why proguard didn't remove them compared to R8, as I expect it would as well unless it's trying to do some clever checks to guess if you're using it.

You could make a more general rule to keep all qualifiers via

```
-keep,allowobfuscation @com.squareup.moshi.JsonQualifier @interface * { *; }
```

**Comment by stairs** [comment]
Only the rule specified here worked for me after migrating to R8. I suggest updating documentation as the current rule for qualifiers: `-keep @com.squareup.moshi.JsonQualifier interface *
`  wasn't helpful for some reason.

**Comment by akhbulatov** [comment]
> You could make a more general rule to keep all qualifiers via
> 
> ```
> -keep,allowobfuscation @com.squareup.moshi.JsonQualifier @interface * { *; }
> ```
It works, but shouldn't the next line from `proguard-rules.pro` of Moshi work in this case? 
`-keep @com.squareup.moshi.JsonQualifier interface *`

**Comment by jkreiser** [comment]
> Nothing else to be done here I think. These are used at runtime, so they need to be retained. Not sure why proguard didn't remove them compared to R8, as I expect it would as well unless it's trying to do some clever checks to guess if you're using it.
> 
> You could make a more general rule to keep all qualifiers via
> 
> ```
> -keep,allowobfuscation @com.squareup.moshi.JsonQualifier @interface * { *; }
> ```

This rule worked for me as well, whereas the `-keep @com.squareup.moshi.JsonQualifier interface *` rule did not.
