### ISSUE TITLE
Embedded discriminator

### ISSUE THREAD

**Issue by raderio** [square/moshi#808]
In polymorphic fields discrimintator(type field) and object are 2 separated fields. 
I am asking if it is possible to deserealize
```
[
    { "type": "rectange", "width": 100, "height": 50 },
    { "type": "circle", "radius": 20 }
]
```
into list of `Shape`
```
open class Shape(val type: String)
data class Rectangle(type: String, val width: Int, val height: Int): Shape(type)
data class Circle(type: String, val radius: Int): Shape(type)
```

This will allow more cleaner json.
![discriminator-demo](https://user-images.githubusercontent.com/4563564/50344758-08c45180-0535-11e9-9830-da5362c33652.gif)

**Comment by JakeWharton** [comment]
Have you looked at the polymorphic adapter we provide?

**Comment by raderio** [comment]
Mm, sorry, do you have a link?

**Comment by JakeWharton** [comment]
https://github.com/square/moshi/blob/master/adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java

**Comment by raderio** [comment]
Thanks.
