### ISSUE TITLE
Moshi code-gen and intrumented tests

### ISSUE THREAD

**Issue by Luistlvr1989** [square/moshi#819]
I'm using moshi-kotlin-codegen to avoid reflect and everything works fine. However, while using it in my Intrumented tests, the json adapter does not work, it only works with reflection. 

I have already tried adding it with **kaptAndroidTest** and compiling the Android tests sources.

Am I missing something? Thanks.

**Comment by NightlyNexus** [comment]
What doesn't work? Are the JsonAdapters not generated? Are other annotation processors working in your build?

**Comment by digitalbuddha** [comment]
Could you kindly include a sample project or a failing test? I am using moshi-codegen with dagger and espresso with no issues.  Happy to help but need to be able to reproduce your problem.

**Comment by Luistlvr1989** [comment]
I found that the issue was related to my Json adapter, sorry about that. I'm closing the issue.
