### ISSUE TITLE
Is there a way to define the key of the JSON at runtime in the class? for example instead of @Json(name = "Token") the name will be defined at runtime

### ISSUE THREAD

**Issue by TurkiM** [square/moshi#820]

**Comment by NightlyNexus** [comment]
Not with that annotation. You'd need to write a custom JsonAdapter. What's the use case, by the way?

**Comment by TurkiM** [comment]
I have api needs to send a request in the following format, and this id (ends with 519) is generated at runtime, so wasn't sure if there is away to define the key dynamic at run time instead of building custom adapter for this case only and not sure what to pass as parameter to retrofit api
"shippingRecipients":{
		"88f49997-c7e4-4f68-a7ba-39ec960c0519"{
				"shippingAddressId":".......",
				"shippingMethodId":"........"
		}
}

**Comment by JakeWharton** [comment]
That's a Map<String, ShippingRecipient>

**Comment by TurkiM** [comment]
Thanks a lot I will try that.
