### ISSUE TITLE
Method adapter for nullable primitive is not discoverable in Kotlin

### ISSUE THREAD

**Issue by alllex** [square/moshi#823]
If you create an adapter for a nullable Kotlin type which has a primitive counterpart in Java, this adapter is requested using a primitive class instead of a wrapped one, which results in failure.

Here is an example with `Double`. 
```kotlin
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class MyDouble {
    companion object {
        // NOTE nullable value
        @ToJson fun toJson(@MyDouble value: Double?) = null
    }
}

data class MyHolder(@MyDouble val myDouble: Double)

fun main() {
    val moshi = Moshi.Builder()
        .add(NullifiedDouble)
        .add(KotlinJsonAdapterFactory())
        .build()
    val myHolder = MyHolder(10.0)
    println(moshi.adapter(myHolder.javaClass).toJson(myHolder)) // throws exception
}
```

The expected result is JSON's null value, but instead an exception is thrown:
```
Exception in thread "main" java.lang.IllegalArgumentException: No JsonAdapter for double annotated [@MyDouble()]
for double myDouble
for class MyHolder
	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:348)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:149)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:241)
	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
	at com.squareup.moshi.MoshiBugKt.main(MoshiBug.kt:11)
	at com.squareup.moshi.MoshiBugKt.main(MoshiBug.kt)
Caused by: java.lang.IllegalArgumentException: No JsonAdapter for double annotated [@MyDouble()]
	at com.squareup.moshi.Moshi.adapter(Moshi.java:147)
	... 7 more
```

Exception says that Moshi tried to find an adapter for `double` class, i.e. JVM's primitive. However, the adapter was created for the wrapped class, i.e. `java.lang.Double`.

This breaks in both reflection approach (`KotlinJsonAdapterFactory`) and codegen approach.

If we take a look at what is being generated by the codegen, we see why it fails:
```kotlin
class MyHolderJsonAdapter(moshi: Moshi) : JsonAdapter<MyHolder>() {
    private val options: JsonReader.Options = JsonReader.Options.of("myDouble")

    @field:MyDouble
    private val doubleAtMyDoubleAdapter: JsonAdapter<Double> =
            moshi.adapter<Double>(Double::class.java, Types.getFieldJsonQualifierAnnotations(javaClass, "doubleAtMyDoubleAdapter"), "myDouble")
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

    // the rest is omitted for brevity
}
```

Here the passed parameter to the `adapter` method call is `Double::class.java` which is translated by Kotlin into `double.class`.

**Comment by NightlyNexus** [comment]
As you said, `data class MyHolder(@MyDouble val myDouble: Double)` is going to use the primitive double.
and the adapter is installed for the boxed type. Moshi correctly sees these as two different types.
I'm not sure you can tell Kotlin to use the boxed type in MyHolder, so I would add another adapter for the primitive type.

**Comment by alllex** [comment]
You are right, my mistake.

If you match "nullability" of the adapter and the field in a class, then
everything works fine for both generated and reflection-based adapters.

One can make Kotlin to use boxed type for a field by simply making it
nullable:
```kotlin
data class MyHolder(@MyDouble val myDouble: Double?)
```

I think the issue may be closed then.

**Comment by chenthorne** [comment]
Not sure if I should zombie this thread or start a new issue, but I am facing a similar issue where moshi is unable to find the constructor for a class that uses a nullable primitive type that sets the default to null. It has a similar issue to OP, where the class uses the boxed type but Moshi is looking for the primitive type.

Example code:

```
@JsonClass(generateAdapter = true)
data class Thing(val id: Long? = null) // If you remove the null default it works

val adapter = Moshi.Builder().build().adapter(Thing::class.java)
adapter.fromJson("{\"id\": 1}")
```

Results in:
```
java.lang.NoSuchMethodException: Thing.<init>(long, int, kotlin.jvm.internal.DefaultConstructorMarker)
```

This was working as expected in 1.8 but upgrading to 1.9.1 breaks my already built out classes. I feel like this should be a valid use case and could be properly handled by Moshi, but if not, I'll have to bite the bullet and go in and update my classes.

**Comment by ZacSweers** [comment]
That issue is fixed in master and will.be available in the next release

**Comment by ZacSweers** [comment]
Closing this since the original issue was resolved
