### ISSUE TITLE
LinkedHashMap (with no annotations) requires explicit JsonAdapter to be registered

### ISSUE THREAD

**Issue by mnayef95** [square/moshi#830]
Hi i'm trying to convert JSON to Java object but my class contains org.json.JSONObject which contains java.util.LinkedHashMap<String, Object>
the result
```
Platform java.util.LinkedHashMap<java.lang.String, java.lang.Object> (with no annotations) requires explicit JsonAdapter to be registered
for java.util.LinkedHashMap<java.lang.String, java.lang.Object> nameValuePairs
for class org.json.JSONObject
```

How i can fix this problem

**Comment by NightlyNexus** [comment]
if you have to use `org.json.JSONObject`, you'll need to register an adapter for `org.json.JSONObject` using only its public API.

**Comment by ZacSweers** [comment]
Closing this out as there's no further action to take

**Comment by vincent-paing** [comment]
> if you have to use `org.json.JSONObject`, you'll need to register an adapter for `org.json.JSONObject` using only its public API.

Can you elaborate futher on this? Do we need to create our own custom adapter for JSONObject?

**Comment by ZacSweers** [comment]
Yes
