### ISSUE TITLE
Kotlin calls typealias adapter when serializing non-aliased type

### ISSUE THREAD

**Issue by andrewtoth** [square/moshi#831]
Creating an adapter for a `typealias` of a primitive causes the adapter to be used for primitives that are not aliased. The following should produce `json` with `"int" -> "1"`:
```
typealias LongAlias = Long

data class DataClass(val int: Long)

class Adapter {
    @ToJson
    fun toJson(long: LongAlias): String = "2"
}

val moshi = Moshi.Builder().add(Adapter()).add(KotlinJsonAdapterFactory()).build()
val adapter = moshi.adapter(DataClass::class.java)
val json = adapter.toJsonValue(DataClass(1)) // "int" -> "2"
```
Is there a workaround for this?

**Comment by NightlyNexus** [comment]
use a JsonQualifier?

**Comment by JakeWharton** [comment]
Seems working as intended. These are called aliases for a reason. A qualifier or wrapper type is required to differentiate.
