### ISSUE TITLE
how to build this project.

### ISSUE THREAD

**Issue by adustdu2015** [square/moshi#833]
I want to add some file in the adapter/ 。But I don't know how to build it.

**Comment by NightlyNexus** [comment]
Moshi currently builds with Apache Maven. If you're using a modern IDE like [IntelliJ IDEA](https://www.jetbrains.com/idea/download/), importing the project will work fine.
Generally, please file issues for missing features before submitting PRs. Sometimes, we leave out features on purpose to maintain focused libraries.

**Comment by adustdu2015** [comment]
thank you ! I build it.
