### ISSUE TITLE
Writing a generic JsonAdapter.Factory for PVector<T>

### ISSUE THREAD

**Issue by DavidMihola** [square/moshi#84]
Hello,

I am currently trying to replace Gson in one of my projects with Moshi - everything is working great so far, but there is one point I'd like to ask for a bit of guidance.

I am often using PVectors from http://pcollections.org/ to have immutable Lists in my data objects. For Gson I was using this:

    public class PCollectionsAdapterFactory implements TypeAdapterFactory {

    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> typeToken) {

        Type type = typeToken.getType();
        if (typeToken.getRawType() != PVector.class
                || !(type instanceof ParameterizedType)) {
            return null;
        }

        Type elementType = ((ParameterizedType) type).getActualTypeArguments()[0];
        TypeAdapter<?> elementAdapter = gson.getAdapter(TypeToken.get(elementType));
        return (TypeAdapter<T>) createPVectorAdapter(elementAdapter);
    }

    private <T> TypeAdapter<PVector<T>> createPVectorAdapter(final TypeAdapter<T> elementAdapter) {
        return new TypeAdapter<PVector<T>>() {
            public void write(JsonWriter out, PVector<T> value) throws IOException {
                if (value == null) {
                    out.nullValue();
                    return;
                }

                out.beginArray();
                for (T element : value) {
                    elementAdapter.write(out, element);
                }
                out.endArray();
            }

            public PVector<T> read(JsonReader in) throws IOException {
                if (in.peek() == JsonToken.NULL) {
                    in.nextNull();
                    return null;
                }

                PVector<T> result = TreePVector.<T>empty();
                in.beginArray();
                while (in.hasNext()) {
                    T element = elementAdapter.read(in);
                    result = result.plus(element);
                }
                in.endArray();
                return result;
            }
        };
    }
    }

For Moshi I rewrote this like this:

    public class PCollectionsAdapterFactory implements JsonAdapter.Factory {

    @Override
    public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
        Class<?> rawType = Types.getRawType(type);

        if (!annotations.isEmpty()) return null;
        if (rawType == PVector.class) {
            return newPVectorAdapter(type, moshi);
        } else {
            return null;
        }
    }

    private static <T> JsonAdapter<PVector<T>> newPVectorAdapter(Type type, Moshi moshi) {
        Type elementType = Types.collectionElementType(type, Collection.class);
        JsonAdapter<T> elementAdapter = moshi.adapter(elementType);
        return new PVectorAdapter<T>(elementAdapter);
    }

    private static class PVectorAdapter<T> extends JsonAdapter<PVector<T>> {
        private final JsonAdapter<T> elementAdapter;

        public PVectorAdapter(JsonAdapter<T> elementAdapter) {
            this.elementAdapter = elementAdapter;
        }

        @Override
        public PVector<T> fromJson(JsonReader reader) throws IOException {
            if (reader.peek() == JsonReader.Token.NULL) {
                reader.nextNull();
                return null;
            }

            PVector<T> result = TreePVector.<T>empty();
            reader.beginArray();
            while (reader.hasNext()) {
                T element = elementAdapter.fromJson(reader);
                result = result.plus(element);
            }
            reader.endArray();
            return result;
        }

        @Override
        public void toJson(JsonWriter writer, PVector<T> value) throws IOException {
            if (value == null) {
                writer.nullValue();
                return;
            }

            writer.beginArray();
            for (T element : value) {
                elementAdapter.toJson(writer, element);
            }
            writer.endArray();
        }
    }
    }

And this seems to work fine, too. However I had to copy your whole `Types` class to my package to have access to `Types.getRawType` and `Types.collectionElementType` - do you have any plans to make all these methods public for use in custom `JsonAdapter.Factory`s or am I just using Moshi wrong?

Also, this seemed to work:

    PVector<Channel> channels = startupResponse.channelMetaData.channelList;
    try {
        final String channelsAsString = mMoshi.adapter(PVector.class).toJson(channels);
        Timber.d("CHANNELS AS JSON:\n%s", channelsAsString);
        final PVector<Channel> channelsAsPVectorAgain = mMoshi.adapter(PVector.class).fromJson(channelsAsString);
        Timber.d("CHANNELS AS PVECTOR AGAIN:\n%s", channelsAsPVectorAgain);
    }

The crucial part here is `adapter(PVector.class)` - for Gson I always had to do something like `new TypeToken<PVector<Channel>>(){}.getType()` to deserialize a generic class. Is Moshi just easier that way or am I doing something wrong?

Any replies greatly appreciated!

David

**Comment by JakeWharton** [comment]
`Types` is public on `master` and there will be a release soon. For instance, to create your parameterized `PVector` you would use `Types.newParameterizedType(PVector.class, Channel.class)`.

**Comment by JakeWharton** [comment]
This does not include `getRawType` or `collectionElementType` though.

**Comment by DavidMihola** [comment]
Jake, thank you very much for your reply and the explanation of how to correctly use `newParameterizedType`.

However, I would still like to know where this leaves me with regard to my `JsonAdapter.Factory` - is there a way to achieve the same result without using the non-public methods in `Types`?

**Comment by swankjesse** [comment]
@DavidMihola wanna send us a PR to make those methods public?

**Comment by DavidMihola** [comment]
@swankjesse I was just about to, but then I noticed that all the methods I needed were indeed public since your commit a167913e5dfa8dce8b131be36efab43365eea1d3

So, sorry for raising a not-anymore-issue and I hope it's OK if I now close this issue!
