### ISSUE TITLE
Getting IncompatibleClassChangeError when parsing using Moshi, but works using Gson. This is tested on Android 5.0

### ISSUE THREAD

**Issue by abitgen** [square/moshi#841]
![Capture2](https://user-images.githubusercontent.com/10978904/56863383-4c433680-69d3-11e9-82a3-c04ca610fb4a.PNG)

The code I am trying to run is

`Moshi.Builder().add(KotlinJsonAdapterFactory()).build().adapter(classType).fromJson(jsonString)`

The above error comes on Android 5.0,
But working fine in other later versions of Android

**Comment by swankjesse** [comment]
This isn't enough to reproduce and fix. Can you please make an executable test case?

**Comment by sosite** [comment]
This is related to [https://issuetracker.google.com/issues/37045084](https://issuetracker.google.com/issues/37045084). Unfortunately, it looks like they won't fix it :/
