### ISSUE TITLE
How to specify root key for JSON array

### ISSUE THREAD

**Issue by steverob** [square/moshi#844]
I have a JSON document like this:

```
{ 
  cards: [{name: "Foo"}, {name: "Bar"}]
}
```

How do I make moshi only parse the array under the attribute `cards`.

**Comment by JakeWharton** [comment]
You can create a `JsonReader` yourself and call `beginObject()`, `nextName()`, and then hand it off to an adapter to parse the nested object, you can create a wrapper class with a single property, or you can ask for a `Map<String, List<Card>>`. Lots of options. If you need help with the code for doing particular one, please ask on StackOverflow with the 'moshi' tag and the community can aid you in coming up with a working version.
