### ISSUE TITLE
Hook for detecting when default value is used for EnumJsonAdapter

### ISSUE THREAD

**Issue by justintuchek** [square/moshi#845]
Hey 👋 

Wanted to put up a proposal for a modification to [EnumJsonAdapter](https://github.com/square/moshi/blob/master/adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.java)

It'd be great to be notified when the default value is used and what the key was that was unable to be mapped so it can be updated.

Here are a few things that came to mind where the name could be provided back to the consumer for reporting:

```kotlin
fun withUnknownFallback(fallbackValue T?, fallbackConsumed: (String) -> Unit): EnumJsonAdapter<T> {
  return EnumJsonAdapter(enumType, fallbackValue, fallbackConsumed, true);
}
```

```kotlin
fun withUnknownFallback(fallback: (String) -> T?): EnumJsonAdapter<T> {
  return EnumJsonAdapter(enumType, fallback, true);
}
```

In use:
```kotlin
enum class Shape {
  Square,
  Circle,
  Undefined
}

EnumJsonAdapter.create(Shape::class.java)
  .withUnknownFallback { name -> // Client doesn't yet have support for "squircle"
    Timber.e("Detected new shape of: $name")
    Undefined
  }
```

I know the implementation isn't currently in Kotlin, was easier to sketch out the changes. If this is something that seems like a good idea I'd be more than willing to open an PR!

**Comment by swankjesse** [comment]
If you want this, you should write your own enum adapter!

**Comment by justintuchek** [comment]
Think that's fair and definitely doable 👍 

Maybe only specific to our use case but wanted to offer upstream if there was a chance to contribute back. Thanks Jesse!
