### ISSUE TITLE
R8 produces the following warning on build

### ISSUE THREAD

**Issue by ber4444** [square/moshi#850]
AGP 3.4.0 and moshi-kotlin/1.5.0

`D8: Type `com.squareup.moshi.Util` was not found, it is required for default or static interface methods desugaring of `com.squareup.moshi.JsonAdapter com.squareup.moshi.KotlinJsonAdapterFactory.create(java.lang.reflect.Type, java.util.Set, com.squareup.moshi.Moshi)`
`

**Comment by ZacSweers** [comment]
Can you make a reproducible sample, seems like an issue likely with moshi's core artifact not being on the compile/implementation classpath

**Comment by ZacSweers** [comment]
Also - what versions are your dependencies? Both Moshi and moshi-kotlin

**Comment by ZacSweers** [comment]
Closing this out for now, happy to revisit if you can provide the information above

**Comment by ber4444** [comment]
Version numbers were in my original post. 1.5
