### ISSUE TITLE
GeoJson support

### ISSUE THREAD

**Issue by kraghu** [square/moshi#853]
Hi there,
Currently moshi crashes for all geoJson objects. Is there any workaround ?Is there any plans on support geoJson ?

**Comment by JakeWharton** [comment]
It's just JSON. Whatever problems your having are likely because your model
disagrees with the input. I can't see anything for Moshi to do here.

**Comment by kraghu** [comment]
geoJson co-ordinates cannot be easily converted to kotlin datatype . So yeah it disagrees with the input. Moshi has to support this co-ordinates data structure no? Or Am I missing something ? 

```
 "geometry": {
    "coordinates": [
      [
        [
          -118.470039367676,
          33.9783096313477
        ],
        [
          -118.4765625,
          33.9851760864258
        ],
        [
          -118.477935791016,
          33.9870643615723
        ],
        [
          -118.462829589844,
          33.9796829223633
        ],
        [
          -118.470039367676,
          33.9783096313477
        ]
      ]
    ]
```

**Comment by swankjesse** [comment]
Try using a custom adapter, as described in Moshi’s readme. Or use `List<Double>` for the 2-element lists.

**Comment by kraghu** [comment]
It worked with List<List<List<Double>>> .. in case any one is looking for the geojson format
