### ISSUE TITLE
Kotlin-Codegen is still using reflection

### ISSUE THREAD

**Issue by topjohnwu** [square/moshi#860]
When using the `moshi-kotlin-codegen` kapt plugin, moshi still uses classname reflection to get the corresponding `JsonAdapter` at runtime. This makes it impossible for my kotlin data classes to be obfuscated since you added proguard rules to `keepnames` and `keep` all generated adapters (which is required for the current implementation).

My project has a special requirement that *ALL* my classes has to be obfuscated. Wouldn't it make more sense to codegen a `JsonAdapter.Factory`, and let users add it while creating a `Moshi` instance using the builder? This is what [kotshi](https://github.com/ansman/kotshi) is doing, and due to my weird requirement I am forced not able to use the official codegen annotation processor and to use kotshi instead.

The kotshi API is almost a 100% drop-in replacement for `moshi-kotlin-codegen`, with the most drastic difference being that the developer has to manually add the generated AdapterFactory when building moshi, while in `moshi-kotlin-codegen` we have to do nothing since all adapters are found at runtime by reflection.

**Comment by ZacSweers** [comment]
The generated adapter name will be a public API in the next release, so you will be able to write your own factory generator if you want. I was considering writing one as a 3rd party option for those that need it as well, but after I'm back from sabbatical :). Does that satisfy your needs?

For what it's worth - here is why we did not opt for that pattern in Moshi: that pattern is difficult to scale in heavily modularized projects, becomes quite slow at run time with a lot of models (not just a simple switch table), and requires manually wiring up the generated factory after. It's also fairly niche. In Moshi we try to keep the footprint and API surface area as light as possible, and the standard implementation Just Works™️ for 99% of the use cases with the least amount of overhead. Yours is the 1% :)

**Comment by swankjesse** [comment]
ALSO – you can hand-author your own factory and install that. That’ll survive Proguarding.

**Comment by topjohnwu** [comment]
Yes I am aware that I could had write my own factory :) , since it's pretty trivial and easy to do. The problem for that though is that the proguard rules currently bundled into moshi's jar prevents the generated adapters (which is non-trivial) and the data classes to be obfuscated (`keepnames` and `keep` in the rules).

**Comment by ZacSweers** [comment]
You'd need to exclude the rules somehow, though admittedly I'm unsure of how to do that with the current AGP tooling. Would suggest you file a bug/feature request on the android tools team, as we can't do much about that here. Closing this out for now
