### ISSUE TITLE
Create a new release with latest improvements in KAPT and code generation avoidance

### ISSUE THREAD

**Issue by baksansk** [square/moshi#861]
There are many nice improvements in the master branch related to KAPT being incremental and falling back to reflection if the code gen adapter is missing and probably others.
I would really love to use these features but there are no new releases since Nov 2018.

Could you consider creating a new release?

**Comment by ZacSweers** [comment]
There is a current issue with using Filer in kapt in projects that do not have Java sources. There's a PR to fix this behavior, but we want to wait for it to merge to confirm that Filer use will be supported. See #854 to follow for updates

**Comment by emartynov** [comment]
Just checked and looks like Filler is not a problem anymore.
