### ISSUE TITLE
Please write MapJsonAdapter examples , thanks

### ISSUE THREAD

**Issue by pangli** [square/moshi#863]

**Comment by NightlyNexus** [comment]
What kind of examples? This class isn't public API. `moshi.adapter(Types.newParameterizedType(Map.class, String.class, String.class))` is an example.

**Comment by pangli** [comment]
Is it correct to use as follows

`fun <T> jsonToMap(type: Class<T>, jsonString: String): Map<String, T>? {
    val moshi: Moshi = Moshi.Builder().build()
    val listOfCardsType: ParameterizedType = Types.newParameterizedType(
        Map::class.java,
        String::class.java, type
    )
    val jsonAdapter: JsonAdapter<Map<String, T>> = moshi.adapter(listOfCardsType)
    return jsonAdapter.fromJson(jsonString)
}`

**Comment by ZacSweers** [comment]
Yep that should work. Closing this out now - please post on stackoverflow for questions like this in the future if you don't mind, we'd like to keep the issue tracker for bug reports :)
