### ISSUE TITLE
Json Adapter Factory for Kotlin to Fail when not using a Kotlin Adapter

### ISSUE THREAD

**Issue by AndrewReitz** [square/moshi#873]
I find myself running into issues where I forget to annotate a class with `@JsonClass(generateAdapter = true)` only to find out due to nullability issues. Or where proguard/R8 messes something up and causes the Java reflect adapter to be used. To save some time I'd like to have a `JsonAdapter.Factory` that could be added to Moshi and fails when trying to use the Java reflection adapter on a Kotlin class. 

I was attempting to write one but the value returned from the Moshi instance in the Factory is `com.squareup.moshi.Moshi.Lookup`.

To wrap this up, this is a feature request for an `JsonAdapter.Factory`, it would be great if this could be in it's own package. If this is out of scope for Moshi, then can additional information be added to what is provided to the `JsonAdapter.Factory` about the adapters so that this can be implemented else where.

**Comment by AndrewReitz** [comment]
I think #749 solves the problem.

**Comment by ZacSweers** [comment]
I think it does too. Going to close this out then, we'll release that soon!
