### ISSUE TITLE
Can't work out how to combine explicit JsonAdaptor classes with Moshi-generated ones at runtime

### ISSUE THREAD

**Issue by lpar** [square/moshi#881]
I feel like I'm failing to understand something fairly basic about Moshi's API and how it handles adapters.

When I have a `Moshi` object, I can ask Moshi to create an adaptor for some random custom class:

    val moshi = Moshi.Builder().build();
    val jsonAdapter = moshi.adapter(BlackjackHand::class.java);

I can also build my Moshi object to have a list of custom adapters it knows about:

    val moshi = Moshi.Builder()
      .add(ZonedDateTimeAdapter)
      .add(BigDecimalAdapter)
      .build()

What I can't work out is how to combine these two features, so that my `moshi` variable knows about `BlackjackHand` and has an adapter for it and also ZonedDateTime and BigDecimal. I can't call `moshi.adapter` until I have called `.build()`, and once I've called `.build()` I can't work out how to add another adapter to the set.

I've tried

    var moshi = Moshi.Builder()
      .add(ZonedDateTimeAdapter)
      .add(BigDecimalAdapter)
      .build()
    moshi = mosh.newBuilder().add(jsonAdapter)
      .add(KotlinJsonAdaptorFactory())
      .build()

but that gives me a run-time error `java.lang.IllegalArgumentException: Expected at least one @ToJson or @FromJson method on com.squareup.moshi.JsonAdapter$2`

**Comment by lpar** [comment]
After discussion on Slack, it seems like `JsonAdapter` serves two different purposes:

1. To provide explicit conversion code to/from JSON, when implemented by a singleton object; and
2. To provide a type safe way to call `toJson`/`fromJson`, when created using `moshi.adapter(...)`.

So `.Builder().add(...adapter...)` and `moshi.adapter(...)` are serving two different purposes. In the card example later:

    Type type = Types.newParameterizedType(List.class, Card.class);
    JsonAdapter<List<Card>> adapter = moshi.adapter(type);

This isn't creating an adapter with custom serialization code, like you'd add with `.Builder().add()`; rather, it's providing Moshi with the full type signature by forcing you to call `.toJson` on the adapter, so that it knows how to serialize/deserialize the object.

This was completely unclear to me from the documentation.

**Comment by IgorGanapolsky** [comment]
@lpar What did you mean by 
>  forcing you to call .toJson

**Comment by lpar** [comment]
> forcing you to call .toJson _on the adapter_

i.e. rather than just call `toJson()` on your data objects or use a `Serialize(object)` function call, you instead have to use the adapter and call `toJson()` on that. The `toJson()` method therefore has access to the adapter, and can use it to serialize/deserialize the object.
