### ISSUE TITLE
constructor with lambda parameter

### ISSUE THREAD

**Issue by shena1983** [square/moshi#884]
```kotlin
package org.jatlinw.framework.dict.tools

import com.squareup.moshi.FromJson
import com.squareup.moshi.Moshi
import com.squareup.moshi.ToJson
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

class PageId(
        val code: String,
        idGetter: (code: String) -> String) {
    val text = idGetter(code)
}

object PageIdAdapter {
    class PageJsonId(val code: String, val text:String)

    @ToJson
    fun toJson(id: PageId): PageJsonId {
        return PageJsonId(id.code, id.text)
    }

    @FromJson
    fun fromJson(pageJsonId: PageJsonId): PageId {
        return PageId(pageJsonId.code){ _ -> pageJsonId.text}
    }
}


fun main() {
    val jsonFactory: Moshi = Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .add(PageIdAdapter)
            .build()


    val pageId = PageId("haha"){_ ->"kkk"}

    val str = jsonFactory.adapter(PageId::class.java).toJson(pageId);
    println(str)
}
```

Run this code will get a Exception (with or without PageIdAdapter)

Exception in thread "main" java.lang.IllegalArgumentException: No property for required constructor parameter #1 idGetter of fun <init>(kotlin.String, (code: kotlin.String) -> kotlin.String): org.jatlinw.framework.dict.tools.PageId
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:253)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
	at org.jatlinw.framework.dict.tools.TestMoshiKt.main(TestMoshi.kt:38)
	at org.jatlinw.framework.dict.tools.TestMoshiKt.main(TestMoshi.kt)

```xml
<dependency>
    <groupId>com.squareup.moshi</groupId>
    <artifactId>moshi-kotlin</artifactId>
    <version>1.8.0</version>
</dependency>
```

**Comment by ZacSweers** [comment]
Unfortunately there's not much we can do with this case, as the kotlin json adapter cannot know that you only want serialization and not deserialization. I would suggest removing it from the constructor and adding a factory method instead that accepts the lambda parameter

```kotlin
class PageId internal constructor(
        val code: String,
        val text: String) {
  companion object {
    fun create(code: String, idGetter: (code: String) -> String): PageId {
      return PageId(code, idGetter(code)
    }
  }
}
```
