### ISSUE TITLE
How do I use moshi with kotlin?

### ISSUE THREAD

**Issue by ColtonIdle** [square/moshi#886]
I want to use Moshi with my kotlin data models so that I get my kotlin default values.

I created my data model

```
data class NetworkResponse(
        val myString: String = ""
)
```

and I want to use moshi + codegen, so I added

```
implementation("com.squareup.moshi:moshi:1.8.0")
kapt("com.squareup.moshi:moshi-kotlin-codegen:1.8.0")
```

but I get a null string if the server doesn't give me back a string. I thought I should get my default value of "". Am I doing something wrong?

**Comment by cortinico** [comment]
Hey @ColtonIdle,

As described in the Readme [here](https://github.com/square/moshi#codegen) if you want to use moshi-kotlin-codegen you need to annotate your classes with `@JsonClass(generateAdapter = true)` in order to generate a type adapter for your data class.

**Comment by ColtonIdle** [comment]
Added `@JsonClass(generateAdapter = true)` and I'm still getting the same issue.

**Comment by ColtonIdle** [comment]
Seems like the server is actually sending back an explicit null

`val myString: String = null` which is why I thought the default value wasn't working correctly. Any way around this?

**Comment by ZacSweers** [comment]
No, moshi kotlin codegen explicitly respects absence, and Kotlin default
values are only for absence and not nullability. You should either talk
with your server folks if that behavior doesn't make sense or model access
to this property to handle your null fallback for consumers in your
codebase.

**Comment by ColtonIdle** [comment]
Interesting. Thanks for the help everyone. Closing!

**Comment by ColtonIdle** [comment]
@ZacSweers any chance you can provide insight on a better way to do this? Backend says they (at the moment) can't guarantee that all nulls will be omitted, but they should be treated as omitted.

This is problematic because something like:

data class Person(
    val person: String = ""
)

doesn't declare `String` as nullable, and so it's easy to shoot ourselves in the foot instead of relying on Kotlin yelling at us. I also don't want to make absolutely everything nullable. Is there any chance to discard all nulls before they get to moshi or something?

**Comment by ZacSweers** [comment]
You can write your own adapter that skips the null value and defaults it with your own default for that property. The alternative I was describing is this:

```kotlin
data class Person(
    @Json(name = "person")
    private val rawPerson: String?
) {
  val person: String get() = rawPerson ?: ""
}
```

Not ideal either, but unfortunately I don't see a way around those two options.

**Comment by ColtonIdle** [comment]
@ZacSweers Thanks. IMO it sucks that my kotlin type is declared as non-nullable, and yet it is still null. That just seems all kinds of weird. I didn't even know it was possible to have a `String` in kotlin that was null.

**Comment by ColtonIdle** [comment]
For anyone that finds this in the future. I had some major problems in my project getting this to work correctly, but I think I found the root of the issue. I was using this article https://medium.com/@naturalwarren/kotlin-users-safely-upgrade-to-moshi-c01168a39f79 and it does some really weird things. If deserialization in Moshi fails it seems to fall back onto gson. This is undocumented and causes some weird issues all around.

Make sure that your data class includes @JsonClass(generateAdapter = true) for every nested class as well.

e.g.

Turn this

@JsonClass(generateAdapter = true)
data class GetProfile(
    val one: List<One> = listOf()
) {
    data class One(
        val two: Two = Two()
    ) {
        data class Two(
            val three: String = ""
        )
    }
}
into

@JsonClass(generateAdapter = true)
data class GetProfile(
    val one: List<One> = listOf()
) {
    @JsonClass(generateAdapter = true)
    data class One(
        val two: Two = Two()
    ) {
        @JsonClass(generateAdapter = true)
        data class Two(
            val three: String = ""
        )
    }
}
