### ISSUE TITLE
Kotlin rewrite

### ISSUE THREAD

**Issue by jaredsburrows** [square/moshi#888]
@swankjesse Would you accept Kotlin pull requests? You have migrated okio and okhttp to Kotlin. I figure that a library that parses JSON for Kotlin should be written in Kotlin. What do you think?

**Comment by swankjesse** [comment]
Not now. Probably someday when we're caught up on other projects.

**Comment by jaredsburrows** [comment]
Feel free to bump this thread when you are ready. Id love to help!
