### ISSUE TITLE
 java.lang.IllegalArgumentException: No JsonAdapter for ? extends Job(with no annotations)

### ISSUE THREAD

**Issue by i-farhanp** [square/moshi#895]
I have 2 POJO classes, i.e Invoice(Kotlin) and Job(Java)

Invoice class contains a List<Job>.

Though this has worked for a while recently I am having crashes with the following stack trace.

>    
![image](https://user-images.githubusercontent.com/13550357/63852993-39f3fc00-c9b7-11e9-9a65-23e5a27a3c85.png)

Just to mention when I converted my java classes to Kotlin it worked again. I have recently updated the kotlin version in my project if that could be the case.

**Comment by i-farhanp** [comment]
Models in java & kotlin

Job.java


`import android.os.Parcel;
import android.os.Parcelable;

import com.squareup.moshi.Json;

` public class Job implements Parcelable {

    public static String TAG = "Job";

    @Json(name = "id")
    private String id;
    @Json(name = "text")
    private String text;
    @Json(name = "source")
    private String source;
    @Json(name = "price")
    private int price;
    @Json(name = "isRecommended")
    private boolean isRecommended = true;
    @Json(name = "isComplete")
    private boolean isComplete = false;
    @Json(name = "vehicleType")
    private String vehicleType;

    private boolean isSelected;


    protected Job(Parcel in) {
        id = in.readString();
        text = in.readString();
        source = in.readString();
        price = in.readInt();
        isRecommended = in.readByte() != 0;
        isComplete = in.readByte() != 0;
        vehicleType = in.readString();
        isSelected = in.readByte() != 0;
    }

    public Job() {
    }
    

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public boolean isRecommended() {
        return isRecommended;
    }

    public void setRecommended(boolean recommended) {
        isRecommended = recommended;
    }

    public boolean isSelected() {
        return isSelected;
    }

    public void setSelected(boolean selected) {
        isSelected = selected;
    }

    public boolean isComplete() {
        return isComplete;
    }

    public void setComplete(boolean complete) {
        isComplete = complete;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Job that = (Job) o;

        if (that.id != null) {
            return that.id.equals(id) && that.text.equals(text);
        } else{
            return that.text.equals(text);
        }
    }

    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + text.hashCode();
        return result;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(text);
        dest.writeString(source);
        dest.writeInt(price);
        dest.writeByte((byte) (isRecommended ? 1 : 0));
        dest.writeByte((byte) (isComplete ? 1 : 0));
        dest.writeString(vehicleType);
        dest.writeByte((byte) (isSelected ? 1 : 0));
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<Job> CREATOR = new Creator<Job>() {
        @Override
        public Job createFromParcel(Parcel in) {
            return new Job(in);
        }

        @Override
        public Job[] newArray(int size) {
            return new Job[size];
        }
    };

}`


Invoice.kt

`
import com.squareup.moshi.Json

class Invoice {

    @Json(name = "remarks")
    internal var remarks: List<String> = ArrayList()

    @Json(name = "jobs")
    internal var jobs: List<Job> = ArrayList()

    internal lateinit var jobIds: List<String>
}`

**Comment by ZacSweers** [comment]
Are you using KotlinJsonAdapter?

**Comment by i-farhanp** [comment]
No, I wasn't but now I am getting all different sort of problems. I'll take that on StackOverflow. Closing this one.
