### ISSUE TITLE
Exclude property with Delegate -- kotlin code gen

### ISSUE THREAD

**Issue by Wasabi375** [square/moshi#922]
The generated adapter for this class behaves differently than the reflection version. When using the `KotlinJsonAdapterFactory` and not the generated adapter the result is an empty json-object, but the generated adapter still serializes the `foo` property.
```kotlin
@JsonClass(generateAdapter = true)
class DelegateTest {
	@delegate:Transient
	var foo: Int by Delegates.observable(5) { _, o, n -> println("$o -> $n")}
}
val test = DelegateTest()
test.foo = 10
val moshi = Moshi.Builder().build()
val adapter = moshi.adapter(DelegateTest::class.java)
val json = adapter.toJson(test)  // json contains property foo, but shouldn't
val result = adapter.fromJson(json) // result.foo is 10, but I would expect it to be 5
```
I'm willing to look into a fix for this if you accept PRs.

**Comment by ZacSweers** [comment]
What happens if you just use `@Transient`? In either case happy to accept a PR, just not sure why the delegate site target is necessary in that case

**Comment by Wasabi375** [comment]
You can't use `@Transient` because the property has no backing field. The backing field is provided by the delegate instead.

**Comment by ZacSweers** [comment]
Gotcha. Yeah happy to see a PR!

**Comment by Wasabi375** [comment]
There are quite a few changes coming in #903. Do you know when this will be merged? I don't really fancy finishing this just to see it broken by a big change to the underlying system. Do you have any insight in when kotlinpoet 1.4 will be released or are you just waiting for the last issue in the [1.4 milestone](https://github.com/square/kotlinpoet/milestone/9)?

**Comment by ZacSweers** [comment]
There is one open PR and that one issue left. The issue depends on the PR and should be quick. I don't have a hard date that will happen by, but it should be soon.

**Comment by ZacSweers** [comment]
The PR is merged!

**Comment by Wasabi375** [comment]
It seems like your PR fixed this already :wink: I can create a PR with a test case though if you want. That way you can catch regression errors.

**Comment by ZacSweers** [comment]
Oops :). Yes a test case would be great!
