### ISSUE TITLE
Kotlin codegen can't handle a class with an uppercase package name

### ISSUE THREAD

**Issue by ColtonIdle** [square/moshi#926]
Added `@JsonClass(generateAdapter = true)` to the top of one of my data classes that happens to sit in a package that starts with an uppercase letter and it won't compile.

**Comment by ZacSweers** [comment]
Can you give us an example package name? We have a test that covers this so
curious what is different about your case.

**Comment by ColtonIdle** [comment]
`package com.myapp.theapp.Network` which admittedly gives a warning in IntelliJ/AS.

"Package name `package com.myapp.theapp.Network` part should not start with an uppercase letter."

But it's still valid AFAIK so it should work. The actual error from Moshi ends up only coming into play if I annotate the class with `@JsonClass(generateAdapter = true)`. If I leave that off of the class then I don't get this error. The build won't compile and links me to the class "GetProfileJsonAdapter".

Error: 

```
/Users/coltonidle/Development/Android/myapp/app/build/tmp/kapt3/stubs/betaDebug/com/myapp/app/network/GetProfileJsonAdapter.java:26: error: cannot find symbol
    public GetProfile fromJson(@org.jetbrains.annotations.NotNull()
           ^
```

If you look at the error you can see that the directory is actually lowercase. Maybe that's the issue?

**Comment by ColtonIdle** [comment]
For anyone that finds this in the future. I couldn't reproduce this in my sample project, but I think I found the root of the issue. In my other project I was using this article https://medium.com/@naturalwarren/kotlin-users-safely-upgrade-to-moshi-c01168a39f79 and it does some really weird things. If deserialization in Moshi fails it seems to fall back onto gson. This is undocumented and causes some weird issues all around. I would say that Moshi does handle this and so I'm closing the issue.
