### ISSUE TITLE
Wrong generated class

### ISSUE THREAD

**Issue by pvegh** [square/moshi#930]
We moved some classes between gradle modules. Looks like it worked on a clean build otherwise CI wouldn't have been able to merge it.

But locally, some of us have problems like:
/build/generated/source/kaptKotlin/foo/bar/BazJsonAdapter.kt: (42, 52): Unresolved reference: Baz

The JsonAdapter is generated but in the wrong place, Baz is in another module now.

Some team mates say a full monkey dance (clean, cleanBuildCache, delete build folders, invalidate caches and restart and sync) helped them when they did it for multiple times.

To me it stinks a bit, sounds like an unknown problem with unknown solution, I thought it might be worth reporting.

gradle 5.6.1, AS 3.5, moshi 1.8.0

**Comment by ZacSweers** [comment]
Please file issues with Kotlin, as we don't control how the Gradle plugin manages stale files

**Comment by pvegh** [comment]
upgrating gradle from 5.6.1 to 5.6.2

**Comment by Nimrodda** [comment]
> Upgrating gradle from 5.6.1 to 5.6.2 solved it on my machine and 2 others.

Most likely not related to Gradle, but to Kapt plugin as Zac mentioned.

**Comment by ZacSweers** [comment]
It looks like this was fixed in Kapt via https://github.com/JetBrains/kotlin/commit/60fa632d0261eb278bec49e5deb6779788bcd807#diff-e88ca9ad046147fe162f04d09f2823ce

**Comment by zetokz** [comment]
I do not it is fixed, we all in our team periodically have this issue, especially when switching between branches where different count of Moshi models.
It is really annoying as we have to remove the whole folder `~/.gradle/caches` and wait then for a while once everything will be loaded again. 
Neither `clean` or `cleanBuildCache` works for sure just sometimes and it seems more like random luck rather than a solution.

**Comment by anjalsaneen** [comment]
@zetokz Yes. it's very annoying and affecting developer productivity. We have a larger codebase every time this happens it's wasting around 30 min of the developer. we are considering switching to kotlin serialization just because of this issue.

@ZacSweers Please open the ticket.

**Comment by ZacSweers** [comment]
Please file an issue on kotlin issue tracker then, we cannot fix build issues.

**Comment by jkreiser** [comment]
We have been having a similar issue where when we switched between two branches that had each named a field in the same json model differently, the generated code kept being generated with the old field name.  Deleting `~/.gradle/caches` didn't help at all.

What did help was changing our gradle wrapper version from 8.4 to 8.1, rebuilding, and then switching back to 8.4.  This must have done something different to clear the gradle cache.  Credit to @doreaimon for figuring this out.

**Comment by jkreiser** [comment]
Another thing to try is telling gradle to clean and rebuild without using the build cache:
`./gradlew clean assembleDebug --no-build-cache`
