### ISSUE TITLE
case insensitive @Json(name = ...)

### ISSUE THREAD

**Issue by ftabashir** [square/moshi#938]
Is there a built-in support to enable case-insensitive json deserilization?
Suppose that I've declared a field like this:
`@Json(name = "email")`
I need to deserilize in a case-insensitive way: also deserilize if the json contains an `Email` feild.

**Comment by ZacSweers** [comment]
Nope!

**Comment by ftabashir** [comment]
Is it a bad practice? Why you don't provide this feature?


> Nope!

**Comment by ZacSweers** [comment]
JSON keys are case-sensitive. `email` and `Email` are two different properties and should be treated as such, as there would be no way to reconcile if both were present in a JSON blob. It would be a bug if Moshi wasn't case-sensitive, so it's definitely not a "feature" that we would add.

**Comment by mortenholmgaard** [comment]
I still thinks this should be a feature that is relavant, as we so offen see endpoints not using any appropiate style, and we would like to make our dto in a more readable cammelcasing.

**Comment by ZacSweers** [comment]
That's a problem with your endpoints

**Comment by mortenholmgaard** [comment]
Yes it is, but there is all kinds of legacy systems in play for backends for different clients, but the clients still wants apps that uses data from such systems. And we would still like to write apps that does not suffer too much from the systems they have to integrate with!

**Comment by trevjonez** [comment]
Moshi does support enough via workaround, you just have to write your own adapter manually. Though I agree with Zac, hold the service accountable as best you can for not following a consistent contract of communication format.
