### ISSUE TITLE
failOnUnknown exception logs the wrong field name

### ISSUE THREAD

**Issue by nkoroste** [square/moshi#939]
`"com.squareup.moshi:moshi-kotlin:1.8.0"`

```kotlin
val json = """
  "foo" : "abc",
  "bar" : "xyz"
}
"""

data class MyClass(val foo: String)

Moshi.Builder().build().adapter(MyClass::class.java).failOnUnknown().fromJson(json)
```

Result:
`com.squareup.moshi.JsonDataException: Cannot skip unexpected NAME at $.foo`

Expected:
`com.squareup.moshi.JsonDataException: Cannot skip unexpected NAME at $.bar`

**Comment by ZacSweers** [comment]
If I'm not mistaken, the current path is what's already been processed, not the unrecognized new one. @swankjesse

**Comment by JakeWharton** [comment]
Just need to flip the exception with the call to doPeek().
