### ISSUE TITLE
Exclude fields from serialization and deserialization

### ISSUE THREAD

**Issue by edwardaa** [square/moshi#94]
To exclude a field from class serialization I create a [custom type adapter] (https://github.com/square/moshi#custom-type-adapters) to write all fields except it, but the class has many fields. 
Is there an easy way to achieve that?

**Comment by swankjesse** [comment]
Use `transient` on the field declaration.

```
private String serialized;
private transient String not_serialized;
````

**Comment by edwardaa** [comment]
cool, thanks.

**Comment by dimsuz** [comment]
Is there a way to make this exclusion happen at the runtime? E.g. something like Gson's [ExclusionStrategy](http://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/ExclusionStrategy.html)? The reason I'm asking is because I'd like to try using Moshi with Realm database. See Realm's instructions for Gson for example (they require using ExclusionStrategy to exclude some internal fields):

https://realm.io/docs/java/0.77.0/#other-libraries

**Comment by swankjesse** [comment]
Not at the moment. We could support say, `@Json(include=false)` or something.

**Comment by dimsuz** [comment]
Looks like it wouldn't solve it in this case. In the example on the above page `User` class inherits `RealmObject` class which would have some field to be excluded and this field is not accessible to library client and `RealmObject` itself is part of the library too, user has no option of annotating its fields with `@Json(include=false)`...

**Comment by swankjesse** [comment]
I think `transient` is probably easiest. Let's stick with that.

**Comment by swankjesse** [comment]
Your best bet is to write a JSON Adapter that converts a value to something that can be encoded. The wiki has examples.

**Comment by dimsuz** [comment]
Yes, `transient` looks really simple and means exactly same as its documentation says :)
Ok, thanks, will play around.

**Comment by vanniktech** [comment]
Would be nice if this `transient` feature could be mentioned in the README.

**Comment by swankjesse** [comment]
Good idea @vanniktech. Done!

**Comment by Shyish** [comment]
Please take into account that making a field `transient` will turn into that field not being serialized; ex: `Bundle.putSerializable(...)` won't work on that specific field.

**Comment by i-farhanp** [comment]
anyone looking for kotlin alternative,it would be @Transient

**Comment by grennis** [comment]
@i-farhanp  Unfortunately @ Transient requires a backing field, so you can't do:
  @ Transient val something: String by lazy { ... }

What is the proper solution to ignore a field for Kotlin?

**Comment by miPlodder** [comment]
@swankjesse How to achieve it in Kotlin ?

**Comment by micHar** [comment]
@swankjesse it would be nice if you revisited this issue, because transient is clearly not suitable for all kotlin usages.

**Comment by hzsweers** [comment]
@grennis could you file a separate issue with a stacktrace or small sample project that reproduces it? Sounds like something we could at least give a better exception for.

**Comment by grennis** [comment]
@hzsweers  and others, I found that you CAN use lazy properties on Moshi classes with: `@delegate:Transient` (instead of `@Transient`...) So, I think it's fine.

**Comment by chimbori** [comment]
`transient` is also used by other libraries, such as [Cupboard](https://bitbucket.org/littlerobots/cupboard) for the same purpose. With two separate annotations (one for Moshi, one for Cupboard), one could mark a field for inclusion/exclusion in JSON as well as (separately) in a database table. But with the current approach of only supporting this via `transient`, Moshi makes it hard to play well with other libraries. Ideally, each library’s builder should provide a way to opt out of special treatment for `transient` and opt into annotation-based exclusion strategies.

**Comment by grennis** [comment]
@chimbori  I agree. Transient has too many meanings in other contexts. Moshi should have its own dedicated annotation for excluding properties.
