### ISSUE TITLE
When is v1.8.1 or 1.90 going to be cut?

### ISSUE THREAD

**Issue by tevjef** [square/moshi#951]
Not to rush the process, but it has been nearly a year since the last major release. Since then there have been many bugs that have been reported and fixed. 

I'm sure many of us in the community would love to see a new release of Moshi soon.

**Comment by swankjesse** [comment]
I've been busy. But the community has spoken and I'm going to make shipping 1.9.0 a priority.

**Comment by ber4444** [comment]
And this is closed because?

**Comment by ZacSweers** [comment]
Because we were originally going to release yesterday, but a regression was
pointed out last minute that we’re fixing (kotlinpoet update required, PR
is open).

Sit tight!
