### ISSUE TITLE
parse genericity

### ISSUE THREAD

**Issue by SpringSmell** [square/moshi#953]
**model**
`public class BeanJava<T> {
   public T data;
   public int code;
   public String msg;
}`

**model2**
`public class BeanJava2 {
   public int code;
   public String msg;
}`
T as ArrayList

`moshi.adapter(BeanJava<ArrayList<BeanJava2>>::class.java).fromJson(json)`
or?
`Types.newParameterizedType(BeanJava::class.java,List::class.java, BeanJava2::class.java)`

I hope you can hlep me , thanks.

**Comment by ZacSweers** [comment]
The latter
