### ISSUE TITLE
What's the use of Moshi's Kotlin codegen?

### ISSUE THREAD

**Issue by jshah873** [square/moshi#958]
I've recently started using Moshi for my Android app and I'm curious to know more about what the annotation `@JsonClass(generateAdapter = true)` really does.

Example data class:

```kotlin
data class Person(
    val name: String
)
```

I'm able to serialise/de-serialise this class as follows:

```kotlin
val moshi: Moshi = Moshi.Builder().build()
moshi.adapter(Person::class.java).toJson(Person())
```

I'm not using the @JsonClass annotation here and hence codegen won't kick in.

My question is, why and when do I need to use `@JsonClass(generateAdapter = true)`

**Comment by ZacSweers** [comment]
Hey @jshah873 - we try to keep this issue tracker just for issues and feature requests. I'm happy to answer this on stackoverflow if you ask there and use the `moshi` tag! Feel free to link the question here once you've posted as well.

**Comment by jshah873** [comment]
@ZacSweers Thank you. I've posteda question already:
https://stackoverflow.com/questions/58501918/whats-the-use-of-moshis-kotlin-codegen/

Could you kindly respond?

**Comment by ZacSweers** [comment]
I’ve answered there now. Another user has offered an answer as well. Thanks for posting there!
