### ISSUE TITLE
Recipe for buffered value

### ISSUE THREAD

**Issue by adriancole** [square/moshi#96]
I've a scenario where I need to know a peer in order to properly interpret the other. In this case, there's a `type` field and a `value` field. The `value` could be a short, int, long, or double. I don't want to depend on field declaration order.

I was thinking about how to defer the decision since `JsonReader` smartly handles numbers.

Ex.

``` java
JsonReader valueReader = null;
switch (reader.nextName()) {
  case "type":
    type = Type.fromValue(reader.nextString());
    break;
  case "value":
    valueReader = reader.bufferValue(); // similar to peek, except consumes the next value
    break;
--snip--

switch (type) {
  case I64:
    value = valueReader.nextLong();
    break;
  case DOUBLE:
    value = valueReader.nextDouble();
    break;
--snip--
```

**Comment by swankjesse** [comment]
Interesting. What I like is that we have some tech that makes this relatively straightforward.

**Comment by NightlyNexus** [comment]
@adriancole
Will [`JsonReader.readJsonValue()`](https://github.com/square/moshi/blob/b4c43ae77193185e30fb062b29006ab03843ece3/moshi/src/main/java/com/squareup/moshi/JsonReader.java#L403) now do what you want?

**Comment by adriancole** [comment]
slight glitch is it makes a thing I might need as a long a double.  but
close enough I think!

**Comment by adriancole** [comment]
actually another glitch is quoted numbers.. In a perfect world, I could snap off the leaf and the poke at it. Even without this change, it is still fine. Thanks though!

**Comment by NightlyNexus** [comment]
Oh, cool! Thank you for clarifying for me.
This seems straightforward to implement now.

I'll try it out this weekend and see if it's something others want to support.

**Comment by NightlyNexus** [comment]
Btw, the alternative is to delegate to the built-in adapters to do the conversions for you (because `JsonAdapter.fromJsonValue` creates the `JsonValueReader`).

```java
final JsonAdapter<Double> doubleDelegate;
final JsonAdapter<Long> longDelegate;
fromJson(JsonReader reader) {
  Map<String, Object> object = reader.readJsonValue();
  String type = object.get("type");
  Object value = object.get("value");
  switch (type) {
    case I64:
      value = longDelegate.fromJsonValue(value);
      break;
    case DOUBLE:
      value = doubleDelegate.fromJsonValue(value);
      break;
    default:
      throw new JsonDataException("Unknown type: " + type);
  }
}
```

**Comment by swankjesse** [comment]
Nice. I think we have everything we need for this.
