### ISSUE TITLE
Rfc3339DateJsonAdapter toJson return double quote

### ISSUE THREAD

**Issue by scutcl** [square/moshi#961]
date toJson return ""2019-10-26T11:29:28.060Z"",
i just want "2019-10-26T11:29:28.060Z",
how to do it?

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable same that demonstrates the problem and how you're interacting with the adapter.

**Comment by scutcl** [comment]
val instance: Moshi = Moshi.Builder()
        .add(Date::class.java, Rfc3339DateJsonAdapter().nullSafe())
        .build()
val json = instance.adapter(Date::class.java).toJson(Date())
json = ""2019-10-28T03:06:58.084Z""

**Comment by JakeWharton** [comment]
That is working as intended. It's a top-level JSON string.
