### ISSUE TITLE
data classes with over 32 properties need multiple masks

### ISSUE THREAD

**Issue by trevjonez** [square/moshi#977]
1.3.60-eap-76 with version 1.9.0 of codegen I started getting `java.lang.IllegalArgumentException: Wrong number of arguments` for data classes that have more than 32  properties.

the decompiled byte code for the synthetic default constructor expects an additional mask for each 32 count boundary crossed.

this issue is a follow up to https://github.com/square/moshi/issues/960

**Comment by ZacSweers** [comment]
> data

Only data classes? Or all data classes?

**Comment by ZacSweers** [comment]
Put together a demo here: https://gist.github.com/ZacSweers/2f22227d3971a1bc64f9e2e6ffa4eee5

Applies to more than just data classes.

**Comment by ZacSweers** [comment]
Thinking out loud of how to do this...

We currently keep a mask int and count. 
- Create n number of masks in an array with size = n properties / 32.
- Keep a pointer to the current mask index, we keep incrementing that as we're traversing args
- After 32, we would reset the counter to 0, move the current mask to the next one. Continue doing so until it's exhausted.

Then factor that into the final "args" count. This should be pretty easy once #976 is in.

**Comment by ZacSweers** [comment]
Thinking out loud of how to do this...

We currently keep a mask int and count. 
- Create n number of masks as local vars lazily. Track in list in code gen for end args
- Track current mask var name
- Keep a pointer to the current mask index, we keep incrementing that as we're traversing args
- After 32, we would reset the counter to 0, add a new mask local var and set that to the current name.

Then factor that into the final "args" count. This should be pretty easy once #976 is in.

**Comment by ZacSweers** [comment]
PR opened here: #978
