### ISSUE TITLE
how to apply default value to the field which servers return null value 

### ISSUE THREAD

**Issue by solomonhit** [square/moshi#980]
When reading JSON that is missing a field, now moshi can apply the default value to this field;
but if the server JSON  return with null value, how can I apply the default I declare  to this field?
for example 
```
data class(val nickName: String = "default  Name", val age: Int)
```
but server returns 
```
{"nickName": null, "age": 11}
```
I want to apply the `default Name` to `nickName` here, is there a way to do these things?

**Comment by ZacSweers** [comment]
You can't. Like Kotlin - Moshi sees absence and `null` as different things. Default values are only used for absent values. You'll need to speak with your server folks to ask them to not send the key at all if that's supposed to indicate absence.
