### ISSUE TITLE
1.9.1 codegen no nullableListOfStringAdapter 

### ISSUE THREAD

**Issue by hugomillwood** [square/moshi#990]
Hi,

First of all, tanks for the fantastic work on the 1.9.x release! I'm not sure if this is an issue or if I've simply misunderstood what the expected behavior is.

I have a data class with a `List<String>?` which would produce the following line in the code-gen generated adapter on 1.8.0:
`14 -> genres = nullableListOfStringAdapter.fromJson(reader)`

With 1.9.1 code-gen produces this:

`        14 -> genres = listOfStringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("genres",
            "genres", reader)`

This results in `com.squareup.moshi.JsonDataException: Required value 'genres' missing at $.programs[0].event`.

Have I missed something in the 1.9.X release for marking lists as optional?

**Comment by vararg** [comment]
Same here. But with List<MyObject>. So looks like problem with nullable lists in general.

**Comment by AlexKrupa** [comment]
Here's a snippet:
```kotlin
@JsonClass(generateAdapter = true)
data class NullableList(
    val nullableList: List<Any>?
)

val adapter = Moshi.Builder().build().adapter(NullableList::class.java)

adapter.fromJson("{}") // com.squareup.moshi.JsonDataException: Required value 'nullableList' missing at $
adapter.fromJson("""{"nullableList":null}""") // com.squareup.moshi.JsonDataException: Non-null value 'nullableList' was null at $.nullableList
```

**Comment by ZacSweers** [comment]
Interestingly, this fails with the same exception in both reflection and code gen. Still investigating

**Comment by ZacSweers** [comment]
I've found the issue, should have a PR shortly

**Comment by ZacSweers** [comment]
Would you mind trying a snapshot build of current master to verify the fix works for you? Same for anyone else affected by this

**Comment by hugomillwood** [comment]
Will do first thing in the morning! Thanks for the quick turnaround on this.On Nov 3, 2019 21:37, Zac Sweers <notifications@github.com> wrote:Would you mind trying a snapshot build of current master to verify the fix works for you? Same for anyone else affected by this

**Comment by hugomillwood** [comment]
@ZacSweers Looks good on my end! Latest snapshot also resolves #991 which I was experiencing.

**Comment by ZacSweers** [comment]
Great! Thanks for confirming, we'll try to get a release out shortly

**Comment by AlexKrupa** [comment]
Works for me too, thanks!
