### ISSUE TITLE
Incorrect reading of the type in codegen

### ISSUE THREAD

**Issue by Faierbel** [square/moshi#991]
Hi
When I use the new codegen version 1.9.1, I get the NoSuchMethodException error. Occurs only in classes that have boxed primitives nullable values for example `Int?`. I discovered that this has to do with the new way of creating objects. When we add, for example, `Int?` this generated adapter instead of creating a constructor for "java.lang.Integer" still uses the primitive value of `int` causing the NoSuchMethodException error.

**Comment by outadoc** [comment]
I think I have the same problem. It doesn't occur when `thatIsATest` is not nullable.

```kotlin
package fr.test.myapplication

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi

@JsonClass(generateAdapter = true)
data class Testy (
    @Json(name = "oh_boy")
    val ohboy: String,
    @Json(name = "that_is_a_test")
    val thatIsATest: Int?,
    @Json(name = "test_again")
    val testAgain: Int = 0
)

fun main() {
    val moshi = Moshi.Builder().build()
    val adapter = moshi.adapter(Testy::class.java)

    val res = adapter.fromJson("""
        {
            "oh_boy": "testing",
            "that_is_a_test": 3
        }
    """.trimIndent())

    println(res)
}
```

Using Moshi 1.9.1, this gives:
```
Exception in thread "main" java.lang.NoSuchMethodException: fr.test.myapplication.Testy.<init>(java.lang.String, int, int, int, kotlin.jvm.internal.DefaultConstructorMarker)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at fr.test.myapplication.TestyJsonAdapter.fromJson(TestyJsonAdapter.kt:65)
	at fr.test.myapplication.TestyJsonAdapter.fromJson(TestyJsonAdapter.kt:18)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:43)
	at fr.test.myapplication.TestyKt.main(Testy.kt:21)
	at fr.test.myapplication.TestyKt.main(Testy.kt)
```

**Comment by Faierbel** [comment]
Yes, if the value is not null then the kotlin uses the primitive value of `int` instead of` Integer` and the adapter can work properly.

**Comment by ZacSweers** [comment]
Figured this out, PR here: #993

**Comment by ZacSweers** [comment]
Would you mind trying a snapshot build of current master to verify the fix works for you? Same for anyone else affected by this

**Comment by abhishekBansal** [comment]
I had the same issue. It works fine with `1.10.0-SNAPSHOT`.

**Comment by burakkarabekir** [comment]
> Yes, if the value is not nullable then the kotlin uses the primitive value of `int` instead of` Integer` and the adapter can work properly.

Thanks, I appreciated.
