### ISSUE TITLE
Can't import PolymorphicJsonAdapterFactory i Kotlin

### ISSUE THREAD

**Issue by mortenholmgaard** [square/moshi#997]
There is properly a simple answer to this but I just can't access `PolymorphicJsonAdapterFactory` from my kotlin app - it can't build because it can't find `PolymorphicJsonAdapterFactory`.

What should be included to get this? I have tried all the below together even though the first one should not be needed, but still this package is not possible to import.
```
    implementation 'com.squareup.moshi:moshi:1.9.1'
    implementation 'com.squareup.moshi:moshi-kotlin:1.9.1'
    kapt "com.squareup.moshi:moshi-kotlin-codegen:1.9.1"
```
And I have this one as well: (should not be related)
```
    implementation 'com.squareup.retrofit2:converter-moshi:2.6.2'
```

**Comment by RBusarow** [comment]
You forgot one. ;)

`implementation 'com.squareup.moshi:moshi-adapters:1.9.1'`

**Comment by ZacSweers** [comment]
Yep @RBusarow has it right

**Comment by mortenholmgaard** [comment]
Thanks - but I think that should be added to the readme - the others are mention there but not this one. (or Polymorphic handling for that sake)

**Comment by ZacSweers** [comment]
Wanna send a PR to add it to the readme?

**Comment by mortenholmgaard** [comment]
Sorry no - I do not have time at the moment and I yet don't know how the Polymorphic stuff works.
